'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "hungryroot",
  company: "Hungryroot",
  industry: "Food & Grocery Technology",
  subIndustry: "AI Meal Personalization",
  accentColor: "lime",
  gradientClasses: "bg-gradient-to-br from-background via-lime-500/5 to-green-500/10",
  heroHeadline: "Hungryroot: AI Grocery and Meal Plans That Adapt Every Week",
  heroSubheadline: "Building the grocery service that learns what you like, remembers what you hated, and reduces food waste by 36%—while improving weekly retention by 178% over static subscription boxes.",
  heroStats: [
    { value: "-36%", label: "Food Waste", color: "text-lime-400" },
    { value: "+178%", label: "Retention Rate", color: "text-green-400" },
    { value: "92%", label: "Preference Match", color: "text-teal-400" },
  ],
  directAnswerQuestion: "How does Hungryroot use AI to personalize grocery and meal deliveries?",
  directAnswer: "Hungryroot uses a preference learning system that combines explicit preference signals (dietary restrictions, liked/disliked items) with behavioral signals (what customers keep, swap, or skip) to build a continuously improving model of each member's food preferences. Every weekly delivery is generated fresh based on this model, dynamically adjusting for dietary changes, seasonal ingredients, and nutritional goals. Members who engage with the preference system have 178% higher retention than those who receive static recommendations.",
  clientDescription: "Hungryroot is a grocery and recipe service that sends members personalized weekly deliveries of healthy groceries alongside simple recipes. Unlike traditional meal kit services with fixed weekly menus, Hungryroot's entire value proposition is personalization—every member gets a different box based on their individual food preferences, dietary needs, and lifestyle goals.",
  clientFounded: "2015",
  clientSize: "100,000+ active members, 500,000+ deliveries monthly",
  clientLocation: "New York, NY, USA",
  problemTitle: "Static Meal Kit Subscriptions Have an Engagement Cliff",
  problemDescription: "Traditional meal kit services send the same recipes to thousands of customers, differentiating only by dietary filter (vegetarian, gluten-free). Members inevitably receive meals they don't want, waste ingredients, and cancel. The core economic problem: you can't build a subscription business when customers disengage the moment novelty wears off.",
  painPoints: [
    { title: "Traditional Meal Kit Churn", stat: "68% yr1", description: "Industry-average first-year churn rate for traditional meal kit subscriptions due to taste mismatch and poor personalization.", color: "red" },
    { title: "Food Waste Per Delivery", stat: "24%", description: "Proportion of traditional meal kit ingredients that go unused or are discarded—an environmental and economic failure.", color: "amber" },
    { title: "Preference Learning Lag", stat: "0 loops", description: "Traditional services don't learn from what customers actually ate vs discarded—the same generic menus repeat week after week.", color: "orange" },
  ],
  solutionTitle: "Continuous Preference Learning From Every Delivery Interaction",
  solutionDescription: "AGIX Technologies built a preference engine that treats every delivery as both a product and a learning event. What customers keep, swap, skip, and reorder tells the system more about their preferences than any survey—and the model updates every week, so personalization improves continuously throughout the membership.",
  solutionComponents: [
    { title: "Dietary Preference Graph", description: "Captures explicit dietary restrictions, allergies, and preferences alongside behavioral signals to build a multi-dimensional preference model per member." },
    { title: "Ingredient-Level Preference Learning", description: "Learns preferences at the ingredient level, not just recipe level—understanding that a member loves salmon but hates it when paired with dill, or loves mushrooms in everything except soup." },
    { title: "Weekly Delivery Generator", description: "Generates a unique weekly delivery for each member from 1,000+ available items, optimized for preference match, nutritional balance, and waste minimization across the week's recipes." },
    { title: "Behavioral Signal Processing", description: "Tracks keeps, swaps, reorders, and explicit ratings at item level—each signal updates the preference model in real time for next week's generation." },
    { title: "Seasonal & Availability Adaptation", description: "Seasonal ingredient availability changes weekly—the preference engine adapts by finding the best available alternatives that match each member's preferences rather than substituting arbitrarily." },
    { title: "Nutritional Goal Alignment", description: "Members who set nutrition goals (high protein, low carb, calorie targets) receive deliveries where recipe combinations naturally align with their goals without restrictive menu options." },
  ],
  architectureTitle: "Hungryroot Personalization Architecture",
  architectureLayers: [
    { name: "Preference Input", components: ["Dietary Profile Setup", "Explicit Item Ratings", "Weekly Keep/Skip Signals", "Nutritional Goal Setting"], color: "lime" },
    { name: "Preference Model", components: ["Ingredient-Level Preference Graph", "Behavioral Signal Integration", "Allergen & Restriction Enforcement", "Nutritional Modeling"], color: "green" },
    { name: "Delivery Generation Engine", components: ["Weekly Item Selection Optimizer", "Recipe-Ingredient Combination", "Waste Minimization Solver", "Seasonal Availability Filter"], color: "teal" },
    { name: "Feedback & Learning", components: ["Post-Delivery Signal Collection", "Real-Time Model Update", "Preference Drift Detection", "A/B Testing Framework"], color: "emerald" },
    { name: "Operations & Fulfillment", components: ["Inventory Planning Integration", "Supplier Demand Signals", "Packaging Optimization", "Delivery Route Integration"], color: "slate" },
  ],
  resultsTitle: "Retention and Waste Reduction at Subscription Scale",
  resultsMetrics: [
    { value: "+178%", label: "Member Retention", description: "vs static recommendation members—preference-engaged members stay 2.78x longer on average", color: "lime" },
    { value: "-36%", label: "Food Waste", description: "Reduction in food waste vs traditional meal kit services through ingredient-level preference matching", color: "green" },
    { value: "92%", label: "Preference Accuracy", description: "Members rate 92% of weekly items as 'good match' or 'love it' after the first 4 weeks of preference learning", color: "teal" },
    { value: "+$31", label: "Avg Basket Size", description: "Increase in weekly basket size as members discover new preferred items through the recommendation engine", color: "emerald" },
  ],
  resultsQuote: {
    text: "We've been subscribers for two years and I genuinely don't think I've received the same box twice. It keeps getting better—it knows I hate cilantro, that my husband loves spicy, and that we only have 20 minutes on Tuesday nights.",
    author: "Hungryroot Member",
    role: "2-Year Subscriber",
  },
  howItWorksTitle: "How Hungryroot Generates a Personalized Weekly Delivery",
  steps: [
    { title: "Preference Profile Building", description: "Build the member's food preference model from initial setup", detail: "During signup, members complete a preference wizard: dietary restrictions, cuisine preferences, cooking time availability by day, household size and composition, nutrition goals. This builds the initial preference vector that seeds the first delivery—which is already more personalized than traditional meal kits." },
    { title: "Weekly Delivery Generation", description: "Generate a unique box for this member this week", detail: "The delivery generator runs every week for each active member. It selects from 1,000+ available items those that best match the preference vector, checks nutritional balance across the week's recipe combinations, minimizes ingredient overlap (reducing waste from unused partial ingredients), and filters by current availability and seasonality." },
    { title: "Member Preview & Swaps", description: "Allow members to review and customize before dispatch", detail: "Members receive a preview of their upcoming box 5 days before delivery. They can swap any item for an alternative (the system suggests swaps that still match their preference profile), remove items, or add extras. Swap patterns are tracked as strong preference signals—choosing spicy chicken over plain chicken tells the system something important." },
    { title: "Delivery & Feedback Collection", description: "Deliver and capture behavioral signals from the experience", detail: "Post-delivery, the app asks for quick ratings on each item (optional but encouraged). Reorder behavior, complaint patterns, and skip rates on specific ingredients are all captured automatically as behavioral signals even without explicit rating." },
    { title: "Preference Model Update", description: "Update the preference model from this week's signals", detail: "All signals from the delivery are processed and update the preference model before the next week's generation runs. A strong signal (explicit 'hate it' rating or reorder of the same item three weeks in a row) updates the model immediately; weak signals (slight preference indicators) accumulate over multiple deliveries before shifting recommendations significantly." },
    { title: "Longitudinal Preference Drift Management", description: "Detect and adapt to changing preferences over time", detail: "Preferences change—new dietary restrictions, seasonal tastes, life changes. The system tracks preference drift: if a member who always selected high-carb meals starts consistently swapping them for protein-heavy alternatives, the model adapts. Long-term members receive annual preference refresh prompts to capture major lifestyle changes the behavioral model might not detect quickly enough." },
  ],
  whyItWorkedTitle: "Why Continuous Preference Learning Beats Static Personalization",
  whyFactors: [
    { title: "Behavioral Signals Outperform Surveys", description: "What members do (keep, swap, skip, reorder) is far more accurate than what they say they like. The behavioral signal loop produces preferences that are more accurate and more current than any intake survey." },
    { title: "Ingredient-Level Granularity", description: "Most personalization systems operate at the recipe or cuisine level. Hungryroot's ingredient-level model captures nuances (loves salmon, hates dill with salmon) that coarser systems miss, directly driving waste reduction." },
    { title: "Waste Minimization as a Design Constraint", description: "Treating waste minimization as an explicit optimization constraint—not just an outcome—drove recipe combination logic that reduced partial ingredient leftovers by design." },
    { title: "Preview + Swap as a Preference Signal Engine", description: "Making the weekly preview interactive turned a customer experience feature into the richest source of preference signals in the system. Every swap is a data point." },
    { title: "Compound Improvement Over Membership Duration", description: "The longer a member stays, the better the personalization—creating a retention flywheel where improvement drives loyalty and loyalty creates more data for improvement." },
  ],
  limitations: [
    { title: "Cold Start Problem for New Members", description: "The first 1–2 deliveries are less personalized as the system lacks behavioral signals. Initial preference wizard data provides a starting point, but the model improves most rapidly after 3–4 deliveries." },
    { title: "Ingredient Availability Constraints", description: "Personalization is limited by what's available from suppliers each week. In weeks with supply disruptions, the preference engine may need to make less ideal substitutions." },
    { title: "Multi-Person Household Complexity", description: "When household members have very different or conflicting preferences, the system must compromise rather than fully satisfy any individual—single-member households get the most accurate personalization." },
    { title: "Novel Preferences Require Explicit Teaching", description: "A new dietary requirement (e.g., suddenly going vegan) is best communicated explicitly rather than inferred from behavioral signals, which may take several weeks to catch up." },
  ],
  whenToUseGoodFit: [
    "Subscription food businesses where personalization is the core differentiation from competitors",
    "Grocery services with large item catalogs where individual matching has high value",
    "Food delivery platforms with repeat customer relationships and behavioral data",
    "Health-focused food services where nutritional goal alignment matters to customers",
  ],
  whenToUseNotGoodFit: [
    "One-time or infrequent purchase food products with no subscription relationship",
    "Restaurant recommendation systems where preferences are extremely variable by occasion",
    "Food services with very limited item variety (< 50 SKUs) where personalization has minimal value",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Preference prediction and behavioral signal modeling", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Personalization engine tailored to subscription food products", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "Grocery and food retail AI deployment patterns", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Weekly delivery generation and optimization decisions", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Inventory planning and fulfillment optimization", type: "intelligence" },
  ],
  keyTakeaways: [
    "Behavioral signals (keep/swap/skip) produce more accurate preference data than any survey",
    "Ingredient-level preference modeling reduces waste by 36% vs recipe-level approaches",
    "Preview + swap mechanism is both a customer experience feature and the best preference signal generator",
    "178% retention improvement proves personalization compounds over time",
    "Waste minimization as an explicit optimization constraint drives design choices beyond preference matching",
  ],
  faqs: [
    { question: "How does Hungryroot's AI handle common food allergies?", answer: "Allergen restrictions are hard-coded as absolute constraints—a member with a peanut allergy will never receive any item containing peanuts or processed in a facility that handles peanuts. These restrictions are enforced at the database level before any personalization model runs, ensuring safety takes priority over preference optimization." },
    { question: "How quickly does the preference model learn?", answer: "Members typically see meaningfully improved personalization within 3–4 deliveries as behavioral signals accumulate. By the 8th delivery (approximately 2 months), most members report that 90%+ of items feel like 'good matches'. The model continues improving indefinitely as preferences evolve, with meaningful updates every week." },
    { question: "Can Hungryroot's approach work for other subscription products beyond food?", answer: "The preference learning architecture is applicable to any subscription product with repeating choices: beauty boxes, pet supplies, kids clothing subscriptions, vitamin and supplement services. The core loop—generate, deliver, collect behavioral signals, update model—works whenever the same customer makes repeated selections from a catalog." },
    { question: "How does the system handle members in a household with different preferences?", answer: "Hungryroot supports household preference profiles where each person can register separate preferences. The delivery generation engine attempts to find items that work for the whole household while satisfying each individual's hard restrictions. In practice, households with very different preferences often order custom split deliveries where the system generates separate boxes optimized for each sub-group." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function HungryrootCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
