'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "brainfish",
  company: "Brainfish",
  industry: "SaaS Customer Support",
  subIndustry: "AI Self-Service Resolution",
  accentColor: "violet",
  gradientClasses: "bg-gradient-to-br from-background via-violet-500/5 to-purple-500/10",
  heroHeadline: "Brainfish: AI Support That Resolves 91% of Tickets Without a Human",
  heroSubheadline: "Moving customer support from reactive ticket queues to instant, contextual resolution—handling 28,000+ support conversations monthly with 91% first-contact resolution and sub-3-second response times.",
  heroStats: [
    { value: "91%", label: "First-Contact Resolution", color: "text-violet-400" },
    { value: "-78%", label: "Escalation to Human", color: "text-purple-400" },
    { value: "<3s", label: "Response Time", color: "text-indigo-400" },
  ],
  directAnswerQuestion: "How does Brainfish achieve 91% AI customer support resolution?",
  directAnswer: "Brainfish uses a retrieval-augmented generation (RAG) system that combines a fine-tuned language model with a live knowledge base of product documentation, past resolved tickets, and policy FAQs. When a customer asks a question, the system retrieves the most relevant context from all knowledge sources, generates a precise answer grounded in that context, and resolves 91% of tickets without human involvement. For the remaining 9%, it generates a detailed handoff summary for the human agent.",
  clientDescription: "Brainfish is an AI-powered customer support platform used by B2B SaaS companies processing millions of customer interactions. The platform sits in front of existing support ticketing systems and handles routine inquiries, product how-to questions, billing issues, and technical troubleshooting—routing only genuine exceptions to human agents.",
  clientFounded: "2019",
  clientSize: "500+ SaaS customers, processing 2M+ monthly interactions",
  clientLocation: "San Francisco, CA, USA",
  problemTitle: "SaaS Support Teams Are Drowning in Repetitive Tickets",
  problemDescription: "In B2B SaaS, the same questions get asked thousands of times. 'How do I export my data?', 'Why was I charged twice?', 'Why is the integration not syncing?'—these account for 70%+ of all support volume. Every ticket is handled identically by a human agent who has answered the same question 500 times before. The work is repetitive, agents burn out, and customers wait.",
  painPoints: [
    { title: "Repetitive Ticket Rate", stat: "73%", description: "Proportion of support tickets that ask questions with existing, known answers in product documentation or past tickets.", color: "amber" },
    { title: "Average First Response Time", stat: "6.5 min", description: "Time customers waited for initial response before AI, including queue time and agent reading time.", color: "red" },
    { title: "Agent Annual Turnover", stat: "42%", description: "High turnover driven by repetitive, low-engagement work—costing companies 6–9 months salary per replacement.", color: "orange" },
  ],
  solutionTitle: "RAG-Powered Self-Service That Learns From Every Resolved Ticket",
  solutionDescription: "AGIX Technologies built a retrieval-augmented support system that ingests the company's entire knowledge base—documentation, FAQs, past tickets, policy documents—and uses semantic search plus a generative model to compose accurate, contextual answers. The system handles the full resolution flow: understand intent, retrieve context, generate answer, confirm resolution, escalate if needed.",
  solutionComponents: [
    { title: "Intent Classification Engine", description: "Classifies incoming queries into intent categories (billing, how-to, technical, account) to route to the appropriate knowledge domains and response templates." },
    { title: "Multi-Source Knowledge Retrieval", description: "Semantic search across product docs, FAQ articles, and 24 months of resolved tickets to find the most relevant context for each specific query." },
    { title: "Answer Generation with Grounding", description: "GPT-4 class model generates answers grounded in retrieved context, with citations to source documents and step-by-step instructions where applicable." },
    { title: "Resolution Confidence Scoring", description: "Each generated answer receives a confidence score based on retrieval quality and answer coherence. Low-confidence responses are flagged for human review before delivery." },
    { title: "Seamless Escalation Handoff", description: "When escalation is needed, the system generates a complete case summary—conversation history, extracted entities, attempted solutions—so agents have full context immediately." },
    { title: "Continuous Learning Pipeline", description: "Every resolved ticket (human or AI) enriches the knowledge base. CSAT scores on AI-handled tickets drive targeted knowledge gap identification and resolution." },
  ],
  architectureTitle: "Brainfish AI Support Architecture",
  architectureLayers: [
    { name: "Intake & Routing", components: ["Multi-Channel Ingestion (Chat, Email, API)", "Language Detection", "Intent Classification", "Priority Scoring"], color: "violet" },
    { name: "Knowledge Retrieval", components: ["Product Documentation Index", "Resolved Ticket Corpus", "Policy & FAQ Database", "Semantic Vector Search"], color: "indigo" },
    { name: "Answer Generation", components: ["Context Assembly", "GPT-4 Grounded Generation", "Step-by-Step Instruction Generation", "Citation Tracking"], color: "purple" },
    { name: "Quality & Resolution", components: ["Confidence Scoring", "Resolution Confirmation Flow", "CSAT Collection", "Escalation Handoff Builder"], color: "blue" },
    { name: "Learning & Improvement", components: ["Ticket Outcome Tracking", "Knowledge Gap Detection", "Model Retraining Triggers", "Agent Feedback Loop"], color: "cyan" },
  ],
  resultsTitle: "Transforming Support from Cost Center to Competitive Advantage",
  resultsMetrics: [
    { value: "91%", label: "First-Contact Resolution", description: "Tickets resolved by AI without any human agent involvement across all intent types", color: "violet" },
    { value: "<3s", label: "Median Response Time", description: "vs 6.5 minutes average before AI implementation across all channels", color: "purple" },
    { value: "-78%", label: "Human Escalations", description: "Reduction in tickets requiring human agent involvement since deployment", color: "indigo" },
    { value: "4.7/5", label: "AI CSAT Score", description: "Customer satisfaction rating on AI-handled conversations vs 4.2 for human-only", color: "blue" },
  ],
  resultsQuote: {
    text: "Our support team used to handle 3,000 tickets a week. Now they handle 650—and they're the hard ones that actually require judgment. Job satisfaction scores went up 40% because agents are finally doing interesting work.",
    author: "VP of Customer Success",
    role: "Series C SaaS Company",
  },
  howItWorksTitle: "How Brainfish Resolves a Support Ticket",
  steps: [
    { title: "Ticket Ingestion & Classification", description: "Receive query and identify what the customer needs", detail: "Incoming queries arrive via chat widget, email integration, or API. The intent classifier identifies the query type (billing, how-to, technical, account management) and extracts key entities: product names, error codes, account identifiers, specific features mentioned." },
    { title: "Knowledge Retrieval", description: "Find the most relevant context from all knowledge sources", detail: "The retrieval layer runs parallel semantic searches across product documentation, the FAQ database, and 24 months of resolved support tickets. The top 5 most relevant chunks from each source are assembled into a retrieval context, ranked by relevance score." },
    { title: "Answer Generation", description: "Compose a precise, grounded answer", detail: "The generative model receives the user query and retrieved context and produces a direct answer. For how-to questions, it generates numbered step-by-step instructions citing the specific documentation section. For billing questions, it references account data where available. All answers include confidence metadata." },
    { title: "Confidence Gating", description: "Decide: deliver, review, or escalate", detail: "Answers above 85% confidence are delivered directly to the customer. Answers between 65–85% confidence are queued for quick human review before delivery (typically <30 seconds). Answers below 65% confidence trigger immediate human escalation with a full case summary." },
    { title: "Resolution Confirmation", description: "Verify the customer's issue was actually solved", detail: "After delivering an answer, the system asks a confirmation question: 'Did this resolve your issue?' Negative responses trigger a follow-up clarification loop, trying a different approach before escalating. This confirmation step raised first-contact resolution from 82% to 91% in A/B testing." },
    { title: "Learning & Knowledge Update", description: "Improve the system from every interaction", detail: "Tickets where the AI answer was confirmed as resolved are added to the knowledge corpus with their query-answer pair. Escalated tickets are reviewed by agents, who update documentation where gaps existed. CSAT data is used to identify which answer types need quality improvement." },
  ],
  whyItWorkedTitle: "Why 91% Resolution Isn't Lucky—It's Engineered",
  whyFactors: [
    { title: "Grounding Prevents Hallucination", description: "By constraining the generative model to only use retrieved context, the system cannot fabricate answers—every response traces back to a verified source document." },
    { title: "Confidence Gating Maintained Quality", description: "Not delivering every answer automatically—routing low-confidence responses through human review—protected customer experience during the transition period." },
    { title: "Resolution Confirmation Loop", description: "Asking customers to confirm resolution rather than assuming success identified a 9% gap between 'answer delivered' and 'issue actually resolved', driving targeted improvements." },
    { title: "Continuous Knowledge Base Enrichment", description: "Every resolved ticket becoming a training example meant the system improved fastest in exactly the areas customers asked about most frequently." },
    { title: "Agent Handoff Quality", description: "Agents receiving AI-generated handoff summaries resolved escalated tickets 45% faster than cold transfers, creating a strong incentive for agents to trust the system." },
  ],
  limitations: [
    { title: "Complex Multi-System Issues", description: "When a customer's problem spans multiple product areas, integrations, or requires account-level investigation, the system often cannot resolve without human access to internal tools." },
    { title: "Emotionally Escalated Customers", description: "Customers who are angry or distressed need human empathy. The system detects emotional escalation signals and routes proactively, but some cases arrive already too elevated for AI handling." },
    { title: "Knowledge Base Quality Dependency", description: "The system is only as good as the documentation it retrieves from. Companies with outdated, inconsistent, or sparse documentation see lower resolution rates until they invest in knowledge management." },
    { title: "Product Changes Require Knowledge Updates", description: "New product features or pricing changes must be reflected in the knowledge base before the AI can handle related questions. There's typically a 24–48 hour lag between a product change and AI coverage." },
  ],
  whenToUseGoodFit: [
    "B2B SaaS companies with 500+ support tickets per month",
    "Support teams spending >60% of time on repetitive, answerable questions",
    "Organizations with reasonably well-documented products and policies",
    "Companies with a clear escalation path to human agents for complex issues",
  ],
  whenToUseNotGoodFit: [
    "Products with extremely high complexity where every ticket is unique",
    "Industries requiring licensed professionals (legal, medical) for support decisions",
    "Companies without a maintained product knowledge base",
    "Low-volume support environments where human touch is core to the value proposition",
  ],
  connections: [
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Core retrieval-augmented generation for support resolution", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Customer-facing dialogue management and intent handling", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Ticket routing, classification, and workflow automation", type: "service" },
    { name: "Enterprise Knowledge AI", slug: "enterprise-knowledge-ai", relevance: "Internal knowledge base management and search", type: "intelligence" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Multi-turn support dialogue with resolution confirmation", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Support operations efficiency and CSAT optimization", type: "intelligence" },
  ],
  keyTakeaways: [
    "91% first-contact resolution achievable with RAG grounding and confidence gating",
    "Resolution confirmation loop is critical—don't assume delivery equals resolution",
    "Closed knowledge loop (resolved tickets → training data) compounds improvement over time",
    "Agent satisfaction improves significantly when AI filters out repetitive work",
    "Handoff quality to human agents is as important as AI resolution rate",
  ],
  faqs: [
    { question: "How long does it take to integrate Brainfish with existing support tools?", answer: "Standard integration with Zendesk, Intercom, or Freshdesk takes 1–2 weeks. Custom integrations via API can handle any ticketing system. Initial knowledge base ingestion from documentation and past tickets takes 3–5 days, after which the system is live for pilot testing." },
    { question: "What happens to agents' jobs when 78% of tickets are handled by AI?", answer: "In every deployment, total ticket volume grew (customers submit more tickets when resolution is instant). Agents shifted from handling 100% of 3,000 tickets to handling 22% of 5,000 tickets—roughly the same workload, but focused on genuinely complex cases. No deployments resulted in agent headcount reductions." },
    { question: "How does the system handle questions about features that don't exist yet?", answer: "The system responds with what the product currently supports and, where configured, offers to log a feature request. It doesn't speculate about future features, which prevents both inaccurate promises to customers and premature product commitments." },
    { question: "What is the minimum ticket volume needed to justify this investment?", answer: "The ROI breakeven point is typically around 300–500 tickets per month, where AI handling costs are offset by reduced human agent time. Below this volume, a well-organized FAQ page is often more cost-effective. The system delivers maximum value above 2,000 tickets per month." },
    { question: "Can the system handle multiple languages?", answer: "Yes. The system detects the customer's language and responds in kind. Current supported languages include English, Spanish, French, German, Portuguese, Japanese, and Mandarin. Knowledge base content must be available in each language, though automated translation of existing documentation is available as an add-on." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function BrainfishCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
