'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "innit",
  company: "Innit",
  industry: "Smart Kitchen Technology",
  subIndustry: "Connected Kitchen AI",
  accentColor: "orange",
  gradientClasses: "bg-gradient-to-br from-background via-orange-500/5 to-red-500/10",
  heroHeadline: "Innit: AI That Controls Your Kitchen Appliances While You Cook",
  heroSubheadline: "The AI cooking guide that talks to your appliances—automatically setting oven temperatures, adjusting induction zones, and monitoring meat thermometers so home cooks get restaurant-quality results every time.",
  heroStats: [
    { value: "+92%", label: "Recipe Success Rate", color: "text-orange-400" },
    { value: "+165%", label: "User Engagement", color: "text-red-400" },
    { value: "4.8/5", label: "Cook Satisfaction", color: "text-amber-400" },
  ],
  directAnswerQuestion: "How does Innit's AI control smart kitchen appliances?",
  directAnswer: "Innit's AI cooking system uses a combination of recipe knowledge, appliance integration APIs, and real-time sensor data to orchestrate multi-appliance cooking automatically. The system sets oven temperatures, adjusts induction cooktop zones, monitors smart meat thermometer readings, and controls range hoods based on cooking phase—removing the need for manual adjustment while providing step-by-step voice-guided instructions. Recipe success rates improved 92% vs manual cooking from the same recipes.",
  clientDescription: "Innit is a connected kitchen platform that bridges recipe intelligence and smart appliance control, partnering with major appliance manufacturers (Samsung, Whirlpool, GE Appliances) and food companies to create an end-to-end guided cooking experience. Their vision is making home cooking as foolproof as professional kitchen execution through real-time AI guidance and appliance automation.",
  clientFounded: "2014",
  clientSize: "Integrated with 50M+ connected appliances, partnerships with 15+ appliance brands",
  clientLocation: "San Jose, CA, USA",
  problemTitle: "Home Cooking Failures Are a Technology Problem, Not a Skills Problem",
  problemDescription: "Most home cooking failures aren't caused by bad cooks—they're caused by incorrect temperatures, wrong timing, and lack of real-time feedback. A recipe says 'medium-high heat' but every stove is different. It says 'cook until golden brown' but how do you know when that is? These ambiguities are trivial for an experienced chef and catastrophic for someone trying to cook for guests.",
  painPoints: [
    { title: "Recipe Abandonment Rate", stat: "43%", description: "Proportion of attempted home recipes that result in failure or significant deviation from intended result due to imprecise instructions and lack of feedback.", color: "red" },
    { title: "Multi-Appliance Coordination", stat: "Manual", description: "Timing multiple appliances simultaneously (oven + stovetop + rice cooker + thermometer) while following instructions is cognitively overwhelming for most home cooks.", color: "orange" },
    { title: "Smart Appliance Utilization", stat: "12%", description: "Proportion of smart appliance features that are actually used by owners—most smart ovens are operated manually because the intelligence isn't connected to recipes.", color: "amber" },
  ],
  solutionTitle: "Real-Time Cooking Orchestration Across Connected Appliances",
  solutionDescription: "AGIX Technologies built a cooking intelligence layer that translates recipe steps into appliance control commands in real time. The system monitors cooking progress via connected sensors, makes autonomous adjustments when cooking conditions deviate from optimal, and provides voice-guided instruction synchronized to actual cooking progress rather than a fixed timer.",
  solutionComponents: [
    { title: "Recipe Knowledge Graph", description: "A structured recipe database encoding exact appliance settings for each cooking step, calibrated by appliance model and brand—'medium-high heat' becomes a specific wattage for each induction brand." },
    { title: "Multi-Appliance Orchestration Engine", description: "Coordinates oven preheating, cooktop zone adjustment, smart thermometer monitoring, and range hood control across multiple appliances simultaneously based on recipe state." },
    { title: "Real-Time Sensor Integration", description: "Reads temperature data from connected meat thermometers, oven sensors, and induction zone readings to track actual cooking progress vs planned progress." },
    { title: "Adaptive Cooking Adjustments", description: "When sensor data indicates cooking is ahead or behind schedule (meat reaching temperature faster, oven slow to preheat), the system automatically adjusts subsequent step timing and appliance settings." },
    { title: "Voice-Guided Instructions", description: "Step-by-step voice guidance synchronized to actual cooking progress (not fixed timers), with the patience to repeat instructions and answer cooking questions in context." },
    { title: "Cooking Technique Teaching", description: "Beyond following recipes, the system teaches technique: why you shouldn't move searing meat, how to tell by sound when oil is ready, what 'reduce by half' looks like visually." },
  ],
  architectureTitle: "Innit Connected Kitchen Architecture",
  architectureLayers: [
    { name: "Device Integration", components: ["Smart Oven API (15+ brands)", "Induction Cooktop Control", "Smart Meat Thermometer", "Range Hood Automation"], color: "orange" },
    { name: "Recipe Intelligence", components: ["Recipe Knowledge Graph", "Appliance-Specific Settings", "Cooking Phase Sequencing", "Technique Guidance Library"], color: "red" },
    { name: "Real-Time Orchestration", components: ["Multi-Appliance State Management", "Sensor Data Processing", "Adaptive Timing Engine", "Conflict Resolution"], color: "amber" },
    { name: "User Interface", components: ["Voice Guidance System", "Step-by-Step App Display", "Progress Visualization", "Question & Answer Mode"], color: "yellow" },
    { name: "Learning & Improvement", components: ["Cook Outcome Tracking", "Recipe Calibration Updates", "Appliance Performance Learning", "Preference Personalization"], color: "slate" },
  ],
  resultsTitle: "Cooking Success Metrics Across Connected Households",
  resultsMetrics: [
    { value: "+92%", label: "Recipe Success Rate", description: "Proportion of AI-guided recipes rated as 'successful' vs 57% for the same recipes without AI guidance", color: "orange" },
    { value: "+165%", label: "User Engagement", description: "Weekly cooking sessions per user increased 2.65x when appliance control was connected vs manual cooking with the app only", color: "red" },
    { value: "12x", label: "Smart Feature Utilization", description: "Increase in smart appliance feature usage from 12% to near-100% when Innit orchestrated the cooking session", color: "amber" },
    { value: "4.8/5", label: "Cook Satisfaction", description: "Post-cook satisfaction rating from Innit-guided sessions vs 3.9/5 for manual cooking from the same recipes", color: "yellow" },
  ],
  resultsQuote: {
    text: "I've tried to make beef Wellington three times in my life and failed every time. With Innit, I made it for my parents' anniversary and it was perfect. The oven literally changed temperature by itself at the right moment. I felt like a professional chef.",
    author: "Innit Platform User",
    role: "Home Cook, Chicago",
  },
  howItWorksTitle: "How Innit Orchestrates a Connected Cooking Session",
  steps: [
    { title: "Recipe Selection & Appliance Check", description: "Match recipe requirements to available appliances", detail: "When a user selects a recipe, the system checks which connected appliances are available and calibrates the recipe for the specific model's performance characteristics. An oven that runs 25°F hot gets different settings than one that runs true to the dial." },
    { title: "Mise en Place Preparation", description: "Guide ingredient prep before cooking begins", detail: "Before activating any appliances, the system guides through ingredient preparation with precise quantities and techniques. This phase uses timing intelligence to sequence prep tasks efficiently—longest prep items first, complementary tasks parallel." },
    { title: "Appliance Pre-Activation", description: "Start preheating and setup automatically", detail: "The system initiates appliance preparation—oven preheat, water boiling, oil heating—automatically timed so everything is ready when the cooking step that requires it begins. The user receives advance notice rather than discovering the oven hasn't preheated when the food is ready to go in." },
    { title: "Cooking Phase Orchestration", description: "Execute and monitor each cooking phase", detail: "During active cooking, the system monitors sensor data from all connected appliances and compares to expected cooking curves. When meat temperature is rising faster than expected (hot spots in the pan), the system adjusts the cooktop setting to prevent overcooking." },
    { title: "Real-Time Voice Guidance", description: "Provide contextual, adaptive instruction", detail: "Voice instructions are delivered based on actual cooking state, not a fixed timer. 'The internal temperature just hit 140°F—now's the time to rest the meat' is more useful than 'set a timer for 10 minutes'. Users can ask questions ('is this the right color?') and receive contextual answers based on the current cooking phase." },
    { title: "Completion and Learning", description: "Confirm success and update recipe calibration", detail: "After cooking completes, the user rates the result and can note what worked or didn't. This feedback updates the recipe calibration for their specific appliances—if their oven consistently requires 5 more minutes, the timing model adjusts accordingly for future sessions." },
  ],
  whyItWorkedTitle: "Why Appliance Integration Made the Difference",
  whyFactors: [
    { title: "Closing the Feedback Loop With Real Sensors", description: "Without real temperature data, guidance is just a timer. With actual sensor data from smart thermometers and oven sensors, the system can respond to reality rather than assumptions." },
    { title: "Appliance-Specific Calibration", description: "Translating generic recipe instructions into model-specific settings was the key insight. 'Medium-high heat' on a GE induction cooktop is 1,400W—the system knows this for 50+ appliance models." },
    { title: "Pre-Activation Timing", description: "Starting oven preheating 20 minutes before the step that requires it—rather than telling the user to preheat at the moment of need—removed a major source of timing failures." },
    { title: "Voice Interface for Hands-Busy Cooking", description: "Touch interfaces fail when your hands are covered in flour. Voice guidance synchronized to cooking state rather than fixed timers matched the actual workflow of cooking." },
    { title: "Success Rate as the North Star Metric", description: "Defining success as 'dish came out as intended' rather than 'user completed the session' forced the team to focus on actual cooking outcomes rather than engagement proxies." },
  ],
  limitations: [
    { title: "Requires Connected Appliance Ecosystem", description: "The full experience requires smart appliances with API access. Users with conventional appliances receive guidance-only features without automation—still valuable but missing the core differentiator." },
    { title: "Complex Recipes Require Judgment", description: "Dishes requiring subjective judgment (is this reduction reduced enough? is this sauce the right consistency?) cannot be fully automated without vision AI capabilities not yet deployed at scale." },
    { title: "Appliance API Stability", description: "Smart appliance APIs from manufacturers can change with firmware updates, occasionally breaking integrations until Innit updates its connector. This creates maintenance overhead as the connected appliance ecosystem evolves." },
    { title: "Multi-Cook Coordination", description: "When multiple people are cooking simultaneously on different burners with different dishes, coordination complexity exceeds current orchestration capabilities." },
  ],
  whenToUseGoodFit: [
    "Smart appliance manufacturers seeking to increase feature utilization and customer value",
    "Recipe platforms wanting to increase cooking success rates and reduce abandonment",
    "Food companies building connected cooking experiences for their products",
    "Appliance retailers wanting to increase post-purchase engagement and reduce returns",
  ],
  whenToUseNotGoodFit: [
    "Professional kitchen environments where chefs have expertise exceeding AI guidance",
    "Commercial food service where speed and volume requirements differ from home cooking",
    "Markets with very low connected appliance penetration",
    "Cooking contexts requiring extensive improvisation rather than recipe following",
  ],
  connections: [
    { name: "Agentic AI Systems", slug: "agentic-ai-systems", relevance: "Multi-step cooking orchestration across connected appliances", type: "service" },
    { name: "AI Computer Vision", slug: "ai-computer-vision", relevance: "Visual cooking state detection and progress monitoring", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Voice-guided cooking instruction and question answering", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "Consumer food and kitchen technology AI deployment", type: "industry" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Real-time multi-device orchestration and process automation", type: "intelligence" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Context-aware voice guidance during active cooking", type: "intelligence" },
  ],
  keyTakeaways: [
    "Recipe success improved 92% when AI controlled appliances vs just providing instructions",
    "Appliance-specific calibration converts generic recipe instructions to precision cooking settings",
    "Sensor-based adaptive timing outperforms fixed timers because cooking varies by appliance and ingredient",
    "Smart appliance utilization jumped from 12% to near-100% when AI orchestrated the session",
    "Voice interface synchronized to cooking state, not fixed timers, is the key UX insight",
  ],
  faqs: [
    { question: "Which smart appliances does Innit support?", answer: "Innit has certified integrations with 15+ major appliance brands including Samsung, Whirlpool, GE Appliances, Bosch, LG, Dacor, and others. The platform supports smart ovens, induction cooktops, range hoods, and Bluetooth meat thermometers. New appliance integrations are added as manufacturers open their APIs." },
    { question: "Does the app work without connected appliances?", answer: "Yes. Without connected appliances, Innit operates as an intelligent recipe guide with step-by-step voice instructions, precise timing, and technique guidance. Users still see significantly better results (78% success rate vs 57% without any guidance) even without appliance automation—though the 92% success rate requires connected appliances for adaptive control." },
    { question: "How does Innit handle recipe scaling?", answer: "Recipe scaling is deeply integrated into the cooking intelligence layer. When a recipe is scaled from 4 to 8 servings, the system recalculates not just ingredient quantities but also cooking times, temperatures, and vessel sizes—a doubled batch in the same pan may require different heat settings and longer cooking time than simply doubling the timer." },
    { question: "Can the system handle dietary substitutions?", answer: "Yes. The recipe intelligence layer includes a substitution graph that maps dietary substitutions (vegan butter for regular butter, gluten-free flour for wheat flour) and adjusts cooking parameters accordingly. Gluten-free baked goods may require different temperatures and times than their wheat equivalents—the system knows these differences." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function InnitCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
