'use client'
import { IndustryPageTemplate, IndustryPageData } from "@/components/industries/IndustryPageTemplate";
import {
  HeartPulse, Stethoscope, Brain, FileText, Clock, Activity,
  CalendarCheck, FileSearch, DollarSign, Eye, Users, Zap, ShieldCheck, BarChart3, MessageSquare
} from "lucide-react";

const data: IndustryPageData = {
  industry: "Healthcare",
  slug: "healthcare-ai-solutions",
  accent: "emerald",
  heroIcon: HeartPulse,
  breadcrumb: "Healthcare AI Solutions",
  heroTitle: "How AI Is Used in",
  heroTitleHighlight: "Healthcare",
  heroSubtitle: "AI in healthcare automates patient intake, assists clinical decisions, reduces administrative burden, accelerates diagnostics, manages revenue cycles, and improves patient outcomes — while maintaining human oversight and HIPAA compliance at every step.",
  directAnswer: "AI in healthcare is used to automate patient intake, assist clinical decisions, reduce administrative burden, accelerate diagnostics, manage revenue cycles, and improve patient outcomes — while maintaining human oversight and HIPAA compliance at every step. It enables healthcare organizations to do more with less, without replacing clinical judgment.",
  signatureQuote: "AI succeeds in healthcare only when it strengthens trust — not when it replaces judgment. We don't build 'AI doctors.' We build decision-support intelligence that healthcare professionals can rely on.",
  signatureAuthor: "Santosh Singh, Founder & CEO, AGIX Technologies",
  heroCards: [
    { icon: Clock, title: "Patient Intake AI", desc: "40–60% faster intake, 24/7 availability" },
    { icon: FileText, title: "Clinical Documentation", desc: "1–2 hrs/day reclaimed per clinician" },
    { icon: CalendarCheck, title: "Care Coordination", desc: "25–40% no-show reduction" },
    { icon: DollarSign, title: "Revenue Cycle", desc: "35–50% claim rejection reduction" },
  ],
  aeoAnswer: "AI in healthcare is used to automate patient intake, assist clinical decisions, reduce administrative burden, accelerate diagnostics, manage revenue cycles, and improve patient outcomes — while maintaining human oversight and HIPAA compliance. It enables healthcare organizations to do more with less, without replacing clinical judgment.",
  statsHeadline: "Why Healthcare Needs AI Now",
  stats: [
    { value: "$36.7B", label: "Healthcare AI market (2025)", icon: BarChart3 },
    { value: "38.9%", label: "CAGR — fastest-growing AI vertical", icon: Activity },
    { value: "66%", label: "of physicians used AI in 2025 (AMA)", icon: Users },
    { value: "73%", label: "of patients face care delays globally", icon: Clock },
    { value: "54%", label: "physician burnout rate in 2025", icon: HeartPulse },
  ],
  definitionTitle: "What Is Healthcare AI?",
  definitionText: "Healthcare AI applies machine learning, NLP, computer vision, and agentic AI to clinical and operational workflows — including patient intake, documentation, diagnostics, revenue cycle, and care coordination. It enables healthcare organizations to process decisions faster, support clinical judgment more reliably, and maintain HIPAA-compliant audit readiness at scale. Unlike general software, healthcare AI learns from data, improves over time, and generates probabilistic recommendations — always with human oversight at every clinical decision point.",
  howItWorksTitle: "How Healthcare AI Works — Simplified",
  howItWorksSteps: [
    { title: "Patient provides input", desc: "Symptoms, questions, documents — via chat, voice, or form", icon: MessageSquare },
    { title: "AI structures the data", desc: "Converts unstructured input into organized, actionable information", icon: Brain },
    { title: "AI retrieves knowledge", desc: "Searches clinical guidelines, patient history, policies, and protocols", icon: FileSearch },
    { title: "AI generates a recommendation", desc: "With source citations, confidence scoring, and reasoning", icon: Zap },
    { title: "Human clinician validates", desc: "Reviews, approves, modifies, or overrides the AI suggestion", icon: ShieldCheck },
    { title: "System learns from outcome", desc: "Feedback loops improve accuracy over time", icon: Activity },
  ],
  comparisonTitle: "AI vs Traditional Healthcare Operations",
  comparisonSubtitle: "The choice isn't AI vs clinicians. It's: clinicians drowning in admin vs clinicians supported by AI.",
  comparisonRows: [
    { dimension: "Patient intake", traditional: "15–25 min manual form filling, front desk bottleneck", ai: "3–5 min pre-visit AI collection via chat/voice, zero wait" },
    { dimension: "Triage decisions", traditional: "Varies by staff experience, inconsistent across shifts", ai: "Consistent, evidence-based, 24/7, 99%+ detection rate" },
    { dimension: "Clinical documentation", traditional: "2–3 hours/day per clinician, post-visit charting", ai: "Ambient AI generates notes during encounter, clinician reviews" },
    { dimension: "Follow-up coordination", traditional: "Staff-dependent, phone calls during business hours", ai: "Automated multi-channel (voice, WhatsApp, SMS), 24/7" },
    { dimension: "Claims processing", traditional: "8–15% rejection rate, manual correction cycles", ai: "AI pre-screens, flags errors before submission, 35–50% rejection reduction" },
    { dimension: "Knowledge retrieval", traditional: "Search through docs, ask colleagues, 15+ minutes", ai: "RAG-powered instant answer with source citation, 30 seconds" },
    { dimension: "Scaling capacity", traditional: "Hire more staff (linear cost increase)", ai: "Same AI system handles 10x volume (non-linear scaling)" },
  ],
  benefitsTitle: "Key Benefits of AI in Healthcare",
  benefits: [
    { icon: Clock, title: "Faster Intake", value: "40–60%", detail: "Reduction in average patient intake time with 24/7 availability" },
    { icon: FileText, title: "Time Reclaimed", value: "1–2 hrs/day", detail: "Per clinician from documentation and admin tasks" },
    { icon: CalendarCheck, title: "No-Show Reduction", value: "25–40%", detail: "Automated multi-channel follow-up and reminders" },
    { icon: DollarSign, title: "Claim Rejection Cut", value: "35–50%", detail: "Pre-submission AI screening catches errors before they cost money" },
    { icon: Eye, title: "Radiologist Workload", value: "−30%", detail: "AI pre-screens scans and flags anomalies for expert review" },
    { icon: Users, title: "Patient Access", value: "10x", detail: "Mental health and between-session care expansion" },
  ],
  useCasesTitle: "Best Use Cases of AI in Healthcare",
  useCasesSubtitle: "Each use case detailed below with AGIX services, intelligence frameworks, case studies, and outcomes.",
  useCasesSummary: [
    { num: "1", title: "Patient Intake & Triage", what: "Collects symptoms via chat/voice, prioritizes urgency", impact: "40–60% faster intake" },
    { num: "2", title: "Clinical Documentation", what: "Ambient notes, auto-generated reports", impact: "1–2 hours/day reclaimed per clinician" },
    { num: "3", title: "Patient Flow & Coordination", what: "Multi-agent scheduling, routing, follow-ups", impact: "65% admin overhead reduction" },
    { num: "4", title: "Clinical Decision Support", what: "RAG-powered guideline retrieval, evidence-based suggestions", impact: "Queries: 12 min → 90 sec" },
    { num: "5", title: "Revenue Cycle & Claims", what: "Pre-submission claim review, coding error detection", impact: "35–50% rejection reduction" },
    { num: "6", title: "Patient Engagement", what: "Voice/chat follow-ups, reminders, adherence monitoring", impact: "25–40% no-show reduction" },
    { num: "7", title: "Medical Imaging", what: "AI pre-screens scans, flags anomalies for review", impact: "30% radiologist workload reduction" },
    { num: "8", title: "Mental Health Support", what: "Empathetic AI companions, crisis detection, between-session care", impact: "10x patient access expansion" },
  ],
  useCasesDetailTitle: "How AI Solves the 8 Critical Healthcare Bottlenecks",
  useCasesDetail: [
    {
      title: "Patient Intake & Triage",
      definition: "Conversational AI collects structured patient information before arrival — via web chat, WhatsApp, or voice. AI-assisted triage prioritizes cases based on symptom severity, medical history, and urgency signals.",
      bottleneck: "Long wait times. Manual symptom collection. Inconsistent triage decisions. Overcrowded reception desks and OPDs.",
      howAISolvesIt: [
        "Pre-arrival AI collects structured patient information via web or SMS before appointment",
        "Symptom-based routing assigns patients to appropriate care pathways automatically",
        "Smart scheduling prioritizes high-acuity patients and fills cancellation slots",
        "Real-time triage dashboard gives clinical staff live patient flow visibility",
      ],
      services: [
        { label: "Conversational AI Chatbots", href: "/services/conversational-ai-chatbots/" },
        { label: "AI Voice Agents", href: "/services/ai-voice-agents/" },
        { label: "AI Automation", href: "/services/ai-automation/" },
      ],
      intelligence: "Conversational Intelligence — Level 3 (Context-Aware) for symptom collection; Level 4 (Reasoning) for triage logic",
      caseStudy: { label: "Babylon Health — 99.2% serious case detection rate", href: "/case-studies/babylon-health/" },
      outcome: "40–60% reduction in average intake time. Consistent triage decisions 24/7.",
    },
    {
      title: "Clinical Documentation & Admin Support",
      bottleneck: "Clinicians spend more time documenting than treating. 35% of healthcare professionals spend less time with patients than on administrative tasks.",
      howAISolvesIt: [
        "Voice capture converts clinical conversations into structured draft notes",
        "Ambient AI listens, generates summaries, and syncs approved notes to EMR",
        "AI pre-fills encounter templates using patient history and presenting symptoms",
        "Post-encounter actions (follow-up orders, referrals) are auto-suggested for clinician review",
      ],
      services: [
        { label: "AI Voice Agents", href: "/services/ai-voice-agents/" },
        { label: "RAG & Knowledge AI", href: "/services/rag-knowledge-ai/" },
        { label: "AI Automation", href: "/services/ai-automation/" },
      ],
      intelligence: "Operational Intelligence — Layer 2 (Understanding) for ambient documentation",
      outcome: "1–2 hours reclaimed per clinician per day. 35% of healthcare professionals report spending less time with patients than on admin — AI fixes this.",
    },
    {
      title: "Patient Flow & Care Coordination",
      bottleneck: "Complex multi-department care journeys lack coordination. Patients fall through the cracks between handoffs, leading to missed follow-ups and readmissions.",
      howAISolvesIt: [
        "Multi-agent AI coordinates scheduling, routing, and follow-ups across departments",
        "Automated personalized follow-up messages via SMS, WhatsApp, or email",
        "Care coordination agents track transitions between departments and providers",
        "AI monitors post-discharge indicators and flags high-risk patients for clinical review",
      ],
      services: [
        { label: "Agentic AI Systems", href: "/services/agentic-ai-systems/" },
        { label: "AI Automation", href: "/services/ai-automation/" },
        { label: "Conversational AI Chatbots", href: "/services/conversational-ai-chatbots/" },
      ],
      intelligence: "Autonomous Agentic Systems — L2 for care coordination workflows",
      outcome: "65% admin overhead reduction. 25–40% reduction in no-shows. 20–35% reduction in 30-day readmissions.",
    },
    {
      title: "Clinical Decision Support",
      bottleneck: "Clinicians query 5+ disconnected systems per decision. Clinical guidelines buried in 200+ page PDFs. Time-critical decisions made without latest evidence.",
      howAISolvesIt: [
        "RAG-powered knowledge retrieval delivers evidence-based answers in 90 seconds — vs 12 minutes of manual search",
        "Differential diagnosis AI surfaces the most probable diagnoses ranked by likelihood with supporting evidence",
        "Drug interaction checking integrated into prescribing workflow flags contraindications before harm",
        "Clinical guidelines retrieved with source citations and confidence scores — clinician always reviews and decides",
      ],
      services: [
        { label: "RAG & Knowledge AI", href: "/services/rag-knowledge-ai/" },
        { label: "Enterprise Knowledge AI", href: "/intelligence/enterprise-knowledge-ai/" },
      ],
      intelligence: "Enterprise Knowledge Intelligence — Stage 4 for clinical knowledge retrieval",
      caseStudy: { label: "Mayo Clinic — 30% diagnostic time cut, 15% fewer unnecessary procedures", href: "/case-studies/mayo-clinic/" },
      outcome: "Clinical queries reduced from 12 minutes to 90 seconds. Fewer near-misses. More confident clinical decisions — all with full audit trail.",
    },
    {
      title: "Revenue Cycle & Claims",
      bottleneck: "8–15% claim rejection rates. Manual correction cycles. Slow reimbursements. Coding inconsistencies between providers.",
      howAISolvesIt: [
        "AI pre-screens claims for coding errors, missing data, and compliance gaps before submission",
        "Automated denial management identifies patterns and corrects root causes systematically",
        "Medical coding AI suggests accurate codes from clinical documentation",
        "Real-time eligibility verification reduces claim submission errors at source",
      ],
      services: [
        { label: "AI Automation", href: "/services/ai-automation/" },
        { label: "AI Predictive Analytics", href: "/services/ai-predictive-analytics/" },
        { label: "Computer Vision", href: "/services/ai-computer-vision/" },
      ],
      intelligence: "Operational Intelligence — Layer 3 (Prediction) for rejection risk scoring",
      outcome: "35–50% claim rejection reduction. Faster reimbursements. Reduced denial management cost.",
    },
    {
      title: "Patient Engagement & Follow-Up",
      bottleneck: "Follow-ups depend on manual reminders, disconnected patient engagement systems, and overloaded care teams. Patients go dark between visits.",
      howAISolvesIt: [
        "Automated personalized follow-up via SMS, WhatsApp, voice, or email",
        "AI monitors medication adherence, appointment compliance, and symptom progression",
        "Proactive outreach for chronic disease management and preventive care",
        "Consent-based engagement — all outreach is transparent and opt-in",
      ],
      services: [
        { label: "AI Voice Agents", href: "/services/ai-voice-agents/" },
        { label: "Conversational AI Chatbots", href: "/services/conversational-ai-chatbots/" },
        { label: "AI Automation", href: "/services/ai-automation/" },
      ],
      outcome: "25–40% no-show reduction. Continuous between-visit engagement. Improved chronic disease management outcomes.",
    },
    {
      title: "Medical Imaging AI",
      bottleneck: "Radiologist shortages, image backlogs, and fatigue-related errors. 340+ FDA-approved AI tools, primarily diagnostics — the evidence base is established.",
      howAISolvesIt: [
        "AI pre-screens scans and flags anomalies for expert radiologist review",
        "Computer vision detects patterns (tumors, fractures, bleeds) with documented accuracy",
        "Prioritization queue ensures critical findings reach radiologists first",
        "AI-assisted reporting drafts preliminary findings for radiologist review and approval",
      ],
      services: [
        { label: "Computer Vision", href: "/services/ai-computer-vision/" },
        { label: "AI Predictive Analytics", href: "/services/ai-predictive-analytics/" },
      ],
      intelligence: "Operational Intelligence — Layer 3–4 for imaging workflow automation",
      outcome: "30% radiologist workload reduction. AI CT scan for stroke: recovery rate 16% → 48%, treatment under 80 minutes (NHS).",
    },
    {
      title: "Mental Health Support AI",
      bottleneck: "Mental health care faces severe access and capacity constraints. Between-session gaps leave patients unsupported.",
      howAISolvesIt: [
        "Empathetic AI companions provide between-session check-ins and coping support",
        "Crisis detection identifies escalating risk signals and triggers human intervention",
        "Mood tracking and journaling AI gives therapists richer session context",
        "Group session facilitation AI reduces therapist administrative burden",
      ],
      services: [
        { label: "Conversational AI Chatbots", href: "/services/conversational-ai-chatbots/" },
        { label: "Custom AI Product Development", href: "/services/custom-ai-product-development/" },
      ],
      intelligence: "Conversational Intelligence — Level 4 (Reasoning) for empathetic, context-aware mental health conversations",
      outcome: "10x patient access expansion. Between-session support without proportional therapist cost increase.",
    },
  ],
  frameworkTitle: "The AGIX Healthcare Intelligence Framework",
  frameworkLayers: [
    { num: "01", name: "Patient Intelligence", what: "Collects, structures, and prioritizes patient data at every touchpoint", how: "Patient data feeds clinical and operational decisions", icon: Users },
    { num: "02", name: "Clinical Intelligence", what: "Supports diagnosis, treatment planning, and documentation", how: "Clinical outcomes improve prediction and knowledge models", icon: Stethoscope },
    { num: "03", name: "Operational Intelligence", what: "Optimizes scheduling, flow, staffing, and resource allocation", how: "Operations data validates patient intelligence signals", icon: Activity },
    { num: "04", name: "Financial Intelligence", what: "Manages revenue cycle, claims, and compliance reporting", how: "Financial data feeds operational planning and risk monitoring", icon: DollarSign },
  ],
  frameworkQuote: "Healthcare AI works best when it's invisible — clinicians don't notice AI; they notice fewer errors, faster answers, and more time with patients. The moment AI adds friction instead of removing it, trust is lost.",
  governanceTitle: "Is AI in Healthcare Safe? Governance & Compliance",
  governancePrinciples: [
    { principle: "HIPAA Compliance", meaning: "All patient data encrypted, access-controlled, and handled under HIPAA throughout the entire AI pipeline" },
    { principle: "Human-in-the-Loop", meaning: "Every clinical recommendation reviewed by a qualified clinician. AI recommends; humans decide" },
    { principle: "Audit Trails", meaning: "Every AI action logged: input data, model version, confidence score, decision, outcome — audit-ready" },
    { principle: "Explainable AI", meaning: "Recommendations include reasoning, evidence citations, and confidence scores — not black-box outputs" },
    { principle: "Bias Monitoring", meaning: "Continuous monitoring for demographic or socioeconomic bias in triage, diagnosis, and treatment recommendations" },
    { principle: "Model Governance", meaning: "Versioned models with rollback capability. Retraining governance. Performance monitoring and drift detection" },
  ],
  limitationsTitle: "Limitations of AI in Healthcare",
  limitations: [
    { title: "AI cannot replace clinical judgment.", desc: "AI supports; clinicians decide. No AI system should autonomously make irreversible clinical decisions without human validation." },
    { title: "Quality depends on data quality.", desc: "Outdated or incomplete EMR data produces unreliable AI recommendations. Data governance is a prerequisite, not an afterthought." },
    { title: "Bias in training data → biased outcomes.", desc: "Historical data encoding systemic disparities produces AI that perpetuates them. Continuous fairness monitoring is non-negotiable." },
    { title: "Regulatory complexity varies by jurisdiction.", desc: "FDA, CE marking, HIPAA, GDPR — compliance requirements differ by use case, geography, and risk class. Legal review is required." },
  ],
  limitationsQuote: "The promise of AI in healthcare isn't replacing clinicians — it's giving every clinician the equivalent of a research assistant, scheduler, and documentation support. But the clinician remains the architect of the care experience.",
  pricingTitle: "How Much Does Healthcare AI Cost?",
  pricingSubtitle: "Transparent investment ranges and implementation timelines.",
  pricingRows: [
    { system: "Patient Intake & Triage AI", investment: "$5,000–$8,000", timeline: "5–8 weeks" },
    { system: "Clinical Documentation AI", investment: "$6,000–$10,000", timeline: "6–10 weeks" },
    { system: "Care Coordination System", investment: "$8,000–$12,000", timeline: "8–12 weeks" },
    { system: "Clinical Decision Support", investment: "$10,000–$14,000", timeline: "10–14 weeks" },
    { system: "Revenue Cycle AI", investment: "$6,000–$10,000", timeline: "6–10 weeks" },
    { system: "Patient Engagement AI", investment: "$4,000–$7,000", timeline: "4–7 weeks" },
    { system: "Full Healthcare Platform", investment: "$16,000–$24,000", timeline: "16–24 weeks" },
  ],
  futureTitle: "The Future of AI in Healthcare by 2028",
  futureItems: [
    { num: "1", title: "340+ FDA-approved AI tools expand to 1,000+ across diagnostics, monitoring, and care coordination" },
    { num: "2", title: "Every patient gets a persistent AI health companion across providers and years" },
    { num: "3", title: "Ambient AI becomes standard in clinical encounters — documentation disappears as a task" },
    { num: "4", title: "Agentic AI coordinates entire care journeys across departments autonomously within governance rules" },
    { num: "5", title: "Predictive population health AI identifies and intervenes before conditions become acute" },
  ],
  relatedIndustries: [
    { name: "Fintech & Lending", href: "/industries/fintech-ai-solutions/" },
    { name: "Insurance", href: "/industries/insurance-ai-solutions/" },
    { name: "Real Estate", href: "/industries/real-estate-ai-solutions/" },
    { name: "Retail & eCommerce", href: "/industries/retail-ai-solutions/" },
    { name: "Logistics & Supply Chain", href: "/industries/logistics-ai-solutions/" },
    { name: "Hospitality & Wellness", href: "/industries/hospitality-ai-solutions/" },
    { name: "EdTech & E-Learning", href: "/industries/edtech-ai-solutions/" },
  ],
  faqs: [
    { q: "How is AI used in healthcare?", a: "AI automates patient intake, supports clinical decisions, reduces admin burden, accelerates diagnostics, manages revenue cycles, and improves patient outcomes — while maintaining HIPAA compliance and human oversight at every step." },
    { q: "Is healthcare AI HIPAA compliant?", a: "Yes — when built correctly. AGIX builds with HIPAA compliance as a foundation: data encryption, access controls, audit logging, and no patient data used for model training without consent." },
    { q: "Can AI replace doctors?", a: "No — and AGIX doesn't build AI doctors. We build decision-support intelligence that clinicians can rely on. AI recommends; humans always decide." },
    { q: "What is the ROI of healthcare AI?", a: "Documented outcomes include: 40–60% faster patient intake, 1–2 hours/day reclaimed per clinician, 35–50% claim rejection reduction, 25–40% no-show reduction, and 30% radiologist workload reduction." },
    { q: "How long does healthcare AI implementation take?", a: "Focused systems: 5–8 weeks. Multi-system deployments: 10–16 weeks. Full healthcare platform: 16–24 weeks." },
    { q: "What is AI clinical documentation?", a: "Ambient AI listens to clinical encounters, generates structured draft notes, and presents them for clinician review — eliminating hours of post-visit charting without replacing clinical judgment." },
    { q: "How much does healthcare AI cost?", a: "Starting from $12K for focused systems. Most deployments range $20K–$60K. Full platforms from $75K. All include governance, compliance setup, and training." },
    { q: "What are the limitations of AI in healthcare?", a: "Key limitations: AI cannot replace clinical judgment, quality depends on data quality, bias monitoring is required, and regulatory compliance varies by use case and jurisdiction." },
    { q: "Can AI reduce physician burnout?", a: "Yes — 54% of physicians experienced burnout in 2025. The #1 fixable driver is admin burden. AI documentation, scheduling, and workflow automation reclaims 1–2 hours per clinician per day." },
    { q: "What is AI patient triage?", a: "AI patient triage uses conversational AI to collect symptoms, assess urgency, and route patients to the right care pathway — consistently, 24/7, without front desk bottlenecks." },
    { q: "Is AI safe for clinical decisions?", a: "With governance: yes. AI provides evidence-based recommendations with confidence scores and source citations. Clinicians always review and approve. No autonomous clinical decisions without human validation." },
    { q: "Which healthcare AI use case should I start with?", a: "Patient intake and documentation — both deliver immediate ROI, low clinical risk, and create the data foundation for more advanced AI use cases. Most clients see measurable results within 8 weeks." },
  ],
  formHeadline: "Get Your Free Healthcare AI Strategy",
  formSubheadline: "Tell us your biggest clinical or operational challenge and we'll show you exactly how AI can solve it — with real timelines, real costs, and a clear starting point.",
  formLeftTitle: "Ready to Deploy AI in Your Healthcare Organization?",
  formLeftBullets: [
    "Free healthcare AI strategy session — HIPAA compliance built in",
    "Clinical use case mapping specific to your specialty",
    "Realistic implementation roadmap with governance",
    "Honest cost estimates starting from $15K",
  ],
  challengeOptions: [
    { value: "patient-intake", label: "Patient Intake & Triage Delays" },
    { value: "clinical-documentation", label: "Clinical Documentation Burden" },
    { value: "care-coordination", label: "Care Coordination & Follow-Up" },
    { value: "clinical-decision", label: "Clinical Decision Support" },
    { value: "revenue-cycle", label: "Revenue Cycle & Claims" },
    { value: "patient-engagement", label: "Patient Engagement & Adherence" },
    { value: "medical-imaging", label: "Medical Imaging & Diagnostics" },
    { value: "mental-health", label: "Mental Health Platform" },
  ],
  formCtaLabel: "Get My Free Healthcare AI Strategy",
  formIndustry: "Healthcare",
};

export default function HealthcareAISolutionsPage() {
  return <IndustryPageTemplate data={data} />;
}
