export interface URLMetadata {
  focusKeyword: string;
  keywords: string;
  mainHeading: string;
  metaTitle: string;
  metaDescription: string;
  ogTitle: string;
  ogDescription: string;
  twitterTitle: string;
  twitterDescription: string;
  featuredImage?: string;
  schemas?: string[];
}

export const urlMetadataConfig: Record<string, URLMetadata> = {
  '/': {
    focusKeyword: 'AI Systems Engineering & Agentic Intelligence Company',
    keywords: 'AI systems engineering, agentic intelligence company, autonomous AI systems, enterprise AI solutions, AI voice agents, AI architecture, Conversational AI',
    mainHeading: 'Not Sure Where to Start With AI?',
    metaTitle: 'AI Systems Engineering & Agentic Intelligence | Agix',
    metaDescription: 'Agix Technologies delivers enterprise AI systems engineering and autonomous agent development, helping Fortune 500 companies achieve 40% operational efficiency gains.',
    ogTitle: 'AI Systems Engineering & Agentic Intelligence Company',
    ogDescription: 'Enterprise-grade AI Systems Engineering and Agentic Intelligence solutions strategy, architecture, and deployment that drive real business outcomes.',
    twitterTitle: 'AI Systems Engineering & Agentic Intelligence Company',
    twitterDescription: 'We build enterprise AI systems and agentic intelligence solutions that move from strategy to scalable, ROI-driven deployment.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Systems-Engineering-Company-page-banner.png',
    schemas: ['Organization', 'WebSite', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/intelligence/operational-ai': {
    focusKeyword: 'Operational AI',
    keywords: 'operational ai, operational ai intelligence, ai for operations, operational ai systems, operational intelligence ai, ai-powered operational intelligence, real-time operational ai, operational decision intelligence, operational ai services',
    mainHeading: 'Operational Intelligence That Keeps Your Business Running Smoothly',
    metaTitle: 'Operational AI Solutions | Agix Technologies',
    metaDescription: 'Agix Operational AI monitors and optimizes business processes in real-time, detecting anomalies within 30 seconds and preventing system failures.',
    ogTitle: 'Operational AI Solutions for Real-Time Business Operations',
    ogDescription: 'AI-powered operational intelligence systems delivering real-time insights and autonomous decision-making for complex business operations.',
    twitterTitle: 'Operational AI | Real-Time AI for Business Operations',
    twitterDescription: 'Operational AI systems that turn real-time operational data into intelligent, autonomous decisions for modern enterprises.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Operational-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/conversational-ai': {
    focusKeyword: 'Conversational AI',
    keywords: 'conversational ai, conversational intelligence, enterprise conversational ai, conversational ai solutions, conversational ai systems, conversational ai platforms',
    mainHeading: 'Conversational Intelligence That Understands, Not Just Responds',
    metaTitle: 'Conversational AI Solutions | Enterprise Conversational Intelligence',
    metaDescription: 'Enterprise Conversational AI solutions that combine conversational intelligence, AI systems, and platforms to build assistants that truly understand business context.',
    ogTitle: 'Enterprise Conversational AI & Conversational Intelligence Solutions',
    ogDescription: 'Build enterprise Conversational AI systems and platforms powered by conversational intelligence that go beyond chatbots to deliver real business outcomes.',
    twitterTitle: 'Conversational AI | Enterprise Conversational Intelligence',
    twitterDescription: 'Enterprise Conversational AI solutions built with conversational intelligence, scalable AI systems, and modern conversational platforms.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Conversations-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/decision-ai': {
    focusKeyword: 'Decision AI',
    keywords: 'decision intelligence, decision ai, decision intelligence solutions, enterprise decision intelligence, decision intelligence systems, ai decision intelligence, decision intelligence platform, intelligent decision systems, agentic ai decision intelligence, intelligent decision support systems',
    mainHeading: 'Decision Intelligence That Helps You Choose Right — Every Time',
    metaTitle: 'Decision AI Solutions | Agix Technologies',
    metaDescription: 'Agix Decision AI processes real-time data streams to automate critical business decisions, improving response times from hours to just milliseconds.',
    ogTitle: 'Decision AI & Enterprise Decision Intelligence Solutions | Agix Technologies',
    ogDescription: 'Build enterprise Decision Intelligence systems powered by Decision AI, agentic intelligence, and intelligent decision support for complex business decisions.',
    twitterTitle: 'Decision AI & Decision Intelligence for Enterprises | AgixTech',
    twitterDescription: 'Enterprise Decision AI and Decision Intelligence solutions using intelligent decision systems and agentic AI to drive better business outcomes.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Decision-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/autonomous-agentic-ai': {
    focusKeyword: 'Agentic AI',
    keywords: 'autonomous agentic systems, autonomous agentic ai, autonomous ai agents, agentic ai autonomous systems, agentic ai autonomous intelligence, autonomous agentic systems intelligence, autonomous agentic intelligence, enterprise autonomous agents',
    mainHeading: 'Autonomous Agentic Systems That Act With Purpose — Not Chaos',
    metaTitle: 'Autonomous Agentic AI Systems | Agix Technologies',
    metaDescription: 'Agix builds autonomous AI agents that execute complex workflows independently, reducing manual intervention by 85% for enterprise business operations.',
    ogTitle: 'Autonomous Agentic Systems & Enterprise Autonomous AI Agents',
    ogDescription: 'Build Autonomous Agentic Systems using agentic AI and autonomous agents that plan, decide, and act with governance and control.',
    twitterTitle: 'Autonomous Agentic Systems | Autonomous AI Agents',
    twitterDescription: 'Enterprise Autonomous Agentic Systems built with agentic AI and autonomous agents designed for control, coordination, and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Autonomous-Agent-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/enterprise-knowledge-ai': {
    focusKeyword: 'Enterprise Knowledge AI',
    keywords: 'Enterprise Knowledge AI, Knowledge Intelligence, Enterprise Knowledge Intelligence, Knowledge Intelligence Systems, AI-powered Knowledge Intelligence, Knowledge Intelligence for AI Systems',
    mainHeading: 'Enterprise Knowledge Intelligence You Can Trust — Not Just Retrieve',
    metaTitle: 'Enterprise Knowledge AI Systems | Agix Technologies',
    metaDescription: 'Agix Knowledge AI transforms unstructured enterprise data into intelligent systems that answer complex business queries with 98% contextual accuracy.',
    ogTitle: 'Enterprise Knowledge & Knowledge Management Systems | Agix Technologies',
    ogDescription: 'Build trusted Enterprise Knowledge AI using Knowledge Intelligence systems designed for governed, reliable AI decision-making and autonomous systems.',
    twitterTitle: 'Enterprise Knowledge AI & Knowledge Intelligence',
    twitterDescription: 'Enterprise Knowledge AI powered by Knowledge Intelligence systems that deliver trusted, governed knowledge for AI-driven decisions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Knowledge-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/services/ai-automation': {
    focusKeyword: 'AI Automation Services',
    keywords: 'AI Automation Services, Enterprise AI Automation, AI Business Automation Services, Intelligent Automation Services, AI Workflow Automation Services, AI Automation Agency, AI Automation Company, AI Business Process Automation',
    mainHeading: 'Engineering AI Automation That Eliminates Manual Operations',
    metaTitle: 'AI Automation Services | Intelligent Workflow Solutions',
    metaDescription: 'Intelligent workflow automation reduces manual tasks by 80% using AI agents, process mining, and RPA integration for enterprise transformation.',
    ogTitle: 'AI Automation Services to Reduce Costs & Scale Operations | AGIX Technologies',
    ogDescription: 'Automate manual workflows and reduce operational costs with AI-driven business process automation. Deploy intelligent automation across your enterprise systems.',
    twitterTitle: 'AI Automation Company for Intelligent Business Workflows & Process Automation',
    twitterDescription: 'Build intelligent workflows with AI automation services that integrate with CRMs, ERPs & enterprise tools. Automate decisions, routing, and operations at scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Automation-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-voice-agents': {
    focusKeyword: 'AI Voice Agents',
    keywords: 'AI Voice Agents, AI voice agent services, AI voice agent solutions, AI-powered voice agent, AI Phone Agents, AI voice agent for businesses, Best ai voice agent services, AI voice automation services, Voice AI solutions, Enterprise AI voice agents',
    mainHeading: 'AI Voice Agents That Talk, Think & Take Action',
    metaTitle: 'AI Voice Agents | Business Phone AI & Voice Solutions',
    metaDescription: 'AI voice agents handle 24/7 customer calls with natural language processing, speech synthesis, and CRM integration for automated phone service.',
    ogTitle: 'AI Voice Agents That Talk, Think & Take Action | Agix Technologies',
    ogDescription: 'Automate calls and conversations with AI-powered voice agents built for businesses. Scalable, intelligent, and enterprise-ready voice AI solutions.',
    twitterTitle: 'AI Voice Agent Services & AI Phone Agents for Businesses',
    twitterDescription: 'AI voice agent services for businesses looking to automate calls, improve customer experience, and reduce costs with intelligent voice AI solutions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Intelligent-Voice-Agents-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/conversational-ai-chatbots': {
    focusKeyword: 'Conversational AI Chatbots',
    keywords: 'Conversational AI chatbots, AI chatbot services, AI chatbot solutions, AI-powered chatbots, AI chatbot for businesses, Conversational AI platform, Enterprise AI chatbots, Intelligent AI chatbots, AI chatbot platform, enterprise ai chatbot solution',
    mainHeading: 'Conversational AI That Works Across Support, Sales & Operations',
    metaTitle: 'Conversational AI Chatbots | Business AI Chat Solutions',
    metaDescription: 'Enterprise chatbots with NLP, intent recognition, and multi-channel deployment handle customer queries with 95% accuracy and seamless handoff support.',
    ogTitle: 'Conversational AI Chatbots That Work Across Support, Sales & Ops',
    ogDescription: 'AI-powered conversational chatbots that work across customer support, sales, and operations. Scalable AI chatbot solutions for modern businesses.',
    twitterTitle: 'Conversational AI Chatbots for Support, Sales & Operations',
    twitterDescription: 'Enterprise-grade conversational AI chatbots that automate conversations, improve customer experience, and scale business operations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Conversations-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/agentic-ai-systems': {
    focusKeyword: 'Agentic AI Systems',
    keywords: 'Agentic AI Systems, Agentic AI solutions, Agentic AI services, Autonomous AI agents, Agentic AI systems for enterprises, Enterprise agentic AI solutions, Intelligent autonomous agents, Agentic AI service provider',
    mainHeading: "Agentic AI Systems That Don't Just Respond — They Operate",
    metaTitle: 'Agentic AI Systems | Autonomous Enterprise AI Agents',
    metaDescription: 'Autonomous AI agents execute complex workflows, make decisions, and integrate with enterprise systems using multi-agent architectures and reasoning.',
    ogTitle: 'Agentic AI Systems That Plan, Decide & Operate Autonomously',
    ogDescription: 'Agentic AI systems for enterprises that replace static automation with intelligent autonomous agents that execute, adapt, and optimize workflows.',
    twitterTitle: 'Agentic AI Systems That Plan, Decide & Operate Autonomously',
    twitterDescription: 'Deploy enterprise-grade agentic AI systems with intelligent autonomous agents built to handle complex workflows, decisions, and execution at scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Agentic-AI-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/rag-knowledge-ai': {
    focusKeyword: 'RAG Services',
    keywords: 'RAG Knowledge AI, Retrieval Augmented Generation services, RAG AI services, RAG AI solutions, Knowledge AI systems, Enterprise RAG solutions, RAG development services, Custom RAG solutions, RAG AI service provider',
    mainHeading: 'Make AI Answer From Your Knowledge — Not the Internet',
    metaTitle: 'RAG Knowledge AI Services | Enterprise Retrieval | Agix',
    metaDescription: 'RAG Knowledge AI combines vector databases with LLMs for enterprise document retrieval. 95% accuracy in context-aware responses. Built for compliance.',
    ogTitle: 'Enterprise RAG Knowledge AI | Retrieval Augmented Generation Services',
    ogDescription: 'Turn your enterprise knowledge into reliable AI. Our RAG Knowledge AI services deliver grounded, secure, and scalable Retrieval Augmented Generation systems.',
    twitterTitle: 'RAG Knowledge AI Solutions for Accurate, Trusted Enterprise AI',
    twitterDescription: 'Deploy RAG Knowledge AI systems that answer from your data—not the internet. Enterprise Retrieval Augmented Generation services built for trust and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/RAG-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-predictive-analytics': {
    focusKeyword: 'Predictive Analytics AI',
    keywords: 'predictive analytics ai, ai predictive analytics, ai predictive analytics company, ai predictive analytics services, predictive analytics services, predictive data analytics services, predictive analytics development services, predictive analytics services company, predictive analytics consulting',
    mainHeading: 'Predict What Happens Next — Not What Already Happened',
    metaTitle: 'AI Predictive Analytics Services | Enterprise Forecasting',
    metaDescription: 'Predictive analytics models forecast business outcomes with machine learning, time series analysis, and statistical modeling for data-driven insight.',
    ogTitle: 'Enterprise AI Predictive Analytics & Forecasting Solutions | AGIX Technologies',
    ogDescription: 'AGIXTech helps enterprises move from reactive to proactive decision-making with AI predictive analytics, forecasting models, risk scoring, and decision intelligence systems.',
    twitterTitle: 'AI Predictive Analytics for Enterprise Decision Intelligence | AGIX Technogies',
    twitterDescription: 'Forecast outcomes, reduce risk, and optimize decisions with AI predictive analytics and enterprise-grade forecasting systems.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Predictive-Analytics-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-computer-vision': {
    focusKeyword: 'Computer Vision Services',
    keywords: 'Computer Vision Services, Computer Vision Solutions, Enterprise Computer Vision, AI Computer Vision, Computer Vision Company, Computer Vision Consulting Services, Computer Vision Integration Services, Custom Computer Vision Solutions, Computer Vision Development Company, Computer Vision Consultant, Custom Computer Vision Development Services',
    mainHeading: 'From Pixels to Decisions',
    metaTitle: 'Computer Vision AI Services | Visual Automation Enterprise',
    metaDescription: 'Computer vision APIs for object detection, OCR, quality inspection, and visual automation with 99.5% accuracy using deep learning and edge deployment.',
    ogTitle: 'Computer Vision Services for Enterprise | AI Visual Automation',
    ogDescription: 'We build customized computer vision solutions for image recognition, visual inspection, defect detection, OCR, and real-time video analytics. Transform operations with AI.',
    twitterTitle: 'Computer Vision Services & AI Visual Automation',
    twitterDescription: 'Custom computer vision solutions for image and video analytics, OCR, defect detection, and automation. Scalable AI built for enterprise operations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Computer-Vision-Solutions-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/custom-ai-product-development': {
    focusKeyword: 'Custom AI Develoment Services',
    keywords: 'Custom AI Product Development, AI Product Development Services, AI Product Development Company, Custom AI Software Development, AI Product Engineering Services, End-to-End AI Product Development, AI MVP Development Services, Custom AI Product Development Consultant, ai poc and mvp development services',
    mainHeading: 'From Idea to Market-Ready AI Product',
    metaTitle: 'Custom AI Product Development | Startup Enterprise Solutions',
    metaDescription: 'Custom AI products from prototype to production with machine learning engineering, model optimization, and cloud deployment for scalable solutions.',
    ogTitle: 'Custom AI Product Development Services for Startups & Enterprises',
    ogDescription: 'Turn your idea into a market-ready AI product. We provide end-to-end AI MVP development, LLM engineering, deployment, and scaling with measurable ROI.',
    twitterTitle: 'Custom AI Product Development & MVP Services for AI Startups',
    twitterDescription: 'From idea to market-ready AI product. We help startups build AI MVPs, validate ideas, deploy models, and scale with production-grade engineering and ROI.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Product-Development-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/healthcare-ai-solutions': {
    focusKeyword: 'Healthcare AI Solutions',
    keywords: 'Healthcare AI, AI in Healthcare, Medical AI, Clinical AI, Healthcare automation',
    mainHeading: 'AI Solutions for Healthcare',
    metaTitle: 'AI Healthcare Solutions | Agix Technologies',
    metaDescription: 'Healthcare AI platforms enable predictive diagnostics, patient monitoring, and clinical workflow automation while ensuring HIPAA compliance standards.',
    ogTitle: 'AI-Powered Solutions in Healthcare | AGIX',
    ogDescription: 'Deliver better patient outcomes with AI in healthcare, advanced solutions for clinical efficiency, diagnosis support, and operational improvement.',
    twitterTitle: 'AI Solutions for Smarter Healthcare | Agix Tech',
    twitterDescription: 'Enhance healthcare efficiency and clinician support with reliable, explainable AI designed for real-world clinical environments.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Healthcare-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/real-estate-ai-solutions': {
    focusKeyword: 'Real Estate AI Solutions',
    keywords: 'Real Estate AI, AI for Real Estate, Property AI, Real Estate automation',
    mainHeading: "AI Solutions for Real Estate That Don't Just Explain — They Show You What to Build",
    metaTitle: 'Real Estate AI Solutions: Property Tech Innovation',
    metaDescription: 'Real estate AI solutions automate property valuation, document processing, and lead management systems. Agix delivers 40% faster transaction closures.',
    ogTitle: 'Scale Your Business with AI Real Estate Solutions | AGIX',
    ogDescription: 'Deploy AI solutions that respond to inquiries faster, prioritize leads, and keep real estate deals moving without manual dependency.',
    twitterTitle: 'Get Custom AI Solutions for Real Estate | Agix Technologies',
    twitterDescription: 'Purpose-built AI solutions for real estate teams struggling with slow responses, missed follow-ups, and stalled deals.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Real-Estate-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/fintech-ai-solutions': {
    focusKeyword: 'Fintech AI Solutions',
    keywords: 'Fintech AI, AI for Financial Services, Financial AI, Lending AI',
    mainHeading: 'AI Solutions for FinTech & Lending That Show You Where Risk Leaks — and How to Fix It',
    metaTitle: 'AI FinTech Risk & Lending Solutions | Agix Technologies',
    metaDescription: 'FinTech AI systems provide real-time risk assessment, fraud detection, and automated lending decisions with 95% accuracy for financial institutions.',
    ogTitle: 'Advanced AI-Driven FinTech Solutions | Agix Technologies',
    ogDescription: 'Eliminate silent revenue leakage with AI-driven fintech solutions. Deploy intelligent risk models that accelerate approvals and strengthen trust.',
    twitterTitle: 'Secure AI FinTech Solutions for Smart Lending | Agix Tech',
    twitterDescription: 'Modernize your financial services with reliable AI fintech solutions. Get custom roadmaps for fraud detection, credit scoring, and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-solutions-for-FinTech-Industry-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/insurance-ai-solutions': {
    focusKeyword: 'Insurance AI Solutions',
    keywords: 'Insurance AI, AI for Insurance, Claims AI, Underwriting AI',
    mainHeading: 'AI Solutions for Insurance That Accelerate Claims, Reduce Fraud & Improve Risk Decisions',
    metaTitle: 'Insurance AI Solutions: Claims & Underwriting Automation',
    metaDescription: 'Insurance AI solutions streamline claims processing, fraud detection, and underwriting. Agix reduces claim processing time by 70% with 95% accuracy.',
    ogTitle: 'AI-Driven Insurance Solutions | Agix Technologies',
    ogDescription: 'Experience seamless operations with AI-driven insurance solutions. Automate claims processing and detect fraud early to protect your loss ratio.',
    twitterTitle: 'AI Insurance Solutions for Core Insurance Operations',
    twitterDescription: 'Secure your competitive edge with reliable AI insurance solutions. Get custom roadmaps for claims automation and underwriting accuracy today.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Insurance-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/retail-ai-solutions': {
    focusKeyword: 'Retail AI Solutions',
    keywords: 'Retail AI, E-commerce AI, AI for Retail, Shopping AI',
    mainHeading: 'AI Solutions for E-Commerce That Show You Where Revenue Is Leaking — and How to Fix It',
    metaTitle: 'Retail AI Solutions | Agix Technologies',
    metaDescription: 'Agix delivers retail AI solutions including inventory optimization, personalized recommendations, and demand forecasting that boost conversions by 40%.',
    ogTitle: 'Advanced AI-Driven E-Commerce Solutions | AGIX',
    ogDescription: 'Boost your margins with AI-driven e-commerce solutions. Automate returns, optimize inventory, and deliver personalized shopping experiences at scale.',
    twitterTitle: 'AI E-Commerce Solutions for D2C & Retail | Agix Technologies',
    twitterDescription: 'Scale your D2C and retail operations with AI e-commerce solutions. Reduce support load, recover abandoned revenue, and streamline workflows.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-E-Commerce-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/logistics-ai-solutions': {
    focusKeyword: 'Logistics AI Solutions',
    keywords: 'Logistics AI, Supply Chain AI, AI for Logistics, Transportation AI',
    mainHeading: 'AI Solutions for Logistics & Supply Chain That Reveal Where Delays, Costs & Inefficiencies Hide',
    metaTitle: 'Logistics AI Solutions: Supply Chain Optimization',
    metaDescription: 'Logistics AI solutions optimize route planning, inventory management, and demand forecasting. Agix delivers 25% cost reduction in supply chain ops.',
    ogTitle: 'AI-Driven Logistics Solutions | Agix Technologies',
    ogDescription: 'Reduce costs and improve OTIF rates with AI-driven logistics solutions. Deploy intelligent routing and forecasting systems designed for global scale.',
    twitterTitle: 'AI Logistics Solutions for Supply Chain Optimization | Agix Tech',
    twitterDescription: 'Streamline operations with AI logistics solutions that fix bottlenecks, optimize routes, balance inventory, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Logistics-Supply-Chain-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/hospitality-ai-solutions': {
    focusKeyword: 'Hospitality AI Solutions',
    keywords: 'Hospitality AI, AI for Hotels, Hotel AI, Guest Experience AI',
    mainHeading: 'Intelligent AI Solutions That Strengthen Human Connection and Elevate Guest Experiences',
    metaTitle: 'Hospitality AI Solutions: Guest Experience Enhancement',
    metaDescription: 'Hospitality AI solutions enhance guest experience through predictive analytics and automated services. Agix increases guest satisfaction by 40%+.',
    ogTitle: 'AI Solutions for Hospitality & Wellness Operations | Agix Technologies',
    ogDescription: 'Deploy AI in hospitality to improve bookings, reduce no-shows, optimize staff workflows, and elevate guest satisfaction across properties.',
    twitterTitle: 'AI Hospitality Solutions for Premium Guest Experiences | AGIX',
    twitterDescription: 'Modernize your guest journey with AI in hospitality. Reduce friction, automate workflows, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Hospitality-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/edtech-ai-solutions': {
    focusKeyword: 'Edtech AI Solutions',
    keywords: 'EdTech AI, AI for Education, Learning AI, Educational AI',
    mainHeading: 'AI Solutions for EdTech That Show You Where Learners Disengage — and How to Fix It',
    metaTitle: 'AI EdTech Solutions | Agix Technologies',
    metaDescription: 'EdTech platforms leverage AI for personalized learning paths, automated grading, and student performance analytics with 85% engagement increases.',
    ogTitle: 'AI Solutions for EdTech & E-Learning | Agix Technologies',
    ogDescription: 'Deploy AI in EdTech to boost course completion, reduce faculty workload, provide intelligent tutoring, and improve student engagement.',
    twitterTitle: 'AI EdTech Solutions for Smarter Learning | AGIX',
    twitterDescription: 'Modernize your institution with AI in EdTech. Enhance engagement, personalize learning, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-EdTech-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/case-studies': {
    focusKeyword: 'Real-World AI Case Studies',
    keywords: 'AI case studies, enterprise AI implementation, AI success stories, AI ROI examples',
    mainHeading: 'Real-World AI Systems. Proven at Enterprise Scale.',
    metaTitle: 'AI Case Studies | AgixTech',
    metaDescription: 'Discover our AI case studies, which showcase real-world results across various industries, including healthcare, finance, retail, and education.',
    ogTitle: 'Artificial Intelligence Case Studies | Agix Technologies',
    ogDescription: 'Explore AI case studies by AgixTech delivering real-world impact across healthcare, finance, retail, education, and more.',
    twitterTitle: 'AI Case Studies & Success Stories | AGIX',
    twitterDescription: 'Explore AI case studies by AgixTech highlighting real results in healthcare, finance, retail, education, and enterprise.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Artificial-Intelligence-Case-Studies.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'CollectionPage'],
  },

  '/case-studies/enova/': {
    focusKeyword: 'Enova AI Credit Decisioning Case Study',
    keywords: 'Enova case study, AI credit decisioning, explainable AI, fintech AI',
    mainHeading: 'Enova International',
    metaTitle: 'Enova AI Credit Decisioning Case Study | Agix Technologies',
    metaDescription: 'Enova reduced loan approval time by 60% with Agix\'s ML credit scoring models. Real-time risk assessment processing 100,000+ applications monthly.',
    ogTitle: 'Enova International Case Study: Enova AI Credit Decisioning Case Study',
    ogDescription: 'Scale your fintech with confidence! Explore how AGIX ensured bias-free credit decisions and 100% audit coverage for Enova. Read more.',
    twitterTitle: 'Enova International Case Study: Enova AI Credit Decisioning Case Study',
    twitterDescription: 'Boost accuracy and trust! See how AGIX slashed Enova audit time by 67% with transparent, regulator-ready AI models. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Enova-International-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/dave/': {
    focusKeyword: 'Dave Fintech AI Assistant Case Study',
    keywords: 'Dave case study, fintech AI, conversational AI, customer support AI',
    mainHeading: 'Dave',
    metaTitle: 'Dave Fintech AI Assistant Case Study | Agix Technologies',
    metaDescription: 'Dave\'s AI banking assistant processes 1M+ customer queries daily with 94% accuracy. Agix deployed conversational AI for financial services automation.',
    ogTitle: 'Dave Case Study: Fintech AI Assistant Case Study',
    ogDescription: 'Scale your fintech with empathy! Explore how AGIX engineered a conversational AI that handles 94% of inquiries for 10M members.',
    twitterTitle: 'Dave Case Study: Fintech AI Assistant Case Study',
    twitterDescription: 'Boost satisfaction and speed! See how AGIX helped Dave achieve a 93 CSAT score while reducing resolution time by 79%.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Dave-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/ocrolus/': {
    focusKeyword: 'Ocrolus Document AI Case Study',
    keywords: 'Ocrolus case study, document AI, document processing, OCR AI',
    mainHeading: 'Ocrolus',
    metaTitle: 'Ocrolus AI Automation: Document Processing Case Study',
    metaDescription: 'Ocrolus achieved 85% document processing automation with Agix AI solutions, reducing manual review time from 8 hours to 45 minutes per application.',
    ogTitle: 'Ocrolus Case Study: Document AI Case Study',
    ogDescription: 'Scale your document processing! Explore how AGIX helped Ocrolus automate 6 million financial documents with 99% accuracy. Read more.',
    twitterTitle: 'Ocrolus Case Study: Document AI Case Study',
    twitterDescription: 'Accelerate speed and precision! See how AGIX supported Ocrolus reach 99.2% accuracy and save $1.8M in annual labor costs. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Ocrolus-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/babylon-health/': {
    focusKeyword: 'Babylon Healthcare AI Case Study',
    keywords: 'Babylon Health case study, healthcare AI, clinical AI, triage AI',
    mainHeading: 'Babylon Health',
    metaTitle: 'Babylon Health AI Implementation Case Study',
    metaDescription: 'Babylon Health deployed Agix AI for patient triage, reducing wait times by 50% and improving diagnostic accuracy to 94% across 2M+ consultations.',
    ogTitle: 'Babylon Health Case Study: care AI Case Study',
    ogDescription: 'Bridge the gap in digital health! See how AgixTech structured a regulator-approved triage system in 15+ languages. Read more.',
    twitterTitle: 'Babylon Health Case Study: care AI Case Study',
    twitterDescription: 'Global healthcare meets AI safety. Discover how we helped Babylon Health reach millions with faster, smarter triage. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Babylon-Health-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/kite-therapy/': {
    focusKeyword: 'Kite Therapy Case Study',
    keywords: 'Kite Therapy case study, mental health AI, therapy AI, crisis detection',
    mainHeading: 'Kite Therapy',
    metaTitle: 'Kite Therapy AI Solution Implementation Case Study',
    metaDescription: 'Kite Therapy implemented Agix AI for treatment planning, increasing patient outcomes by 35% while reducing therapist administrative work by 60%.',
    ogTitle: 'Kite Therapy Case Study: AI Solution',
    ogDescription: 'Supercharge user trust! Explore how AGIX powered Kite Therapy with emotional intelligence and seamless human escalation. Read more.',
    twitterTitle: 'Kite Therapy Case Study: AI Solution',
    twitterDescription: 'Transform the patient journey! See how AGIX streamlined Kite Therapy reach a 4.8/5 user rating through calibrated AI support.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Kite-Therapy-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hello-driven/': {
    focusKeyword: 'Hello Driven AI Coach Case Study',
    keywords: 'Hello Driven case study, healthcare voice AI, patient scheduling, HIPAA AI',
    mainHeading: 'Hello Driven',
    metaTitle: 'Hello Driven AI Marketing Automation Case Study',
    metaDescription: 'Hello Driven achieved 3x lead conversion with Agix AI-powered customer journey optimization, generating $2M additional revenue in just 6 months.',
    ogTitle: 'Hello Driven Case Study: AI Coach Case Study',
    ogDescription: 'Explore how AGIX engineered life-like voice agents that handle scheduling with HIPAA-grade security. Read more.',
    twitterTitle: 'Hello Driven Case Study: AI Coach Case Study',
    twitterDescription: 'Revolutionize patient outreach! See how AGIX helped Hello Driven achieve sub-300ms response times and 50+ EHR integrations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hello-Driven-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/albertsons/': {
    focusKeyword: 'Albertson AI Analytics Case Study',
    keywords: 'Albertsons case study, retail AI, demand forecasting, food waste AI',
    mainHeading: 'Albertsons',
    metaTitle: 'Albertsons AI Analytics Case Study | Agix Technologies',
    metaDescription: 'Albertsons achieved 25% inventory optimization using Agix\'s predictive analytics AI. Real-time demand forecasting across 2,200+ retail locations.',
    ogTitle: 'Albertsons Case Study: Albertson AI Analytics Case Study',
    ogDescription: 'Supercharge retail efficiency! Explore how AGIX structured multi-signal demand intelligence to keep shelves stocked and fresh.',
    twitterTitle: 'Albertsons Case Study: Albertson AI Analytics Case Study',
    twitterDescription: 'Crush inventory spoilage! See how AGIX collaborated with Albertsons to achieve a 97.2% in-stock rate with advanced demand analytics.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Albertsons-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/kroger/': {
    focusKeyword: 'Kroger Case Study',
    keywords: 'Kroger case study, retail AI, fulfillment AI, e-commerce AI',
    mainHeading: 'Kroger',
    metaTitle: 'Kroger AI Retail Automation: 40% Efficiency Boost | Agix',
    metaDescription: 'Agix Technologies deployed computer vision and predictive analytics to automate Kroger\'s inventory management, achieving 40% operational efficiency gains across 2,800 stores.',
    ogTitle: 'Kroger Case Study: AI Solution',
    ogDescription: 'Transform your retail space! Explore how AGIX engineered pick-path intelligence and smart substitutions for 2,700+ stores. Read more.',
    twitterTitle: 'Kroger Case Study: AI Solution',
    twitterDescription: 'Master in-store efficiency! See how Agix Technologies enabled Kroger to reach 94% on-time delivery by optimizing walking paths and inventory logic. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Kroger-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/stitch-fix/': {
    focusKeyword: 'Stitch Fix Case Study',
    keywords: 'Stitch Fix case study, fashion AI, personalization AI, styling AI',
    mainHeading: 'Stitch Fix',
    metaTitle: 'Stitch Fix AI Personalization: 25% Higher Retention | Agix',
    metaDescription: 'Agix Technologies built machine learning recommendation engine for Stitch Fix, increasing customer retention 25% through personalized styling algorithms and preference modeling.',
    ogTitle: 'Stitch Fix Case Study: AI Solution',
    ogDescription: 'Upgrade your customer experience! Explore how AGIX powered Stitch Fix with AI fit prediction and human-in-the-loop styling.',
    twitterTitle: 'Stitch Fix Case Study: AI Solution',
    twitterDescription: 'Modernize retail recommendations! See how AgixTech empowered Stitch Fix lower fit-related returns by 32% using advanced style embeddings.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Stitch-Fix-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/ulta-beauty/': {
    focusKeyword: 'Ulta Beauty Personalization AI Case Study',
    keywords: 'Ulta Beauty case study, retail personalization, loyalty AI, beauty AI',
    mainHeading: 'Ulta Beauty',
    metaTitle: 'Ulta Beauty Personalization AI Case Study | Agix Technologies',
    metaDescription: 'Ulta Beauty increased conversion 35% using Agix\'s recommendation engine. AI-powered product matching for 50M+ customers across digital channels now!',
    ogTitle: 'Ulta Beauty Case Study: Personalization AI Case Study',
    ogDescription: 'Explore how Agix Technologies engineered predictive marketing and dynamic rewards for 37M Ulta Beauty members.',
    twitterTitle: 'Ulta Beauty Case Study: Personalization AI Case Study',
    twitterDescription: 'Minimize customer churn! See how AGIX helped Ulta Beauty transform generic offers into tailored experiences using affinity modeling.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Ulta-Beauty-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/quizlet/': {
    focusKeyword: 'Quizlet AI Learning Case Study',
    keywords: 'Quizlet case study, EdTech AI, adaptive learning, AI tutoring',
    mainHeading: 'Quizlet',
    metaTitle: 'Quizlet AI EdTech: 60% Learning Speed Improvement | Agix',
    metaDescription: 'Agix Technologies developed adaptive learning AI for Quizlet, accelerating student learning speed by 60% using spaced repetition algorithms and personalized study paths.',
    ogTitle: 'Quizlet Case Study: AI Learning Case Study',
    ogDescription: 'Advance your EdTech platform! Explore how AGIX structured a Socratic AI tutor for 60M students to drive lasting mastery. Read more.',
    twitterTitle: 'Quizlet Case Study: AI Learning Case Study',
    twitterDescription: 'Strengthen student thinking! See how Agix Technologies streamlined Quizlet transform homework help into a guided discovery experience for millions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Quizlet-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/knewton/': {
    focusKeyword: 'Knewton Case Study',
    keywords: 'Knewton case study, adaptive learning, knowledge graph AI, EdTech AI',
    mainHeading: 'Knewton',
    metaTitle: 'Knewton Adaptive Learning AI: 35% Better Outcomes | Agix',
    metaDescription: 'Agix Technologies engineered personalized learning platform for Knewton, improving student outcomes 35% through real-time adaptive content delivery and progress analytics.',
    ogTitle: 'Knewton Case Study: AI Solution',
    ogDescription: 'Reconstruct your educational platform! Explore how AGIX developed knowledge graph mapping to deliver 683% better personalization for Knewton. Read more.',
    twitterTitle: 'Knewton Case Study: AI Solution',
    twitterDescription: 'Secure higher completion rates! See how Agix Technologies empowered Knewton identify learning gaps and optimize study paths with 96% accuracy. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Knewton-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/riiid-labs/': {
    focusKeyword: 'Riid Labs Case Study',
    keywords: 'Riiid Labs case study, test prep AI, adaptive assessment, EdTech AI',
    mainHeading: 'Riiid Labs',
    metaTitle: 'Riiid Labs AI Tutoring: 50% Score Improvements | Agix',
    metaDescription: 'Agix Technologies created intelligent tutoring system for Riiid Labs, delivering 50% test score improvements through personalized AI-driven learning recommendations.',
    ogTitle: 'Riiid Labs Case Study: Riid Labs Case Study',
    ogDescription: 'Advance your learning platform! Review how AgixTech constructed diagnostic AI to map 400+ concept nodes and maximize study efficiency.',
    twitterTitle: 'Riiid Labs Case Study: Riid Labs Case Study',
    twitterDescription: 'Achieve higher pass rates! See how AgixTech helped Riiid Labs deliver personalized remediation paths that address root learning causes.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Riiid-Labs-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hilton-hotels/': {
    focusKeyword: 'Hilton Hotels Case Study',
    keywords: 'Hilton case study, hospitality AI, guest intelligence, hotel AI',
    mainHeading: 'Hilton Hotels',
    metaTitle: 'Hilton Hotels AI Hospitality: 30% Revenue Growth | Agix',
    metaDescription: 'Agix Technologies implemented dynamic pricing and guest experience AI for Hilton Hotels, generating 30% revenue increase through predictive demand optimization.',
    ogTitle: 'Hilton Hotels Case Study: AI Solution',
    ogDescription: 'Reimagine hospitality engagement! See how AGIX architected predictive upsell engines and real-time pricing for 173M annual guests.',
    twitterTitle: 'Hilton Hotels Case Study: AI Solution',
    twitterDescription: 'Secure higher repeat bookings! See how AGIX enabled Hilton to transform stay patterns into personalized experiences for Diamond members. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hilton-Hotels-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/housecanary/': {
    focusKeyword: 'HouseCanary',
    keywords: 'HouseCanary case study, real estate AI, property valuation AI, AVM',
    mainHeading: 'HouseCanary',
    metaTitle: 'HouseCanary AI Real Estate: 95% Valuation Accuracy | Agix',
    metaDescription: 'Agix Technologies built automated valuation models for HouseCanary, achieving 95% property pricing accuracy using machine learning and comprehensive market data analysis.',
    ogTitle: 'HouseCanary Case Study: AI Solution',
    ogDescription: 'Upgrade your PropTech infrastructure! Discover how AGIX orchestrated an AVM engine that analyzes 400+ signals with institutional-grade precision.',
    twitterTitle: 'HouseCanary Case Study: AI Solution',
    twitterDescription: 'Evolve property assessment! See how we assisted HouseCanary deliver digital-speed valuations with 9.2% higher accuracy than industry standards.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/HouseCanary-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/mindtrip/': {
    focusKeyword: 'MindTrip',
    keywords: 'Mindtrip case study, travel AI, trip planning AI, conversational travel',
    mainHeading: 'Mindtrip',
    metaTitle: 'Mindtrip AI Travel Planning: 80% Booking Conversion | Agix',
    metaDescription: 'Agix Technologies developed intelligent travel recommendation engine for Mindtrip, increasing booking conversions 80% through personalized itinerary generation algorithms.',
    ogTitle: 'Mindtrip Case Study: AI Solution',
    ogDescription: 'Evolve your travel platform! Explore how AGIX developed a conversational engine that understands traveler personas and slashes research time. Read more.',
    twitterTitle: 'Mindtrip Case Study: AI Solution',
    twitterDescription: 'Enhance the traveler journey! See how AGIX supported Mindtrip deliver 91% personalization accuracy through interactive, AI-led planning. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Mindtrip-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/polyai/': {
    focusKeyword: 'PolyAI Voice AI',
    keywords: 'PolyAI case study, voice AI, call center AI, conversational AI',
    mainHeading: 'PolyAI',
    metaTitle: 'PolyAI Voice AI: 90% Call Resolution Rate | Agix',
    metaDescription: 'Agix Technologies engineered conversational AI platform for PolyAI, achieving 90% automated call resolution through advanced natural language processing and voice synthesis.',
    ogTitle: 'PolyAI Case Study: Voice AI',
    ogDescription: 'Analyze how AGIX optimized a multilingual voice AI that handles millions of calls with natural understanding.',
    twitterTitle: 'PolyAI Case Study: Voice AI',
    twitterDescription: 'Lower cost per call! See how AGIX helped PolyAI achieve 81% first-call resolution across 8+ languages with low-latency voice AI. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/PolyAI-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/brainfish/': {
    focusKeyword: 'Brainfish Case Study',
    keywords: 'Brainfish case study, support AI, ticket deflection, knowledge AI',
    mainHeading: 'Brainfish',
    metaTitle: 'Brainfish AI Support: 70% Faster Response Times | Agix',
    metaDescription: 'Agix Technologies built intelligent customer support system for Brainfish, reducing response times 70% using automated knowledge base search and contextual AI assistance.',
    ogTitle: 'Brainfish Case Study: AI Solution',
    ogDescription: 'Reimagine your customer care! Explore how AGIX developed a knowledge distillation engine that handles 100k+ monthly queries with elite precision.',
    twitterTitle: 'Brainfish Case Study: AI Solution',
    twitterDescription: 'Lower operational overhead! See how AGIX propelled Brainfish to a monthly deflection of 83,000 tickets while securing a 4.8/5 CSAT score.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Brainfish-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/properti-ai/': {
    focusKeyword: 'Properti AI Case Study',
    keywords: 'Properti AI case study, real estate matching, property AI, lead conversion',
    mainHeading: 'Properti AI',
    metaTitle: 'Properti AI Real Estate: 45% Faster Transactions | Agix',
    metaDescription: 'Agix Technologies created automated property matching platform for Properti AI, accelerating real estate transactions 45% through intelligent buyer-seller pairing algorithms.',
    ogTitle: 'Properti AI Case Study: AI Solution',
    ogDescription: 'Analyze how AGIX optimized lifestyle-aware search capabilities to refine property discovery and slash agent qualification time.',
    twitterTitle: 'Properti AI Case Study: AI Solution',
    twitterDescription: 'Drive higher lead conversion! See how we helped Properti AI deliver 89% match accuracy by understanding buyer lifestyle needs and neighborhood context.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Properti-AI-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/dartmouth-college/': {
    focusKeyword: 'Dartmouth College Case Study',
    keywords: 'Dartmouth case study, university AI, IT support AI, helpdesk AI',
    mainHeading: 'Dartmouth College',
    metaTitle: 'Dartmouth College AI Education: 55% Engagement Rise | Agix',
    metaDescription: 'Agix Technologies deployed adaptive learning platform for Dartmouth College, increasing student engagement 55% through personalized curriculum delivery and progress tracking.',
    ogTitle: 'Dartmouth College Case Study: AI Solution',
    ogDescription: 'Enable round-the-clock student assistance! Explore how AGIX developed a support engine to handle routine IT queries with elite efficiency. Read more.',
    twitterTitle: 'Dartmouth College Case Study: AI Solution',
    twitterDescription: 'Reduce support backlogs! See how AGIX enabled Dartmouth College to maintain 96% satisfaction through effective ticket clearing. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Dartmouth-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/suno/': {
    focusKeyword: 'Sonu Case Study',
    keywords: 'Suno case study, generative AI, music AI, audio synthesis',
    mainHeading: 'Suno',
    metaTitle: 'Suno AI Music Generation: Million-Track Library | Agix',
    metaDescription: 'Agix Technologies built generative AI music platform for Suno, creating million-song library through advanced neural networks and real-time composition algorithms.',
    ogTitle: 'Suno Case Study: Sonu Case Study',
    ogDescription: 'Understand how AGIX integrated a parallel processing pipeline for Suno to enable real-time music iteration and multi-GPU sharding.',
    twitterTitle: 'Suno Case Study: Sonu Case Study',
    twitterDescription: 'Boost session engagement! See how AGIX helped Suno achieve 3x more songs per session by removing cold start penalties and latency bottlenecks.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Suno-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/innit/': {
    focusKeyword: 'Innit Case Study',
    keywords: 'Innit case study, smart kitchen AI, IoT AI, cooking AI',
    mainHeading: 'Innit',
    metaTitle: 'Innit AI Food Tech: 60% Waste Reduction | Agix',
    metaDescription: 'Agix Technologies developed smart kitchen AI for Innit, reducing food waste 60% through predictive meal planning algorithms and ingredient optimization technology.',
    ogTitle: 'Innit Case Study: AI Solution',
    ogDescription: 'How AgixTech architected appliance coordination to mitigate culinary failure and compress preparation cycles by 45%.',
    twitterTitle: 'Innit Case Study: AI Solution',
    twitterDescription: "Achieve 98% device sync accuracy using the monitoring logic AGIX deployed for Innit's connected ecosystem. Examine the technicals.",
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Innit-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hungryroot/': {
    focusKeyword: 'Hungryroot Case Study',
    keywords: 'Hungryroot case study, meal planning AI, grocery AI, personalization',
    mainHeading: 'Hungryroot',
    metaTitle: 'Hungryroot AI Grocery: 40% Higher Order Value | Agix',
    metaDescription: 'Agix Technologies created personalized grocery recommendation system for Hungryroot, increasing average order value 40% through intelligent product bundling algorithms.',
    ogTitle: 'Hungryroot Case Study: AI Solution',
    ogDescription: 'To solve retail friction, AGIX deployed a selection lattice that maps dietary requirements against weekly food logistics.',
    twitterTitle: 'Hungryroot Case Study: AI Solution',
    twitterDescription: 'AgixTech synchronized taste profiling with waste-reduction logic to deliver elite precision in every box and drive long-term user loyalty.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hungryroot-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/navan/': {
    focusKeyword: 'Navan AI Travel Assistant Case Study',
    keywords: 'Navan case study, corporate travel AI, expense AI, travel automation',
    mainHeading: 'Navan',
    metaTitle: 'Navan AI Travel Assistant Case Study | Agix Technologies',
    metaDescription: 'Navan\'s AI travel assistant automates 80% of booking requests with personalized recommendations. Agix built enterprise travel automation platform.',
    ogTitle: 'Navan Case Study: AI Travel Assistant Case Study',
    ogDescription: 'To scale finance oversight, AGIX architected a risk-mapping engine that processes high-volume travel logistics and automates expense reporting in real-time.',
    twitterTitle: 'Navan Case Study: AI Travel Assistant Case Study',
    twitterDescription: 'We eliminated manual reporting bottlenecks by deploying category detection logic that truncated booking cycles by 67%. Review the implementation.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Navan-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/geovea/': {
    focusKeyword: 'Geivea Case Study',
    keywords: 'Geovea case study, travel AI, trip planning, route intelligence',
    mainHeading: 'Geovea',
    metaTitle: 'Geovea AI Real Estate Property Search Optimization Case Study',
    metaDescription: 'Geovea achieved 40% faster property matching with Agix\'s AI recommendation engine. Custom ML algorithms analyze user preferences and market data.',
    ogTitle: 'Geovea Case Study: Geivea Case Study',
    ogDescription: 'To modernize trip discovery, AGIX deployed a synchronization framework that monitors real-time environmental signals to coordinate personalized travel schedules.',
    twitterTitle: 'Geovea Case Study: Geivea Case Study',
    twitterDescription: 'AgixTech bypassed static route limitations by deploying crowd-avoidance profiling that optimized journey flows and raised user ratings to 4.9/5. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Luxury-Escapes-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/luxury-escapes/': {
    focusKeyword: 'Luxury Escapes Case Study',
    keywords: 'Luxury Escapes case study, luxury travel AI, concierge AI, VIP experience',
    mainHeading: 'Luxury Escapes',
    metaTitle: 'Luxury Escapes AI Travel Personalization Case Study',
    metaDescription: 'Luxury Escapes boosted booking conversions 35% using Agix\'s AI personalization platform. Dynamic pricing and recommendations optimize experiences.',
    ogTitle: 'Luxury Escapes Case Study: AI Solution',
    ogDescription: 'Coordinate premium travel logistics with a curation engine AGIX developed to process 47 preference signals and deliver bespoke VIP experiences at scale. Read more.',
    twitterTitle: 'Luxury Escapes Case Study: AI Solution',
    twitterDescription: 'AGIX boosted booking value by 71% by deploying scenario planning logic that handles personalized requests for 4,500 guests daily. See the breakdown.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AlphaSense-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/naratix/': {
    focusKeyword: 'Nartix Case Study',
    keywords: 'Naratix case study, content localization AI, e-commerce AI, multilingual AI',
    mainHeading: 'Naratix',
    metaTitle: 'Naratix AI Content Generation Automation Case Study',
    metaDescription: 'Naratix reduced content production time by 60% with Agix\'s advanced NLP solution. Automated writing assistants generate brand-consistent copy.',
    ogTitle: 'Naratix Case Study: Nartix Case Study',
    ogDescription: 'To accelerate international growth, AGIX deployed a content automation studio that manages semantic accuracy and SEO optimization across 28 regions simultaneously.',
    twitterTitle: 'Naratix Case Study: Nartix Case Study',
    twitterDescription: 'We eliminate localization bottlenecks using the brand voice consistency and legal compliance logic Agix Technologies deployed to accelerate content creation by 96%. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AlphaSense-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/alphasense/': {
    focusKeyword: 'AlphaSense Case Study',
    keywords: 'AlphaSense case study, financial research AI, NLP analytics, market intelligence AI, analyst productivity AI',
    mainHeading: 'AlphaSense',
    metaTitle: 'AlphaSense AI Financial Intelligence Platform Case Study',
    metaDescription: 'AlphaSense enhanced research accuracy 50% through Agix\'s advanced AI analytics platform. ML models process financial data for investment insights.',
    ogTitle: 'AlphaSense Case Study: AI Solution',
    ogDescription: 'AGIX engineered NLP-powered research systems for AlphaSense that surface signals from earnings calls, filings, and research in seconds—boosting analyst productivity by 500%.',
    twitterTitle: 'AlphaSense Case Study: AI Solution',
    twitterDescription: 'How AGIX transformed AlphaSense research workflows with NLP analytics, delivering 97% faster research and 500% analyst productivity improvement.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AlphaSense-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },
  '/corporate/about/': {
    focusKeyword: 'About Agix Technologies',
    keywords: 'about agix technologies, ai systems engineering company',
    mainHeading: 'About Agix Technologies',
    metaTitle: 'About Agix Technologies | AI Systems Engineering',
    metaDescription: 'Agix Technologies is an AI-First System Engineering Company building intelligent automation for global enterprises. 200+ AI implementations delivered.',
    ogTitle: 'About Agix Technologies | AI Systems Engineering',
    ogDescription: 'About Agix Technologies | AI Systems Engineering',
    twitterTitle: 'About Agix Technologies | AI Systems Engineering',
    twitterDescription: 'About Agix Technologies | AI Systems Engineering',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList'],
  },

  '/corporate/careers/': {
    focusKeyword: 'Careers at Agix Technologies',
    keywords: 'careers at agix technologies, ai engineering jobs',
    mainHeading: 'Careers at Agix Technologies',
    metaTitle: 'Careers at Agix Technologies | AI Engineering Jobs',
    metaDescription: 'Join Agix Technologies\' AI engineering team. Build cutting-edge AI systems, work with LLMs, computer vision, and enterprise automation technologies.',
    ogTitle: 'Careers at Agix Technologies | AI Engineering Jobs',
    ogDescription: 'Careers at Agix Technologies | AI Engineering Jobs',
    twitterTitle: 'Careers at Agix Technologies | AI Engineering Jobs',
    twitterDescription: 'Careers at Agix Technologies | AI Engineering Jobs',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList'],
  },

  '/corporate/contact/': {
    focusKeyword: 'Contact Agix Technologies',
    keywords: 'contact agix technologies, ai development experts',
    mainHeading: 'Contact Agix Technologies',
    metaTitle: 'Contact Agix Technologies | AI Development Experts',
    metaDescription: 'Contact Agix Technologies\' AI experts for custom system engineering. Discuss your AI automation needs with our technical consultation team today.',
    ogTitle: 'Contact Agix Technologies | AI Development Experts',
    ogDescription: 'Contact Agix Technologies | AI Development Experts',
    twitterTitle: 'Contact Agix Technologies | AI Development Experts',
    twitterDescription: 'Contact Agix Technologies | AI Development Experts',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList'],
  },
};

export function getURLMetadata(path: string): URLMetadata | null {
  const withLeading = path.startsWith('/') ? path : `/${path}`;
  const withoutTrailing = withLeading.endsWith('/') ? withLeading.slice(0, -1) : withLeading;
  const withTrailing = withoutTrailing + '/';
  return urlMetadataConfig[withoutTrailing] || urlMetadataConfig[withTrailing] || urlMetadataConfig[withLeading] || null;
}

export function getKeywordsArray(keywords: string): string[] {
  return keywords.split(',').map(k => k.trim()).filter(Boolean);
}
