export interface URLMetadata {
  focusKeyword: string;
  keywords: string;
  mainHeading: string;
  metaTitle: string;
  metaDescription: string;
  ogTitle: string;
  ogDescription: string;
  twitterTitle: string;
  twitterDescription: string;
  featuredImage?: string;
  schemas?: string[];
}

export const urlMetadataConfig: Record<string, URLMetadata> = {
  '/': {
    focusKeyword: 'AI Systems Engineering & Agentic Intelligence Company',
    keywords: 'AI systems engineering, agentic intelligence company, autonomous AI systems, enterprise AI solutions, AI voice agents, AI architecture, Conversational AI',
    mainHeading: 'Not Sure Where to Start With AI?',
    metaTitle: 'AI Systems Engineering & Agentic Intelligence Company | Agix Technologies',
    metaDescription: 'We are an AI Systems Engineering & Agentic Intelligence company helping enterprises design, deploy, and scale autonomous AI systems that deliver measurable ROI.',
    ogTitle: 'AI Systems Engineering & Agentic Intelligence Company',
    ogDescription: 'Enterprise-grade AI Systems Engineering and Agentic Intelligence solutions strategy, architecture, and deployment that drive real business outcomes.',
    twitterTitle: 'AI Systems Engineering & Agentic Intelligence Company',
    twitterDescription: 'We build enterprise AI systems and agentic intelligence solutions that move from strategy to scalable, ROI-driven deployment.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Systems-Engineering-Company-page-banner.png',
    schemas: ['Organization', 'WebSite', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/intelligence/operational-ai': {
    focusKeyword: 'Operational AI',
    keywords: 'operational ai, operational ai intelligence, ai for operations, operational ai systems, operational intelligence ai, ai-powered operational intelligence, real-time operational ai, operational decision intelligence, operational ai services',
    mainHeading: 'Operational Intelligence That Keeps Your Business Running Smoothly',
    metaTitle: 'Operational AI Solutions | Real-Time AI for Business Operations',
    metaDescription: 'Operational AI solutions that transform real-time operational data into intelligent, autonomous decisions. Build scalable AI systems for modern business operations.',
    ogTitle: 'Operational AI Solutions for Real-Time Business Operations',
    ogDescription: 'AI-powered operational intelligence systems delivering real-time insights and autonomous decision-making for complex business operations.',
    twitterTitle: 'Operational AI | Real-Time AI for Business Operations',
    twitterDescription: 'Operational AI systems that turn real-time operational data into intelligent, autonomous decisions for modern enterprises.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Operational-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/conversational-ai': {
    focusKeyword: 'Conversational AI',
    keywords: 'conversational ai, conversational intelligence, enterprise conversational ai, conversational ai solutions, conversational ai systems, conversational ai platforms',
    mainHeading: 'Conversational Intelligence That Understands, Not Just Responds',
    metaTitle: 'Conversational AI Solutions | Enterprise Conversational Intelligence',
    metaDescription: 'Enterprise Conversational AI solutions that combine conversational intelligence, AI systems, and platforms to build assistants that truly understand business context.',
    ogTitle: 'Enterprise Conversational AI & Conversational Intelligence Solutions',
    ogDescription: 'Build enterprise Conversational AI systems and platforms powered by conversational intelligence that go beyond chatbots to deliver real business outcomes.',
    twitterTitle: 'Conversational AI | Enterprise Conversational Intelligence',
    twitterDescription: 'Enterprise Conversational AI solutions built with conversational intelligence, scalable AI systems, and modern conversational platforms.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Conversations-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/decision-ai': {
    focusKeyword: 'Decision AI',
    keywords: 'decision intelligence, decision ai, decision intelligence solutions, enterprise decision intelligence, decision intelligence systems, ai decision intelligence, decision intelligence platform, intelligent decision systems, agentic ai decision intelligence, intelligent decision support systems',
    mainHeading: 'Decision Intelligence That Helps You Choose Right — Every Time',
    metaTitle: 'Decision AI & Decision Intelligence Solutions for Enterprises | Agix Technologies',
    metaDescription: 'Decision AI and Decision Intelligence solutions that help enterprises make faster, smarter decisions using intelligent systems, agentic AI, and real-time insights.',
    ogTitle: 'Decision AI & Enterprise Decision Intelligence Solutions | Agix Technologies',
    ogDescription: 'Build enterprise Decision Intelligence systems powered by Decision AI, agentic intelligence, and intelligent decision support for complex business decisions.',
    twitterTitle: 'Decision AI & Decision Intelligence for Enterprises | AgixTech',
    twitterDescription: 'Enterprise Decision AI and Decision Intelligence solutions using intelligent decision systems and agentic AI to drive better business outcomes.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Decision-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/autonomous-agentic-ai': {
    focusKeyword: 'Agentic AI',
    keywords: 'autonomous agentic systems, autonomous agentic ai, autonomous ai agents, agentic ai autonomous systems, agentic ai autonomous intelligence, autonomous agentic systems intelligence, autonomous agentic intelligence, enterprise autonomous agents',
    mainHeading: 'Autonomous Agentic Systems That Act With Purpose — Not Chaos',
    metaTitle: 'Autonomous Agentic Systems | Enterprise Autonomous AI Agents',
    metaDescription: 'Autonomous Agentic Systems powered by agentic AI and autonomous AI agents. Design governed, multi-agent systems that act intelligently at enterprise scale.',
    ogTitle: 'Autonomous Agentic Systems & Enterprise Autonomous AI Agents',
    ogDescription: 'Build Autonomous Agentic Systems using agentic AI and autonomous agents that plan, decide, and act with governance and control.',
    twitterTitle: 'Autonomous Agentic Systems | Autonomous AI Agents',
    twitterDescription: 'Enterprise Autonomous Agentic Systems built with agentic AI and autonomous agents designed for control, coordination, and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Autonomous-Agent-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/intelligence/enterprise-knowledge-ai': {
    focusKeyword: 'Enterprise Knowledge AI',
    keywords: 'Enterprise Knowledge AI, Knowledge Intelligence, Enterprise Knowledge Intelligence, Knowledge Intelligence Systems, AI-powered Knowledge Intelligence, Knowledge Intelligence for AI Systems',
    mainHeading: 'Enterprise Knowledge Intelligence You Can Trust — Not Just Retrieve',
    metaTitle: 'Enterprise Knowledge AI & Knowledge Intelligence Systems',
    metaDescription: 'Enterprise Knowledge AI and Knowledge Intelligence systems that deliver trusted, governed, AI-powered knowledge for intelligent decision-making and autonomous AI systems.',
    ogTitle: 'Enterprise Knowledge & Knowledge Management Systems | Agix Technologies',
    ogDescription: 'Build trusted Enterprise Knowledge AI using Knowledge Intelligence systems designed for governed, reliable AI decision-making and autonomous systems.',
    twitterTitle: 'Enterprise Knowledge AI & Knowledge Intelligence',
    twitterDescription: 'Enterprise Knowledge AI powered by Knowledge Intelligence systems that deliver trusted, governed knowledge for AI-driven decisions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Knowledge-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service', 'SoftwareApplication', 'FAQPage'],
  },

  '/services/ai-automation': {
    focusKeyword: 'AI Automation Services',
    keywords: 'AI Automation Services, Enterprise AI Automation, AI Business Automation Services, Intelligent Automation Services, AI Workflow Automation Services, AI Automation Agency, AI Automation Company, AI Business Process Automation',
    mainHeading: 'Engineering AI Automation That Eliminates Manual Operations',
    metaTitle: 'AI Automation Services for Enterprises | Intelligent Workflow Automation',
    metaDescription: 'Accelerate operations with AI-powered workflow automation. We help enterprises automate processes, reduce costs, and scale with intelligent automation solutions.',
    ogTitle: 'AI Automation Services to Reduce Costs & Scale Operations | AGIX Technologies',
    ogDescription: 'Automate manual workflows and reduce operational costs with AI-driven business process automation. Deploy intelligent automation across your enterprise systems.',
    twitterTitle: 'AI Automation Company for Intelligent Business Workflows & Process Automation',
    twitterDescription: 'Build intelligent workflows with AI automation services that integrate with CRMs, ERPs & enterprise tools. Automate decisions, routing, and operations at scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Automation-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-voice-agents': {
    focusKeyword: 'AI Voice Agents',
    keywords: 'AI Voice Agents, AI voice agent services, AI voice agent solutions, AI-powered voice agent, AI Phone Agents, AI voice agent for businesses, Best ai voice agent services, AI voice automation services, Voice AI solutions, Enterprise AI voice agents',
    mainHeading: 'AI Voice Agents That Talk, Think & Take Action',
    metaTitle: 'AI Voice Agents for Businesses | AI Phone Agents & Voice AI Solutions',
    metaDescription: 'Deploy AI voice agents that handle calls, automate conversations, and scale customer support. AI-powered phone agents built for modern businesses.',
    ogTitle: 'AI Voice Agents That Talk, Think & Take Action | Agix Technologies',
    ogDescription: 'Automate calls and conversations with AI-powered voice agents built for businesses. Scalable, intelligent, and enterprise-ready voice AI solutions.',
    twitterTitle: 'AI Voice Agent Services & AI Phone Agents for Businesses',
    twitterDescription: 'AI voice agent services for businesses looking to automate calls, improve customer experience, and reduce costs with intelligent voice AI solutions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Intelligent-Voice-Agents-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/conversational-ai-chatbots': {
    focusKeyword: 'Conversational AI Chatbots',
    keywords: 'Conversational AI chatbots, AI chatbot services, AI chatbot solutions, AI-powered chatbots, AI chatbot for businesses, Conversational AI platform, Enterprise AI chatbots, Intelligent AI chatbots, AI chatbot platform, enterprise ai chatbot solution',
    mainHeading: 'Conversational AI That Works Across Support, Sales & Operations',
    metaTitle: 'Conversational AI Chatbots for Businesses | AI Chatbot Services',
    metaDescription: 'Deploy conversational AI chatbots that automate support, sales, and operations. Enterprise-grade AI chatbot services built to scale securely.',
    ogTitle: 'Conversational AI Chatbots That Work Across Support, Sales & Ops',
    ogDescription: 'AI-powered conversational chatbots that work across customer support, sales, and operations. Scalable AI chatbot solutions for modern businesses.',
    twitterTitle: 'Conversational AI Chatbots for Support, Sales & Operations',
    twitterDescription: 'Enterprise-grade conversational AI chatbots that automate conversations, improve customer experience, and scale business operations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Conversations-Intelligence-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/agentic-ai-systems': {
    focusKeyword: 'Agentic AI Systems',
    keywords: 'Agentic AI Systems, Agentic AI solutions, Agentic AI services, Autonomous AI agents, Agentic AI systems for enterprises, Enterprise agentic AI solutions, Intelligent autonomous agents, Agentic AI service provider',
    mainHeading: "Agentic AI Systems That Don't Just Respond — They Operate",
    metaTitle: 'Agentic AI Systems for Enterprises | Autonomous AI Agents & Solutions',
    metaDescription: 'Build agentic AI systems that plan, decide, and operate autonomously. Enterprise-ready autonomous AI agents designed to scale complex business workflows.',
    ogTitle: 'Agentic AI Systems That Plan, Decide & Operate Autonomously',
    ogDescription: 'Agentic AI systems for enterprises that replace static automation with intelligent autonomous agents that execute, adapt, and optimize workflows.',
    twitterTitle: 'Agentic AI Systems That Plan, Decide & Operate Autonomously',
    twitterDescription: 'Deploy enterprise-grade agentic AI systems with intelligent autonomous agents built to handle complex workflows, decisions, and execution at scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Agentic-AI-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/rag-knowledge-ai': {
    focusKeyword: 'RAG Services',
    keywords: 'RAG Knowledge AI, Retrieval Augmented Generation services, RAG AI services, RAG AI solutions, Knowledge AI systems, Enterprise RAG solutions, RAG development services, Custom RAG solutions, RAG AI service provider',
    mainHeading: 'Make AI Answer From Your Knowledge — Not the Internet',
    metaTitle: 'RAG Knowledge AI Services | Enterprise Retrieval Augmented Generation',
    metaDescription: 'Build RAG Knowledge AI systems that deliver accurate, trusted answers from your data. Enterprise Retrieval Augmented Generation services with secure, scalable architecture.',
    ogTitle: 'Enterprise RAG Knowledge AI | Retrieval Augmented Generation Services',
    ogDescription: 'Turn your enterprise knowledge into reliable AI. Our RAG Knowledge AI services deliver grounded, secure, and scalable Retrieval Augmented Generation systems.',
    twitterTitle: 'RAG Knowledge AI Solutions for Accurate, Trusted Enterprise AI',
    twitterDescription: 'Deploy RAG Knowledge AI systems that answer from your data—not the internet. Enterprise Retrieval Augmented Generation services built for trust and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/RAG-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-predictive-analytics': {
    focusKeyword: 'Predictive Analytics AI',
    keywords: 'predictive analytics ai, ai predictive analytics, ai predictive analytics company, ai predictive analytics services, predictive analytics services, predictive data analytics services, predictive analytics development services, predictive analytics services company, predictive analytics consulting',
    mainHeading: 'Predict What Happens Next — Not What Already Happened',
    metaTitle: 'AI Predictive Analytics Services for Enterprises | AGIX Technologies',
    metaDescription: 'Deploy AI predictive analytics to forecast business outcomes, reduce risk, and enable proactive decisions at scale. Enterprise-grade forecasting & decision intelligence.',
    ogTitle: 'Enterprise AI Predictive Analytics & Forecasting Solutions | AGIX Technologies',
    ogDescription: 'AGIXTech helps enterprises move from reactive to proactive decision-making with AI predictive analytics, forecasting models, risk scoring, and decision intelligence systems.',
    twitterTitle: 'AI Predictive Analytics for Enterprise Decision Intelligence | AGIX Technogies',
    twitterDescription: 'Forecast outcomes, reduce risk, and optimize decisions with AI predictive analytics and enterprise-grade forecasting systems.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Predictive-Analytics-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/ai-computer-vision': {
    focusKeyword: 'Computer Vision Services',
    keywords: 'Computer Vision Services, Computer Vision Solutions, Enterprise Computer Vision, AI Computer Vision, Computer Vision Company, Computer Vision Consulting Services, Computer Vision Integration Services, Custom Computer Vision Solutions, Computer Vision Development Company, Computer Vision Consultant, Custom Computer Vision Development Services',
    mainHeading: 'From Pixels to Decisions',
    metaTitle: 'Computer Vision Services & AI Visual Automation for Enterprise',
    metaDescription: 'Enterprise-grade computer vision services for image recognition, video analytics, defect detection, OCR, and automation. Build scalable AI visual solutions.',
    ogTitle: 'Computer Vision Services for Enterprise | AI Visual Automation',
    ogDescription: 'We build customized computer vision solutions for image recognition, visual inspection, defect detection, OCR, and real-time video analytics. Transform operations with AI.',
    twitterTitle: 'Computer Vision Services & AI Visual Automation',
    twitterDescription: 'Custom computer vision solutions for image and video analytics, OCR, defect detection, and automation. Scalable AI built for enterprise operations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Computer-Vision-Solutions-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/services/custom-ai-product-development': {
    focusKeyword: 'Custom AI Develoment Services',
    keywords: 'Custom AI Product Development, AI Product Development Services, AI Product Development Company, Custom AI Software Development, AI Product Engineering Services, End-to-End AI Product Development, AI MVP Development Services, Custom AI Product Development Consultant, ai poc and mvp development services',
    mainHeading: 'From Idea to Market-Ready AI Product',
    metaTitle: 'Custom AI Product Development Services for Startups & Enterprises',
    metaDescription: 'Turn your idea into a market-ready AI product. We help founders and enterprises with AI MVP development, LLM engineering, deployment, scaling, and ROI-focused productization.',
    ogTitle: 'Custom AI Product Development Services for Startups & Enterprises',
    ogDescription: 'Turn your idea into a market-ready AI product. We provide end-to-end AI MVP development, LLM engineering, deployment, and scaling with measurable ROI.',
    twitterTitle: 'Custom AI Product Development & MVP Services for AI Startups',
    twitterDescription: 'From idea to market-ready AI product. We help startups build AI MVPs, validate ideas, deploy models, and scale with production-grade engineering and ROI.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Product-Development-Service-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/healthcare-ai-solutions': {
    focusKeyword: 'Healthcare AI Solutions',
    keywords: 'Healthcare AI, AI in Healthcare, Medical AI, Clinical AI, Healthcare automation',
    mainHeading: 'AI Solutions for Healthcare',
    metaTitle: 'AI-Powered Healthcare Solutions | Agix Technologies',
    metaDescription: 'Explore AI-powered healthcare solutions that streamline workflows, empower clinicians, and boost patient outcomes at scale.',
    ogTitle: 'AI-Powered Solutions in Healthcare | AGIX',
    ogDescription: 'Deliver better patient outcomes with AI in healthcare, advanced solutions for clinical efficiency, diagnosis support, and operational improvement.',
    twitterTitle: 'AI Solutions for Smarter Healthcare | Agix Tech',
    twitterDescription: 'Enhance healthcare efficiency and clinician support with reliable, explainable AI designed for real-world clinical environments.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Healthcare-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/real-estate-ai-solutions': {
    focusKeyword: 'Real Estate AI Solutions',
    keywords: 'Real Estate AI, AI for Real Estate, Property AI, Real Estate automation',
    mainHeading: "AI Solutions for Real Estate That Don't Just Explain — They Show You What to Build",
    metaTitle: 'AI-Powered Real Estate Solutions | Agix Tech',
    metaDescription: 'AI solutions for real estate teams to manage leads, automate follow-ups, and reduce deal leakage across high-volume sales pipelines.',
    ogTitle: 'Scale Your Business with AI Real Estate Solutions | AGIX',
    ogDescription: 'Deploy AI solutions that respond to inquiries faster, prioritize leads, and keep real estate deals moving without manual dependency.',
    twitterTitle: 'Get Custom AI Solutions for Real Estate | Agix Technologies',
    twitterDescription: 'Purpose-built AI solutions for real estate teams struggling with slow responses, missed follow-ups, and stalled deals.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Real-Estate-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/fintech-ai-solutions': {
    focusKeyword: 'Fintech AI Solutions',
    keywords: 'Fintech AI, AI for Financial Services, Financial AI, Lending AI',
    mainHeading: 'AI Solutions for FinTech & Lending That Show You Where Risk Leaks — and How to Fix It',
    metaTitle: 'AI Solutions for FinTech Risk & Lending | AGIX',
    metaDescription: 'Scale your lending platform with AI-powered fintech solutions. Reduce fraud, automate underwriting, and ensure compliant, explainable decisions.',
    ogTitle: 'Advanced AI-Driven FinTech Solutions | Agix Technologies',
    ogDescription: 'Eliminate silent revenue leakage with AI-driven fintech solutions. Deploy intelligent risk models that accelerate approvals and strengthen trust.',
    twitterTitle: 'Secure AI FinTech Solutions for Smart Lending | Agix Tech',
    twitterDescription: 'Modernize your financial services with reliable AI fintech solutions. Get custom roadmaps for fraud detection, credit scoring, and scale.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-solutions-for-FinTech-Industry-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/insurance-ai-solutions': {
    focusKeyword: 'Insurance AI Solutions',
    keywords: 'Insurance AI, AI for Insurance, Claims AI, Underwriting AI',
    mainHeading: 'AI Solutions for Insurance That Accelerate Claims, Reduce Fraud & Improve Risk Decisions',
    metaTitle: 'AI-Powered Insurance Solutions | Agix Tech',
    metaDescription: 'Accelerate claims and reduce fraud with AI-powered insurance solutions. Streamline underwriting and improve risk decisions with explainable AI.',
    ogTitle: 'AI-Driven Insurance Solutions | Agix Technologies',
    ogDescription: 'Experience seamless operations with AI-driven insurance solutions. Automate claims processing and detect fraud early to protect your loss ratio.',
    twitterTitle: 'AI Insurance Solutions for Core Insurance Operations',
    twitterDescription: 'Secure your competitive edge with reliable AI insurance solutions. Get custom roadmaps for claims automation and underwriting accuracy today.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Insurance-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/retail-ai-solutions': {
    focusKeyword: 'Retail AI Solutions',
    keywords: 'Retail AI, E-commerce AI, AI for Retail, Shopping AI',
    mainHeading: 'AI Solutions for E-Commerce That Show You Where Revenue Is Leaking — and How to Fix It',
    metaTitle: 'AI E-Commerce Solutions for Retail | Agix Tech',
    metaDescription: 'Stop revenue leakage with AI-powered e-commerce solutions. Recover abandoned carts, automate support, and scale your retail operations with ease.',
    ogTitle: 'Advanced AI-Driven E-Commerce Solutions | AGIX',
    ogDescription: 'Boost your margins with AI-driven e-commerce solutions. Automate returns, optimize inventory, and deliver personalized shopping experiences at scale.',
    twitterTitle: 'AI E-Commerce Solutions for D2C & Retail | Agix Technologies',
    twitterDescription: 'Scale your D2C and retail operations with AI e-commerce solutions. Reduce support load, recover abandoned revenue, and streamline workflows.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-E-Commerce-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/logistics-ai-solutions': {
    focusKeyword: 'Logistics AI Solutions',
    keywords: 'Logistics AI, Supply Chain AI, AI for Logistics, Transportation AI',
    mainHeading: 'AI Solutions for Logistics & Supply Chain That Reveal Where Delays, Costs & Inefficiencies Hide',
    metaTitle: 'AI-Powered Logistics Solutions | AGIX',
    metaDescription: 'Optimize your network with AI-powered logistics solutions. Predict demand, balance inventory, and eliminate delays with real-time supply chain visibility.',
    ogTitle: 'AI-Driven Logistics Solutions | Agix Technologies',
    ogDescription: 'Reduce costs and improve OTIF rates with AI-driven logistics solutions. Deploy intelligent routing and forecasting systems designed for global scale.',
    twitterTitle: 'AI Logistics Solutions for Supply Chain Optimization | Agix Tech',
    twitterDescription: 'Streamline operations with AI logistics solutions that fix bottlenecks, optimize routes, balance inventory, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Logistics-Supply-Chain-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/hospitality-ai-solutions': {
    focusKeyword: 'Hospitality AI Solutions',
    keywords: 'Hospitality AI, AI for Hotels, Hotel AI, Guest Experience AI',
    mainHeading: 'Intelligent AI Solutions That Strengthen Human Connection and Elevate Guest Experiences',
    metaTitle: 'AI-Powered Hospitality Solutions | Agix Tech',
    metaDescription: 'Enhance guest experiences with AI in hospitality. Reduce missed bookings, automate scheduling, and optimize staff operations at scale.',
    ogTitle: 'AI Solutions for Hospitality & Wellness Operations | Agix Technologies',
    ogDescription: 'Deploy AI in hospitality to improve bookings, reduce no-shows, optimize staff workflows, and elevate guest satisfaction across properties.',
    twitterTitle: 'AI Hospitality Solutions for Premium Guest Experiences | AGIX',
    twitterDescription: 'Modernize your guest journey with AI in hospitality. Reduce friction, automate workflows, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-Hospitality-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/industries/edtech-ai-solutions': {
    focusKeyword: 'Edtech AI Solutions',
    keywords: 'EdTech AI, AI for Education, Learning AI, Educational AI',
    mainHeading: 'AI Solutions for EdTech That Show You Where Learners Disengage — and How to Fix It',
    metaTitle: 'AI-Powered EdTech Solutions for Learning & Growth | Agix Tech',
    metaDescription: 'Enhance learning outcomes with AI in EdTech. Personalize paths, predict dropouts, and scale 24/7 support for students efficiently.',
    ogTitle: 'AI Solutions for EdTech & E-Learning | Agix Technologies',
    ogDescription: 'Deploy AI in EdTech to boost course completion, reduce faculty workload, provide intelligent tutoring, and improve student engagement.',
    twitterTitle: 'AI EdTech Solutions for Smarter Learning | AGIX',
    twitterDescription: 'Modernize your institution with AI in EdTech. Enhance engagement, personalize learning, and deliver real results.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AI-Solutions-in-EdTech-page-banner.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Service'],
  },

  '/case-studies': {
    focusKeyword: 'Real-World AI Case Studies',
    keywords: 'AI case studies, enterprise AI implementation, AI success stories, AI ROI examples',
    mainHeading: 'Real-World AI Systems. Proven at Enterprise Scale.',
    metaTitle: 'AI Case Studies | AgixTech',
    metaDescription: 'Discover our AI case studies, which showcase real-world results across various industries, including healthcare, finance, retail, and education.',
    ogTitle: 'Artificial Intelligence Case Studies | Agix Technologies',
    ogDescription: 'Explore AI case studies by AgixTech delivering real-world impact across healthcare, finance, retail, education, and more.',
    twitterTitle: 'AI Case Studies & Success Stories | AGIX',
    twitterDescription: 'Explore AI case studies by AgixTech highlighting real results in healthcare, finance, retail, education, and enterprise.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Artificial-Intelligence-Case-Studies.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'CollectionPage'],
  },

  '/case-studies/enova': {
    focusKeyword: 'Enova AI Credit Decisioning Case Study',
    keywords: 'Enova case study, AI credit decisioning, explainable AI, fintech AI',
    mainHeading: 'Enova International',
    metaTitle: 'Enova International Case Study | Agix Technologies',
    metaDescription: 'Explore how we built an explainable AI system for Enova to hit 94.7% accuracy and 100% audit compliance. Read the full success story now.',
    ogTitle: 'Slashed Audit Times by 67% | Enova Success Story | Agix Tech',
    ogDescription: 'Scale your fintech with confidence! Explore how AGIX ensured bias-free credit decisions and 100% audit coverage for Enova. Read more.',
    twitterTitle: 'Scale Fintech with Trustworthy AI | Enova Case Study | AGIX',
    twitterDescription: 'Boost accuracy and trust! See how AGIX slashed Enova audit time by 67% with transparent, regulator-ready AI models. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Enova-International-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/dave': {
    focusKeyword: 'Dave Fintech AI Assistant Case Study',
    keywords: 'Dave case study, fintech AI, conversational AI, customer support AI',
    mainHeading: 'Dave',
    metaTitle: 'Dave Fintech AI Success Story | Agix Technologies',
    metaDescription: 'Find how we built an empathetic AI assistant for Dave to slash support volume by 57% and hit a 93 CSAT score. Read the success story.',
    ogTitle: 'Cut Support Response Times by 99% | Dave Success Story',
    ogDescription: 'Scale your fintech with empathy! Explore how AGIX engineered a conversational AI that handles 94% of inquiries for 10M members.',
    twitterTitle: 'Scale Neobanking with Human-Like AI | Dave Case Study',
    twitterDescription: 'Boost satisfaction and speed! See how AGIX helped Dave achieve a 93 CSAT score while reducing resolution time by 79%.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Dave-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/ocrolus': {
    focusKeyword: 'Ocrolus Document AI Case Study',
    keywords: 'Ocrolus case study, document AI, document processing, OCR AI',
    mainHeading: 'Ocrolus',
    metaTitle: 'Automate Document AI with 99% Accuracy | Ocrolus Case Study',
    metaDescription: 'Analyze how we built a document AI for Ocrolus to process 6M+ docs monthly with 99.2% accuracy. Read the full success story now.',
    ogTitle: 'Slashed Manual Review by 78% | Ocrolus Success Story',
    ogDescription: 'Scale your document processing! Explore how AGIX helped Ocrolus automate 6 million financial documents with 99% accuracy. Read more.',
    twitterTitle: 'Process 6M+ Documents in Seconds | Ocrolus Case Study',
    twitterDescription: 'Accelerate speed and precision! See how AGIX supported Ocrolus reach 99.2% accuracy and save $1.8M in annual labor costs. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Ocrolus-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/babylon-health': {
    focusKeyword: 'Babylon Healthcare AI Case Study',
    keywords: 'Babylon Health case study, healthcare AI, clinical AI, triage AI',
    mainHeading: 'Babylon Health',
    metaTitle: 'Clinical AI Triage at Scale | Babylon Case Study | AGIX',
    metaDescription: 'Explore our safety-first clinical AI that identifies urgent cases with 99.2% precision for global patients.',
    ogTitle: 'Accelerate Patient Care by 34% | Babylon Case Study',
    ogDescription: 'Bridge the gap in digital health! See how AgixTech structured a regulator-approved triage system in 15+ languages. Read more.',
    twitterTitle: '99.2% Urgent Case Detection | Babylon Case Study | Agix Technologies',
    twitterDescription: 'Global healthcare meets AI safety. Discover how we helped Babylon Health reach millions with faster, smarter triage. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Babylon-Health-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/kite-therapy': {
    focusKeyword: 'Kite Therapy Case Study',
    keywords: 'Kite Therapy case study, mental health AI, therapy AI, crisis detection',
    mainHeading: 'Kite Therapy',
    metaTitle: 'Build Safe Mental Health AI | Kite Case Study | Agix Technologies',
    metaDescription: 'Discover how we developed an empathetic AI for Kite Therapy to boost retention by 89% with zero-miss crisis detection.',
    ogTitle: 'Achieve 100% Crisis Detection | Kite Success Story | AGIX',
    ogDescription: 'Supercharge user trust! Explore how AGIX powered Kite Therapy with emotional intelligence and seamless human escalation. Read more.',
    twitterTitle: 'AI for Mental Health | Kite Case Study | AgixTech',
    twitterDescription: 'Transform the patient journey! See how AGIX streamlined Kite Therapy reach a 4.8/5 user rating through calibrated AI support.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Kite-Therapy-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hello-driven': {
    focusKeyword: 'Hello Driven AI Coach Case Study',
    keywords: 'Hello Driven case study, healthcare voice AI, patient scheduling, HIPAA AI',
    mainHeading: 'Hello Driven',
    metaTitle: 'Automate Patient Scheduling | Hello Driven Case Study',
    metaDescription: 'Examine how we built a healthcare voice AI for Hello Driven to reach a 78% answer rate and eliminate 61% of no-shows. Read the success story.',
    ogTitle: 'Crush No-Show Rates by 61% | Hello Driven Success Story',
    ogDescription: 'Explore how AGIX engineered life-like voice agents that handle scheduling with HIPAA-grade security. Read more.',
    twitterTitle: 'Healthcare Voice AI That Works | Hello Driven Case Study',
    twitterDescription: 'Revolutionize patient outreach! See how AGIX helped Hello Driven achieve sub-300ms response times and 50+ EHR integrations.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hello-Driven-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/albertsons': {
    focusKeyword: 'Albertson AI Analytics Case Study',
    keywords: 'Albertsons case study, retail AI, demand forecasting, food waste AI',
    mainHeading: 'Albertsons',
    metaTitle: 'Optimize Retail Demand Forecasting | Albertsons Case Study',
    metaDescription: 'Discover how we built an AI forecasting system for Albertsons to cut food waste by 45% and save $83M annually.',
    ogTitle: 'Save $83M in Annual Food Waste | Albertsons Success Story',
    ogDescription: 'Supercharge retail efficiency! Explore how AGIX structured multi-signal demand intelligence to keep shelves stocked and fresh.',
    twitterTitle: 'AI-Powered Grocery Supply Chain | Albertsons Case Study',
    twitterDescription: 'Crush inventory spoilage! See how AGIX collaborated with Albertsons to achieve a 97.2% in-stock rate with advanced demand analytics.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Albertsons-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/kroger': {
    focusKeyword: 'Kroger Case Study',
    keywords: 'Kroger case study, retail AI, fulfillment AI, e-commerce AI',
    mainHeading: 'Kroger',
    metaTitle: 'Revolutionize E-commerce Fulfillment | Kroger Case Study',
    metaDescription: 'Examine how we engineered a fulfillment AI for Kroger to slice pick times by 47% and drop delivery costs by 42%. Read the full success story now.',
    ogTitle: 'Cut Fulfillment Costs by 42% | Kroger Success Story | AGIX Tech',
    ogDescription: 'Transform your retail space! Explore how AGIX engineered pick-path intelligence and smart substitutions for 2,700+ stores. Read more.',
    twitterTitle: 'Smart Retail Fulfillment AI | Kroger Case Study | Agix Technologies',
    twitterDescription: 'Master in-store efficiency! See how Agix Technologies enabled Kroger to reach 94% on-time delivery by optimizing walking paths and inventory logic. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Kroger-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/stitch-fix': {
    focusKeyword: 'Stitch Fix Case Study',
    keywords: 'Stitch Fix case study, fashion AI, personalization AI, styling AI',
    mainHeading: 'Stitch Fix',
    metaTitle: 'Elevate Style Personalization | Stitch Fix Case Study',
    metaDescription: 'Review how we developed a stylist copilot for Stitch Fix to boost keep rates to 61% and cut 58% off styling time.',
    ogTitle: 'Boost Client Value by 42% | Stitch Fix Success Story',
    ogDescription: 'Upgrade your customer experience! Explore how AGIX powered Stitch Fix with AI fit prediction and human-in-the-loop styling.',
    twitterTitle: 'AI-Powered Fashion Personalization | Stitch Fix Case Study',
    twitterDescription: 'Modernize retail recommendations! See how AgixTech empowered Stitch Fix lower fit-related returns by 32% using advanced style embeddings.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Stitch-Fix-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/ulta-beauty': {
    focusKeyword: 'Ulta Beauty Personalization AI Case Study',
    keywords: 'Ulta Beauty case study, retail personalization, loyalty AI, beauty AI',
    mainHeading: 'Ulta Beauty',
    metaTitle: 'Modernize Retail Loyalty Systems | Ulta Beauty Case Study',
    metaDescription: 'Find out how we built a personalization engine for Ulta Beauty to skyrocket conversions by 172% and drop churn by 57%.',
    ogTitle: 'Ignite Member Engagement | Ulta Beauty Success Story',
    ogDescription: 'Explore how Agix Technologies engineered predictive marketing and dynamic rewards for 37M Ulta Beauty members.',
    twitterTitle: 'Individualized Beauty Retail AI | Ulta Beauty Case Study',
    twitterDescription: 'Minimize customer churn! See how AGIX helped Ulta Beauty transform generic offers into tailored experiences using affinity modeling.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Ulta-Beauty-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/quizlet': {
    focusKeyword: 'Quizlet AI Learning Case Study',
    keywords: 'Quizlet case study, EdTech AI, adaptive learning, AI tutoring',
    mainHeading: 'Quizlet',
    metaTitle: 'Transform Adaptive Learning | Quizlet Case Study | AGIX',
    metaDescription: 'Discover how we built Q-Chat for Quizlet to resolve 89% of misconceptions and boost learning gains by 67%. Read the full success story now.',
    ogTitle: 'Refine Student Outcomes | Quizlet Success Story | AGIX Tech',
    ogDescription: 'Advance your EdTech platform! Explore how AGIX structured a Socratic AI tutor for 60M students to drive lasting mastery. Read more.',
    twitterTitle: 'Quizlet Case Study | Agix Technologies',
    twitterDescription: 'Strengthen student thinking! See how Agix Technologies streamlined Quizlet transform homework help into a guided discovery experience for millions.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Quizlet-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/knewton': {
    focusKeyword: 'Knewton Case Study',
    keywords: 'Knewton case study, adaptive learning, knowledge graph AI, EdTech AI',
    mainHeading: 'Knewton',
    metaTitle: 'Evolve Adaptive Learning Systems | Knewton Case Study',
    metaDescription: 'Examine how we engineered real-time AI feedback loops for Knewton to boost course completion by 109%. Read the full success story now.',
    ogTitle: 'Accelerate Student Mastery | Knewton Success Story',
    ogDescription: 'Reconstruct your educational platform! Explore how AGIX developed knowledge graph mapping to deliver 683% better personalization for Knewton. Read more.',
    twitterTitle: 'Dynamic Knowledge Graph AI | Knewton Case Study | Agix Technologies',
    twitterDescription: 'Secure higher completion rates! See how Agix Technologies empowered Knewton identify learning gaps and optimize study paths with 96% accuracy. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Knewton-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/riiid-labs': {
    focusKeyword: 'Riid Labs Case Study',
    keywords: 'Riiid Labs case study, test prep AI, adaptive assessment, EdTech AI',
    mainHeading: 'Riiid Labs',
    metaTitle: 'Refine Adaptive Test Prep | Riiid Case Study | AGIX',
    metaDescription: 'We built the Santa AI engine for Riiid Labs to increase exam scores by 176% while cutting study time by 58%. Read more.',
    ogTitle: 'Outperform Standard Exam Results | Riiid Labs Success Story',
    ogDescription: 'Advance your learning platform! Review how AgixTech constructed diagnostic AI to map 400+ concept nodes and maximize study efficiency.',
    twitterTitle: 'Precision Test Intelligence AI | Riiid Case Study | AgixTech',
    twitterDescription: 'Achieve higher pass rates! See how AgixTech helped Riiid Labs deliver personalized remediation paths that address root learning causes.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Riiid-Labs-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hilton-hotels': {
    focusKeyword: 'Hilton Hotels Case Study',
    keywords: 'Hilton case study, hospitality AI, guest intelligence, hotel AI',
    mainHeading: 'Hilton Hotels',
    metaTitle: 'Advance Hospitality Revenue Systems | Hilton Case Study',
    metaDescription: 'AgixTech engineered a guest intelligence engine for Hilton to increase RevPAR by 4.7% across 7,000 properties. Read the success story now.',
    ogTitle: 'Elevate Global Guest Satisfaction | Hilton Success Story',
    ogDescription: 'Reimagine hospitality engagement! See how AGIX architected predictive upsell engines and real-time pricing for 173M annual guests.',
    twitterTitle: 'Predictive Guest Intelligence AI | Hilton Case Study | AGIX',
    twitterDescription: 'Secure higher repeat bookings! See how AGIX enabled Hilton to transform stay patterns into personalized experiences for Diamond members. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hilton-Hotels-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/housecanary': {
    focusKeyword: 'HouseCanary',
    keywords: 'HouseCanary case study, real estate AI, property valuation AI, AVM',
    mainHeading: 'HouseCanary',
    metaTitle: 'Real-Time Property Valuation AI | HouseCanary Case Study',
    metaDescription: 'We structured an AVM engine for HouseCanary to achieve 97.2% accuracy across 400+ property signals. Read the full success story now.',
    ogTitle: 'Digital-Speed Property Valuations | HouseCanary Story',
    ogDescription: 'Upgrade your PropTech infrastructure! Discover how AGIX orchestrated an AVM engine that analyzes 400+ signals with institutional-grade precision.',
    twitterTitle: 'Instant Real Estate Intelligence | HouseCanary Case Study',
    twitterDescription: 'Evolve property assessment! See how we assisted HouseCanary deliver digital-speed valuations with 9.2% higher accuracy than industry standards.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/HouseCanary-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/mindtrip': {
    focusKeyword: 'MindTrip',
    keywords: 'Mindtrip case study, travel AI, trip planning AI, conversational travel',
    mainHeading: 'Mindtrip',
    metaTitle: 'Conversational Travel Planning AI | Mindtrip Case Study',
    metaDescription: 'AGIX architected a travel AI framework for Mindtrip that compressed planning cycles by 99% and drove a 272% uplift in repeat usage. Read the success story.',
    ogTitle: 'Automate Personal Travel Itineraries | Mindtrip Story',
    ogDescription: 'Evolve your travel platform! Explore how AGIX developed a conversational engine that understands traveler personas and slashes research time. Read more.',
    twitterTitle: 'AI-Driven Trip Discovery Engine | Mindtrip Case Study',
    twitterDescription: 'Enhance the traveler journey! See how AGIX supported Mindtrip deliver 91% personalization accuracy through interactive, AI-led planning. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Mindtrip-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/polyai': {
    focusKeyword: 'PolyAI Voice AI',
    keywords: 'PolyAI case study, voice AI, call center AI, conversational AI',
    mainHeading: 'PolyAI',
    metaTitle: 'Enterprise Voice AI Automation | PolyAI Case Study | AgixTech',
    metaDescription: 'How we engineered a voice AI for PolyAI to resolve 89% of calls and reduce costs by 74%. Read the full success story.',
    ogTitle: 'Human-Level Voice Resolution | PolyAI Success Story',
    ogDescription: 'Analyze how AGIX optimized a multilingual voice AI that handles millions of calls with natural understanding.',
    twitterTitle: 'Next-Gen Call Center Intelligence | PolyAI Case Study',
    twitterDescription: 'Lower cost per call! See how AGIX helped PolyAI achieve 81% first-call resolution across 8+ languages with low-latency voice AI. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/PolyAI-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/brainfish': {
    focusKeyword: 'Brainfish Case Study',
    keywords: 'Brainfish case study, support AI, ticket deflection, knowledge AI',
    mainHeading: 'Brainfish',
    metaTitle: 'Automate Support Ticket Deflection | Brainfish Case Study | AGIX',
    metaDescription: 'Examine how AGIX built a logic-led system for Brainfish to handle 83% of ticket volume via real-time intent alignment.',
    ogTitle: 'Achieve Instant Support Resolution | Brainfish Case Study',
    ogDescription: 'Reimagine your customer care! Explore how AGIX developed a knowledge distillation engine that handles 100k+ monthly queries with elite precision.',
    twitterTitle: 'AI-Powered Support Intelligence | Brainfish Success Story',
    twitterDescription: 'Lower operational overhead! See how AGIX propelled Brainfish to a monthly deflection of 83,000 tickets while securing a 4.8/5 CSAT score.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Brainfish-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/properti-ai': {
    focusKeyword: 'Properti AI Case Study',
    keywords: 'Properti AI case study, real estate matching, property AI, lead conversion',
    mainHeading: 'Properti AI',
    metaTitle: 'Transform Real Estate Discovery | Properti AI Case Study | AGIX',
    metaDescription: 'Discover how we engineered a property matching engine for Properti AI to boost lead conversion by 156% and achieve 89% match accuracy. Read more.',
    ogTitle: 'Elevate Buyer Match Accuracy | Properti AI Success Story',
    ogDescription: 'Analyze how AGIX optimized lifestyle-aware search capabilities to refine property discovery and slash agent qualification time.',
    twitterTitle: 'Advanced Property Discovery Engine | Properti AI Case Study',
    twitterDescription: 'Drive higher lead conversion! See how we helped Properti AI deliver 89% match accuracy by understanding buyer lifestyle needs and neighborhood context.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Properti-AI-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/dartmouth-college': {
    focusKeyword: 'Dartmouth College Case Study',
    keywords: 'Dartmouth case study, university AI, IT support AI, helpdesk AI',
    mainHeading: 'Dartmouth College',
    metaTitle: 'Streamline Campus IT Support | Dartmouth College Case Study | Agix Technologies',
    metaDescription: 'Agix built a 24/7 helpdesk for Dartmouth College to deflect 74% of tickets and achieve 2-minute resolution times. Read more.',
    ogTitle: 'Expand University Helpdesk Capacity | Dartmouth Success Story',
    ogDescription: 'Enable round-the-clock student assistance! Explore how AGIX developed a support engine to handle routine IT queries with elite efficiency. Read more.',
    twitterTitle: 'Dartmouth Case Study | AgixTech',
    twitterDescription: 'Reduce support backlogs! See how AGIX enabled Dartmouth College to maintain 96% satisfaction through effective ticket clearing. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Dartmouth-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/suno': {
    focusKeyword: 'Sonu Case Study',
    keywords: 'Suno case study, generative AI, music AI, audio synthesis',
    mainHeading: 'Suno',
    metaTitle: 'Accelerate Generative Music Pipelines | Suno Case Study | Agix Technologies',
    metaDescription: "See how we re-engineered Suno's audio synthesis to drop generation time from 90s to 20s and increase user retention by 34%. Read the success story.",
    ogTitle: 'High-Speed Audio Generation | Suno Success Story',
    ogDescription: 'Understand how AGIX integrated a parallel processing pipeline for Suno to enable real-time music iteration and multi-GPU sharding.',
    twitterTitle: 'Generative AI Infrastructure Performance | Suno Case Study',
    twitterDescription: 'Boost session engagement! See how AGIX helped Suno achieve 3x more songs per session by removing cold start penalties and latency bottlenecks.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Suno-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/innit': {
    focusKeyword: 'Innit Case Study',
    keywords: 'Innit case study, smart kitchen AI, IoT AI, cooking AI',
    mainHeading: 'Innit',
    metaTitle: 'Connected Kitchen Systems Engineering | Innit Case Study | AGIX',
    metaDescription: 'Analyze the real-time cooking guidance engine that synchronized smart kitchen ecosystems and uplifted recipe success rates by 89%.',
    ogTitle: 'Synchronized Smart Kitchen Performance | Innit Success Story',
    ogDescription: 'How AgixTech architected appliance coordination to mitigate culinary failure and compress preparation cycles by 45%.',
    twitterTitle: 'Innit Case Study | Agix Technologies',
    twitterDescription: "Achieve 98% device sync accuracy using the monitoring logic AGIX deployed for Innit's connected ecosystem. Examine the technicals.",
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Innit-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/hungryroot': {
    focusKeyword: 'Hungryroot Case Study',
    keywords: 'Hungryroot case study, meal planning AI, grocery AI, personalization',
    mainHeading: 'Hungryroot',
    metaTitle: 'Customized Meal Planning Systems | Hungryroot Case Study | AgixTech',
    metaDescription: 'Reduce food waste by 73% using the grocery optimization engine AgixTech, engineered for Hungryroot to deliver 94% meal alignment.',
    ogTitle: 'Predictive Grocery Selection Engine | Hungryroot Story',
    ogDescription: 'To solve retail friction, AGIX deployed a selection lattice that maps dietary requirements against weekly food logistics.',
    twitterTitle: 'Personalized Nutrition Infrastructure | Hungryroot Case Study',
    twitterDescription: 'AgixTech synchronized taste profiling with waste-reduction logic to deliver elite precision in every box and drive long-term user loyalty.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Hungryroot-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/navan': {
    focusKeyword: 'Navan AI Travel Assistant Case Study',
    keywords: 'Navan case study, corporate travel AI, expense AI, travel automation',
    mainHeading: 'Navan',
    metaTitle: 'Corporate Spend Governance Systems | Navan Case Study | Agix Technologies',
    metaDescription: 'Lower corporate travel overhead by 23% with the AGIX expense governance framework, designed to enforce 94% policy compliance across global teams.',
    ogTitle: 'Operational Spend Intelligence | Navan Success Story',
    ogDescription: 'To scale finance oversight, AGIX architected a risk-mapping engine that processes high-volume travel logistics and automates expense reporting in real-time.',
    twitterTitle: 'Enterprise Expense Management Infrastructure | Navan Case Study',
    twitterDescription: 'We eliminated manual reporting bottlenecks by deploying category detection logic that truncated booking cycles by 67%. Review the implementation.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Navan-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/geovea': {
    focusKeyword: 'Geivea Case Study',
    keywords: 'Geovea case study, travel AI, trip planning, route intelligence',
    mainHeading: 'Geovea',
    metaTitle: 'Dynamic Trip Itinerary Systems | Geovea Case Study | AGIX',
    metaDescription: 'Drive travel engagement by 214% with the route intelligence lattice AGIX engineered for Geovea to provide 92% plan accuracy. Read the success story.',
    ogTitle: 'Adaptive Travel Route Performance | Geovea Success Story',
    ogDescription: 'To modernize trip discovery, AGIX deployed a synchronization framework that monitors real-time environmental signals to coordinate personalized travel schedules.',
    twitterTitle: 'Real-Time Journey Planning Infrastructure | Geovea Case Study',
    twitterDescription: 'AgixTech bypassed static route limitations by deploying crowd-avoidance profiling that optimized journey flows and raised user ratings to 4.9/5. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/Luxury-Escapes-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/luxury-escapes': {
    focusKeyword: 'Luxury Escapes Case Study',
    keywords: 'Luxury Escapes case study, luxury travel AI, concierge AI, VIP experience',
    mainHeading: 'Luxury Escapes',
    metaTitle: 'Premium Concierge Scaling Systems | Luxury Escapes Case Study | AgixTech',
    metaDescription: 'Expand concierge service capacity by 36x using the high-touch curation framework AgixTech built for Luxury Escapes to achieve 96/100 guest satisfaction.',
    ogTitle: 'White-Glove Service Scaling Performance | Luxury Escapes Story',
    ogDescription: 'Coordinate premium travel logistics with a curation engine AGIX developed to process 47 preference signals and deliver bespoke VIP experiences at scale. Read more.',
    twitterTitle: 'Luxury Travel Personalization Infrastructure | Luxury Escapes Case Study',
    twitterDescription: 'AGIX boosted booking value by 71% by deploying scenario planning logic that handles personalized requests for 4,500 guests daily. See the breakdown.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AlphaSense-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },

  '/case-studies/naratix': {
    focusKeyword: 'Nartix Case Study',
    keywords: 'Naratix case study, content localization AI, e-commerce AI, multilingual AI',
    mainHeading: 'Naratix',
    metaTitle: 'Multi-Market Content Localization Systems | Naratix Case Study | AGIX',
    metaDescription: 'Drive a 129% conversion uplift with the cultural adaptation framework AGIX engineered for Naratix to localize product content for 28 markets in minutes. Read the success story.',
    ogTitle: 'Global E-commerce Content Performance | Naratix Success Story',
    ogDescription: 'To accelerate international growth, AGIX deployed a content automation studio that manages semantic accuracy and SEO optimization across 28 regions simultaneously.',
    twitterTitle: 'Cross-Border Content Infrastructure | Naratix Case Study',
    twitterDescription: 'We eliminate localization bottlenecks using the brand voice consistency and legal compliance logic Agix Technologies deployed to accelerate content creation by 96%. Learn more.',
    featuredImage: 'https://cms.agixtech.com/wp-content/uploads/2026/01/AlphaSense-Case-Study-Image.png',
    schemas: ['Organization', 'WebPage', 'BreadcrumbList', 'Article'],
  },
};

export function getURLMetadata(path: string): URLMetadata | null {
  const normalizedPath = path.endsWith('/') ? path.slice(0, -1) : path;
  const pathWithoutLeading = normalizedPath.startsWith('/') ? normalizedPath : `/${normalizedPath}`;
  return urlMetadataConfig[pathWithoutLeading] || null;
}

export function getKeywordsArray(keywords: string): string[] {
  return keywords.split(',').map(k => k.trim()).filter(Boolean);
}
