'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "dartmouth-college",
  company: "Dartmouth College",
  industry: "Higher Education",
  subIndustry: "AI IT Helpdesk",
  accentColor: "emerald",
  gradientClasses: "bg-gradient-to-br from-background via-green-500/5 to-emerald-500/10",
  heroHeadline: "Dartmouth College: AI IT Helpdesk That Resolves Tickets in Minutes",
  heroSubheadline: "Transforming a 12,000-student university IT helpdesk—reducing ticket volume by 65%, cutting resolution time from 4 days to 14 minutes, and freeing IT staff for infrastructure projects.",
  heroStats: [
    { value: "-65%", label: "Ticket Volume", color: "text-emerald-400" },
    { value: "14 min", label: "Avg Resolution Time", color: "text-green-400" },
    { value: "92%", label: "Student Satisfaction", color: "text-teal-400" },
  ],
  directAnswerQuestion: "How does Dartmouth use AI for IT support?",
  directAnswer: "Dartmouth College deployed an AI helpdesk system that handles common IT requests—password resets, software installations, Wi-Fi troubleshooting, VPN access, and account provisioning—through a conversational interface integrated into the student and staff portal. The system uses RAG over Dartmouth's IT knowledge base and service catalog, resolving 65% of tickets automatically and reducing average resolution time from 4 days to 14 minutes.",
  clientDescription: "Dartmouth College is an Ivy League research university with approximately 12,000 students and 4,500 faculty and staff. The Office of Information Technology (DartIT) manages IT services for the entire campus, handling thousands of support tickets per semester covering everything from email access to research computing. Legacy helpdesk processes required IT staff to manually process routine requests, creating bottlenecks during high-demand periods like the start of academic terms.",
  clientFounded: "1769",
  clientSize: "12,000 students, 4,500 staff, 500+ IT service types",
  clientLocation: "Hanover, New Hampshire, USA",
  problemTitle: "University IT Teams Can't Scale for Semester Start Demand Spikes",
  problemDescription: "Every August and January, ticket volume spikes 400% as returning students need password resets, new students need account setups, and faculty need access to new course tools. With a fixed-size IT team, these spikes meant 3–5 day resolution times and frustrated students at the worst possible time in the academic calendar.",
  painPoints: [
    { title: "Semester Start Ticket Spike", stat: "+400%", description: "Ticket volume surge during first two weeks of each semester when IT staff capacity is fixed.", color: "amber" },
    { title: "Average Resolution Time", stat: "4 days", description: "Time from ticket submission to resolution during peak periods—critical when students can't access course materials.", color: "red" },
    { title: "Repetitive Ticket Types", stat: "78%", description: "Proportion of tickets that were identical or near-identical requests IT staff had answered hundreds of times before.", color: "orange" },
  ],
  solutionTitle: "Conversational AI Helpdesk Integrated with Campus Identity Systems",
  solutionDescription: "AGIX Technologies built an AI helpdesk layer that connects to Dartmouth's Active Directory, service catalog, and knowledge base to handle IT requests autonomously. The system can execute self-service actions (password resets, software license provisioning, VPN account creation) rather than just providing instructions—resolving issues instantly rather than guiding users through complex processes.",
  solutionComponents: [
    { title: "IT Knowledge RAG Engine", description: "Semantic search over Dartmouth's entire IT documentation library, service catalog, and 3 years of resolved tickets to answer any known question instantly." },
    { title: "Identity System Integration", description: "Direct API connection to Active Directory and Duo MFA enables the AI to verify identity and execute account actions (password resets, group membership) without human involvement." },
    { title: "Service Catalog Automation", description: "Common service requests (software installs, VPN access, email forwarding) are fulfilled automatically via integration with the IT service management platform." },
    { title: "Escalation Intelligence", description: "Complex tickets are automatically classified and routed to the appropriate IT specialist team with a full context summary, eliminating the triage step that previously added 1–2 days to resolution." },
    { title: "Multilingual Student Support", description: "Support for 12 languages serving Dartmouth's international student population, with culturally adapted communication styles." },
    { title: "IT Staff Dashboard", description: "Real-time visibility into AI resolution rates, common failure modes, and knowledge gaps helps IT managers continuously improve both the AI system and underlying IT processes." },
  ],
  architectureTitle: "Dartmouth AI Helpdesk Architecture",
  architectureLayers: [
    { name: "Student & Staff Interface", components: ["Campus Portal Chat Widget", "Email Ticket Integration", "Mobile App Support", "12-Language Support"], color: "emerald" },
    { name: "Request Intelligence", components: ["Intent Classification (50+ categories)", "Entity Extraction (Asset IDs, NetIDs)", "Urgency Scoring", "Eligibility Verification"], color: "green" },
    { name: "Knowledge & Policy Engine", components: ["IT Documentation RAG", "Service Catalog Search", "Policy Compliance Checking", "Solution History Corpus"], color: "teal" },
    { name: "Execution & Integration", components: ["Active Directory API", "Duo MFA Integration", "ServiceNow Connector", "Software License Management"], color: "blue" },
    { name: "Monitoring & Improvement", components: ["Resolution Rate Tracking", "Knowledge Gap Detection", "IT Staff Feedback Loop", "SLA Compliance Dashboard"], color: "slate" },
  ],
  resultsTitle: "Academic Year Outcomes Across Both Semesters",
  resultsMetrics: [
    { value: "-65%", label: "Ticket Volume", description: "Reduction in tickets requiring human agent handling across the full academic year", color: "emerald" },
    { value: "14 min", label: "Avg Resolution", description: "Down from 4 days during peak periods—students get help before their next class", color: "green" },
    { value: "92%", label: "Student CSAT", description: "Student satisfaction with AI helpdesk—higher than 84% human-only baseline", color: "teal" },
    { value: "3x", label: "IT Project Capacity", description: "IT staff freed to work on infrastructure and security projects previously deferred", color: "blue" },
  ],
  resultsQuote: {
    text: "Students submit a ticket at 2am on a Sunday before a Monday morning exam and it's resolved in 12 minutes. That simply wasn't possible before. The AI never sleeps, never has office hours.",
    author: "Chief Information Officer",
    role: "Dartmouth College Office of Information Technology",
  },
  howItWorksTitle: "How Dartmouth's AI Helpdesk Resolves an IT Request",
  steps: [
    { title: "Ticket Submission & Classification", description: "Student submits request via portal or email", detail: "The student submits a request in natural language. The AI classifier identifies the request type from 50+ categories and extracts key entities: the student's NetID, the affected service (email, VPN, software), and any error messages. Urgency is scored based on academic calendar context (exam week = high urgency)." },
    { title: "Identity Verification", description: "Confirm who is making the request", detail: "For account actions, the system verifies identity via the campus SSO session or sends a Duo push notification for out-of-session verification. This ensures account actions can only be taken by the authorized account holder—no social engineering vulnerability." },
    { title: "Knowledge Retrieval & Solution Generation", description: "Find and compose the resolution", detail: "The RAG engine searches IT documentation, service catalog entries, and resolved tickets for the most relevant context. A generative model composes a step-by-step resolution specific to the student's situation, including links to relevant documentation and any campus-specific variations." },
    { title: "Self-Service Action Execution", description: "Execute account or service actions automatically", detail: "For request types where direct action is authorized (password resets, VPN re-provisioning, email quota increases), the system executes the action via API integration rather than providing instructions for the student to follow. The ticket is resolved in seconds, not minutes." },
    { title: "Resolution Confirmation & Feedback", description: "Confirm the issue is resolved", detail: "The student receives confirmation of the action taken and is asked to verify the issue is resolved. Negative confirmations trigger a secondary resolution attempt or immediate escalation. CSAT ratings are collected automatically on ticket close." },
    { title: "Escalation with Full Context", description: "Route complex issues to specialists efficiently", detail: "For tickets outside AI scope, a complete summary is generated: issue description, troubleshooting already attempted, student's system environment, and urgency level. Specialists receive all context before touching the ticket, cutting their resolution time by 60% even for complex issues." },
  ],
  whyItWorkedTitle: "Why University IT AI Adoption Succeeded at Dartmouth",
  whyFactors: [
    { title: "Action Execution vs Instructions Only", description: "Systems that tell students what to do have 40% lower completion rates than systems that execute the action directly. Dartmouth's AI does both, depending on the request type." },
    { title: "Campus Calendar Awareness", description: "The system knew exam periods, add/drop deadlines, and semester starts and auto-escalated tickets during high-stress academic moments, maintaining trust at critical times." },
    { title: "IT Staff as Curators, Not Just Operators", description: "IT staff were given a knowledge management interface to add solutions and flag errors. Staff ownership of the knowledge base quality drove faster improvement than any automated process." },
    { title: "Always-On 24/7 Availability", description: "Students submit IT tickets outside of business hours—weekends, late nights—and university IT can't staff 24/7. AI coverage during off-hours alone resolved 35% of previously deferred tickets." },
    { title: "Transparent Routing to Humans", description: "When the AI can't help, it says so explicitly and provides an estimated human response time. Honesty about limitations maintained student trust more than pretending the AI could handle everything." },
  ],
  limitations: [
    { title: "Physical Hardware Issues Require On-Site Support", description: "Broken laptop screens, malfunctioning peripherals, and network infrastructure problems cannot be resolved remotely—the AI routes these to on-site support immediately." },
    { title: "Novel Software Not in Knowledge Base", description: "When a professor adopts new research software mid-semester, there's a 48-72 hour gap before the AI has documentation to draw from. Edge cases like this still require human specialists." },
    { title: "FERPA-Sensitive Requests", description: "Requests involving student academic records or sensitive personal data require human review to ensure FERPA compliance—the AI cannot make privacy judgment calls autonomously." },
    { title: "Institutional Policy Interpretation", description: "Complex questions about IT policy exceptions (e.g., can a student use a non-standard VPN client for research?) require human policy judgment." },
  ],
  whenToUseGoodFit: [
    "Universities and colleges with 2,000+ students and regular IT helpdesk demand",
    "Organizations with high-volume, repetitive service requests during predictable peak periods",
    "IT departments with documented service catalogs and resolution guides",
    "Institutions needing 24/7 support coverage without 24/7 staffing budgets",
  ],
  whenToUseNotGoodFit: [
    "Small departments with highly specialized, non-repeating IT environments",
    "Organizations where every support request is unique and requires deep investigation",
    "IT teams without existing documentation or service catalog infrastructure",
    "Environments with very high security classifications requiring human oversight of all access changes",
  ],
  connections: [
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "IT documentation retrieval and solution generation", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Student-facing helpdesk dialogue interface", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Automated account actions and service provisioning", type: "service" },
    { name: "EdTech AI Solutions", slug: "edtech-ai-solutions", relevance: "AI deployment patterns for educational institutions", type: "industry" },
    { name: "Enterprise Knowledge AI", slug: "enterprise-knowledge-ai", relevance: "Institutional knowledge management and search", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Service desk operations automation and efficiency", type: "intelligence" },
  ],
  keyTakeaways: [
    "65% ticket reduction achieved in first full academic year deployment",
    "Action execution (doing tasks automatically) is 40% more effective than instruction delivery",
    "24/7 AI availability resolves 35% of tickets outside business hours",
    "Transparent AI limitations maintain user trust better than overreach",
    "IT staff transition from reactive support to proactive infrastructure investment",
  ],
  faqs: [
    { question: "How does Dartmouth handle FERPA compliance with AI-processed tickets?", answer: "The AI system is deployed within Dartmouth's secure infrastructure environment and only accesses identity systems through authorized API integrations. FERPA-sensitive data is never sent to external AI APIs—all processing uses on-premises models or contracted service providers with FERPA Business Associate Agreements." },
    { question: "How did Dartmouth train the AI on their specific IT environment?", answer: "The initial training data consisted of 3 years of resolved support tickets, Dartmouth's IT documentation library, and the service catalog. IT staff spent 2 weeks reviewing AI responses in a test environment and adding corrections. This human-in-the-loop validation process produced a knowledge base accurate enough for live deployment within 8 weeks." },
    { question: "What was the student adoption rate for the new AI helpdesk?", answer: "Student adoption was nearly universal within the first semester because the AI was integrated into the existing portal students already used to submit tickets. No new app or account was required. Students who initially preferred human support self-selected to the traditional path, which remained available." },
    { question: "Can this model work for administrative departments beyond IT?", answer: "Yes. After the IT helpdesk success, Dartmouth expanded the AI model to the Registrar's office (common enrollment questions) and the Financial Aid office (standard policy questions). Each department required a separate knowledge base but shared the same underlying platform." },
    { question: "What did this cost to implement, and what's the ROI?", answer: "The implementation cost was recovered in the first semester through reduced overtime staffing during peak periods. Annual savings from reduced ticket handling labor (estimated at 1.5 FTE per year) and improved staff retention exceed implementation and operational costs by approximately 4x." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function DartmouthCollegeCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
