
const bottlenecks = [
  {
    id: "1",
    title: "Real-Time Fraud Detection",
    icon: Shield,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    reality: ["$42B annual fraud losses", "rules updated quarterly", "synthetic identity bypass"],
    impact: [
      "Fraudsters adapt daily while static rules wait for quarterly updates — leading to massive unrecovered losses.",
      "Manual fraud reviews create high false-positive rates, blocking legitimate high-value transactions.",
    ],
    outcomeCallout: "Fraud losses reduced by up to 40%. False positives cut by 35% with real-time ML detection.",
    agixSystem: "Real-Time Fraud Intelligence Engine",
    services: [
      { name: "AI Predictive Analytics", href: "/services/ai-predictive-analytics/" },
      { name: "Agentic AI Systems", href: "/services/agentic-ai-systems/" },
    ],
    caseStudy: { name: "Enova", href: "/case-studies/enova/", text: "AI-powered lending and risk intelligence across consumer and SMB credit products." },
  },
  {
    id: "2",
    title: "Credit Underwriting & Scoring",
    icon: CreditCard,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    reality: ["2-5 day approval wait", "thin-file rejection", "manual reviewer variance"],
    impact: [
      "67% of customers expect instant decisions; every hour of manual underwriting delay drives applicants to competitors.",
      "Traditional bureau scoring misses creditworthy thin-file segments, leaving billions in untapped revenue.",
    ],
    outcomeCallout: "Decision time: days → minutes. Default prediction accuracy: +25%. Thin-file approval rates: +40%.",
    agixSystem: "Automated ML Underwriting Engine",
    services: [
      { name: "AI Predictive Analytics", href: "/services/ai-predictive-analytics/" },
      { name: "Custom AI Product Development", href: "/services/custom-ai-product-development/" },
    ],
    caseStudy: { name: "Dave", href: "/case-studies/dave/", text: "Neobank AI serving underserved populations with AI-powered financial inclusion." },
  },
  {
    id: "3",
    title: "KYC/AML Compliance",
    icon: UserCheck,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    reality: ["30+ min per case", "$30 cost per applicant", "manual audit prep stress"],
    impact: [
      "Compliance staff spend 30% of their time on repetitive document validation rather than actual risk analysis.",
      "Slow KYC/AML onboarding causes a 45% abandonment rate among high-quality digital-first applicants.",
    ],
    outcomeCallout: "KYC processing: 30 min → 3 min per case. False positive reduction: 50%. Audit prep time: -40%.",
    agixSystem: "AI KYC & AML Automation Suite",
    services: [
      { name: "AI Automation", href: "/services/ai-automation/" },
      { name: "AI Computer Vision", href: "/services/ai-computer-vision/" },
    ],
    caseStudy: { name: "Ocrolus", href: "/case-studies/ocrolus/", text: "AI document intelligence extracting structured data from bank statements, pay stubs, and tax documents at 99%+ accuracy." },
  },
  {
    id: "4",
    title: "Customer Onboarding",
    icon: Zap,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    reality: ["multiple document uploads", "low mobile conversion", "repetitive data entry"],
    impact: [
      "Complex onboarding flows are the #1 cause of customer acquisition cost wastage in digital banking.",
      "Inconsistent data capture across channels creates massive downstream friction for risk and compliance teams.",
    ],
    outcomeCallout: "Abandonment: 45% → 15%. Onboarding time: 20 min → 5 min. Conversion: +35%.",
    agixSystem: "Conversational Onboarding Intelligence",
    services: [
      { name: "Conversational AI Chatbots", href: "/services/conversational-ai-chatbots/" },
      { name: "AI Automation", href: "/services/ai-automation/" },
    ],
  },
  {
    id: "5",
    title: "Collections & Recovery",
    icon: Clock,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    reality: ["blanket reminder campaigns", "manual agent follow-ups", "unprioritized risk queues"],
    impact: [
      "Traditional collections use the same tone and timing for every account, eroding borrower trust and recovery rates.",
      "Agents waste 40% of their day calling accounts that either will pay anyway or have zero likelihood of recovery.",
    ],
    outcomeCallout: "Recovery rates: +30%. Contact-to-promise: +45%. Cost per recovery: -35%.",
    agixSystem: "Predictive Recovery Optimization",
    services: [
      { name: "AI Predictive Analytics", href: "/services/ai-predictive-analytics/" },
      { name: "AI Voice Agents", href: "/services/ai-voice-agents/" },
    ],
  },
  {
    id: "6",
    title: "Regulatory Reporting & Audit",
    icon: Scale,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    reality: ["weeks of manual effort", "disconnected audit trails", "reactive change monitoring"],
    impact: [
      "One missed regulatory update creates massive liability; manual change monitoring is slow and error-prone.",
      "Audit preparation is a 'periodic scramble' rather than a continuous state of governance and readiness.",
    ],
    outcomeCallout: "Reporting time: -40%. Change detection: real-time. Audit readiness: 24/7/365.",
    agixSystem: "Autonomous Governance & Audit Agent",
    services: [
      { name: "RAG & Knowledge AI", href: "/services/rag-knowledge-ai/" },
      { name: "AI Automation", href: "/services/ai-automation/" },
    ],
  },
  {
    id: "7",
    title: "Financial Research & Intelligence",
    icon: BarChart3,
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    reality: ["days to synthesize filings", "lagging market sentiment", "manual data extraction"],
    impact: [
      "Investment and credit risk committees often make decisions on information that is already 48-72 hours old.",
      "Analysts spend 80% of their time on data collection and only 20% on higher-value risk and opportunity synthesis.",
    ],
    outcomeCallout: "Research time: days → minutes. Coverage breadth: 10x. Every insight source-cited.",
    agixSystem: "AI Research & Synthesis Agent",
    services: [
      { name: "Agentic AI Systems", href: "/services/agentic-ai-systems/" },
      { name: "RAG & Knowledge AI", href: "/services/rag-knowledge-ai/" },
    ],
    caseStudy: { name: "AlphaSense", href: "/case-studies/alphasense/", text: "AI-powered financial research platform serving investment professionals." },
  },
];

const aiSystems = [
  {
    id: "1",
    title: "Real-Time Fraud Intelligence",
    icon: Shield,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "6–8 weeks",
    bottleneckSolved: "Real-Time Fraud Detection",
    whatItDoes: [
      "Analyzes every transaction against behavioral baselines, network patterns, and known fraud typologies in milliseconds.",
      "Detects synthetic identity rings and account takeover attempts before disbursement happens.",
      "Continuously retrains on confirmed outcomes to stay ahead of evolving fraud tactics.",
    ],
    whatItDoesNot: ["No automatic freezing of high-value accounts without human review", "No sharing of PII across model training sets", "Final investigation is always human-led."],
    whyItWorks: "Anomaly detection identifies novel patterns that rules-based systems miss. Every flag includes explainable reasoning for investigators.",
    impact: ["Fraud losses: -40%", "False positives: -35%", "Detection latency: <200ms"],
    integration: "Stripe, Plaid, Core Banking APIs, Visa/Mastercard feeds",
    learnMoreHref: "/services/ai-predictive-analytics/",
  },
  {
    id: "2",
    title: "Automated ML Underwriting",
    icon: CreditCard,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "8–10 weeks",
    bottleneckSolved: "Credit Underwriting & Scoring",
    whatItDoes: [
      "Generates risk scores in seconds using historical lending data, bureau data, and alternative data sources.",
      "Produces explainable credit decisions with confidence intervals that meet regulatory audit requirements.",
      "Automatically routes edge cases to human underwriters with a decision-support summary.",
    ],
    whatItDoesNot: ["No use of protected demographic attributes for scoring", "No binding approvals without liquidity check", "Not a replacement for credit committee policy."],
    whyItWorks: "ML models find risk signals in alternative data that traditional bureau scores miss, unlocking creditworthy thin-file segments.",
    impact: ["Decision time: <2 min", "Default prediction: +25%", "Thin-file approvals: +40%"],
    integration: "Experian/Equifax, Plaid, Argyle, Custom LOS/LMS",
    learnMoreHref: "/services/ai-predictive-analytics/",
  },
  {
    id: "3",
    title: "AI KYC & AML Automation",
    icon: UserCheck,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "5–7 weeks",
    bottleneckSolved: "KYC/AML Compliance",
    whatItDoes: [
      "Automates document extraction and validation for IDs, bank statements, and tax filings with 99%+ accuracy.",
      "Performs real-time sanctions screening and adverse media checks via NLP agents.",
      "Generates a full, tamper-proof audit trail for every onboarding decision automatically.",
    ],
    whatItDoesNot: ["No final SAR filing without human compliance officer review", "No bypass of required document steps", "Does not replace the MLRO (Money Laundering Reporting Officer)."],
    whyItWorks: "Computer vision and NLP handle the volume of 'checking' while humans focus on 'investigating' high-risk exceptions.",
    impact: ["Processing time: -90%", "Manual review hours: -70%", "Compliance cost: -40%"],
    integration: "Jumio, Onfido, Alloy, LexisNexis, Government DBs",
    learnMoreHref: "/services/ai-automation/",
  },
  {
    id: "4",
    title: "Onboarding Intelligence",
    icon: Zap,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "5–7 weeks",
    bottleneckSolved: "Customer Onboarding & Conversion",
     whatItDoes: [
      "Guides applicants through complex financial forms via context-aware conversational AI.",
      "Validates data in real-time, reducing errors and 'ping-pong' document requests.",
      "Pre-qualifies applicants instantly so low-intent leads don't consume human resources.",
    ],
    whatItDoesNot: ["No binding financial advice provided to applicants", "No contract signing without verified identity", "Does not store PII outside of encrypted production DB."],
    whyItWorks: "Reducing friction at the point of intent is the highest-ROI optimization for digital-first lenders.",
    impact: ["Abandonment rate: -30%", "Time to first decision: <5 min", "Mobile conversion: +45%"],
    integration: "HubSpot, Salesforce, Twilio, WhatsApp, Web SDK",
    learnMoreHref: "/services/conversational-ai-chatbots/",
  },
  {
    id: "5",
    title: "Predictive Recovery Optimization",
    icon: Clock,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "6–8 weeks",
    bottleneckSolved: "Collections & Recovery",
    whatItDoes: [
      "Segments accounts by repayment propensity, intent-to-pay, and behavioral risk signals.",
      "Optimizes outreach channel, timing, and tone to maximize recovery while protecting customer relationships.",
      "Automates first-line collections calls and reminders via empathetic AI voice agents.",
    ],
    whatItDoesNot: ["No aggressive or non-compliant debt collection tactics", "No legal threats without human legal review", "No outreach outside of permitted regulatory hours."],
    whyItWorks: "Treating every borrower like a unique risk rather than a static bucket increases both repayment and long-term retention.",
    impact: ["Recovery rate: +30%", "Collection cost: -35%", "Customer NPS: +15%"],
    integration: "Twilio, SendGrid, Dialers, Core Banking, Collections CRM",
    learnMoreHref: "/services/ai-voice-agents/",
  },
  {
    id: "6",
    title: "Governance & Audit Agent",
    icon: Scale,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "6–8 weeks",
    bottleneckSolved: "Regulatory Reporting & Audit",
    whatItDoes: [
      "Continuously monitors regulatory changes and flags affected internal policies and workflows.",
      "Automates the compilation of regulatory reports from across transaction and lending systems.",
      "Maintains a centralized, queryable knowledge base of all compliance procedures and audit history.",
    ],
    whatItDoesNot: ["No submission of regulatory filings without human sign-off", "No autonomous policy changes", "Not a replacement for legal counsel."],
    whyItWorks: "Continuous monitoring replaces the 'periodic scramble' and ensures you are always audit-ready.",
    impact: ["Reporting time: -40%", "Compliance visibility: 100%", "Audit findings: -60%"],
    integration: "Reg-Feeds, Internal DBs, Slack/Teams, Document Management",
    learnMoreHref: "/services/rag-knowledge-ai/",
  },
  {
    id: "7",
    title: "AI Research & Synthesis Agent",
    icon: BarChart3,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    timeline: "4–6 weeks",
    bottleneckSolved: "Financial Research & Intelligence",
    whatItDoes: [
      "Synthesizes insights from millions of data points across filings, transcripts, and news in seconds.",
      "Flags emerging risks and opportunities in the portfolio based on market sentiment and economic signals.",
      "Generates source-cited research memos for credit and investment committees automatically.",
    ],
    whatItDoesNot: ["No autonomous trading or investment execution", "No reliance on unverified news sources", "Recommendations are suggestions, not financial advice."],
    whyItWorks: "10x coverage breadth means you never miss a signal in a 10-K or earnings call again.",
    impact: ["Research time: -85%", "Coverage: +1000%", "Insight latency: <1 min"],
    integration: "Bloomberg, Reuters, EDGAR, Custom Data Lakes",
    learnMoreHref: "/services/rag-knowledge-ai/",
  },
];

const roleBasedBottlenecks = [
  {
    id: "lender",
    role: "Digital Lender / Neobank",
    icon: Zap,
    description: "High-growth lending platforms focused on speed, conversion, and scalable risk management.",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    bottleneckIds: ["1", "2", "4", "5"],
    recommendedSystemIds: ["1", "2", "4", "5"],
    roadmapItems: [
      { phase: "Week 1-4: Risk Core", action: "Deploy Real-Time Fraud and ML Underwriting to stabilize loss rates while scaling." },
      { phase: "Week 5-8: Conversion", action: "Integrate Onboarding Intelligence to maximize CAC efficiency and mobile approval rates." },
      { phase: "Week 9-12: Recovery", action: "Launch Predictive Recovery to optimize collections and protect portfolio health." },
    ],
  },
  {
    id: "bank",
    role: "Traditional Bank / Credit Union",
    icon: Landmark,
    description: "Established institutions prioritizing compliance, auditability, and operational efficiency.",
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/20",
    bottleneckIds: ["2", "3", "6", "7"],
    recommendedSystemIds: ["2", "3", "6", "7"],
    roadmapItems: [
      { phase: "Week 1-4: Governance", action: "Deploy Audit & Compliance Agents to automate reporting and monitor regulatory changes." },
      { phase: "Week 5-8: Efficiency", action: "Launch KYC/AML Automation to compress manual review times by 70%." },
      { phase: "Week 9-12: Intelligence", action: "Integrate AI Research for data-driven credit committee and portfolio reviews." },
    ],
  },
  {
    id: "startup",
    role: "Fintech Startup",
    icon: Search,
    description: "Early-stage teams building the next generation of niche financial products and services.",
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    borderColor: "border-cyan-500/20",
    bottleneckIds: ["1", "3", "4"],
    recommendedSystemIds: ["1", "3", "4"],
    roadmapItems: [
      { phase: "Week 1-4: Onboarding", action: "Build context-aware onboarding to drive early user growth and document collection." },
      { phase: "Week 5-8: Trust", action: "Implement core Fraud and KYC layers to satisfy banking partners and regulators." },
      { phase: "Week 9-12: Scale", action: "Automate routine support and compliance tasks to keep overhead low during growth." },
    ],
  },
  {
    id: "payments",
    role: "BNPL / Payments",
    icon: CreditCard,
    description: "Transaction-heavy platforms requiring millisecond decisions and behavioral risk profiling.",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    bottleneckIds: ["1", "2", "5"],
    recommendedSystemIds: ["1", "2", "5"],
    roadmapItems: [
      { phase: "Week 1-4: Instant Risk", action: "Deploy millisecond-latency Fraud and Credit Scoring for at-point-of-sale decisions." },
      { phase: "Week 5-8: Retention", action: "Implement behavioral risk monitoring to identify and prevent account takeovers." },
      { phase: "Week 9-12: Collections", action: "Launch automated, high-frequency collections for low-balance delinquencies." },
    ],
  },
  {
    id: "compliance",
    role: "Compliance & Risk Teams",
    icon: Scale,
    description: "Specialized teams focused on maintaining the integrity and regulatory standing of the institution.",
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/20",
    bottleneckIds: ["3", "6", "7"],
    recommendedSystemIds: ["3", "6", "7"],
    roadmapItems: [
      { phase: "Week 1-4: Audit Readiness", action: "Automate evidence collection and report generation for impending audits." },
      { phase: "Week 5-8: Monitoring", action: "Deploy regulatory change agents to scan and interpret jurisdiction-specific updates." },
      { phase: "Week 9-12: Optimization", action: "Refine AML/KYC false-positive models to reduce the 'noise' of manual reviews." },
    ],
  },
];

const principles = [
  { number: 1, title: "Explainable AI (XAI)", desc: "Every credit decision and fraud flag includes human-readable reasoning and specific data inputs. No 'black box' decisions that fail regulatory audits." },
  { number: 2, title: "Fairness & Bias Monitoring", desc: "Continuous automated testing for demographic and socioeconomic bias in scoring models. Fair lending is a technical requirement, not a policy suggestion." },
  { number: 3, title: "Data Governance & Privacy", desc: "SOC 2, PCI-DSS, and GDPR compliant architectures. Financial data is encrypted, access-controlled, and never used for unauthorized training." },
  { number: 4, title: "Human-in-the-Loop", desc: "AI assists professionals; it doesn't replace them. High-value decisions and investigation escalations always route to qualified human experts." },
  { number: 5, title: "Model Traceability", desc: "Full version control and audit trails for every model version. Rollback capabilities and performance drift monitoring are built into the core." },
  { number: 6, title: "Regulatory Alignment", desc: "Built to adapt to evolving frameworks (NAIC, ECB, CFPB). Compliance isn't a post-launch check; it's the architecture's primary constraint." },
];

const governanceRows = [
  { principle: "Explainable Decisions", requirement: "Interpretability for every model output", relevance: "CFPB / ECB / Audit requirements" },
  { principle: "Bias Auditing", requirement: "No protected-attribute influence in scoring", relevance: "Equal Credit Opportunity Act (ECOA)" },
  { principle: "Data Encryption", requirement: "AES-256 at rest, TLS 1.3 in transit", relevance: "PCI-DSS / SOC 2 / GDPR" },
  { principle: "Human Override", requirement: "Final investigation/sign-off by professional", relevance: "Risk management & liability standards" },
  { principle: "Audit Trails", requirement: "Tamper-proof logging of all system actions", relevance: "FINRA / SEC / Regulatory reporting" },
  { principle: "Continuous Monitoring", requirement: "Real-time drift and performance alerts", relevance: "Model Risk Management (MRM) standards" },
];
