'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "riiid-labs",
  company: "Riiid Labs",
  industry: "EdTech",
  subIndustry: "Adaptive AI Test Preparation",
  accentColor: "violet",
  gradientClasses: "bg-gradient-to-br from-background via-violet-500/5 to-purple-500/10",
  heroHeadline: "Riiid Labs: AI That Gets Students to Their Target Score 58% Faster",
  heroSubheadline: "Adaptive AI engine using deep knowledge tracing to personalize TOEIC and standardized test preparation—delivering +176% score improvement while cutting required study time in half.",
  heroStats: [
    { value: "+176%", label: "Score Improvement", color: "text-violet-400" },
    { value: "-58%", label: "Faster Prep", color: "text-purple-400" },
    { value: "+40%", label: "Pass Rate", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does Riiid Labs use AI to improve test preparation outcomes?",
  directAnswer: "Riiid Labs deploys an AI adaptive testing engine using deep knowledge tracing that maintains a real-time model of each student's mastery state across 300+ granular concept nodes. The system predicts the single next question that will maximize expected score improvement for that specific learner at that moment—implementing AI-driven spaced repetition and generating personalized score trajectory forecasts. Students using the adaptive engine achieve +176% score gains vs. non-adaptive study plans in the same time period, because every question serves a precise learning purpose.",
  clientDescription: "Riiid Labs is an AI edtech company whose Santa AI engine powers personalized test preparation for high-stakes exams including TOEIC, SAT, and professional certification tests. Riiid's platform is particularly significant in South Korea, Japan, and Southeast Asia where standardized test scores have profound impact on career trajectories and university admission.",
  clientFounded: "2014",
  clientSize: "400+ employees, 10M+ students served",
  clientLocation: "Seoul, South Korea",
  problemTitle: "Generic Study Plans Were Wasting Precious Prep Time",
  problemDescription: "Traditional test prep forced students through identical content sequences regardless of their individual knowledge gaps. Advanced students wasted time on mastered concepts; struggling students hit advanced material before foundational gaps were addressed. Score plateaus were common, motivation dropped, and pass rates remained frustratingly low despite massive time investment.",
  painPoints: [
    { title: "Content Relevance Rate", stat: "34%", description: "Only 34% of questions studied were at the right difficulty level for each student—the rest were either too easy or too hard to drive improvement.", color: "red" },
    { title: "Average Study Time Required", stat: "100+ hrs", description: "Students in traditional programs spent 100+ hours to achieve target score improvements that adaptive AI achieves in 42 hours.", color: "amber" },
    { title: "Typical Score Improvement", stat: "+70 pts", description: "Non-adaptive programs delivered +70 points on TOEIC vs. +224 points with Riiid's AI-powered adaptive path.", color: "orange" },
  ],
  solutionTitle: "Deep Knowledge Tracing With Maximum Information Question Selection",
  solutionDescription: "AGIX Technologies built an AI adaptive testing engine using deep knowledge tracing (DKT) that models each student's mastery probability across 300+ concept nodes and selects the next question using maximum information theory—always choosing the question that will provide the most information about the student's true ability.",
  solutionComponents: [
    { title: "Deep Knowledge Tracing (DKT)", description: "LSTM-based knowledge state model that tracks mastery probability for 300+ concept nodes per student, updating continuously with every answered question." },
    { title: "Maximum Information Question Selection", description: "Each next question is selected by calculating the expected information gain across all available questions—choosing the item that maximally reduces uncertainty about the student's true ability." },
    { title: "Score Trajectory Forecasting", description: "Personalized score prediction model that forecasts expected score at target exam date based on current mastery state, study pace, and historical learning velocity data from similar learner profiles." },
    { title: "Spaced Repetition Optimization", description: "AI-driven review scheduling that times review of each concept at the predicted optimal moment before memory decay—eliminating both too-early (wasteful) and too-late (forgotten) review." },
    { title: "Concept Dependency Mapping", description: "Prerequisite relationship map for all 300+ concepts ensures foundational knowledge is solidified before dependent skills are introduced, preventing frustration from premature advanced exposure." },
    { title: "Study Efficiency Dashboard", description: "Student-facing analytics showing time-to-target-score, most valuable concepts to study next, and mastery progression across all skill areas—creating accountability and motivation." },
  ],
  architectureTitle: "Riiid Labs Adaptive Learning Architecture",
  architectureLayers: [
    { name: "Student Interaction", components: ["Question Delivery Interface", "Answer Recording", "Time-on-Task Tracking", "Confidence Rating Collection", "Study Mode Selection"], color: "sky" },
    { name: "Knowledge Modeling", components: ["Deep Knowledge Tracing (LSTM)", "300+ Concept Node Graph", "Mastery Probability Updating", "Forgetting Curve Modeling", "Learning Velocity Estimation"], color: "violet" },
    { name: "Question Selection", components: ["Item Response Theory (IRT)", "Maximum Information Selection", "Concept Dependency Enforcement", "Difficulty Band Management", "Anti-Fatigue Sequencing"], color: "purple" },
    { name: "Schedule & Forecast", components: ["Spaced Repetition Scheduler", "Score Trajectory Model", "Study Session Planner", "Target Date Calculator", "Concept Priority Ranker"], color: "blue" },
    { name: "Analytics & Motivation", components: ["Progress Dashboard", "Efficiency Metrics", "Peer Comparison Insights", "Streak & Achievement System", "Teacher/Parent Reporting"], color: "indigo" },
  ],
  resultsTitle: "Dramatic Score Improvements in Dramatically Less Time",
  resultsMetrics: [
    { value: "+224 pts", label: "TOEIC Score Gain", description: "Adaptive AI path in 10 weeks vs. +70 points on the same traditional curriculum", color: "violet" },
    { value: "-58%", label: "Study Hours Required", description: "42 hours to target score vs. 100+ hours with non-adaptive study plans", color: "purple" },
    { value: "91%", label: "Content Relevance Rate", description: "vs. 34% with traditional plans—nearly every question is at the right difficulty level", color: "blue" },
    { value: "+40%", label: "Pass Rate Improvement", description: "Higher proportion of students reaching target score cutoffs for career advancement", color: "green" },
  ],
  resultsQuote: {
    text: "Traditional test prep is like using a map without knowing where you are. Santa AI gives every student GPS-level precision—it knows exactly which concepts need work and the fastest route to mastery. That's why our students gain 3x more points in half the time.",
    author: "VP of Test Innovation",
    role: "Riiid Labs",
  },
  howItWorksTitle: "How Riiid's Adaptive Engine Accelerates Mastery",
  steps: [
    { title: "Baseline Assessment", description: "Establish the student's starting knowledge state across all concept nodes", detail: "A short adaptive diagnostic (25-40 questions) maps the student's initial mastery probabilities across all 300+ concept nodes. Questions are selected to maximize information gain—efficiently establishing baseline rather than exhaustive testing of every concept." },
    { title: "Knowledge State Modeling", description: "Maintain a real-time probabilistic model of mastery per concept", detail: "The DKT model maintains a mastery probability vector for the student. When a question is answered correctly or incorrectly, Bayesian updates propagate through the concept dependency graph—improving a concept's mastery estimate also improves related prerequisite concepts." },
    { title: "Maximum Information Question Selection", description: "Select the next question that most reduces uncertainty about ability", detail: "Before presenting each question, the system calculates the expected information gain for every available question in the item bank. The question selected maximizes the expected reduction in uncertainty about the student's true ability—making every question count." },
    { title: "Spaced Repetition Scheduling", description: "Schedule review of each concept at the optimal future moment", detail: "Each time a concept is studied, a review interval is calculated using a forgetting curve model calibrated to the student's historical retention patterns. Concepts approaching forgetting are automatically scheduled for review before the decay reaches a threshold." },
    { title: "Score Trajectory Projection", description: "Show the student their projected score and time-to-target", detail: "Based on current mastery state, learning velocity, and historical data from similar learner profiles, the system projects the expected score at the target exam date. If study pace is insufficient to reach the target, it calculates the required additional sessions per week." },
    { title: "Continuous Model Calibration", description: "Improve accuracy using actual exam outcomes as ground truth", detail: "When students sit the actual exam, their score is logged and compared to the model's prediction. Discrepancies trigger recalibration of the question difficulty estimates and mastery-to-score mapping, improving accuracy for subsequent students." },
  ],
  whyItWorkedTitle: "Why Riiid's Adaptive Engine Outperforms Traditional Prep",
  whyFactors: [
    { title: "Every Question Has a Purpose", description: "Maximum information question selection eliminates wasted practice—every question is chosen because it provides the most information about the student's current ability, not because it's next in a sequence." },
    { title: "Concept Dependencies Respected", description: "The concept dependency graph ensures students master foundational skills before attempting dependent concepts, eliminating the frustration of hitting advanced material before prerequisites are solid." },
    { title: "Score Visibility Creates Accountability", description: "Showing students their projected score and time-to-target creates goal-directed motivation that generic progress indicators cannot match—students can see exactly how today's study session moves the needle." },
    { title: "Forgetting Curve Integration", description: "Spaced repetition that adapts to each student's personal retention rate (not a fixed interval formula) dramatically reduces forgotten material—improving both efficiency and retention." },
    { title: "Item Bank Size and Quality", description: "The system's effectiveness scales with item bank size and calibration quality. Riiid's large, well-calibrated item bank provides enough items to support maximum information selection without repetition." },
    { title: "Market Context: High-Stakes Exams", description: "In markets where TOEIC scores determine career advancement, students are highly motivated to optimize their prep. The platform's efficiency promise resonated strongly in time-constrained professional markets." },
  ],
  limitations: [
    { title: "Requires Large, Calibrated Item Bank", description: "Maximum information question selection only works with a large, well-calibrated item bank. The system cannot operate effectively with fewer than ~1,000 items per subject." },
    { title: "Cold Start Diagnostic Has Uncertainty", description: "The initial diagnostic has higher uncertainty than later predictions. Students who perform unusually well or poorly on diagnostic questions can cause the model to start from a misestimated baseline." },
    { title: "Subject-Specific Knowledge Graphs Required", description: "Each test subject requires a custom concept dependency graph and item bank mapping. Launching new subjects requires significant curriculum mapping and item tagging investment." },
    { title: "Doesn't Replace Test Strategy Training", description: "The adaptive engine optimizes knowledge mastery but doesn't cover test-taking strategy—time management, elimination techniques, and format-specific skills require separate instruction." },
  ],
  whenToUseGoodFit: [
    "High-stakes standardized tests with large established item banks (TOEIC, SAT, GRE, GMAT)",
    "Learner populations with significant variance in starting knowledge states",
    "Markets where study time is constrained and efficiency is paramount",
    "Platforms with sufficient item calibration data (1,000+ items per concept area)",
    "Tests where score improvement has significant personal or career consequences",
  ],
  whenToUseNotGoodFit: [
    "Highly subjective assessments where multiple correct answers exist",
    "Skills-based certifications where practical demonstration matters more than knowledge recall",
    "Subjects with fewer than 500 available practice items",
    "Populations where internet access or digital literacy is limited",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Knowledge state modeling and score trajectory prediction", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Deep knowledge tracing system architecture and item selection engine", type: "service" },
    { name: "EdTech AI Solutions", slug: "edtech-ai-solutions", relevance: "AI-powered adaptive learning across standardized test preparation", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Adaptive question selection and spaced repetition scheduling", type: "intelligence" },
    { name: "Autonomous Agentic AI", slug: "autonomous-agentic-ai", relevance: "Autonomous study path optimization without manual curriculum design", type: "intelligence" },
  ],
  keyTakeaways: [
    "+224 TOEIC points in 10 weeks vs. +70 with traditional non-adaptive programs",
    "58% less study time required—42 hours vs. 100+ hours to reach target score",
    "Deep knowledge tracing updates mastery estimates across concept dependency graph with every answer",
    "Maximum information question selection ensures every practice question maximizes learning value",
    "Score trajectory projection creates goal-directed motivation unavailable in generic prep programs",
  ],
  faqs: [
    { question: "What is deep knowledge tracing and how is it different from traditional adaptive learning?", answer: "Traditional adaptive learning adjusts difficulty based on recent correct/incorrect rates. Deep knowledge tracing (DKT) uses LSTM neural networks to model the underlying probability of mastery for each concept, accounting for forgetting over time and updating estimates across related concepts when any concept is practiced. It's a fundamentally richer model of what the student actually knows." },
    { question: "How accurate is the score trajectory forecast?", answer: "Within 10% of actual exam score for students with 2+ weeks of study history in the system. Accuracy improves with study history. The model is recalibrated quarterly using actual exam outcomes from students who report their results." },
    { question: "How many questions does the system need before it gives reliable recommendations?", answer: "The initial diagnostic (~25-40 questions) establishes a usable baseline within the first session. Recommendations are meaningful from session one, but accuracy improves substantially after 200+ questions across multiple sessions as the model refines its mastery estimates." },
    { question: "Can the platform be used for subjects other than standardized tests?", answer: "The underlying technology (deep knowledge tracing, spaced repetition, item selection) is subject-agnostic. However, effective deployment requires a well-calibrated item bank and concept dependency graph for the target subject—which is the primary investment for new subject expansion." },
    { question: "How does the system handle students who plateau?", answer: "When a student's learning velocity drops below expected rate for a given concept, the system identifies the plateau, analyzes which prerequisite concepts may have gaps, and switches to a remediation path addressing the root cause rather than continuing to push the stuck concept." },
  ],
  prevCase: { name: "Knewton", url: "/case-studies/knewton/" },
  nextCase: { name: "HouseCanary", url: "/case-studies/housecanary/" },
};

export default function RiiidLabsCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
