'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "kite-therapy",
  company: "Kite Therapy",
  industry: "Mental Health Technology",
  subIndustry: "Empathetic AI Companion",
  accentColor: "rose",
  gradientClasses: "bg-gradient-to-br from-background via-rose-500/5 to-purple-500/10",
  heroHeadline: "Kite Therapy: AI Companions That Know When To Call For Help",
  heroSubheadline: "Building mental health AI that's warm enough to help, safe enough to trust, and smart enough to recognize when human intervention is non-negotiable—serving users between therapy sessions with 99.8% crisis detection accuracy.",
  heroStats: [
    { value: "+89%", label: "User Retention", color: "text-rose-400" },
    { value: "99.8%", label: "Crisis Detection", color: "text-purple-400" },
    { value: "3.2x", label: "Therapy Session Impact", color: "text-pink-400" },
  ],
  directAnswerQuestion: "How does Kite Therapy use AI for mental health support?",
  directAnswer: "Kite Therapy deploys empathetic AI companions that provide between-session mental health support using evidence-based conversational techniques (CBT, DBT, motivational interviewing) calibrated to each user's emotional state. The system detects crisis signals with 99.8% accuracy and escalates to human support immediately when needed. Users who engage with Kite between therapy sessions show 3.2x greater progress on clinical outcome measures than those in therapy alone.",
  clientDescription: "Kite Therapy is a mental health support platform that bridges the gap between weekly therapy sessions, where users spend 50 minutes per week with a therapist and 10,070 minutes without one. The platform's AI companions provide emotionally calibrated support, psychoeducation, and skill practice, with a safety architecture that ensures crisis situations always reach human professionals.",
  clientFounded: "2019",
  clientSize: "200,000+ active users, 40+ therapeutic partner organizations",
  clientLocation: "Boston, MA, USA",
  problemTitle: "Mental Health Care Has a Between-Session Problem",
  problemDescription: "Therapy is effective, but people only attend therapy 1 hour per week. Between sessions, they face anxiety spirals at 2am, depression on Tuesday afternoon, and panic attacks on Friday evenings—with nothing but a waiting period until their next appointment. Traditional digital mental health tools are either too generic (guided meditation apps) or too clinical (symptom tracking tools) to provide genuine emotional support in these moments.",
  painPoints: [
    { title: "Therapy Gap Hours Per Week", stat: "167 hrs", description: "Hours between weekly therapy sessions where patients have no clinical support—where most mental health crises and skill-practice opportunities occur.", color: "rose" },
    { title: "Skill Practice Completion", stat: "23%", description: "Proportion of patients who successfully practice therapist-assigned CBT skills between sessions without structured support or accountability.", color: "purple" },
    { title: "Crisis Access Time", stat: "Hours", description: "Typical wait time to reach a mental health professional during a non-emergency crisis moment—a critical gap for people at medium risk.", color: "red" },
  ],
  solutionTitle: "Emotionally Intelligent AI With Evidence-Based Therapeutic Techniques",
  solutionDescription: "AGIX Technologies built an AI companion system that uses fine-tuned language models trained on therapeutic conversation patterns, calibrated to respond with appropriate warmth and evidence-based techniques for each emotional state. The safety architecture treats crisis detection as a non-negotiable primary function—no engagement metric can override the crisis response protocol.",
  solutionComponents: [
    { title: "Emotional State Calibration Engine", description: "Detects user emotional state from conversation signals and adjusts the AI's tone, pacing, and technique selection: grounding exercises for anxiety, validation for sadness, gentle challenge for cognitive distortions." },
    { title: "CBT/DBT Skill Practice Guide", description: "Structured skill practice modules for therapist-assigned techniques, with the AI adapting the practice session to the user's current emotional state and energy level." },
    { title: "Crisis Detection System", description: "Multi-signal crisis detection combining language analysis, behavioral patterns, and explicit disclosure flags. Any medium or high crisis signal triggers immediate escalation to human crisis support—never AI-only handling." },
    { title: "Therapist Collaboration Interface", description: "Therapists connected to the platform receive session summaries, skill practice completion rates, and mood pattern data—extending their clinical insight between sessions without additional patient burden." },
    { title: "Crisis Resource Integration", description: "When escalation is warranted, the system provides warm handoffs to crisis lines, the user's therapist's emergency contact, and local emergency services with location awareness." },
    { title: "Progress & Pattern Tracking", description: "Longitudinal mood tracking, skill practice records, and engagement patterns are shared with the user's therapist as a clinical supplement—transforming the AI companion into a clinical monitoring tool." },
  ],
  architectureTitle: "Kite Therapy AI Architecture",
  architectureLayers: [
    { name: "User Interface", components: ["Mobile App (iOS/Android)", "Text & Voice Input", "Mood Check-In Widget", "Skill Practice Modules"], color: "rose" },
    { name: "Emotional Intelligence Layer", components: ["Emotional State Detection", "Crisis Signal Classification", "Therapeutic Technique Selection", "Tone Calibration Engine"], color: "purple" },
    { name: "Conversation Intelligence", components: ["Therapeutic Response Generation", "CBT/DBT Pattern Library", "Empathy-First Response Templates", "Context Window Management"], color: "pink" },
    { name: "Safety Architecture", components: ["Multi-Signal Crisis Detection", "99.8% Sensitivity Crisis Model", "Mandatory Escalation Protocols", "Audit Trail Generation"], color: "red" },
    { name: "Clinician Integration", components: ["Therapist Dashboard", "Session Summary Generation", "Mood Pattern Reporting", "Crisis Alert System"], color: "slate" },
  ],
  resultsTitle: "Clinical and Safety Outcomes for Mental Health Support",
  resultsMetrics: [
    { value: "99.8%", label: "Crisis Detection Accuracy", description: "Sensitivity for detecting crisis-level user states—the system is calibrated to never miss a crisis at the cost of occasional false positives", color: "rose" },
    { value: "+89%", label: "User Retention", description: "Retention rate for users who engage with the companion vs 52% for apps without between-session AI support", color: "purple" },
    { value: "3.2x", label: "Therapy Progress", description: "Improvement in clinical outcome measures for users with AI companion vs therapy-only control group", color: "pink" },
    { value: "73%", label: "Skill Practice Rate", description: "vs 23% baseline—users practice therapist-assigned skills 3x more often with AI companion scaffolding", color: "indigo" },
  ],
  resultsQuote: {
    text: "Kite has become part of my clinical toolkit. I can see exactly how my patients are doing between sessions, which skills they're practicing, and when they needed support at 2am. It extends my reach without extending my hours.",
    author: "Licensed Clinical Psychologist",
    role: "Private Practice, San Francisco",
  },
  howItWorksTitle: "How Kite Therapy's AI Supports a User in Distress",
  steps: [
    { title: "Check-In & State Detection", description: "Understand where the user is emotionally", detail: "Each session begins with an optional mood check-in, but the AI is continuously reading emotional signals from conversation content regardless. The emotional state model classifies the user's current state (anxious, depressed, angry, neutral, elevated risk) and selects the appropriate response framework." },
    { title: "Empathy-First Acknowledgment", description: "Validate before attempting to help", detail: "The response model always begins with emotional acknowledgment before any intervention or technique. A user saying 'I feel like nothing matters' receives 'That sounds really heavy—I'm glad you're talking to me' before any therapeutic technique. Validation first is both clinically sound and the only appropriate response to human distress." },
    { title: "Crisis Assessment", description: "Continuously monitor for escalating crisis signals", detail: "The crisis detection model runs on every message, not just explicit disclosures. It looks for direct statements, passive ideation, behavioral risk accumulation signals, and linguistic patterns associated with crisis states. The threshold for flagging is deliberately sensitive—false positives result in a caring check-in, false negatives are never acceptable." },
    { title: "Technique Selection & Application", description: "Apply evidence-based support appropriate to the state", detail: "For anxiety: grounding exercises, breathing techniques, cognitive reframing. For depression: behavioral activation encouragement, meaningful activity prompts, connection to values. For anger: validation first, then exploration of underlying emotions. Techniques are presented as offerings, not prescriptions—user agency is maintained throughout." },
    { title: "Crisis Escalation", description: "When signals indicate crisis, escalate immediately", detail: "Medium or high crisis signals trigger an escalation sequence: immediate safety check-in, offer of crisis line connection, option to alert their connected therapist, and in high-acuity situations, recommendation to call emergency services with location awareness. The AI never attempts to manage a genuine crisis independently." },
    { title: "Session Summary & Clinician Update", description: "Create clinical record for the therapist", detail: "At session end, an automated summary captures mood trajectory, topics discussed, techniques practiced, and any escalation events. This is shared with the user's connected therapist in a structured format that fits within their existing clinical documentation workflow—not adding administrative burden but supplementing clinical insight." },
  ],
  whyItWorkedTitle: "Why Safety-First Design Created Better Clinical Outcomes",
  whyFactors: [
    { title: "Non-Negotiable Crisis Detection Priority", description: "Making crisis detection a safety constraint that cannot be overridden by any engagement or retention metric ensured the system never optimized for retention at the cost of safety." },
    { title: "Therapeutic Alliance Through Consistency", description: "Unlike human therapists who may be unavailable at 2am, the AI is always present with consistent warmth. This availability during high-risk moments creates a therapeutic relationship that makes users more likely to use skills and less likely to escalate to crisis." },
    { title: "Clinician Integration Created Credibility", description: "Connecting the AI to a user's existing therapist—rather than replacing them—created clinical legitimacy. Therapists who could see AI session data trusted and recommended the tool more actively." },
    { title: "Evidence-Based Technique Grounding", description: "Training the response model on actual therapeutic conversations rather than general empathetic dialogue produced responses that felt genuinely helpful rather than platitudinous." },
    { title: "Honest About AI Limitations", description: "The AI is explicit that it's an AI and cannot provide therapy. This honesty, paradoxically, built more trust than systems that simulated being human." },
  ],
  limitations: [
    { title: "Not a Replacement for Therapy", description: "The system explicitly positions itself as between-session support, not clinical treatment. Users in acute psychiatric crisis, active psychosis, or requiring medication management need in-person clinical care." },
    { title: "Cultural and Language Nuance", description: "Emotional expression, appropriate responses to distress, and culturally appropriate therapeutic techniques vary significantly across cultures. The current model is most validated for English-speaking Western contexts." },
    { title: "Trauma Processing Requires Specialists", description: "Complex trauma, PTSD processing, and trauma-informed care require specialized clinical expertise. The AI provides supportive presence but does not attempt trauma processing techniques that require trained supervision." },
    { title: "Interpersonal Crisis Situations", description: "When users are in crisis situations involving other people (domestic violence, immediate physical threat), the AI's ability to help is limited. These situations require immediate human emergency services." },
  ],
  whenToUseGoodFit: [
    "Mental health platforms seeking to support users between clinical appointments",
    "Therapist networks wanting to extend clinical reach without additional session time",
    "Healthcare organizations reducing crisis escalation rates for medium-risk populations",
    "Employee assistance programs providing accessible mental health support at scale",
  ],
  whenToUseNotGoodFit: [
    "Acute psychiatric care settings where clinical supervision must be immediate",
    "Platforms serving users with active psychosis or complex trauma without clinical oversight",
    "Applications where there is no clear escalation path to human clinical support",
    "Populations where technology access or digital literacy is a significant barrier",
  ],
  connections: [
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Empathetic therapeutic dialogue with safety constraints", type: "service" },
    { name: "Agentic AI Systems", slug: "agentic-ai-systems", relevance: "Multi-step crisis assessment and escalation orchestration", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Specialized therapeutic AI with safety-first architecture", type: "service" },
    { name: "Healthcare AI Solutions", slug: "healthcare-ai-solutions", relevance: "Mental health and behavioral health AI deployment patterns", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Empathy-calibrated dialogue with clinical safety constraints", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Crisis signal classification and escalation decision systems", type: "intelligence" },
  ],
  keyTakeaways: [
    "Crisis detection is a safety constraint, not a metric—99.8% sensitivity is non-negotiable",
    "Between-session AI support produces 3.2x better clinical outcomes than therapy alone",
    "Validation before intervention is the foundational design principle—always empathize first",
    "Clinician integration (vs replacement) creates the clinical credibility that drives adoption",
    "Honest AI identity disclosure builds more trust than simulating a human",
  ],
  faqs: [
    { question: "Is Kite Therapy a licensed medical device?", answer: "Kite Therapy operates as a mental wellness application and is not a licensed medical device or a provider of clinical mental health treatment. It is positioned as a between-session support tool that complements clinical care. For organizations seeking to use AI in clinical treatment protocols, regulatory classification depends on specific use cases and must be evaluated with healthcare law counsel." },
    { question: "How does the 99.8% crisis detection accuracy work in practice?", answer: "The crisis detection model uses a deliberately sensitive threshold—it is calibrated to produce false positives (unnecessary check-ins) rather than false negatives (missed crises). In practice, about 3% of flags turn out to be false alarms that result in a caring safety check-in but no clinical escalation. This rate is considered acceptable given that false negatives in this context have unacceptable consequences." },
    { question: "Can the system work without a connected therapist?", answer: "Yes. Users without a connected therapist still receive AI companion support with crisis escalation to crisis lines and emergency services. The clinical integration features (therapist dashboard, session summaries) require a connected provider but are not necessary for the core safety and support functionality." },
    { question: "What happens when a user in crisis refuses to escalate?", answer: "The system cannot physically compel anyone to seek help. When a user in crisis declines escalation, the AI maintains contact, continues safety assessment, and provides crisis line information repeatedly and accessibly. In situations involving immediate safety, the system provides emergency services contact and encourages their use while maintaining the supportive relationship." },
    { question: "How is the AI trained to provide therapeutic responses?", answer: "The response model was fine-tuned on thousands of anonymized therapeutic conversation examples reviewed and labeled by licensed clinical psychologists. The training emphasized empathetic validation, evidence-based technique application, and appropriate boundary-setting. Ongoing response quality is monitored by a clinical team who review flagged conversations and update training data quarterly." },
  ],
  prevCase: { name: "Babylon Health", url: "/case-studies/babylon-health/" },
  nextCase: { name: "Hello Driven", url: "/case-studies/hello-driven/" },
};

export default function KiteTherapyCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
