'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "navan",
  company: "Navan",
  industry: "Business Travel & Expense",
  subIndustry: "AI Travel & Expense Management",
  accentColor: "indigo",
  gradientClasses: "bg-gradient-to-br from-background via-indigo-500/5 to-violet-500/10",
  heroHeadline: "Navan: AI That Automates 89% of Expense Report Reviews",
  heroSubheadline: "Eliminating the expense report as we know it—AI captures, categorizes, and validates business expenses in real time, reducing manual review by 89% and policy violations by 64% while improving employee satisfaction.",
  heroStats: [
    { value: "-89%", label: "Manual Review Time", color: "text-indigo-400" },
    { value: "-64%", label: "Policy Violations", color: "text-violet-400" },
    { value: "+94%", label: "Policy Compliance", color: "text-blue-400" },
  ],
  directAnswerQuestion: "How does Navan use AI to automate business travel and expense management?",
  directAnswer: "Navan uses an AI system that automatically captures expenses from corporate card transactions, email receipts, and manual uploads, then applies company policy rules in real time to classify, validate, and route each expense for approval—or auto-approve it if it meets all policy criteria. The system detects policy violations at the point of spend (not weeks later in a report review), reducing violations by 64% and eliminating the 3-hour monthly expense report ritual for most employees.",
  clientDescription: "Navan (formerly TripActions) is an integrated travel, corporate card, and expense management platform used by over 10,000 companies worldwide. Their platform manages business travel booking, corporate card spending, and expense reporting in a unified system—the AI layer connects all three to enable policy-aware automation that standalone expense tools can't achieve.",
  clientFounded: "2015",
  clientSize: "10,000+ company customers, $9B+ in annual spend managed",
  clientLocation: "Palo Alto, CA, USA",
  problemTitle: "Expense Management Is Everyone's Least Favorite Process—And It's Broken",
  problemDescription: "Finance teams waste thousands of hours reviewing expense reports for policy violations that employees could have avoided if they'd known about them at the time of purchase. Employees spend 3+ hours per month submitting expenses from crumpled receipts. Reimbursement cycles take 2-4 weeks. And despite all this effort, 15-30% of expense reports contain policy violations—most of which slip through undetected.",
  painPoints: [
    { title: "Finance Review Time Per Report", stat: "45 min", description: "Average time finance staff spend reviewing a single expense report—multiplied by hundreds of reports per month creates a significant labor cost.", color: "indigo" },
    { title: "Undetected Policy Violations", stat: "~22%", description: "Proportion of submitted expense reports containing at least one policy violation that was not caught before reimbursement.", color: "red" },
    { title: "Employee Expense Reporting Time", stat: "3.1 hrs/mo", description: "Average hours per employee per month spent on expense report completion—universally cited as the most disliked administrative task.", color: "amber" },
  ],
  solutionTitle: "Real-Time Expense Intelligence That Enforces Policy at the Point of Spend",
  solutionDescription: "AGIX Technologies built an expense intelligence layer that captures spending across all channels in real time, applies policy rules immediately rather than in a post-hoc review, and automates the approval workflow for compliant expenses—so finance teams only see the exceptions that actually need human judgment.",
  solutionComponents: [
    { title: "Automatic Receipt Capture", description: "Captures receipts from three sources automatically: corporate card transaction feeds, email receipt parsing (Gmail and Outlook integrations), and mobile photo capture—eliminating manual data entry for 87% of expenses." },
    { title: "Real-Time Policy Engine", description: "Applies company expense policy rules at the point of transaction, providing immediate feedback when a purchase approaches or exceeds a policy threshold rather than catching violations weeks later in report review." },
    { title: "Intelligent Categorization", description: "Auto-categorizes expenses using merchant classification, transaction description, and contextual signals—85% of expenses are correctly categorized without employee input, reducing report completion time." },
    { title: "Smart Approval Routing", description: "Fully compliant expenses are auto-approved and processed for reimbursement without manager touchpoints. Non-compliant expenses are routed with an AI-generated explanation of the specific policy issue." },
    { title: "Anomaly Detection", description: "Identifies statistical anomalies in spending patterns—a meal expense 4x the usual for that employee's department, a hotel booking at a property not on the approved vendor list—flagging them for priority review." },
    { title: "Predictive Policy Coaching", description: "Before travel, the AI surfaces relevant policy reminders for the booked destination: per diem rates, preferred hotel tiers, transportation policies for that city—reducing violations through advance awareness." },
  ],
  architectureTitle: "Navan AI Expense Intelligence Architecture",
  architectureLayers: [
    { name: "Data Capture Layer", components: ["Corporate Card Transaction Feed", "Email Receipt Parsing", "Mobile Receipt OCR", "Travel Booking Integration"], color: "indigo" },
    { name: "Classification Engine", components: ["Merchant Category Classification", "Receipt Data Extraction", "Trip Context Matching", "Employee Profile Integration"], color: "violet" },
    { name: "Policy Intelligence", components: ["Real-Time Policy Rule Engine", "Per-Diem Rate Tables", "Vendor Approval Lists", "Limit & Threshold Checking"], color: "blue" },
    { name: "Workflow Automation", components: ["Auto-Approval Logic", "Exception Routing", "Manager Notification System", "Reimbursement Processing"], color: "purple" },
    { name: "Analytics & Compliance", components: ["Spend Analytics Dashboard", "Anomaly Detection Alerts", "Policy Compliance Reporting", "Audit Trail Generation"], color: "slate" },
  ],
  resultsTitle: "Finance Efficiency and Employee Satisfaction Outcomes",
  resultsMetrics: [
    { value: "-89%", label: "Manual Review Time", description: "Finance team hours spent on expense report review—from 45 min average to 5 min for auto-reviewed reports", color: "indigo" },
    { value: "+94%", label: "Policy Compliance", description: "Proportion of expenses compliant with company policy vs 78% before real-time policy enforcement", color: "blue" },
    { value: "-64%", label: "Policy Violations", description: "Reduction in detected policy violations with real-time enforcement vs post-hoc report review", color: "violet" },
    { value: "-72%", label: "Reporting Time", description: "Reduction in employee time spent on monthly expense reporting—from 3.1 hours to under 45 minutes", color: "purple" },
  ],
  resultsQuote: {
    text: "Our finance team used to spend the last week of every month in expense report hell. Now they review maybe 15% of reports manually—the rest are auto-approved because the AI already verified them. The whole team has their time back for actual financial analysis.",
    author: "VP of Finance",
    role: "Series D Technology Company",
  },
  howItWorksTitle: "How Navan's AI Manages an Expense End-to-End",
  steps: [
    { title: "Transaction Capture & Receipt Matching", description: "Capture the expense the moment it occurs", detail: "When an employee makes a purchase on the corporate card, the transaction is captured in real time. The system immediately attempts to match it to a receipt from the employee's email (scanning for matching merchant name, date, and amount) or sends a push notification requesting the mobile receipt capture. No more collecting receipts to enter at month end." },
    { title: "Data Extraction & Categorization", description: "Extract and classify expense details automatically", detail: "The expense record is enriched: merchant name from the MCC code, amount and currency, business purpose inferred from merchant type and travel context, and expense category classification. The AI uses the employee's current trip booking context (if traveling) to auto-suggest the business purpose." },
    { title: "Real-Time Policy Validation", description: "Apply company policy rules immediately", detail: "Every expense is checked against the company's policy rules in real time: is this merchant on the approved vendor list? Does this meal expense exceed the per-diem for this city? Is this hotel above the nightly rate cap for this region? Policy issues generate immediate in-app notifications, not post-submission rejection emails." },
    { title: "Auto-Approval or Exception Routing", description: "Process compliant expenses automatically", detail: "Expenses that clear all policy validations are automatically approved and queued for reimbursement without requiring manager action. Expenses with policy questions are routed to the appropriate approver with an AI-generated explanation of exactly which policy was triggered and why—cutting approval decision time from 20 minutes to 2." },
    { title: "Anomaly Detection & Priority Flagging", description: "Identify unusual spending patterns for finance review", detail: "The anomaly detection model flags expenses that are statistically unusual relative to the employee's history, department norms, and similar trip profiles. These flags prioritize the finance team's manual review queue—directing attention where risk is actually elevated rather than applying uniform review to every expense." },
    { title: "Reimbursement Processing & Reporting", description: "Close the expense cycle efficiently", detail: "Approved expenses are processed for reimbursement on the configured schedule. Finance analytics dashboards show real-time spend across categories, departments, and vendors—enabling proactive budget management rather than backward-looking expense analysis." },
  ],
  whyItWorkedTitle: "Why Point-of-Spend Policy Enforcement Beats Report Review",
  whyFactors: [
    { title: "Enforcement at Transaction Time Changes Behavior", description: "Telling an employee about a policy violation the moment they make the purchase is 10x more effective at changing behavior than telling them 3 weeks later in a report rejection—they can still make a different choice." },
    { title: "Automatic Capture Eliminated the Bottleneck", description: "The single largest source of employee expense reporting friction was manual data entry. Automatic receipt capture from cards and email eliminated the primary reason expense reports took 3 hours." },
    { title: "Auto-Approval for Compliant Expenses", description: "Finance teams can only add value reviewing genuinely problematic expenses. Auto-approving the 85%+ of compliant expenses returns hours to finance staff for strategic work while maintaining oversight where it matters." },
    { title: "Travel Booking Integration Created Policy Context", description: "Knowing an employee is traveling (from their booking) allows the AI to apply the correct per diem, hotel tier policy, and transportation policy for the specific destination automatically—without requiring the employee to know policy details." },
  ],
  limitations: [
    { title: "Complex Policy Exceptions Need Human Judgment", description: "Unusual business situations (client entertainment above standard limits for a major deal, emergency travel expenses) require human context that automated policy rules can't fully accommodate." },
    { title: "Cross-Jurisdiction Tax Complexity", description: "International expense reporting with VAT reclaim requirements, local tax codes, and multi-currency complexity benefits from AI assistance but still requires human review in many jurisdictions." },
    { title: "Personal Card Reimbursement Has Data Gaps", description: "When employees use personal cards, automatic capture relies on email receipt parsing—less reliable than direct card integration and requires employee cooperation to forward receipts promptly." },
    { title: "Policy Customization Requires Configuration Investment", description: "The full value of real-time policy enforcement requires the customer's complete expense policy to be configured in the system—a one-time investment of 2-4 weeks but a prerequisite for automation benefits." },
  ],
  whenToUseGoodFit: [
    "Companies with 50+ employees spending meaningfully on business travel and entertainment",
    "Finance teams spending 20+ hours per month on expense report review",
    "Organizations with complex expense policies across multiple employee types or markets",
    "Companies whose corporate card issuer provides real-time transaction data feeds",
  ],
  whenToUseNotGoodFit: [
    "Very small companies (under 20 employees) where manual review is trivial",
    "Organizations with extremely simple expense policies (flat per diems, no exceptions)",
    "Companies where cash expenses are the primary mechanism and receipt capture is impractical",
  ],
  connections: [
    { name: "AI Automation", slug: "ai-automation", relevance: "Expense capture, categorization, and approval workflow automation", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Spend pattern anomaly detection and policy violation prediction", type: "service" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Corporate finance and expense management AI deployment", type: "industry" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Finance operations automation and compliance management", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Policy compliance decisioning and exception routing", type: "intelligence" },
  ],
  keyTakeaways: [
    "Point-of-spend enforcement reduces violations 64% vs post-submission report review",
    "Automatic receipt capture from cards and email eliminates the primary employee reporting burden",
    "Auto-approval for compliant expenses returns hours to finance teams for strategic work",
    "Travel booking integration provides policy context (per diems, hotel tiers) automatically",
    "Anomaly detection directs finance attention to genuinely elevated-risk expenses",
  ],
  faqs: [
    { question: "How does Navan handle expense reports for employees using personal credit cards?", answer: "Personal card expenses are captured through email receipt forwarding (automated parsing of emailed receipts from major retailers and services) and manual mobile upload. The capture is less seamless than corporate card integration but still enables categorization, policy checking, and approval routing for personal card reimbursement requests." },
    { question: "What happens when the AI miscategorizes an expense?", answer: "Employees can correct any auto-categorized expense in the mobile app with a single tap before submission. Corrections are logged as training signals, improving categorization accuracy for similar merchants over time. After 3–6 months, most customers see auto-categorization accuracy above 90% for their specific expense patterns." },
    { question: "How are expense policy updates deployed?", answer: "Finance administrators update policy rules through a configuration interface—no code changes required. Policy updates are effective for all new transactions within 24 hours of configuration. Expenses already in progress at the time of a policy change are governed by the policy in effect when the transaction occurred." },
    { question: "Does Navan support multi-currency and international expenses?", answer: "Yes. International transactions are automatically converted to the company's reporting currency using the exchange rate at transaction time, with the original currency amount and exchange rate retained in the expense record. Per diem rates and hotel tier policies are configured per country/city to apply locally appropriate limits to international travel expenses." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function NavanCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
