'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "geovea",
  company: "Geovea",
  industry: "Travel Technology",
  subIndustry: "AI Itinerary Planning",
  accentColor: "rose",
  gradientClasses: "bg-gradient-to-br from-background via-rose-500/5 to-pink-500/10",
  heroHeadline: "Geovea: AI That Creates Perfect Travel Itineraries With 92% Accuracy",
  heroSubheadline: "Replacing static travel templates with dynamically personalized itineraries—matching traveler style, pace, budget, and hidden gem preferences to generate plans users actually follow.",
  heroStats: [
    { value: "+214%", label: "User Engagement", color: "text-rose-400" },
    { value: "92%", label: "Itinerary Accuracy", color: "text-pink-400" },
    { value: "4.9/5", label: "User Rating", color: "text-amber-400" },
  ],
  directAnswerQuestion: "How does Geovea use AI to generate personalized travel itineraries?",
  directAnswer: "Geovea uses a multi-modal AI planning system that combines traveler preference profiling, real-time data about destinations (opening hours, crowd levels, seasonal conditions), and a travel knowledge graph to generate day-by-day itineraries optimized for the individual. The system learns from completion rates—which activities users actually do vs skip—and continuously improves personalization accuracy. Users rate 92% of Geovea itineraries as 'accurate to what I actually wanted.'",
  clientDescription: "Geovea is an AI-native travel planning platform that serves individual travelers, travel agents, and tour operators who want to create genuinely personalized travel experiences rather than generic packages. The platform differentiates on itinerary quality and personalization depth—users provide preference signals and receive plans that feel like they were curated by a friend who knows both them and the destination well.",
  clientFounded: "2020",
  clientSize: "500,000+ itineraries generated, 50+ countries covered",
  clientLocation: "Austin, TX, USA",
  problemTitle: "Travel Templates Are One-Size-Fits-None",
  problemDescription: "Existing travel planning tools offer the same Paris itinerary to every visitor: Eiffel Tower, Louvre, Versailles. These templates ignore who the traveler is—a food-obsessed couple who wants to spend three days in one neighborhood is not the same as a family with three kids who needs playgrounds near every museum. Generic templates lead to itineraries travelers abandon on day two.",
  painPoints: [
    { title: "Template Abandonment Rate", stat: "58%", description: "Proportion of users who abandon generated travel itineraries mid-trip because the plan didn't match their actual preferences or pace.", color: "rose" },
    { title: "Time to Build Custom Plan", stat: "8+ hours", description: "Average time travelers spend manually researching and building a personalized trip itinerary across blogs, maps, and review sites.", color: "amber" },
    { title: "Hidden Gem Discovery Rate", stat: "12%", description: "Proportion of travelers who discover off-the-beaten-path experiences they loved—most end up at the same overcrowded tourist sites.", color: "orange" },
  ],
  solutionTitle: "Dynamic Itinerary Generation With Real-Time Destination Intelligence",
  solutionDescription: "AGIX Technologies built a planning engine that builds a deep preference model for each traveler from a 5-minute onboarding conversation, then matches those preferences against a continuously updated destination knowledge graph including crowd patterns, seasonal conditions, and local intelligence curated from traveler feedback.",
  solutionComponents: [
    { title: "Traveler Preference Profiling", description: "A conversational onboarding flow builds a rich preference vector: pace (fast vs slow), interests (food, history, nature, nightlife), budget tier, accommodation style, and adventure level." },
    { title: "Real-Time Destination Graph", description: "A continuously updated knowledge graph for 50+ countries includes venue hours, crowd levels by day/time, seasonal closures, entry requirements, and community-curated hidden gems." },
    { title: "Day-by-Day Itinerary Optimizer", description: "The planner optimizes across geography (minimize backtracking), energy (balance intensive and relaxed activities), and time (account for actual travel durations between venues)." },
    { title: "Weather & Event Integration", description: "Real-time weather forecasts and local event calendars are integrated at generation time—rain tomorrow means swapping outdoor venues for indoor alternatives automatically." },
    { title: "Completion Tracking & Adaptation", description: "As travelers use the app during their trip, completions and skips are tracked. The plan adapts in real time: if they're running late, subsequent activities are adjusted in duration or replaced." },
    { title: "Local Intelligence Layer", description: "Crowdsourced local tips from previous travelers and curated expert insights are matched to the traveler's preference profile to add genuinely personal hidden gem recommendations." },
  ],
  architectureTitle: "Geovea AI Travel Planning Architecture",
  architectureLayers: [
    { name: "Preference Input", components: ["Conversational Onboarding Flow", "Interest & Pace Profiling", "Budget & Style Calibration", "Past Trip Learning"], color: "rose" },
    { name: "Destination Intelligence", components: ["50-Country Knowledge Graph", "Real-Time Hours & Crowd Data", "Weather API Integration", "Local Events Calendar"], color: "pink" },
    { name: "Planning Engine", components: ["Preference-Destination Matching", "Geographic Route Optimization", "Energy Level Scheduling", "Temporal Constraint Solving"], color: "orange" },
    { name: "Dynamic Adaptation", components: ["In-Trip Completion Tracking", "Real-Time Itinerary Adjustment", "Weather-Based Swapping", "Pace Adaptation"], color: "amber" },
    { name: "Learning & Improvement", components: ["Completion Rate Analysis", "User Rating Collection", "Local Intelligence Crowdsourcing", "Preference Model Refinement"], color: "slate" },
  ],
  resultsTitle: "Engagement and Satisfaction Metrics",
  resultsMetrics: [
    { value: "+214%", label: "User Engagement", description: "Users who received AI-personalized itineraries engaged 3x more vs template users", color: "rose" },
    { value: "92%", label: "Itinerary Accuracy", description: "Rated 'accurate to what I wanted' by users after completing their trip", color: "pink" },
    { value: "4.9/5", label: "Average Rating", description: "App store and in-trip satisfaction rating across all platforms", color: "amber" },
    { value: "-58%", label: "Mid-Trip Abandonment", description: "Reduction in users who abandoned their itinerary before completing it", color: "orange" },
  ],
  resultsQuote: {
    text: "I gave the AI three things: I hate crowds, I love food, and I have a 6-year-old. It gave me a Paris itinerary I would never have found on my own. We hit zero tourist traps and found a crepe stand that's been there since 1948.",
    author: "Platform User",
    role: "Paris Family Trip, July 2024",
  },
  howItWorksTitle: "How Geovea Generates a Personalized Itinerary",
  steps: [
    { title: "Preference Profiling", description: "5-minute conversational onboarding", detail: "The onboarding conversation asks about travel style, not just interests. 'Do you prefer to have one deep experience or cover more ground?' tells the planner more than 'I like museums'. The conversation builds a preference vector that weights 40+ planning dimensions before the first itinerary is generated." },
    { title: "Destination Knowledge Pull", description: "Retrieve live destination intelligence", detail: "The knowledge graph query returns all venues in the destination matching the traveler's preferences, enriched with real-time data: current hours, known crowd patterns for their travel dates, seasonal closures, weather forecast, and local events during their stay." },
    { title: "Itinerary Construction", description: "Build a day-by-day plan", detail: "The planning algorithm constructs a day-by-day itinerary that optimizes across three dimensions simultaneously: geographic efficiency (minimize travel time), energy balance (alternate intense and relaxed activities), and preference alignment (high-weight items scheduled in their best conditions)." },
    { title: "Hidden Gem Integration", description: "Add off-the-beaten-path recommendations", detail: "For each traveler's preference profile, the local intelligence layer adds 2–3 hidden gem recommendations per day—venues that appear in local knowledge but not major travel guides. These are matched to the traveler's specific interests rather than generic 'local favorites'." },
    { title: "Pre-Trip Confirmation & Adjustments", description: "Finalize with traveler before departure", detail: "The traveler reviews the generated itinerary and can make adjustments via natural language: 'Can we add a half day at the coast?' or 'Move the museum to Wednesday, we have dinner plans Tuesday night.' The planner re-optimizes around changes instantly." },
    { title: "In-Trip Dynamic Adaptation", description: "Adapt the plan as the trip unfolds", detail: "During the trip, the app tracks which activities are completed and skipped. If running 45 minutes behind schedule, it automatically adjusts subsequent activity durations and suggests the most time-efficient alternative venues. If a venue is unexpectedly closed, it immediately substitutes a matched alternative." },
  ],
  whyItWorkedTitle: "Why Geovea's AI Actually Beats Human Travel Agents",
  whyFactors: [
    { title: "Completion Tracking Creates Real Feedback", description: "By tracking which activities users actually did vs skipped, the system learns what 'actually matches preferences' means for each traveler type, not just what looks good on paper." },
    { title: "Real-Time Data Integration", description: "A human travel agent can't check crowd levels and weather forecasts for 50+ venues simultaneously and rebuild a 7-day itinerary in real time. The AI does this trivially." },
    { title: "Pace Personalization", description: "The single biggest failure mode of generic itineraries is wrong pace. A traveler who wants to spend an entire day in one neighborhood vs one who wants to cover 10 sites in 12 hours need fundamentally different plans." },
    { title: "Local Intelligence at Scale", description: "The crowdsourced local knowledge layer gives users insider tips matched to their preference profile—replicating the 'friend who lives there' experience at scale without requiring a network of local contacts." },
  ],
  limitations: [
    { title: "Dependent on Destination Data Completeness", description: "Coverage quality varies by destination. Major European and US cities have excellent data coverage; emerging destinations in less-documented regions have thinner knowledge graphs." },
    { title: "Cannot Replicate Human Spontaneity", description: "The AI plans efficiently but doesn't know when to say 'just wander—some cities are better without a plan.' Highly spontaneous travelers may find even well-personalized itineraries feel too structured." },
    { title: "Logistics Complexity for Multi-City Trips", description: "Trips requiring complex transportation logistics (trains, ferries, flights between cities) require more manual planning than single-city itineraries." },
    { title: "Last-Minute Changes Have Data Lag", description: "A new restaurant that opened last week or a venue that closed for private events today may not be reflected in the knowledge graph immediately." },
  ],
  whenToUseGoodFit: [
    "Travelers who want personalized itineraries but lack time for extensive research",
    "Travel platforms seeking to differentiate on itinerary quality and personalization",
    "Tour operators building scalable custom trip planning for diverse client types",
    "Corporate travel programs managing complex multi-destination business trips",
  ],
  whenToUseNotGoodFit: [
    "Highly spontaneous travelers who prefer to improvise without a plan",
    "Trips to very off-grid destinations with minimal digital infrastructure",
    "Travelers visiting destinations they already know extremely well",
    "Ultra-niche itinerary types (research expeditions, extreme sports) with specialized requirements",
  ],
  connections: [
    { name: "Agentic AI Systems", slug: "agentic-ai-systems", relevance: "Multi-step itinerary planning and real-time adaptation", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Preference elicitation and in-trip conversational adjustments", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Crowd prediction and seasonal demand forecasting", type: "service" },
    { name: "Hospitality AI Solutions", slug: "hospitality-ai-solutions", relevance: "Travel and tourism industry AI deployment patterns", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Preference-driven travel planning dialogue", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Multi-constraint itinerary optimization and route planning", type: "intelligence" },
  ],
  keyTakeaways: [
    "Completion tracking (did users actually follow the plan?) is the most honest performance metric",
    "Pace personalization matters more than interest matching for traveler satisfaction",
    "Real-time destination data integration enables dynamic adaptation that static tools can't match",
    "92% accuracy means measuring post-trip against what travelers said they wanted before",
    "+214% engagement demonstrates personalization drives behavior change, not just satisfaction",
  ],
  faqs: [
    { question: "How many destinations does Geovea cover?", answer: "Geovea has curated knowledge graphs for 500+ cities across 50+ countries, with particular depth in Western Europe, North America, Southeast Asia, and Japan. Coverage is continuously expanded based on user demand and platform growth. Destinations outside the current coverage area can be partially planned with reduced personalization depth." },
    { question: "How does the system handle dietary restrictions in food recommendations?", answer: "Dietary preferences (vegetarian, vegan, gluten-free, kosher, halal, allergies) are collected during onboarding and are applied as hard filters on all food venue recommendations. The system prioritizes venues with documented adherence to these requirements rather than just claiming accommodation." },
    { question: "Can travel agents use Geovea to build client itineraries?", answer: "Yes. Geovea has a professional tier for travel agents that includes client management, multi-traveler preference management, white-label itinerary export, and margin management tools. Travel agents using the platform report a 70% reduction in itinerary building time and higher client satisfaction scores." },
    { question: "How does Geovea monetize without selling the user's data?", answer: "Geovea operates on a subscription model for users and a professional tier for travel agents. Venue partnerships (featured placement for verified businesses meeting quality criteria) provide additional revenue. User travel data is used only to improve personalization for that individual user—it is not sold to third parties or used for advertising targeting." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function GeoveaCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
