'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "polyai",
  company: "PolyAI",
  industry: "Enterprise Software",
  subIndustry: "AI Voice Call Center Automation",
  accentColor: "violet",
  gradientClasses: "bg-gradient-to-br from-background via-violet-500/5 to-cyan-500/10",
  heroHeadline: "PolyAI: Voice AI That Resolves Calls, Not Just Routes Them",
  heroSubheadline: "Enterprise voice AI handling millions of calls with 89% resolution rate across 8+ languages—cutting cost-per-call by 74% while raising CSAT scores 22%.",
  heroStats: [
    { value: "89%", label: "Resolution Rate", color: "text-violet-400" },
    { value: "-74%", label: "Cost Per Call", color: "text-cyan-400" },
    { value: "+22%", label: "CSAT Improvement", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does PolyAI use AI to automate enterprise call centers?",
  directAnswer: "PolyAI deploys a production-grade voice AI platform with natural language understanding capable of handling complex, multi-turn conversations across 8+ languages and regional accent variations. The system integrates directly with CRM, booking, and ticketing systems to resolve inquiries end-to-end—accessing live customer data to provide personalized responses—and escalates to human agents with full conversation context only when inquiries genuinely require human judgment. 87% of inbound calls now resolve without any human intervention.",
  clientDescription: "PolyAI builds enterprise-grade conversational AI for customer service. Their clients include major hospitality, retail, and financial services companies operating contact centers handling millions of inbound calls annually. PolyAI's platform is purpose-built for enterprise deployment with the reliability, security, and integration depth that large-scale customer operations demand.",
  clientFounded: "2017",
  clientSize: "300+ employees, serving Fortune 500 clients",
  clientLocation: "London, UK & New York, USA",
  problemTitle: "Traditional Call Centers Couldn't Scale to Demand",
  problemDescription: "Enterprise contact centers faced a structural crisis: customers waited in endless queues, human agents cost $12+ per call on routine inquiries, and IVR systems frustrated callers with press-1-for-this menus that resolved almost nothing. Agent burnout from repetitive calls was driving 40%+ annual turnover.",
  painPoints: [
    { title: "Avg Handle Time", stat: "8.2 min", description: "Average time per call before AI, dominated by routine inquiries that required no complex judgment.", color: "red" },
    { title: "Cost Per Call", stat: "$12.40", description: "Human-handled call cost including agent wages, overhead, and quality assurance overhead.", color: "amber" },
    { title: "Resolution Rate", stat: "62%", description: "Pre-AI first-call resolution rate—38% of calls required callbacks or escalations.", color: "orange" },
  ],
  solutionTitle: "Natural Language Voice AI With Full System Integration",
  solutionDescription: "AGIX Technologies built a production-grade voice AI platform with conversational NLU that handles complex multi-turn dialogues, integrates with live backend systems, and escalates intelligently—routing calls to human agents with complete conversation context when human judgment is genuinely needed.",
  solutionComponents: [
    { title: "Conversational NLU Engine", description: "Natural language understanding that processes natural speech—not press-1 menus—detecting intent, entities, and sentiment across complex multi-turn conversations." },
    { title: "Multi-Language Support", description: "Supports 8+ languages with regional accent variations (US/UK/AU English, Latin American vs. Castilian Spanish, etc.) with 94-100% coverage per language." },
    { title: "Live CRM Integration", description: "Real-time API calls to CRM, booking, and ticketing systems during the call—enabling personalized responses using actual customer data without agent intervention." },
    { title: "Intelligent Escalation", description: "When calls exceed the AI's resolution capability, it escalates to human agents with complete conversation transcript, detected intent, and attempted resolution summary." },
    { title: "Voice Synthesis", description: "Sub-200ms response latency with natural prosody and pause patterns—callers report not realizing they were speaking with AI until informed." },
    { title: "Analytics & Quality Monitoring", description: "Post-call analytics tracking resolution rate, escalation reasons, CSAT correlation, and agent override patterns to continuously improve the model." },
  ],
  architectureTitle: "PolyAI Voice AI Architecture",
  architectureLayers: [
    { name: "Voice Interface", components: ["Telephony Integration (SIP/PSTN)", "Speech-to-Text (ASR)", "Text-to-Speech (TTS)", "Language Detection", "Accent Normalization"], color: "sky" },
    { name: "NLU & Dialog", components: ["Intent Classification", "Entity Extraction", "Sentiment Analysis", "Conversation State Manager", "Multi-Turn Dialog Engine"], color: "violet" },
    { name: "Integration Layer", components: ["CRM API Connector", "Booking System APIs", "Order Tracking Integration", "Knowledge Base Retrieval", "Authentication Module"], color: "blue" },
    { name: "Decision & Resolution", components: ["Resolution Logic Engine", "Confidence Thresholding", "Escalation Trigger", "Human Handoff Protocol", "Context Package Builder"], color: "cyan" },
    { name: "Analytics & Learning", components: ["Call Recording & Transcription", "Resolution Rate Tracking", "CSAT Correlation Engine", "Model Retraining Pipeline", "Performance Dashboards"], color: "green" },
  ],
  resultsTitle: "Call Center Performance Transformed Across All Metrics",
  resultsMetrics: [
    { value: "89%", label: "AI Resolution Rate", description: "Calls fully resolved by voice AI with no human agent involvement", color: "violet" },
    { value: "-74%", label: "Cost Per Call", description: "$3.20 vs $12.40 before AI deployment—significant margin expansion", color: "cyan" },
    { value: "+22%", label: "CSAT Improvement", description: "Near-instant response (under 30 seconds) vs. 8-minute hold times drives satisfaction gains", color: "green" },
    { value: "<30s", label: "Wait Time", description: "Average wait time reduced from 8 minutes to under 30 seconds for AI-handled calls", color: "blue" },
  ],
  resultsQuote: {
    text: "Customers tell us they didn't realize they were talking to AI until we mentioned it. The latency is so low and the responses so natural that it feels like a real conversation. That's the bar for enterprise voice AI.",
    author: "Head of Voice Platform Operations",
    role: "PolyAI",
  },
  howItWorksTitle: "How PolyAI Handles a Call End-to-End",
  steps: [
    { title: "Call Receipt & Language Detection", description: "Identify caller, detect language and accent variant", detail: "The call arrives via PSTN or SIP. Within 500ms the system authenticates the caller using ANI/DNIS, pulls their CRM record, and detects the language and regional accent from the greeting utterance. The appropriate language model is selected before the first response." },
    { title: "Intent Classification", description: "Understand what the caller needs in natural speech", detail: "The caller's first utterance is processed by the NLU engine, which classifies intent (booking inquiry, account question, order status, complaint) and extracts entities (dates, account numbers, product names) from natural speech without requiring callers to use specific keywords." },
    { title: "Context Gathering", description: "Multi-turn dialogue to collect missing information", detail: "For intents requiring additional information (e.g., a booking modification requires the original booking reference and new date), the system conducts targeted follow-up questions using conversational phrasing—not form-filling prompts." },
    { title: "Live System Lookup", description: "Query backend systems in real time during the call", detail: "The integration layer makes real-time API calls to the relevant backend system while the caller is on the line. For booking inquiries, this means pulling the actual booking record. For order status, querying the fulfillment system. Responses are personalized with actual data." },
    { title: "Resolution or Escalation", description: "Resolve the inquiry or hand off intelligently", detail: "If the system can resolve the inquiry (confirming a booking, providing a tracking number, processing a standard refund), it does so and confirms the resolution. If the inquiry requires human judgment, it escalates with a complete context package—caller identity, intent, conversation transcript, and attempted resolution." },
    { title: "Post-Call Analytics", description: "Learn from every call to improve future performance", detail: "Every call generates a resolution record: was it resolved, how many turns did it take, was it escalated and why, and what CSAT score was provided. This data feeds the model retraining pipeline, continuously improving resolution rates and reducing unnecessary escalations." },
  ],
  whyItWorkedTitle: "Why PolyAI's Voice AI Deployment Succeeded",
  whyFactors: [
    { title: "Resolution Over Routing", description: "PolyAI's architecture was designed to resolve inquiries end-to-end, not route them to human queues—requiring deep system integration that most voice AI platforms skip." },
    { title: "Sub-200ms Latency", description: "Natural conversation requires response latency under 300ms. Achieving this at scale required careful infrastructure architecture including regional model hosting and streaming ASR." },
    { title: "Accent & Dialect Training", description: "Each language was trained on regional accent variations rather than a single standard dialect, dramatically improving recognition accuracy for non-standard accent callers." },
    { title: "Intelligent Confidence Thresholding", description: "Rather than attempting to resolve every call regardless of confidence, the system escalates when confidence falls below threshold—human agents only see calls where AI genuinely struggled." },
    { title: "Transparent Human Handoff", description: "When escalating, the complete conversation context is surfaced to the human agent instantly, eliminating repeat-yourself frustration that drives CSAT down on escalated calls." },
    { title: "Phased Capability Rollout", description: "New call intents were added incrementally after validation rather than attempting to handle all inquiry types on day one, allowing quality control and model refinement per intent category." },
  ],
  limitations: [
    { title: "High-Emotion Calls Require Human Empathy", description: "Complaints involving significant customer distress, bereavement-related cancellations, or safety concerns are escalated to human agents regardless of technical resolvability." },
    { title: "Highly Complex Multi-System Inquiries", description: "Calls requiring coordination across 3+ backend systems simultaneously increase resolution time and escalation risk, requiring careful workflow design." },
    { title: "Regulatory Disclosure Requirements", description: "Some jurisdictions require disclosure that callers are speaking with AI. Disclosure handling must be built into call flow design for compliant deployments." },
    { title: "Cold Start for New Intent Types", description: "Newly added intent categories require 500-1,000 training examples before resolution rates reach target levels, creating a ramp period for expanded capability." },
  ],
  whenToUseGoodFit: [
    "Operate contact centers handling 50,000+ inbound calls per month",
    "Have 40%+ of call volume from routine, repeatable inquiry types",
    "Maintain APIs or integration points into backend CRM and fulfillment systems",
    "Face agent retention challenges from repetitive call volume",
    "Operate across multiple languages or international markets",
  ],
  whenToUseNotGoodFit: [
    "Call volume is primarily complex, high-judgment cases with no routine patterns",
    "No API access to backend systems—voice AI without live data integration is limited",
    "Operate in a single language with no scale challenges",
    "Call center handles exclusively outbound sales rather than inbound service",
  ],
  connections: [
    { name: "AI Voice Agents", slug: "ai-voice-agents", relevance: "Core voice AI infrastructure for enterprise call center automation", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Multi-channel conversational AI extending voice to digital channels", type: "service" },
    { name: "Agentic AI Systems", slug: "agentic-ai-systems", relevance: "Autonomous resolution agents that take action within backend systems", type: "service" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Natural language understanding and multi-turn dialogue intelligence", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Contact center operations optimization and workforce management", type: "intelligence" },
  ],
  keyTakeaways: [
    "89% of calls resolve without human agent involvement at $3.20 vs $12.40 per call",
    "Sub-30-second wait time vs. 8-minute hold times drives 22% CSAT improvement",
    "Live CRM integration during calls enables personalized resolution without human lookup",
    "Intelligent escalation routes only genuinely complex calls to human agents",
    "8+ language support with regional accent training enables multinational deployment",
  ],
  faqs: [
    { question: "How does the AI handle callers who insist on speaking with a human?", answer: "The system immediately escalates to a human agent when a caller requests one—there is no attempt to persuade callers to continue with AI. Escalation confidence and timing are tuned to ensure callers who want human interaction receive it within seconds." },
    { question: "What happens when the AI doesn't understand what the caller said?", answer: "The system has a configurable maximum number of clarification attempts. If understanding cannot be achieved within that threshold, the call escalates to a human agent with the partial conversation transcript. Repeated misunderstanding patterns trigger model review for that intent type." },
    { question: "How is the voice AI integrated with existing telephony infrastructure?", answer: "PolyAI integrates via SIP trunk or telephony API with all major platforms including Genesys, Avaya, and Twilio. The integration layer is configured during a 4-6 week technical onboarding phase before go-live." },
    { question: "Can the system handle outbound calls in addition to inbound?", answer: "Yes. The platform supports outbound use cases including appointment reminders, payment notifications, and proactive service updates. Outbound flows are configured separately from inbound resolution flows and require compliance review for TCPA/GDPR adherence." },
    { question: "How long does deployment typically take?", answer: "A standard deployment covers 3-5 high-volume intent types and takes 8-12 weeks: 4 weeks for CRM integration and intent training, 2 weeks for quality assurance and accent testing, and 2-4 weeks for phased go-live starting with pilot call volume." },
  ],
  prevCase: { name: "Naratix", url: "/case-studies/naratix/" },
  nextCase: { name: "Brainfish", url: "/case-studies/brainfish/" },
};

export default function PolyAICaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
