'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "properti-ai",
  company: "Properti AI",
  industry: "Real Estate",
  subIndustry: "AI Property Discovery Platform",
  accentColor: "teal",
  gradientClasses: "bg-gradient-to-br from-background via-teal-500/5 to-cyan-500/10",
  heroHeadline: "Properti AI: Conversational Property Discovery That Converts",
  heroSubheadline: "AI chatbot that understands lifestyle needs, not just square footage—delivering +156% lead conversion and 89% match accuracy while cutting agent qualification time 68%.",
  heroStats: [
    { value: "+156%", label: "Lead Conversion", color: "text-teal-400" },
    { value: "89%", label: "Match Accuracy", color: "text-cyan-400" },
    { value: "-68%", label: "Agent Time", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does Properti AI use AI to improve property discovery?",
  directAnswer: "Properti AI deployed a conversational property discovery AI that engages buyers in structured natural language dialogue to surface both explicit requirements and implicit preferences—commute priorities, neighborhood character, renovation appetite, and lifestyle fit. The AI cross-references the resulting intent profile against live listing data, school district ratings, walkability scores, and historical price trend data to generate ranked, personalized property recommendations. Buyers now find properties matching their actual preferences after viewing an average of 4.2 listings compared to 23.7 with traditional search.",
  clientDescription: "Properti AI is a technology-forward real estate platform serving buyers and sellers across multiple markets. The platform generates significant lead volume but faced poor lead-to-qualified-viewing conversion rates driven by misalignment between stated buyer preferences and actual property needs—a gap that only became apparent after multiple wasted property tours.",
  clientFounded: "2019",
  clientSize: "150+ employees, operating in 12 markets",
  clientLocation: "Singapore & Southeast Asia",
  problemTitle: "Property Searches That Wasted Everyone's Time",
  problemDescription: "Buyers waded through hundreds of mismatched listings while agents spent 60-70% of qualification time on prospects whose stated preferences didn't reflect what they actually wanted. Traditional search filters couldn't capture the nuanced factors—school districts, commute times, neighborhood character—that actually drove purchase decisions.",
  painPoints: [
    { title: "Mismatched Listings", stat: "73%", description: "Percentage of properties shown to buyers that didn't match their actual preferences—discovered only after tours.", color: "red" },
    { title: "Agent Time Per Buyer", stat: "12+ hrs", description: "Hours agents spent qualifying each buyer through repetitive back-and-forth before reaching a good property match.", color: "amber" },
    { title: "Lead Conversion Rate", stat: "34%", description: "Pre-AI conversion from initial inquiry to qualified viewing—leaving 66% of leads unrealized.", color: "orange" },
  ],
  solutionTitle: "Conversational Intent Profiling for Precision Property Matching",
  solutionDescription: "AGIX Technologies built a conversational AI that discovers the buyer's true property requirements through structured dialogue—capturing lifestyle needs that filter-based search cannot express—then matches those requirements against live listings enriched with neighborhood, school, walkability, and appreciation data.",
  solutionComponents: [
    { title: "Conversational Intent Engine", description: "Multi-turn dialogue system that surfaces both explicit requirements (bedrooms, price) and implicit preferences (quiet street vs. vibrant area, renovation appetite, school priority) through natural conversation." },
    { title: "Neighborhood Intelligence Layer", description: "Live enrichment of listings with school district ratings, walkability scores, commute time calculations, crime data, and 5-year price appreciation trends per neighborhood." },
    { title: "Buyer Profile Modeling", description: "Structured buyer intent profiles combining stated preferences, inferred priorities, budget trajectory, and timeline signals—persisted across sessions as preferences refine." },
    { title: "Ranked Match Engine", description: "Semantic matching algorithm that scores each listing against the buyer's complete intent profile, generating match percentage scores and ranked recommendation lists." },
    { title: "Agent Handoff Intelligence", description: "When buyers reach viewing intent, agents receive the complete buyer profile, top-matched properties, and AI-detected motivation signals to accelerate the relationship from first meeting." },
    { title: "Feedback Loop Refinement", description: "Every property tour outcome (interested/not interested and reasons) refines the buyer's preference model, improving subsequent recommendations throughout the purchase journey." },
  ],
  architectureTitle: "Properti AI Property Discovery Architecture",
  architectureLayers: [
    { name: "Buyer Engagement", components: ["Conversational Chat Interface", "Intent Dialogue Engine", "Preference Elicitation Flows", "Session Persistence", "Mobile & Web SDKs"], color: "sky" },
    { name: "Intent Modeling", components: ["Explicit Requirement Extraction", "Implicit Preference Inference", "Lifestyle Scoring Model", "Buyer Segment Classification", "Priority Weighting Engine"], color: "teal" },
    { name: "Listing Intelligence", components: ["Live MLS/Listing Feed", "School District API", "Walk Score Integration", "Commute Time Calculator", "Price Trend Database"], color: "cyan" },
    { name: "Matching Engine", components: ["Semantic Profile Matching", "Match Score Generation", "Ranked Recommendation List", "Diversity & Exploration Balancing", "New Listing Alerts"], color: "blue" },
    { name: "Agent Enablement", components: ["Buyer Profile Dashboard", "Match Explanation Export", "Viewing Readiness Score", "CRM Integration", "Conversion Tracking"], color: "green" },
  ],
  resultsTitle: "Lead Quality and Agent Efficiency Both Transformed",
  resultsMetrics: [
    { value: "+156%", label: "Lead-to-Viewing Conversion", description: "Buyers pre-qualified by AI arrive at viewings with genuine property fit", color: "teal" },
    { value: "4.2", label: "Avg Properties to Purchase", description: "Down from 23.7 viewings under the old process—dramatically shorter buyer journeys", color: "cyan" },
    { value: "-68%", label: "Agent Qualification Time", description: "Agents focus on high-intent buyers where relationship skills drive outcomes", color: "green" },
    { value: "89%", label: "Match Accuracy", description: "Percentage of AI-recommended properties that buyers rate as genuinely fitting their needs", color: "blue" },
  ],
  resultsQuote: {
    text: "Buyers used to waste weeks looking at properties that didn't fit. Our AI asks the right questions, understands lifestyle needs—not just square footage—and surfaces matches that feel like magic. Agents now spend time closing deals, not qualifying tire-kickers.",
    author: "VP of Growth",
    role: "Properti AI",
  },
  howItWorksTitle: "How Properti AI Matches Buyers to Properties",
  steps: [
    { title: "Conversational Onboarding", description: "Engage buyers in structured dialogue about needs and lifestyle", detail: "Rather than presenting filter dropdowns, the AI opens a conversation: 'Tell me what's important to you in your next home.' It guides the buyer through a structured but natural dialogue that surfaces both explicit requirements and lifestyle priorities—school proximity, work-from-home needs, entertaining space—in 5-7 minutes." },
    { title: "Intent Profile Construction", description: "Build a structured buyer profile from dialogue signals", detail: "Each conversational exchange is parsed to extract and weight requirements. Repeated mentions of school ratings across multiple questions signal higher priority than a single mention of parking. The system constructs a weighted intent vector that captures the buyer's true preference hierarchy." },
    { title: "Listing Enrichment", description: "Enrich every listing with contextual neighborhood data", detail: "Each listing in the market is enriched in real time with school district ratings, walk score, commute time to the buyer's stated workplace, safety scores, and 5-year price appreciation for that specific neighborhood—converting raw listing data into lifestyle-relevant profiles." },
    { title: "Semantic Matching", description: "Score every listing against the buyer's intent profile", detail: "The matching engine calculates a fit score for every listing in the market against the buyer's intent vector, weighting factors by the buyer's stated and inferred priorities. Listings are ranked by match score and presented with match explanations." },
    { title: "Recommendation Delivery", description: "Present ranked recommendations with match explanations", detail: "The top 5-10 properties are presented with percentage match scores and specific explanations—'93% match: 4 bedrooms, excellent school district (9.1/10), 18-min commute, quiet cul-de-sac street.' Buyers understand why each property was recommended." },
    { title: "Preference Refinement", description: "Learn from viewing feedback to improve future matches", detail: "After each viewing, the buyer rates the property and optionally explains why it did or didn't fit. These feedback signals update the intent model—if a buyer consistently rejects open-plan layouts despite not mentioning them initially, the system infers that preference and filters accordingly." },
  ],
  whyItWorkedTitle: "Why Properti AI's Matching Platform Succeeded",
  whyFactors: [
    { title: "Lifestyle Needs Over Filter Logic", description: "Capturing 'good for remote work' and 'family-friendly neighborhood' through dialogue is impossible with dropdown filters—conversational AI unlocked preferences that traditional search cannot express." },
    { title: "Match Explanations Build Trust", description: "Showing buyers exactly why each property was recommended—with specific data on schools, commute, and fit factors—increased engagement with recommendations vs. algorithmic black-box lists." },
    { title: "Agent Collaboration Not Replacement", description: "The AI positions itself as a pre-qualification layer that improves agent effectiveness, not a replacement. Agents receive better-qualified buyers—a value proposition that drove adoption." },
    { title: "Enriched Listing Data as Competitive Moat", description: "Integrating school district, walkability, and commute data per listing created a richer matching surface than raw listing attributes alone—improving recommendation quality across all buyer types." },
    { title: "Session Persistence Across Journey", description: "Persisting buyer profiles across multiple sessions allowed the AI to refine recommendations over days and weeks as buyer preferences evolved—not just one-time matching." },
    { title: "Feedback Loop as Training Data", description: "Viewing outcome feedback creates a continuously improving training set specific to each market's buyer preferences, giving the platform a data moat that strengthens over time." },
  ],
  limitations: [
    { title: "Limited in Off-Market Inventory", description: "The matching engine can only recommend listed properties. Off-market opportunities, new construction pre-sales, and auction properties require separate integration." },
    { title: "Buyer Preference Volatility", description: "Buyer preferences sometimes shift dramatically after seeing a property (realizing they actually want more space than they said). Rapid preference changes require multiple feedback cycles to stabilize the model." },
    { title: "Market Data Currency", description: "School ratings, crime data, and walkability scores can lag actual neighborhood conditions by 6-12 months, potentially creating mismatches for rapidly changing areas." },
    { title: "Investment Property Matching Is Different", description: "Investor buyers evaluating rental yield, cap rate, and appreciation potential require a separate model focused on financial metrics rather than lifestyle fit." },
  ],
  whenToUseGoodFit: [
    "Operate a property marketplace with 1,000+ active listings generating significant lead volume",
    "Face lead quality issues where agents spend excessive time on unqualified buyers",
    "Sell residential properties where lifestyle fit is a significant purchase driver",
    "Have API access to listing data and can integrate neighborhood data sources",
    "Want to differentiate on buyer experience rather than competing purely on listing volume",
  ],
  whenToUseNotGoodFit: [
    "Small single-agent practices where personal consultation handles pre-qualification",
    "Pure commercial real estate where financial metrics dominate lifestyle considerations",
    "Markets with very limited inventory (fewer than 100 active listings)",
    "Auction or distressed property platforms where speed and price dominate all other factors",
  ],
  connections: [
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Multi-turn dialogue system for buyer intent discovery", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Property match scoring and buyer preference modeling", type: "service" },
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Neighborhood intelligence and listing data enrichment", type: "service" },
    { name: "Real Estate AI Solutions", slug: "real-estate-ai-solutions", relevance: "AI deployment patterns across residential and commercial real estate", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Natural language buyer profiling and preference elicitation", type: "intelligence" },
  ],
  keyTakeaways: [
    "Lead-to-qualified-viewing conversion increased +156% through AI pre-qualification",
    "Average properties viewed before purchase: 4.2 vs 23.7 with traditional search",
    "Conversational AI surfaces lifestyle preferences that filter-based search cannot capture",
    "Agent qualification time reduced 68%—agents focus on high-intent buyers",
    "89% match accuracy achieved by enriching listings with school, commute, and walkability data",
  ],
  faqs: [
    { question: "How does the AI discover implicit preferences that buyers don't explicitly state?", answer: "The dialogue system uses structured prompting that surfaces lifestyle context: asking about a typical weekend, work location, family stage, and how the buyer currently spends time reveals preferences around neighborhood character, commute, and space needs that buyers rarely volunteer unprompted." },
    { question: "What data sources power the neighborhood enrichment layer?", answer: "School district ratings from GreatSchools, walkability scores from Walk Score, commute times from Google Maps API, crime data from local police APIs, and price appreciation from MLS historical data are aggregated per listing to create the neighborhood intelligence layer." },
    { question: "How does the system handle buyers who don't know what they want?", answer: "The dialogue is designed for exactly this case. Rather than asking buyers to specify requirements, it presents concrete trade-offs ('Would you prefer a smaller home in a top school district or more space in a good-but-not-top district?') that reveal priorities through choices rather than free-form specification." },
    { question: "Can agents adjust or override AI recommendations?", answer: "Yes. Agents can view and modify the buyer's intent profile, add or remove specific requirements, and manually override match rankings based on information gathered in consultation. Agent overrides are tracked as feedback that improves the model." },
    { question: "How does the system integrate with existing CRM and listing platforms?", answer: "Properti AI provides REST APIs and webhooks for CRM integration (Salesforce, HubSpot) and connects to MLS feeds via standard RETS or RESO Web API protocols. Typical integration takes 3-4 weeks including testing and data validation." },
  ],
  prevCase: { name: "Brainfish", url: "/case-studies/brainfish/" },
  nextCase: { name: "Dartmouth College", url: "/case-studies/dartmouth-college/" },
};

export default function PropertiAICaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
