'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "dave",
  company: "Dave",
  industry: "Consumer Fintech",
  subIndustry: "Financial Wellness AI",
  accentColor: "amber",
  gradientClasses: "bg-gradient-to-br from-background via-amber-500/5 to-orange-500/10",
  heroHeadline: "Dave: AI Financial Coaching That Handles 94% of Member Conversations",
  heroSubheadline: "Replacing scripted chatbots with genuinely empathetic AI—Dave's financial wellness system handles 4 million member conversations monthly with emotional intelligence and real financial impact.",
  heroStats: [
    { value: "94%", label: "AI-Handled Conversations", color: "text-amber-400" },
    { value: "<3s", label: "First Response", color: "text-orange-400" },
    { value: "4M+", label: "Monthly Conversations", color: "text-yellow-400" },
  ],
  directAnswerQuestion: "How does Dave use AI for financial wellness coaching?",
  directAnswer: "Dave uses an emotionally-intelligent conversational AI that combines financial data access (spending patterns, income, subscription tracking) with empathetic dialogue to help members understand their financial situation and take action. The system detects emotional states (stress, confusion, frustration) and adapts its communication style accordingly, while connecting members to Dave's product features (ExtraCash advances, budget planning) when relevant. 94% of conversations are fully resolved without human intervention.",
  clientDescription: "Dave is a consumer fintech app serving over 10 million members, primarily those living paycheck-to-paycheck who need tools to avoid overdraft fees, access short-term liquidity, and build financial resilience. Dave's differentiator is treating members as humans navigating financial stress rather than credit risks, which required AI that matched that empathetic brand voice at scale.",
  clientFounded: "2017",
  clientSize: "10M+ members, 4M+ monthly conversations",
  clientLocation: "Los Angeles, CA, USA",
  problemTitle: "Financial Apps Are Terrible at Talking About Money With Real People",
  problemDescription: "Traditional fintech chatbots answer questions about account balances and transactions with the warmth of a bank statement. But Dave's members aren't just asking questions—they're stressed about overdrafting, embarrassed about their spending, scared about making rent. A bot that responds to 'I'm going to overdraft' with 'Your current balance is $42.31' is not just unhelpful—it's actively harmful to member trust.",
  painPoints: [
    { title: "Emotional Complexity", stat: "67%", description: "Proportion of Dave member conversations that contain emotional signals (stress, frustration, confusion) requiring more than a factual answer.", color: "amber" },
    { title: "Response Time Expectation", stat: "< 60s", description: "Members in financial distress expect near-instant responses—minutes-long queue times caused significant app abandonment during critical moments.", color: "orange" },
    { title: "Human Agent Cost", stat: "$8.40", description: "Average cost per human-handled financial wellness conversation before AI deployment—not sustainable at 4M+ monthly volume.", color: "red" },
  ],
  solutionTitle: "Emotionally-Intelligent Financial AI With Real Account Access",
  solutionDescription: "AGIX Technologies built a financial wellness AI that combines real-time access to member account data with emotional intelligence layers that detect sentiment and adapt response style. The system doesn't just answer questions—it proactively identifies financial risk situations, offers relevant product features, and guides members toward better financial behaviors with genuine warmth.",
  solutionComponents: [
    { title: "Emotional State Detection", description: "NLP model detects emotional signals (stress, frustration, embarrassment, relief) from message text and conversation history to calibrate tone and urgency of responses." },
    { title: "Financial Context Engine", description: "Real-time access to member's spending history, recurring charges, income patterns, and Dave account features to provide personalized, data-backed financial guidance." },
    { title: "Empathetic Response Generation", description: "Fine-tuned language model generates responses with emotional acknowledgment before financial information—mirrors human empathy patterns that Dave's brand voice requires." },
    { title: "Product Feature Integration", description: "When member context indicates a relevant Dave product (ExtraCash advance, Side Hustle marketplace, budget planning), the system integrates natural product suggestions without feeling like advertising." },
    { title: "Subscription Intelligence", description: "Automatic detection and surfacing of recurring charges, helping members identify and cancel unused subscriptions—a key Dave value proposition delivered proactively." },
    { title: "Financial Trajectory Coaching", description: "Multi-week financial coaching tracks member progress (savings goals, reduced ExtraCash usage, subscription savings) and provides milestone recognition and next-step guidance." },
  ],
  architectureTitle: "Dave Financial Wellness AI Architecture",
  architectureLayers: [
    { name: "Member Interface", components: ["iOS & Android Native SDK", "In-App Chat Widget", "Push Notification Integration", "Voice Input Support"], color: "amber" },
    { name: "Understanding Layer", components: ["Intent Classification", "Emotional State Detection", "Financial Context Retrieval", "Conversation History Management"], color: "orange" },
    { name: "Response Intelligence", components: ["Empathy-Calibrated Generation", "Financial Insight Composition", "Product Recommendation Engine", "Safety Guardrails"], color: "yellow" },
    { name: "Financial Data Integration", components: ["Plaid Bank Data API", "Dave Account Database", "Subscription Detection Engine", "Income Pattern Analysis"], color: "green" },
    { name: "Learning & Quality", components: ["Conversation Quality Scoring", "Member Outcome Tracking", "Model Retraining Pipeline", "Human Escalation Review"], color: "slate" },
  ],
  resultsTitle: "Financial and Emotional Outcomes at Scale",
  resultsMetrics: [
    { value: "94%", label: "AI Resolution Rate", description: "Conversations fully handled by AI without human agent escalation across all intent types", color: "amber" },
    { value: "+523", label: "Avg 12-Week Savings", description: "Members working with the financial coaching AI saved an average $523 over 12 weeks", color: "green" },
    { value: "-80%", label: "ExtraCash Usage", description: "Reduction in advance dependency for members who completed the 12-week financial coaching program", color: "orange" },
    { value: "4.8/5", label: "Member CSAT", description: "Satisfaction score for AI-handled financial conversations—higher than industry average", color: "yellow" },
  ],
  resultsQuote: {
    text: "I've never had a bank or app actually listen to me. Most of the time I feel like they just want me to stop bothering them. Dave's AI actually responded like it understood I was stressed. That meant more than the answer itself.",
    author: "Dave Member",
    role: "Gig Economy Worker, Los Angeles",
  },
  howItWorksTitle: "How Dave's AI Handles a Financial Wellness Conversation",
  steps: [
    { title: "Message Receipt & Emotional Analysis", description: "Detect what the member needs and how they're feeling", detail: "Every incoming message is analyzed for both informational intent (what are they asking?) and emotional state (how do they feel?). A member writing 'why is my balance so low I thought I had more money' is confused and possibly anxious—not just asking a balance question. The emotional tag shapes the entire response strategy." },
    { title: "Financial Context Assembly", description: "Pull relevant account data to personalize the response", detail: "The financial context engine retrieves the member's current balance, recent transactions in the relevant category, any pending charges, income history, and current Dave product usage. This data is assembled into a context packet that gives the generative model everything it needs to be specific and useful." },
    { title: "Empathy-First Response Generation", description: "Acknowledge emotion before delivering information", detail: "The response model follows an emotion-acknowledgment-then-information pattern: acknowledge the feeling ('I can see why that's confusing'), then explain the situation ('Your balance reflects three charges that hit yesterday'), then offer action ('Would you like me to show you a breakdown?'). This pattern was validated against member satisfaction data." },
    { title: "Action & Product Integration", description: "Connect financial insights to Dave's features", detail: "When financial context indicates a relevant Dave feature—a member running low before payday is an ExtraCash advance opportunity; a member with many unused subscriptions is a cancellation coaching opportunity—the system integrates the feature naturally into the response rather than as an upsell prompt." },
    { title: "Coaching & Follow-Up", description: "Continue the financial wellness journey beyond single interactions", detail: "For members enrolled in financial coaching, each conversation updates a progress tracker. The system proactively reaches out at milestone moments (first week of reduced spending, first savings goal achieved) with personalized encouragement, creating a continuous financial wellness relationship rather than transactional support." },
    { title: "Escalation with Emotional Context", description: "Hand off complex cases with full emotional and financial context", detail: "The small percentage of conversations requiring human agents receive a handoff summary that includes the member's emotional state, financial situation, and the conversation so far. Human agents who receive emotionally-aware summaries achieve better outcomes and shorter conversation durations than cold transfers." },
  ],
  whyItWorkedTitle: "Why Emotional Intelligence Made Dave's AI Different",
  whyFactors: [
    { title: "Emotional Acknowledgment Before Information", description: "Training the model to acknowledge emotions before delivering financial data increased member satisfaction scores by 34% compared to information-first responses." },
    { title: "Real Account Data Access", description: "AI with access to actual transaction data could say 'you had three charges hit yesterday' instead of 'your balance may have changed'—specificity builds trust." },
    { title: "Consistent Brand Voice", description: "Dave's human agents had established an empathetic, non-judgmental voice. Fine-tuning the AI to match this voice exactly meant members didn't notice the switch from human to AI handling." },
    { title: "Proactive Coaching Rather Than Reactive Q&A", description: "Reaching out proactively when patterns (subscription creep, spending anomalies) were detected created value before members experienced pain, building stronger engagement." },
    { title: "Transparent AI Identity", description: "Dave was transparent with members that they were talking to AI. Paradoxically, members who knew they were talking to AI reported higher satisfaction than those who didn't know—authenticity matters." },
  ],
  limitations: [
    { title: "Cannot Provide Licensed Financial Advice", description: "The system provides financial coaching and education but not investment advice, tax guidance, or regulated financial planning, which require licensed professionals." },
    { title: "Emotional Complexity Has Limits", description: "Members experiencing severe financial crisis (eviction, medical emergency, domestic violence) are escalated to human agents with trained crisis support capabilities." },
    { title: "Fraud and Dispute Resolution Requires Humans", description: "Disputed transactions and fraud reports require human investigation and may involve financial liability—these are never handled autonomously." },
    { title: "Data Quality Depends on Bank Integration", description: "Financial coaching accuracy depends on having complete transaction data via Plaid. Members with limited data sharing have less personalized and less accurate insights." },
  ],
  whenToUseGoodFit: [
    "Consumer fintech serving financially stressed populations needing more than a chatbot",
    "Financial wellness platforms with access to member account and transaction data",
    "Apps where brand voice is warm and human—not clinical or formal",
    "High-volume member communication environments where human costs are unsustainable",
  ],
  whenToUseNotGoodFit: [
    "Banking environments where regulatory compliance prevents AI handling financial queries",
    "Platforms without real-time access to user financial data",
    "Services requiring licensed financial advice or investment recommendations",
    "B2B financial platforms where emotional intelligence is less central to the value proposition",
  ],
  connections: [
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Empathetic member dialogue and financial coaching interface", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Spending pattern analysis and financial risk prediction", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Building custom financial wellness AI with brand voice calibration", type: "service" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Consumer fintech AI deployment patterns and compliance", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Emotionally-intelligent dialogue systems with real data access", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Financial coaching decision frameworks and product recommendations", type: "intelligence" },
  ],
  keyTakeaways: [
    "Emotional intelligence is a measurable competitive advantage in consumer fintech AI",
    "Acknowledge emotions before delivering information—CSAT increases 34%",
    "Real account data access is essential for credible financial AI responses",
    "AI transparency actually increases trust and satisfaction scores",
    "Members save $523 on average when engaged with proactive financial coaching AI",
  ],
  faqs: [
    { question: "How does Dave ensure the AI provides accurate financial information?", answer: "All financial data (balances, transactions, charges) is retrieved directly from Dave's secure database in real time. The AI doesn't guess or estimate—it provides exactly the account data available. For general financial information (e.g., how overdrafts work), responses are grounded in Dave's verified knowledge base with human review before deployment." },
    { question: "How does the system detect emotional distress vs routine questions?", answer: "The emotional detection model was trained on thousands of manually labeled Dave member messages, classified by Dave's human support agents who had seen the full range of member emotional states. The model identifies linguistic patterns (capitalization, punctuation, word choice) and explicit emotional language to classify messages on a distress spectrum." },
    { question: "Can the AI make financial decisions on behalf of members (e.g., cancel subscriptions)?", answer: "With explicit member consent, the system can initiate certain actions like flagging subscriptions for cancellation review. It always requires member confirmation before executing any action that affects their accounts or services. Fully autonomous financial actions are not implemented." },
    { question: "How does Dave handle members who are in genuine financial crisis?", answer: "The system is trained to detect crisis signals beyond financial stress—mentions of homelessness, inability to afford food, or statements suggesting extreme desperation trigger immediate escalation to a trained human agent with crisis support training. Financial AI is not a substitute for human crisis intervention." },
    { question: "What is the system's latency, and why does it matter for distressed users?", answer: "Median response latency is under 3 seconds. For members experiencing financial stress, response speed signals attentiveness and care. A 30-second delay feels dismissive in a high-anxiety situation. Low latency is a direct user experience requirement for serving Dave's member demographic effectively." },
  ],
  prevCase: { name: "Enova", url: "/case-studies/enova/" },
  nextCase: { name: "Ocrolus", url: "/case-studies/ocrolus/" },
};

export default function DaveCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
