'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "kroger",
  company: "Kroger",
  industry: "Grocery Retail",
  subIndustry: "E-Commerce Fulfillment AI",
  accentColor: "blue",
  gradientClasses: "bg-gradient-to-br from-background via-blue-500/5 to-green-500/10",
  heroHeadline: "Kroger: AI Fulfillment That Picks 87% More Items Per Hour",
  heroSubheadline: "Transforming grocery e-commerce operations—AI-optimized pick paths reduce travel distance by 50%, smart substitutions improve customer satisfaction by 41%, and pickup order accuracy reaches 99.2%.",
  heroStats: [
    { value: "+87%", label: "Items Per Hour", color: "text-blue-400" },
    { value: "-50%", label: "Pick Travel Distance", color: "text-green-400" },
    { value: "99.2%", label: "Order Accuracy", color: "text-teal-400" },
  ],
  directAnswerQuestion: "How does Kroger use AI to optimize grocery e-commerce fulfillment?",
  directAnswer: "Kroger's AI fulfillment system uses a combination of route optimization, computer vision verification, and customer-preference-aware substitution to maximize picker efficiency and order accuracy. The route optimizer generates pick paths that reduce travel distance by 50% by batching orders intelligently and sequencing picks by store zone. When items are out of stock, the substitution AI selects replacements based on the individual customer's purchase history rather than generic rules—reducing substitution rejection rates by 73%.",
  clientDescription: "The Kroger Co. is America's largest supermarket chain, operating 2,700+ stores and a rapidly growing e-commerce business serving millions of grocery pickup and delivery orders per week. As e-commerce grocery orders grew from 5% to over 25% of sales in three years, fulfillment efficiency became a critical operational and margin challenge—picking grocery orders in-store is expensive, and order accuracy directly impacts customer satisfaction.",
  clientFounded: "1883",
  clientSize: "2,700+ stores, 420,000+ employees, $148B annual revenue",
  clientLocation: "Cincinnati, Ohio, USA",
  problemTitle: "Manual Grocery Fulfillment Can't Scale With E-Commerce Growth",
  problemDescription: "When order pickers fill grocery orders manually, they walk whatever path they remember, pick items in whatever order seems natural, and make substitution decisions based on generic rules or personal judgment. At low order volumes this works. At millions of orders per week, it doesn't—inefficient paths, wrong substitutions, and missed items erode both economics and customer trust.",
  painPoints: [
    { title: "Manual Pick Path Efficiency", stat: "4.2 mi/shift", description: "Average distance a picker walked per shift with unoptimized routing—redundant backtracking accounted for nearly half of total walking distance.", color: "red" },
    { title: "Substitution Rejection Rate", stat: "28%", description: "Proportion of out-of-stock substitutions rejected by customers as 'not what I wanted'—creating refunds, rescheduling, and negative reviews.", color: "amber" },
    { title: "Order Accuracy Without AI", stat: "96.8%", description: "Baseline accuracy before AI verification—the 3.2% error rate translated to hundreds of thousands of wrong-item complaints per month at scale.", color: "orange" },
  ],
  solutionTitle: "Integrated Fulfillment AI: Route Optimization, Vision Verification, Smart Substitution",
  solutionDescription: "AGIX Technologies built three integrated AI systems that work together to transform grocery fulfillment: a route optimizer that generates pick paths by batching orders across store zones, a computer vision verifier that confirms the right item was picked, and a substitution recommender that uses individual customer history to make personalized out-of-stock replacements.",
  solutionComponents: [
    { title: "Multi-Order Pick Path Optimizer", description: "Batches multiple pickup orders simultaneously and generates a single optimized pick path that covers all items across orders efficiently, minimizing backtracking between store zones." },
    { title: "Real-Time Inventory Integration", description: "Live inventory data prevents pickers from being directed to out-of-stock locations—routing directly to alternate locations or triggering substitution flow before the picker arrives at an empty shelf." },
    { title: "Computer Vision Item Verification", description: "Handheld scanner with vision model verifies that the item scanned matches the order item—catching wrong-flavor, wrong-size, and wrong-brand errors before they reach the customer." },
    { title: "Customer-Preference Substitution AI", description: "When an item is out of stock, the substitution model queries the customer's 18-month purchase history to identify the most likely acceptable alternative—not just the nearest-shelf item." },
    { title: "Order Completion Prediction", description: "Predicts likely completion time for each batch, flagging orders at risk of missing their pickup window so managers can allocate additional picker support proactively." },
    { title: "Picker Performance Analytics", description: "Real-time dashboard showing pick rate per hour, accuracy rate, and substitution acceptance rate by picker—enabling targeted coaching and performance management." },
  ],
  architectureTitle: "Kroger AI Fulfillment Architecture",
  architectureLayers: [
    { name: "Order Management", components: ["E-Commerce Order Queue", "Multi-Order Batch Formation", "Pickup Window Scheduling", "Priority Scoring Engine"], color: "blue" },
    { name: "Route Intelligence", components: ["Store Zone Graph", "Multi-Order Path Optimizer", "Real-Time Inventory Feed", "Dynamic Re-routing"], color: "green" },
    { name: "Pick Execution", components: ["Picker Handheld App", "Barcode + Vision Verification", "Out-of-Stock Detection", "Substitution Recommendation Flow"], color: "teal" },
    { name: "Substitution Intelligence", components: ["Customer Purchase History", "Product Attribute Graph", "Brand Preference Model", "Dietary Restriction Enforcement"], color: "indigo" },
    { name: "Analytics & Management", components: ["Picker Performance Dashboard", "Order Accuracy Tracking", "Substitution Acceptance Rates", "Fulfillment Cost Reporting"], color: "slate" },
  ],
  resultsTitle: "Operational and Customer Satisfaction Outcomes",
  resultsMetrics: [
    { value: "+87%", label: "Items Per Hour", description: "Pick rate improvement from 40 to 75 items/hour with optimized routing and batch picking", color: "blue" },
    { value: "-50%", label: "Pick Path Distance", description: "Average shift walking distance reduced from 4.2 miles to 2.1 miles through route optimization", color: "green" },
    { value: "99.2%", label: "Order Accuracy", description: "vs 96.8% baseline—vision verification eliminated most wrong-item errors", color: "teal" },
    { value: "-73%", label: "Sub Rejection Rate", description: "Customer substitution rejections fell from 28% to 7.6% with personalized substitution AI", color: "indigo" },
  ],
  resultsQuote: {
    text: "Our pickers used to dread substitutions because customers would reject them and we'd have to issue refunds. Now the AI knows this customer hates Red Delicious apples and always buys organic—it suggests the right substitute and customers appreciate it instead of complaining.",
    author: "Head of E-Commerce Operations",
    role: "Kroger",
  },
  howItWorksTitle: "How Kroger's AI Fulfillment System Works",
  steps: [
    { title: "Order Batching & Path Generation", description: "Group orders and generate an optimal pick sequence", detail: "When an order enters the fulfillment queue, it's batched with 3–5 other orders with nearby pickup windows. The route optimizer generates a single pick path that visits each store zone once, covering all items across all batched orders in the minimum travel distance." },
    { title: "Picker Assignment & App Loading", description: "Assign a picker and load the route to their device", detail: "The optimal batch is assigned to the available picker with the best position in the store relative to the starting zone. The picker's handheld app displays the first item to pick with its store location, and subsequent items are queued in the optimized sequence." },
    { title: "Item Scan & Vision Verification", description: "Verify the right item was selected", detail: "When the picker scans an item barcode, the vision model confirms the item matches the order specification across multiple dimensions: product name, brand, size, flavor, organic certification. Mismatches trigger an immediate alert before the picker moves on, preventing wrong-item errors from reaching the bag." },
    { title: "Out-of-Stock Detection & Substitution", description: "Handle unavailable items with intelligent alternatives", detail: "If an item is unavailable, the system generates up to 3 substitution options ranked by predicted customer acceptance, drawn from the customer's 18-month purchase history. The picker selects the best available option from the ranked list, and the substitution is communicated to the customer via the app with an explanation." },
    { title: "Order Completion & Staging", description: "Complete and stage the order for pickup", detail: "Completed items are staged in temperature-appropriate pickup zones. The system tracks completion status in real time and sends the customer a notification when their order is ready, including any substitutions with a reason and options to accept or request adjustment." },
    { title: "Customer Pickup & Feedback", description: "Facilitate pickup and capture satisfaction signals", detail: "At pickup, staff confirm order identity and handoff. Post-pickup, the customer can rate the substitutions they received—these ratings directly update the substitution model for future orders, creating a continuous improvement loop driven by actual customer preferences." },
  ],
  whyItWorkedTitle: "Why AI Made Grocery Fulfillment Better for Everyone",
  whyFactors: [
    { title: "Batch Picking Multiplied Individual Efficiency", description: "Picking 4–5 orders simultaneously with a single optimized path was 3x more efficient per picker than picking one order at a time—a structural efficiency gain that no individual behavior change could achieve." },
    { title: "Customer-Specific Substitution Is Non-Obvious But Critical", description: "A customer who always buys Honeycrisp apples doesn't want Red Delicious as a substitute. Using individual purchase history to generate substitutions was the single most impactful customer satisfaction improvement." },
    { title: "Vision Verification Catches Edge Cases at Scale", description: "1-in-30 scans produced a wrong match in testing—insignificant individually but at millions of orders per week, vision verification prevented hundreds of thousands of wrong-item errors per month." },
    { title: "Picker Adoption Through Immediate Benefit", description: "Pickers walked 2 miles less per shift on day one of deployment. The efficiency improvement was so immediate and tangible that adoption was nearly universal without mandates." },
  ],
  limitations: [
    { title: "Only Works for Planned E-Commerce Orders", description: "The route optimizer requires advance order data. Walk-in customers and last-minute orders can't be batched effectively and are handled through conventional picking." },
    { title: "New Customers Have No History for Substitution", description: "First-time and infrequent customers don't have enough purchase history for the substitution model to generate accurate personalized alternatives—these orders use category-level substitution rules as fallback." },
    { title: "Store Layout Changes Require Model Updates", description: "Planogram resets and store layout changes require manual updates to the store zone graph before the route optimizer reflects new product locations accurately." },
    { title: "High Complexity Items Need Human Judgment", description: "Fresh prepared foods, deli orders, and items requiring quality judgment (produce ripeness, seafood freshness) still require picker discretion that the system supports but cannot fully automate." },
  ],
  whenToUseGoodFit: [
    "Grocery retailers with significant e-commerce pickup and delivery volume (1,000+ orders/week)",
    "Retailers experiencing high picker labor costs and declining fulfillment margins",
    "Operations where substitution rejection rates are causing customer satisfaction problems",
    "Multi-location chains where learnings from one store can improve substitution models across all locations",
  ],
  whenToUseNotGoodFit: [
    "Small-format stores without systematic product location data",
    "Pure delivery operations without the in-store pick component",
    "Retailers with primarily walk-in customers and minimal pre-ordered fulfillment",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Purchase history modeling and substitution preference prediction", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Pick path optimization and fulfillment workflow automation", type: "service" },
    { name: "AI Computer Vision", slug: "ai-computer-vision", relevance: "Item verification scanning during pick operations", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "Grocery and CPG fulfillment AI deployment patterns", type: "industry" },
    { name: "Logistics AI Solutions", slug: "logistics-ai-solutions", relevance: "Last-mile delivery and fulfillment center optimization", type: "industry" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Picker performance and fulfillment operations optimization", type: "intelligence" },
  ],
  keyTakeaways: [
    "+87% pick rate achieved through multi-order batch routing, not individual picker speed increases",
    "Customer-specific substitution using 18-month purchase history reduces rejection by 73%",
    "Vision verification catches 1-in-30 wrong scans—critical at millions-per-week scale",
    "Picker adoption was immediate because walkers covered 2 fewer miles per shift on day one",
    "Route optimization ROI was measurable in the first week of deployment",
  ],
  faqs: [
    { question: "How does the route optimizer handle frozen and refrigerated items?", answer: "The route optimizer is temperature-zone aware. It sequences picks so that frozen and refrigerated items are collected last before staging to minimize temperature exposure time. The zone graph includes temperature classifications for each store section, and staging assignment routes cold items to refrigerated staging zones." },
    { question: "What happens when a customer's preferred substitute is also out of stock?", answer: "The substitution model generates a ranked list of alternatives. When the first choice is unavailable, the picker moves to the second-ranked option. If all suggested substitutes are unavailable, the item is flagged for removal from the order and the customer is notified via app with a refund option." },
    { question: "How does the system handle age-restricted items like alcohol?", answer: "Age-restricted items are flagged in the order and require ID verification at pickup—the system surfaces this requirement to the customer proactively in their pickup confirmation so they arrive prepared. Pickers are prompted to verify that the ID check step will be required at handoff." },
    { question: "Can the system be deployed in micro-fulfillment centers as well as in-store?", answer: "Yes. The same route optimization, vision verification, and substitution intelligence layers can be deployed in micro-fulfillment center environments. The zone graph structure and batch picking logic are applicable to any organized product storage environment, with some configuration for the physical layout differences vs in-store settings." },
  ],
  prevCase: { name: "Albertsons", url: "/case-studies/albertsons/" },
  nextCase: { name: "Stitch Fix", url: "/case-studies/stitch-fix/" },
};

export default function KrogerCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
