'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "knewton",
  company: "Knewton",
  industry: "Education Technology",
  subIndustry: "Adaptive Learning AI",
  accentColor: "indigo",
  gradientClasses: "bg-gradient-to-br from-background via-indigo-500/5 to-blue-500/10",
  heroHeadline: "Knewton: Adaptive Learning AI That Personalizes Every Practice Problem",
  heroSubheadline: "Real-time adaptive learning that adjusts difficulty, format, and sequence to each student's knowledge state—delivering +683% personalization improvement and +109% course completion rates.",
  heroStats: [
    { value: "+683%", label: "Personalization", color: "text-indigo-400" },
    { value: "+109%", label: "Completion Rate", color: "text-blue-400" },
    { value: "50%", label: "Faster Mastery", color: "text-violet-400" },
  ],
  directAnswerQuestion: "How does Knewton's adaptive learning AI work?",
  directAnswer: "Knewton uses a knowledge tracing algorithm that models each student's current mastery level across every concept in a curriculum graph. Based on this model, the system selects the next practice problem that maximizes the probability of learning—not too easy (boring), not too hard (frustrating). The algorithm updates its estimate of the student's knowledge state after every response and recalculates the optimal next item in real time, producing personalized sequences that reduce time to mastery by 50% vs fixed curricula.",
  clientDescription: "Knewton is an adaptive learning technology company whose platform powers personalized education experiences for publishers, universities, and K-12 school districts. Their core technology—probabilistic knowledge tracing and adaptive sequencing—has been embedded into leading textbooks and learning management systems to provide real-time personalization at the item level.",
  clientFounded: "2008",
  clientSize: "Integrated into 10M+ student learning experiences across 200+ institutions",
  clientLocation: "New York, NY, USA",
  problemTitle: "Fixed Curricula Teach to the Average Student—Missing Everyone",
  problemDescription: "Traditional curricula move every student through the same sequence at the same pace. A student who already understands fractions sits through the fractions lesson; a student who hasn't yet mastered it moves on anyway. Fixed pacing systematically fails both the fastest and slowest students, who spend their time on material at the wrong difficulty level—either bored or lost.",
  painPoints: [
    { title: "Curriculum Efficiency Loss", stat: "47%", description: "Proportion of learning time students spend on content they either already know or aren't ready for—wasted time that could be directed to genuine learning opportunities.", color: "indigo" },
    { title: "Course Completion Baseline", stat: "34%", description: "Average online course completion rate before adaptive personalization—most students disengage when content difficulty doesn't match their current level.", color: "red" },
    { title: "Mastery Time Variance", stat: "8x", description: "Range of time needed for different students to reach the same mastery level—fixed-pace curricula can't accommodate this variance without failing someone.", color: "amber" },
  ],
  solutionTitle: "Real-Time Knowledge Tracing and Adaptive Item Selection",
  solutionDescription: "AGIX Technologies built a probabilistic knowledge tracing system that maintains a live model of each student's mastery across every concept in the curriculum graph, selecting the next learning activity to maximize the rate of knowledge gain for that individual student at that moment.",
  solutionComponents: [
    { title: "Curriculum Knowledge Graph", description: "A structured representation of the curriculum as a directed graph of concepts, with prerequisite relationships, difficulty gradations, and multiple content formats for each concept." },
    { title: "Bayesian Knowledge Tracing", description: "For each concept, the model maintains a probability estimate of student mastery, updating after every response using Bayesian inference over correct/incorrect patterns and time-on-task signals." },
    { title: "Adaptive Item Selection Engine", description: "Selects the next practice item to maximize expected knowledge gain: targeting concepts where mastery probability is in the 40-70% range—the zone of proximal development where learning is most efficient." },
    { title: "Multi-Format Content Matching", description: "Different students learn better from different formats (worked examples, practice problems, video, reading). The system learns each student's format preferences and matches content format to knowledge state." },
    { title: "Mastery Threshold Management", description: "Configurable mastery thresholds allow institutions to define what level of evidence constitutes 'ready to advance'—preventing both premature advancement and unnecessary repetition." },
    { title: "Instructor Analytics Dashboard", description: "Real-time class-level view showing which concepts each student is working on, where students cluster in the curriculum, and which concepts have high confusion rates across the class." },
  ],
  architectureTitle: "Knewton Adaptive Learning Architecture",
  architectureLayers: [
    { name: "Curriculum Structure", components: ["Knowledge Graph (Concepts + Prerequisites)", "Item Bank with Metadata", "Difficulty Calibration", "Multi-Format Content Library"], color: "indigo" },
    { name: "Knowledge Modeling", components: ["Bayesian Knowledge Tracing", "Response Pattern Analysis", "Time-on-Task Signals", "Cross-Concept Correlation"], color: "blue" },
    { name: "Adaptive Engine", components: ["Zone of Proximal Development Targeting", "Item Selection Optimizer", "Format Preference Matching", "Sequence Personalization"], color: "violet" },
    { name: "Delivery & Interface", components: ["Student Learning Interface", "Instructor Dashboard", "LMS Integration (Canvas, Blackboard)", "Progress Reporting"], color: "purple" },
    { name: "Assessment & Calibration", components: ["Item Difficulty Estimation", "Mastery Threshold Management", "A/B Testing Framework", "Learning Outcome Measurement"], color: "slate" },
  ],
  resultsTitle: "Learning Outcomes Across Millions of Student-Concept Interactions",
  resultsMetrics: [
    { value: "+683%", label: "Personalization Index", description: "Increase in learning path diversity vs fixed curricula—students take fundamentally different routes to the same learning objectives", color: "indigo" },
    { value: "+109%", label: "Completion Rate", description: "Course completion improved from 34% to 71% with adaptive personalization vs fixed curriculum", color: "blue" },
    { value: "50%", label: "Faster Mastery", description: "Students reach defined mastery thresholds in half the time with adaptive sequencing vs linear progression", color: "violet" },
    { value: "-42%", label: "Student Frustration", description: "Reduction in self-reported frustration events (too hard content) with adaptive difficulty calibration", color: "purple" },
  ],
  resultsQuote: {
    text: "Our students were spending half their study time reviewing material they'd already mastered or struggling with material they weren't ready for. Knewton put everyone exactly where they needed to be, and completion rates nearly doubled in the first semester.",
    author: "Dean of Learning Innovation",
    role: "University Partner Institution",
  },
  howItWorksTitle: "How Knewton Adapts in Real Time to Each Student",
  steps: [
    { title: "Knowledge State Initialization", description: "Establish baseline for each student", detail: "When a student begins, the system can start with a placement assessment, import data from previous courses, or use default priors based on grade level. The initial knowledge state is intentionally uncertain—the system is designed to learn quickly from early interactions rather than rely heavily on pre-assessment." },
    { title: "Item Presentation & Response Collection", description: "Present a practice item and capture the response", detail: "The student receives a practice problem selected by the adaptive engine. Their response (correct/incorrect, time taken, confidence if collected) is the primary signal. The system accepts any format: multiple choice, free response, drag-and-drop, worked example with reflection question." },
    { title: "Knowledge State Update", description: "Update the model with the new evidence", detail: "The Bayesian knowledge tracing model updates the posterior probability of mastery for the target concept, incorporating the response, the concept difficulty, and the prior mastery estimate. Related concepts in the graph are also adjusted based on prerequisite and co-requisite relationships." },
    { title: "Next Item Selection", description: "Choose the optimal next learning activity", detail: "The item selection algorithm scans the item bank for the activity that maximizes expected knowledge gain given the current state. This typically means targeting concepts in the 40-70% mastery probability range—above this threshold, items are too easy to produce significant learning; below 40%, the student isn't ready for success." },
    { title: "Mastery Detection & Curriculum Advancement", description: "Identify when a student is ready to progress", detail: "When a concept's mastery probability crosses the institution-configured threshold (typically 85-90%), the concept is marked mastered and removed from active practice selection. The student advances through the curriculum at their own pace, guided by prerequisite completion rather than calendar pacing." },
    { title: "Instructor & Analytics Updates", description: "Provide real-time visibility to instructors", detail: "Instructor dashboards update in real time showing class-wide knowledge state distributions, individual student progress, and concepts with high confusion rates. Instructors can act on this intelligence—triggering review sessions for high-confusion concepts or identifying students needing intervention before assessments." },
  ],
  whyItWorkedTitle: "Why Knowledge Tracing Outperforms Fixed Curricula",
  whyFactors: [
    { title: "Zone of Proximal Development Targeting", description: "Selecting items at the right difficulty—challenging enough to produce learning, achievable enough to produce success—is the single most powerful lever in learning science and was operationalized at scale for the first time." },
    { title: "Response Pattern as the Richest Signal", description: "Every response (not just test scores) updates the knowledge model. This continuous inference produces more accurate mastery estimates than periodic assessments and enables real-time adaptation." },
    { title: "Prerequisite Graph Enables Intelligent Sequencing", description: "Items are selected based on the full prerequisite structure, not just the target concept in isolation—ensuring students are never asked to practice skills that depend on concepts they haven't mastered yet." },
    { title: "Engagement Through Appropriate Challenge", description: "Students who work on material matched to their level report higher engagement and lower frustration—the intrinsic motivation improvement compounds over the course duration." },
    { title: "Instructor Visibility Into Class-Level Patterns", description: "Showing instructors where students are struggling at the class level enabled targeted lecture and review sessions, amplifying the effect of AI-driven individual practice." },
  ],
  limitations: [
    { title: "Requires Rich Item Banks", description: "Effective adaptive sequencing requires many items at varied difficulty levels for each concept. Curricula with thin item banks can't produce sufficient personalization without significant content development investment." },
    { title: "Conceptual Understanding vs Procedural Practice", description: "Knowledge tracing works best for procedural skills (math procedures, language rules) where right/wrong is clear. Conceptual understanding, creativity, and complex writing require different assessment approaches." },
    { title: "Cold Start With No Prior Data", description: "New students require 5–10 interactions per concept before the knowledge model becomes accurate. Early personalization is necessarily limited until sufficient data is collected." },
    { title: "Doesn't Address Motivation or Non-Cognitive Factors", description: "Adaptive content selection addresses cognitive load but not motivation, anxiety, or engagement. Students who are disengaged for non-cognitive reasons need interventions beyond adaptive difficulty adjustment." },
  ],
  whenToUseGoodFit: [
    "Online courses or textbooks with large, diverse student populations at different starting levels",
    "STEM subjects (math, science, coding) with clear prerequisite structures and procedural skills",
    "Skill-based training programs where measurable competency milestones define advancement",
    "High-stakes test preparation where practice efficiency directly impacts performance outcomes",
  ],
  whenToUseNotGoodFit: [
    "Courses focused on discussion, creative writing, or project-based learning",
    "Very small class sizes where individual instructor attention is the more efficient personalization mechanism",
    "Curricula with insufficient item banks (fewer than 10 items per concept)",
    "Contexts where social learning and peer comparison are more important than individual optimization",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Bayesian knowledge state modeling and mastery prediction", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Adaptive learning engine tailored to specific curricula", type: "service" },
    { name: "EdTech AI Solutions", slug: "edtech-ai-solutions", relevance: "Educational institution AI deployment patterns", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Adaptive item selection and curriculum advancement decisions", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Learning operations and instructor workflow support", type: "intelligence" },
  ],
  keyTakeaways: [
    "+683% personalization means students take fundamentally different paths to the same objectives",
    "Zone of proximal development targeting (40-70% mastery probability) is the core scientific insight",
    "Every response updates the knowledge model—continuous inference beats periodic assessment",
    "+109% completion rate proves appropriate difficulty is the primary engagement lever in digital learning",
    "Prerequisite graph structure enables sequencing that never asks students to exceed their preparation",
  ],
  faqs: [
    { question: "How does Knewton integrate with existing LMS platforms?", answer: "Knewton has pre-built LTI (Learning Tools Interoperability) integrations with Canvas, Blackboard, Moodle, and other major LMS platforms. Students access adaptive content through their existing LMS interface, and grade data flows back automatically. Custom integrations via API are available for proprietary platforms." },
    { question: "How long does it take to see measurable results after deployment?", answer: "Completion rate and engagement improvements typically appear within the first 2-4 weeks as the knowledge models accumulate sufficient data to drive meaningful adaptation. Outcome improvements (test scores, final grades) are typically measured at the end of the first full course cycle—semester or quarter." },
    { question: "What happens when a student struggles with a concept for a long time?", answer: "When a student has many failed attempts on a concept without improvement, the system flags them for instructor intervention and may temporarily pivot to prerequisite concepts that may be the root cause of the struggle. Persistent difficulty is treated as a signal for human intervention, not just more adaptive practice." },
    { question: "Can the adaptive algorithm work across subjects?", answer: "Yes, the underlying knowledge tracing and item selection algorithms are subject-agnostic. The quality of adaptation depends on the quality of the curriculum knowledge graph and item bank, which vary by subject. Mathematics, language learning, and coding have the richest existing item banks and produce the most dramatic results." },
    { question: "How does the system handle students who game the system (click through quickly)?", answer: "Time-on-task is incorporated into the knowledge model. Extremely fast responses are weighted lower in mastery estimation, and items requiring genuine engagement (constructed response, multi-step problems) are included in the item bank to prevent simple click-through gaming strategies from producing false mastery signals." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function KnewtonCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
