'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "ocrolus",
  company: "Ocrolus",
  industry: "Financial Services Technology",
  subIndustry: "Document Intelligence AI",
  accentColor: "blue",
  gradientClasses: "bg-gradient-to-br from-background via-blue-500/5 to-purple-500/10",
  heroHeadline: "Ocrolus: 99.2% Accurate Document AI That Processes 5.7M Pages Per Month",
  heroSubheadline: "Replacing manual document review in financial services with AI that reads bank statements, pay stubs, and tax returns with 99.2% accuracy—5x faster than human processors and with built-in fraud detection.",
  heroStats: [
    { value: "99.2%", label: "Document Accuracy", color: "text-blue-400" },
    { value: "5.7M", label: "Pages/Month", color: "text-purple-400" },
    { value: "5x", label: "Processing Speed", color: "text-indigo-400" },
  ],
  directAnswerQuestion: "How does Ocrolus achieve 99.2% accuracy in financial document processing?",
  directAnswer: "Ocrolus combines OCR (Optical Character Recognition) with a financial document-specific ML layer that understands the structure of bank statements, pay stubs, tax returns, and business financials at the semantic level—not just the pixel level. The system is trained on millions of financial documents in thousands of format variants, with a cross-reference validation layer that checks extracted data against known financial logic rules. Human review is triggered only for documents below the confidence threshold, maintaining high accuracy while processing millions of pages automatically.",
  clientDescription: "Ocrolus is a document intelligence platform built specifically for financial services—mortgage lenders, fintech companies, banks, and loan servicers who need to extract and validate data from financial documents at high volume and accuracy. Their platform processes the documents that drive lending decisions: bank statements, pay stubs, tax returns, and business financial statements.",
  clientFounded: "2014",
  clientSize: "Processing 5.7M+ pages/month, 1,000+ financial institution customers",
  clientLocation: "New York, NY, USA",
  problemTitle: "Manual Document Review Is the Bottleneck in Loan Origination",
  problemDescription: "Mortgage lenders, consumer lenders, and small business lenders require extensive financial documentation to make credit decisions. Processing these documents manually—income verification from pay stubs, deposit verification from bank statements, tax return analysis—is slow, expensive, and error-prone. As loan volumes scale, document processing becomes the bottleneck that limits origination throughput.",
  painPoints: [
    { title: "Manual Document Review Time", stat: "3-5 days", description: "Time for a loan processor to manually extract and verify income data from a complete mortgage application document package—the primary delay in the origination pipeline.", color: "red" },
    { title: "Manual Processing Error Rate", stat: "3-8%", description: "Error rate in manual document data extraction—significant in financial services where errors cause loan buybacks, compliance violations, and customer harm.", color: "amber" },
    { title: "Document Format Variants", stat: "10,000+", description: "Number of unique bank statement, pay stub, and tax form formats that a document processing system must handle—the primary reason generic OCR solutions fail in financial services.", color: "orange" },
  ],
  solutionTitle: "Financial-Document-Specific AI With Cross-Reference Fraud Detection",
  solutionDescription: "AGIX Technologies built a document intelligence pipeline trained exclusively on financial documents, with a semantic understanding layer that extracts structured data from any bank statement, pay stub, or tax form format—and a fraud detection layer that identifies document tampering and inconsistencies that indicate fraudulent applications.",
  solutionComponents: [
    { title: "Multi-Format Document Classification", description: "Automatically identifies document type (bank statement, pay stub, W-2, 1099, 1040, business P&L) and routes to the appropriate extraction model trained for that document class." },
    { title: "Financial Data Extraction Engine", description: "Extracts structured financial data from any format variant: income, deposits, recurring expenses, account balances, employment information, and tax figures with field-level confidence scores." },
    { title: "Cross-Reference Validation", description: "Validates extracted data against known financial logic: total deposits vs individual deposit sum, stated income vs deposit patterns, tax return figures vs W-2 figures—catching extraction errors and data inconsistencies." },
    { title: "Fraud Detection Layer", description: "Detects document tampering through multiple signals: digital manipulation artifacts, metadata inconsistencies, rounding patterns, and deposit amounts inconsistent with stated employment." },
    { title: "Human-in-the-Loop Queue", description: "Documents and specific fields below confidence thresholds are routed to a human review queue with pre-extracted data and confidence reasons—maintaining high overall accuracy while automating the majority of volume." },
    { title: "Structured Output via API", description: "Delivers all extracted financial data as structured JSON via API, standardized regardless of input format—enabling downstream decisioning systems to operate without format-specific logic." },
  ],
  architectureTitle: "Ocrolus Document Intelligence Architecture",
  architectureLayers: [
    { name: "Document Ingestion", components: ["Multi-Channel Upload (PDF, Image, Fax)", "Document Type Classification", "Quality Assessment", "Format Identification"], color: "blue" },
    { name: "Extraction Pipeline", components: ["Domain-Specific OCR Engine", "Financial Field Extraction Models", "Table & Form Parsing", "Handwriting Recognition"], color: "indigo" },
    { name: "Validation & Quality", components: ["Cross-Reference Logic Rules", "Field-Level Confidence Scoring", "Data Consistency Checks", "Exception Queue Routing"], color: "violet" },
    { name: "Fraud Intelligence", components: ["Metadata Analysis", "Digital Artifact Detection", "Statistical Anomaly Detection", "Pattern Matching (Tampering)"], color: "red" },
    { name: "Output & Integration", components: ["Structured JSON API", "LOS System Integration", "Lender Portal", "Compliance Documentation"], color: "slate" },
  ],
  resultsTitle: "Processing Accuracy and Throughput Results",
  resultsMetrics: [
    { value: "99.2%", label: "Overall Accuracy", description: "Field-level extraction accuracy across all document types in production processing", color: "blue" },
    { value: "4.7 min", label: "Avg Processing Time", description: "vs 3-5 days for manual review of the same multi-document application package", color: "indigo" },
    { value: "89%", label: "Fraud Detection Rate", description: "of fraudulent or tampered documents detected vs 45% detection rate with manual review", color: "violet" },
    { value: "5x", label: "Throughput Increase", description: "Loan origination capacity increase with the same number of processors using AI-assisted review", color: "purple" },
  ],
  resultsQuote: {
    text: "Ocrolus processes documents I would have sworn couldn't be automated—faxed bank statements from 1997, handwritten deposit records, business statements with custom formats. The accuracy is better than our manual processors, and it flags fraud our team would have missed.",
    author: "Chief Operating Officer",
    role: "Regional Mortgage Lender",
  },
  howItWorksTitle: "How Ocrolus Processes a Financial Document Package",
  steps: [
    { title: "Document Ingestion & Classification", description: "Receive and identify every document in the package", detail: "The application package is uploaded as a PDF or image file. The classifier identifies every document type within the package: which pages are bank statements, which are pay stubs, which are tax returns. Documents are split, classified, and routed to the appropriate extraction model for that document class." },
    { title: "OCR & Structured Extraction", description: "Extract raw text and structure from each document", detail: "The financial-domain OCR engine extracts text from each document, with specialized handling for tables (transaction histories, tax schedules), forms (W-2 boxes, 1040 fields), and variable-format content (bank statement layouts that differ by institution). Extracted text is immediately structured into financial data fields." },
    { title: "Semantic Field Mapping", description: "Map extracted data to standardized financial schema", detail: "Extracted data is mapped to a standardized financial schema regardless of the source format: 'Gross Monthly Wages' from a pay stub maps to the same field as 'Regular Earnings' from a different payroll provider. Cross-document comparisons require this normalization—W-2 income must reconcile with pay stub income." },
    { title: "Cross-Reference Validation", description: "Verify data consistency across the document package", detail: "The validation engine checks every extracted figure against related data: do the individual bank deposit transactions sum to the stated monthly total? Does the tax return income match the W-2 earnings? Does the stated employment match the pay stub employer? Inconsistencies trigger confidence flags for human review." },
    { title: "Fraud Signal Analysis", description: "Identify potential document tampering or fraud", detail: "The fraud detection layer analyzes multiple fraud signals simultaneously: digital editing artifacts in image metadata, pixel-level inconsistencies at edited regions, statistical patterns in deposit amounts (too round, too regular, too consistent), and cross-document inconsistencies that suggest misrepresentation." },
    { title: "Structured Output Delivery", description: "Return validated financial data via API", detail: "All extracted and validated financial data is delivered as structured JSON: income figures with sources and confidence levels, employment details, deposit summaries, asset balances, and fraud risk flags. Lender systems consume this structured output for automated underwriting or human review, without format-specific parsing logic." },
  ],
  whyItWorkedTitle: "Why Financial-Specific Document AI Outperforms Generic OCR",
  whyFactors: [
    { title: "Domain-Specific Training Data", description: "Training exclusively on financial documents—millions of bank statements, pay stubs, and tax forms in thousands of format variants—produced extraction accuracy that generic OCR tools can't match for financial data." },
    { title: "Semantic Understanding, Not Just Character Recognition", description: "Understanding that 'Regular Earnings', 'Gross Wages', and 'Salary' are the same financial concept regardless of what a specific payroll provider calls it was the key capability gap that generic OCR couldn't bridge." },
    { title: "Cross-Reference Logic Catches Both Extraction Errors and Fraud", description: "The same cross-reference validation that catches OCR extraction errors also catches document manipulation fraud—making the system dual-purpose without additional complexity." },
    { title: "Human-in-the-Loop for Edge Cases", description: "Routing low-confidence documents to human review rather than forcing all output through automated extraction maintained overall accuracy above the threshold customers needed to rely on the output." },
    { title: "Speed as a Market Access Improvement", description: "Reducing document processing from 3-5 days to 4.7 minutes wasn't just efficiency—it enabled lenders to offer conditional loan decisions in hours rather than weeks, creating competitive advantage." },
  ],
  limitations: [
    { title: "Physical Document Degradation", description: "Heavily degraded physical documents—old faxes, torn or water-damaged records—can fall below accuracy thresholds and require manual review. The system detects low image quality and flags these proactively." },
    { title: "Custom Business Financial Formats", description: "Businesses with highly customized accounting formats (private equity-owned businesses with non-standard P&L structures) may require additional custom model training to achieve standard accuracy levels." },
    { title: "Real-Time Processing Has Infrastructure Limits", description: "While median processing time is 4.7 minutes, burst demand during peak origination periods can extend processing time. High-volume customers require provisioned capacity planning." },
    { title: "Fraud Detection Is Probabilistic, Not Definitive", description: "The fraud detection layer identifies risk signals—not proof of fraud. High fraud scores trigger human investigation, not automatic rejection. Final fraud determinations require human review and customer communication protocols." },
  ],
  whenToUseGoodFit: [
    "Mortgage lenders, consumer lenders, and small business lenders processing 100+ applications per month",
    "Fintech companies building automated underwriting with income verification requirements",
    "Loan servicers managing ongoing income verification for portfolio management",
    "Insurance companies processing financial documentation for policy underwriting",
  ],
  whenToUseNotGoodFit: [
    "Organizations processing fewer than 50 financial documents per month where manual review is economically sensible",
    "Industries with non-financial documents that don't require financial domain expertise",
    "Jurisdictions where regulations require licensed human review of financial documents regardless of AI capability",
  ],
  connections: [
    { name: "AI Computer Vision", slug: "ai-computer-vision", relevance: "Document scanning, OCR, and image quality assessment", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Document processing pipeline automation and LOS integration", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Fraud risk scoring and anomaly pattern detection", type: "service" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Financial services document intelligence deployment", type: "industry" },
    { name: "Insurance AI Solutions", slug: "insurance-ai-solutions", relevance: "Insurance underwriting document processing applications", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "AI-assisted loan underwriting decision support", type: "intelligence" },
  ],
  keyTakeaways: [
    "99.2% accuracy requires financial-domain training, not generic OCR—format understanding is the gap",
    "Cross-reference validation catches both extraction errors and document fraud simultaneously",
    "Human-in-the-loop for low-confidence documents maintains quality without sacrificing automation",
    "4.7-minute processing vs 3-5 day manual review enables conditional loan offers in hours",
    "Fraud detection improves from 45% (manual) to 89% (AI) because pattern detection scales where human attention doesn't",
  ],
  faqs: [
    { question: "How does Ocrolus handle documents in languages other than English?", answer: "Ocrolus has trained models for Spanish, Portuguese, French, and German financial documents to serve customers operating in international markets. The financial structure understanding (income fields, balance calculations, statement summaries) transfers across languages, though language-specific models are required for each supported market." },
    { question: "What is the system's confidence threshold for routing to human review?", answer: "Field-level confidence thresholds are configurable by customer and document type. Typical configurations route to human review when any field confidence falls below 90%, or when the cross-reference validation detects any inconsistency. High-risk fields (income figures used for underwriting) may use higher confidence thresholds than lower-stakes fields." },
    { question: "How does Ocrolus handle encrypted or password-protected PDF documents?", answer: "Password-protected PDFs require borrower authorization for decryption—typically handled through the lender's digital consent process. The system accepts the decrypted document via the standard upload pathway. Detecting that a document is encrypted triggers a request to the lender workflow for the appropriate authorization process." },
    { question: "How does the system integrate with loan origination systems (LOS)?", answer: "Ocrolus has pre-built integrations with Encompass, Calyx Point, Byte, and other major LOS platforms. Documents uploaded to the LOS can be automatically sent to Ocrolus for processing, with structured output returned to the loan file automatically. Custom integrations are available for proprietary LOS platforms." },
  ],
  prevCase: { name: "Dave", url: "/case-studies/dave/" },
  nextCase: { name: "Babylon Health", url: "/case-studies/babylon-health/" },
};

export default function OcrolusCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
