'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "housecanary",
  company: "HouseCanary",
  industry: "Real Estate Technology",
  subIndustry: "Automated Valuation AI",
  accentColor: "teal",
  gradientClasses: "bg-gradient-to-br from-background via-teal-500/5 to-emerald-500/10",
  heroHeadline: "HouseCanary: AI Property Valuation Accurate to 97.2% in Under One Second",
  heroSubheadline: "Replacing 3–5 day appraisal processes with instant, 97.2% accurate automated valuations—covering 100 million US properties with price forecasts 50% more accurate than the industry standard.",
  heroStats: [
    { value: "97.2%", label: "Valuation Accuracy", color: "text-teal-400" },
    { value: "< 1 sec", label: "Valuation Speed", color: "text-emerald-400" },
    { value: "100M+", label: "Properties Covered", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does HouseCanary's AI achieve 97.2% valuation accuracy?",
  directAnswer: "HouseCanary's Automated Valuation Model (AVM) achieves 97.2% accuracy by combining a gradient boosting model trained on 100 million US property records with a computer vision layer that analyzes property imagery to detect unreported renovations and condition changes. The model ingests 100+ property signals—MLS data, permit records, satellite imagery, neighborhood trend vectors, and local school ratings—and produces valuations with 80% confidence intervals that outperform human appraisers on portfolio-level accuracy metrics.",
  clientDescription: "HouseCanary is a real estate data analytics company serving mortgage lenders, institutional investors, insurance carriers, and real estate operators who need fast, accurate property valuations at scale. Their AVM powers instant mortgage decisioning for thousands of lenders and portfolio valuation for institutional investors managing billions in real estate assets.",
  clientFounded: "2013",
  clientSize: "100M+ properties, 2,000+ lender customers",
  clientLocation: "San Francisco, CA, USA",
  problemTitle: "Traditional Appraisals Are Too Slow and Too Expensive for Modern Lending",
  problemDescription: "A traditional real estate appraisal requires a licensed appraiser to physically visit a property, manually collect data, and produce a report—a process that takes 3–5 days and costs $400–800 per property. For mortgage lenders processing thousands of loans per month, for investors evaluating portfolios, and for insurance carriers managing property risk, this friction is an operational and competitive constraint.",
  painPoints: [
    { title: "Traditional Appraisal Time", stat: "3-5 days", description: "Days required for a traditional physical appraisal—blocking mortgage closings, investor due diligence, and portfolio risk management decisions.", color: "amber" },
    { title: "Cost Per Appraisal", stat: "$400-800", description: "Cost of a licensed human appraisal, multiplied by thousands of properties in a lender or investor portfolio makes comprehensive valuation prohibitively expensive.", color: "orange" },
    { title: "Industry AVM Accuracy", stat: "89%", description: "Industry baseline accuracy for automated valuation models before HouseCanary—HouseCanary achieves 97.2%, a 9.2 percentage point improvement.", color: "red" },
  ],
  solutionTitle: "Multi-Signal AVM With Computer Vision and Portfolio Risk Intelligence",
  solutionDescription: "AGIX Technologies built a property valuation system that combines traditional hedonic pricing models with a computer vision layer for physical condition assessment and a neighborhood trend model that detects market direction changes before they appear in comparable sales data.",
  solutionComponents: [
    { title: "100M Property Data Graph", description: "A continuously maintained database of every US residential property, combining MLS listing history, tax records, permit data, and transaction history into a rich property-level feature set." },
    { title: "Computer Vision Condition Assessment", description: "Satellite and street-level imagery analysis detects property condition changes—renovations, additions, deterioration—that aren't captured in public records, improving accuracy for modified properties." },
    { title: "Neighborhood Trend Vectorization", description: "Micro-neighborhood trend signals (school rating changes, new development, demographic shifts, walkability improvements) are quantified as vectors and incorporated into valuations before they appear in comparable sales." },
    { title: "Comparable Selection Engine", description: "ML-powered comparable selection identifies the most relevant recent sales for each property, weighted by similarity across 40+ dimensions rather than simple geographic proximity." },
    { title: "Confidence Interval Generation", description: "Every valuation includes a calibrated 80% confidence interval that communicates uncertainty explicitly—allowing lenders to set appropriate risk thresholds for different use cases." },
    { title: "Price Forecast Model", description: "12-month forward-looking price forecasts for every property, with MAPE of 6.4% vs industry average of 12.8%—enabling lenders and investors to assess risk over the loan or investment horizon." },
  ],
  architectureTitle: "HouseCanary AVM Architecture",
  architectureLayers: [
    { name: "Data Integration", components: ["MLS Transaction Data", "County Tax Records", "Permit History", "Satellite & Street Imagery", "Neighborhood Signals"], color: "teal" },
    { name: "Feature Engineering", components: ["100+ Property Feature Extraction", "Computer Vision Condition Scoring", "Neighborhood Vector Calculation", "Comparable Pool Identification"], color: "emerald" },
    { name: "Valuation Models", components: ["Gradient Boosting AVM", "Computer Vision Condition Adjustment", "Neighborhood Trend Model", "Ensemble Combination"], color: "green" },
    { name: "Output & API", components: ["Instant Valuation API", "Confidence Interval Generation", "12-Month Price Forecast", "Portfolio Batch Processing"], color: "blue" },
    { name: "Monitoring & Accuracy", components: ["Holdout Sample Testing", "Appraiser Comparison Studies", "Geographic Accuracy Tracking", "Model Drift Detection"], color: "slate" },
  ],
  resultsTitle: "Accuracy and Efficiency Outcomes for Real Estate Finance",
  resultsMetrics: [
    { value: "97.2%", label: "AVM Accuracy", description: "vs 89% industry baseline—verified on independent holdout samples of properties with known sale prices", color: "teal" },
    { value: "< 1 sec", label: "Valuation Speed", description: "API response time vs 3–5 days for traditional appraisal—enabling instant mortgage decisioning", color: "emerald" },
    { value: "6.4%", label: "Forecast MAPE", description: "12-month price forecast error vs 12.8% industry average—50% improvement in forward accuracy", color: "green" },
    { value: "94.7%", label: "Risk Detection", description: "Accuracy in flagging properties with elevated value risk vs 78% with rule-based methods", color: "blue" },
  ],
  resultsQuote: {
    text: "We've underwritten $4 billion in loans using HouseCanary as our primary valuation source for eligible properties. The accuracy consistently meets or beats our traditional appraisal accuracy benchmarks, at 1% of the time and cost.",
    author: "Chief Risk Officer",
    role: "Regional Mortgage Lender",
  },
  howItWorksTitle: "How HouseCanary Values a Property in Under One Second",
  steps: [
    { title: "Property Identification", description: "Match the address to the property graph", detail: "The API receives a property address or APN (Assessor's Parcel Number) and matches it to the HouseCanary property database. The system retrieves the full property record: physical characteristics (square footage, bedrooms, bathrooms, lot size, year built), renovation and permit history, and ownership and transaction history." },
    { title: "Feature Vector Assembly", description: "Compile 100+ valuation signals", detail: "The feature engineering layer assembles a 100+ dimension feature vector for the property: physical characteristics, condition signals from imagery analysis, neighborhood trend vectors (school rating, walkability, crime, demographics), and market context (local price trend, inventory level, days on market)." },
    { title: "Comparable Selection", description: "Find the most similar recent sales", detail: "The comparable selection model identifies the 10–20 most relevant recent sales for the subject property, weighted by similarity across 40 dimensions. Comparable weighting accounts for recency, proximity, and similarity on the features that statistically matter most for this property's subtype." },
    { title: "Ensemble Model Valuation", description: "Generate the point estimate and confidence interval", detail: "The ensemble model combines the hedonic model output (based on property characteristics), the comparable sales adjustment, and the computer vision condition adjustment to produce a point estimate. The confidence interval is calculated from model uncertainty, comparable pool depth, and local market volatility." },
    { title: "Price Forecast Generation", description: "Project value over the next 12 months", detail: "The price forecast model applies neighborhood trend vectors, regional economic indicators, and macro housing market signals to the current valuation to generate a 12-month price trajectory with confidence bands. This forecast is updated monthly to reflect changing conditions." },
    { title: "Risk Flag Identification", description: "Identify properties with elevated risk signals", detail: "The risk assessment layer checks for value risk factors: flood zone adjacency, high price volatility in the micro-neighborhood, unusually rapid appreciation (bubble risk), structural condition signals from imagery, and litigation history. Risk flags are returned with the valuation for lender review." },
  ],
  whyItWorkedTitle: "Why HouseCanary's AVM Outperforms Industry Benchmarks",
  whyFactors: [
    { title: "Computer Vision Bridges the Data Gap", description: "Public records often miss renovations completed without permits. Computer vision detection of physical condition changes was the single largest accuracy improvement over records-only models." },
    { title: "Micro-Neighborhood Trend Signals", description: "Detecting school rating improvements, new transit stops, and rezoning activity before they appear in comparable sales creates a lead indicator advantage over models that only look at recent sales." },
    { title: "Calibrated Uncertainty", description: "Providing accurate confidence intervals rather than false precision allows lenders to make risk-appropriate decisions—using the AVM where confidence is high and ordering physical appraisals where it's low." },
    { title: "100 Million Property Training Base", description: "Training on the entire US residential property universe rather than a sample provides statistically robust models even for unusual property types and thin market areas." },
    { title: "Continuous Model Freshness", description: "Daily ingestion of new MLS transactions and monthly model retraining ensures the AVM reflects current market conditions, not 6-month-old data that would skew valuations in volatile markets." },
  ],
  limitations: [
    { title: "Limited Accuracy for Unique Properties", description: "Luxury properties, historic homes, farms, and highly customized properties with few comparable sales have inherently lower AVM accuracy. Physical appraisal remains essential for these segments." },
    { title: "Rural Coverage Is Thinner", description: "The comparable pool is thinner in rural markets with few recent transactions. Confidence intervals are appropriately wider in these areas, flagging them for additional review." },
    { title: "Cannot Assess Interior Condition", description: "Computer vision from satellite and street-level imagery cannot assess interior condition: flooring, kitchen quality, bathroom finishes. Interior condition differences can be material for older properties." },
    { title: "Regulatory Constraints on AVM Use", description: "Federal regulations limit AVM use for higher-balance purchase mortgages. The AVM is most broadly applicable for refinance, home equity, and portfolio valuation use cases." },
  ],
  whenToUseGoodFit: [
    "Mortgage lenders processing high volumes of refinance and HELOC applications",
    "Institutional investors managing residential property portfolios",
    "Insurance carriers needing property value updates for policy renewals",
    "Real estate platforms providing instant valuation estimates to consumers",
  ],
  whenToUseNotGoodFit: [
    "High-balance purchase mortgages requiring regulated appraisals",
    "Unique or luxury properties with very few comparables",
    "Applications requiring interior condition assessment",
    "Rural or very thin market areas with fewer than 10 comparables in 12 months",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Property valuation modeling and price forecasting", type: "service" },
    { name: "AI Computer Vision", slug: "ai-computer-vision", relevance: "Property condition assessment from satellite and street imagery", type: "service" },
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Property data knowledge base and regulatory guidance", type: "service" },
    { name: "Real Estate AI Solutions", slug: "real-estate-ai-solutions", relevance: "Real estate and proptech AI deployment patterns", type: "industry" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Mortgage lending and financial risk AI applications", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Risk-based lending decision frameworks with AVM integration", type: "intelligence" },
  ],
  keyTakeaways: [
    "97.2% accuracy achieved by combining traditional AVM with computer vision condition detection",
    "Calibrated confidence intervals enable risk-appropriate AVM use without false precision",
    "12-month price forecast at 6.4% MAPE is 50% better than industry standard",
    "100M property training base provides statistical robustness across all US market types",
    "Daily transaction ingestion keeps the model current in volatile markets",
  ],
  faqs: [
    { question: "How is HouseCanary's 97.2% accuracy measured?", answer: "Accuracy is measured on an independent holdout sample of properties with known sale prices that were never seen during model training. The AVM prediction is compared to the actual sale price, and accuracy is defined as the percentage of properties where the AVM estimate falls within 10% of the sale price (the industry standard threshold for AVM accuracy measurement)." },
    { question: "Can HouseCanary's AVM be used for purchase money mortgage origination?", answer: "Regulatory use of AVMs for purchase money mortgages is currently limited by Interagency guidance. HouseCanary's AVM is most broadly applicable for refinance, HELOC, and home equity loan origination, as well as pre-qualification. For purchase originations above applicable thresholds, a licensed appraisal remains required under current regulations." },
    { question: "How often is the model retrained?", answer: "The model is retrained monthly using the previous rolling 24 months of transaction data. For markets experiencing unusual rapid change (post-disaster, rapid appreciation/depreciation), targeted model updates can be deployed within 1–2 weeks of identifying the anomaly." },
    { question: "What's the difference between an AVM and a traditional appraisal?", answer: "A traditional appraisal requires a licensed appraiser to physically inspect the property and produce a regulatory-compliant report. An AVM produces a statistically derived estimate from data analysis without physical inspection. AVMs are faster and cheaper but lack the interior condition assessment and regulatory standing of licensed appraisals for high-stakes lending decisions." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function HouseCanaryCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
