'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "ulta-beauty",
  company: "Ulta Beauty",
  industry: "Beauty Retail",
  subIndustry: "AI Loyalty Program Optimization",
  accentColor: "pink",
  gradientClasses: "bg-gradient-to-br from-background via-pink-500/5 to-purple-500/10",
  heroHeadline: "Ulta Beauty: Turning 37M Members Into a Personalization Engine",
  heroSubheadline: "Transforming Ultamate Rewards from a generic points program into an AI personalization platform—delivering +172% campaign conversion, -57% churn, and nearly 3x offer redemption rates.",
  heroStats: [
    { value: "+172%", label: "Campaign Conversion", color: "text-pink-400" },
    { value: "37M", label: "Members", color: "text-purple-400" },
    { value: "-57%", label: "Customer Churn", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does Ulta Beauty use AI to optimize its loyalty program?",
  directAnswer: "Ulta Beauty's AI personalization system models each of 37M+ members' beauty category affinity, brand preferences, purchase cycle patterns, and price sensitivity—generating individualized offers that align with actual purchase intent. AI-generated offers surface skincare replenishment reminders before a user runs out, recommend complementary products based on recent purchases, and deliver personalized rewards at predicted moments of highest purchase intent through the member's preferred channel. Offer redemption rates increased from 12% to 34%—nearly tripling engagement without increasing marketing spend.",
  clientDescription: "Ulta Beauty is the largest specialty beauty retailer in the United States, operating 1,350+ stores and serving 37M+ active Ultamate Rewards loyalty members. With 25,000+ products across mass and prestige categories, the challenge of delivering relevant personalization at scale across the full beauty spectrum is uniquely complex.",
  clientFounded: "1990",
  clientSize: "47,000+ employees, 1,350+ stores, $10B+ revenue",
  clientLocation: "Bolingbrook, Illinois, USA",
  problemTitle: "37 Million Members, Zero Meaningful Personalization",
  problemDescription: "Ultamate Rewards had massive scale but treated every member identically. Skincare enthusiasts received fragrance promotions. Value seekers got prestige brand emails. The result: 12% email open rates, 3.2% campaign conversion, and 28% annual member churn—leaving billions in loyalty value unrealized.",
  painPoints: [
    { title: "Email Open Rate", stat: "12%", description: "Generic blast emails to all 37M members achieved only 12% open rates—irrelevant content drove disengagement.", color: "red" },
    { title: "Campaign Conversion", stat: "3.2%", description: "Under 4% of campaign recipients converted to purchase—personalization gap costing hundreds of millions annually.", color: "amber" },
    { title: "Member Churn Rate", stat: "28%", description: "Nearly one-third of active members lapsed annually, driven largely by irrelevant communication and offers.", color: "orange" },
  ],
  solutionTitle: "Predictive Personalization Across the Full Member Lifecycle",
  solutionDescription: "AGIX Technologies transformed Ultamate Rewards into a predictive personalization engine that models each member's beauty preferences, purchase cycles, and price sensitivity—delivering hyper-relevant offers through the right channel at the right moment.",
  solutionComponents: [
    { title: "Beauty Category Affinity Modeling", description: "ML models classify each member's primary beauty category affinities (skincare, makeup, fragrance, haircare, tools) and brand tier preferences (mass vs. prestige) from purchase history." },
    { title: "Purchase Cycle Prediction", description: "Product-specific repurchase cycle models predict when each member is likely to run out of a frequently purchased product—enabling perfectly timed replenishment reminders." },
    { title: "Churn Risk Scoring", description: "Binary churn classifier generates a real-time churn probability score for every member, triggering proactive retention interventions 30 days before predicted lapse." },
    { title: "Next Best Action Engine", description: "Decision engine determines the optimal offer, product recommendation, or engagement trigger for each member in each communication cycle—choosing from hundreds of action options." },
    { title: "Channel and Send-Time Optimization", description: "Per-member channel preference model (email vs. app push vs. SMS) and send-time optimization predicts the hour and channel most likely to drive engagement for each individual member." },
    { title: "Tier Advancement Nudge System", description: "Identifies members within reach of tier advancement, calculates the exact points needed, and delivers personalized incentives timed to accelerate tier qualification." },
  ],
  architectureTitle: "Ulta Beauty AI Personalization Architecture",
  architectureLayers: [
    { name: "Member Data Platform", components: ["Purchase History (7+ years)", "In-Store & Online Transactions", "App Engagement Signals", "Email Click/Open Data", "Review & Rating History"], color: "pink" },
    { name: "Preference Modeling", components: ["Category Affinity Model", "Brand Tier Preference Model", "Price Sensitivity Estimator", "Ingredient/Formulation Matching", "Seasonal Purchase Patterns"], color: "purple" },
    { name: "Predictive Engines", components: ["Repurchase Cycle Prediction", "Churn Risk Scorer", "CLV Projection Model", "Tier Advancement Calculator", "Product Discovery Ranker"], color: "rose" },
    { name: "Next Best Action", components: ["Offer Selection Engine", "Channel Optimizer", "Send-Time Personalization", "Frequency Capping Logic", "A/B Test Orchestration"], color: "violet" },
    { name: "Execution & Measurement", components: ["ESP Integration", "Push Notification Platform", "SMS Delivery Layer", "Real-Time Segmentation", "Conversion Attribution"], color: "blue" },
  ],
  resultsTitle: "Personalization Transformed Every Loyalty Metric",
  resultsMetrics: [
    { value: "34%", label: "Offer Redemption Rate", description: "Up from 12%—nearly tripling engagement with loyalty program communications", color: "pink" },
    { value: "+28%", label: "Purchase Frequency", description: "Mid-tier loyalty members purchasing more frequently driven by timely, relevant outreach", color: "purple" },
    { value: "-57%", label: "Member Churn Rate", description: "Annual lapse rate dropped from 28% to 12% through proactive churn intervention", color: "green" },
    { value: "+19%", label: "Revenue Per Member", description: "Highest-return tech investment that year—personalization drives meaningful revenue growth", color: "blue" },
  ],
  resultsQuote: {
    text: "We had 37 million members and we were sending the same email to all of them. Now every offer, every recommendation, every touchpoint is built around what that specific person actually buys. Our best members say it feels like we know them.",
    author: "Chief Marketing Officer",
    role: "Ulta Beauty",
  },
  howItWorksTitle: "How Ulta Beauty's Personalization Engine Works",
  steps: [
    { title: "Member Profile Enrichment", description: "Build a rich multi-dimensional profile for every member", detail: "Purchase history across 7+ years, in-store and online transactions, app engagement patterns, email click behavior, and product review text are combined into a multi-dimensional member profile that captures beauty preferences, brand affinities, spending patterns, and channel behavior per member." },
    { title: "Category Affinity Classification", description: "Segment each member by beauty category preferences", detail: "The category affinity model classifies each of 37M members into primary and secondary beauty segments: skincare-focused, makeup collector, fragrance enthusiast, haircare-loyal, value-seeker, or prestige-oriented. These segments drive fundamentally different content, product, and offer strategies." },
    { title: "Repurchase Cycle Modeling", description: "Predict when each member will repurchase each product", detail: "For each member's frequently purchased products, a product-level repurchase cycle model predicts the expected repurchase date based on historical intervals, quantity purchased, and usage rate signals. Replenishment reminders are triggered 7 days before the predicted run-out date." },
    { title: "Churn Risk Assessment", description: "Score every member's churn risk daily and intervene proactively", detail: "A daily batch scoring job assigns each member a churn probability score based on recency, frequency, monetary value trajectory, and engagement pattern signals. Members crossing the risk threshold receive targeted retention offers before lapse—not win-back campaigns after." },
    { title: "Next Best Action Selection", description: "Choose the optimal offer and channel per member per cycle", detail: "The next best action engine evaluates every member before each communication cycle, selecting the highest-value action from the available option space: replenishment reminder, new product recommendation, tier advancement nudge, points multiplier event, or no contact (frequency cap). Channel and timing are optimized per member." },
    { title: "Continuous A/B Testing and Learning", description: "Systematically improve every model through controlled experiments", detail: "Every major model decision—offer selection, channel preference, send time—is subject to ongoing A/B tests that measure actual conversion lift vs. holdout groups. Test results feed model retraining cycles that improve recommendation accuracy continuously across all 37M members." },
  ],
  whyItWorkedTitle: "Why Ulta Beauty's Personalization Program Succeeded",
  whyFactors: [
    { title: "Beauty Category Requires Deep Segmentation", description: "Unlike general retail, beauty preferences are deeply personal and category-specific. A fragrance enthusiast and a skincare minimalist require completely different engagement strategies—recognizing this drove the category affinity architecture." },
    { title: "Repurchase Timing Is a Superpower", description: "Most loyalty programs send offers based on calendar schedules. Timing outreach to when a member is actually likely to buy based on predicted repurchase cycles delivers dramatically higher conversion at the same or lower contact frequency." },
    { title: "Churn Prevention vs. Win-Back", description: "Retaining a member costs 5-7x less than winning one back. Building churn risk scoring into the architecture enabled early intervention before lapse—the most cost-efficient loyalty improvement available." },
    { title: "Frequency Capping Protects Engagement", description: "Personalization without frequency control creates message fatigue. Hard frequency caps (max 2 communications per week per member) ensured that hyper-relevance didn't curdle into overwhelming volume." },
    { title: "Full Funnel Attribution", description: "Connecting personalization touches to both online and in-store conversions required a robust attribution model that captured the full member journey—enabling accurate measurement of program ROI and driving continued investment." },
    { title: "Tier Advancement as a Loyalty Lever", description: "Members who advance tiers show dramatically higher subsequent engagement and spend. The tier nudge system creating targeted incentives for near-threshold members created measurable tier graduation acceleration." },
  ],
  limitations: [
    { title: "Cold Start for New Members", description: "New members with fewer than 3 purchases have insufficient purchase history for robust affinity modeling—defaulting to category-level new member journeys rather than individual personalization." },
    { title: "Omnichannel Attribution Complexity", description: "Members who research online and purchase in-store create attribution gaps that require device graph and loyalty card matching to close—an ongoing data infrastructure challenge." },
    { title: "Privacy Regulations Limit Some Data Uses", description: "CCPA and emerging state privacy laws limit certain behavioral data uses, requiring ongoing legal review of data pipelines and opt-out mechanics that reduce data availability for some member segments." },
    { title: "Frequency Cap Trade-offs", description: "Conservative frequency caps reduce message fatigue but also reduce opportunities to surface high-value offers during periods of high purchase intent—calibrating this trade-off requires ongoing experimentation." },
  ],
  whenToUseGoodFit: [
    "Loyalty programs with 500,000+ active members and sufficient purchase history per member",
    "Retailers with broad product catalogs where personalized navigation adds significant value",
    "Businesses where purchase cycle is predictable enough to support replenishment timing",
    "Loyalty programs with meaningful churn that proactive intervention could reduce",
    "Retailers operating both online and in-store channels with cross-channel attribution capability",
  ],
  whenToUseNotGoodFit: [
    "Very small loyalty programs with insufficient purchase history for reliable modeling",
    "Single-product businesses where personalization options are limited",
    "Products with extremely long and unpredictable repurchase cycles",
    "Businesses without existing customer data infrastructure for analytics integration",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Churn prediction, repurchase cycle modeling, and CLV forecasting", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Personalized beauty consultation and product recommendation chatbot", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Automated next-best-action execution and campaign trigger orchestration", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "AI personalization and loyalty optimization for specialty retailers", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Next-best-action engine for real-time loyalty offer selection", type: "intelligence" },
  ],
  keyTakeaways: [
    "Offer redemption rate increased from 12% to 34% by personalizing every offer to individual beauty preferences",
    "Member churn dropped from 28% to 12% through proactive risk scoring and pre-lapse intervention",
    "Repurchase cycle prediction enables replenishment reminders timed to actual product run-out",
    "Category affinity modeling across skincare, makeup, fragrance, and haircare enables fundamentally different strategies per member",
    "+19% revenue per member made AI personalization Ulta's highest-return technology investment that year",
  ],
  faqs: [
    { question: "How does the churn prediction model know a member is at risk before they lapse?", answer: "The model identifies early warning signals: declining purchase frequency vs. historical baseline, reduced email engagement, fewer in-store visits, and shrinking average order value. These signals, in combination, have strong predictive validity 30-45 days before actual lapse—the window where intervention is most effective." },
    { question: "How does the system handle members who prefer in-store shopping vs. online?", answer: "Channel preference is modeled per member from historical behavior patterns. In-store-preferring members receive communications optimized for driving store visits (nearby store events, in-store-only offers). Online members receive digital journey communications. Mixed-channel members receive omnichannel messaging with flexible redemption options." },
    { question: "How are offers personalized without requiring members to explicitly state preferences?", answer: "Preferences are inferred from purchase behavior—a member who buys SPF50 moisturizer, eye cream, and vitamin C serum is classified as skincare-focused with clean beauty affinity without ever having to complete a preference survey. Behavioral inference is supplemented by explicit preferences when members provide them." },
    { question: "What is the minimum member base size for this type of personalization to be effective?", answer: "Robust individual-level personalization requires meaningful purchase history per member (3+ transactions), which typically takes 6+ months to accumulate for a new program. For programs with fewer than 100,000 active members, cluster-level personalization (treating similar members the same) is more practical than individual-level modeling." },
    { question: "How does the frequency cap work to prevent message fatigue?", answer: "Each member has a contact frequency budget (maximum 2 communications per week) enforced across all channels. When multiple campaigns would qualify for the same member in the same week, the next best action engine prioritizes the highest expected-value communication and suppresses the others—ensuring members receive the most relevant message rather than all possible messages." },
  ],
  prevCase: { name: "Hilton Hotels", url: "/case-studies/hilton-hotels/" },
  nextCase: { name: "Naratix", url: "/case-studies/naratix/" },
};

export default function UltaBeautyCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
