'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "alphasense",
  company: "AlphaSense",
  industry: "Financial Intelligence",
  subIndustry: "Market Intelligence AI",
  accentColor: "blue",
  gradientClasses: "bg-gradient-to-br from-background via-blue-500/5 to-emerald-500/10",
  heroHeadline: "AlphaSense: AI That Finds the Signal in 10M+ Financial Documents",
  heroSubheadline: "Replacing weeks of analyst research with minutes—processing earnings calls, SEC filings, and research reports to surface investment-grade insights before competitors do.",
  heroStats: [
    { value: "94%", label: "Signal Accuracy", color: "text-blue-400" },
    { value: "-60%", label: "Research Time", color: "text-emerald-400" },
    { value: "10M+", label: "Documents Indexed", color: "text-cyan-400" },
  ],
  directAnswerQuestion: "How does AlphaSense use AI to accelerate financial research?",
  directAnswer: "AlphaSense uses a combination of NLP, semantic search, and sentiment analysis to process over 10 million financial documents—including earnings call transcripts, SEC filings, broker research, and news—in real time. The AI extracts investment signals, tracks sentiment shifts across company cohorts, and surfaces relevant context for any financial query with source attribution, reducing analyst research time by 60% while improving signal coverage.",
  clientDescription: "AlphaSense is an enterprise market intelligence platform used by over 4,000 enterprise customers, including 85% of the S&P 500 and leading investment firms, strategy consultancies, and Fortune 500 companies. The platform helps investment analysts, corporate strategists, and M&A teams rapidly find actionable intelligence buried in vast unstructured financial data.",
  clientFounded: "2011",
  clientSize: "4,000+ enterprise customers, 1,500+ employees",
  clientLocation: "New York, NY, USA",
  problemTitle: "Investment Intelligence Is Buried in an Ocean of Unstructured Text",
  problemDescription: "Financial analysts at major investment firms spend 40–60% of their time reading, summarizing, and cross-referencing documents to find the signals that actually matter for investment decisions. Earnings calls alone generate millions of words per quarter. No human team can read everything—which means valuable signals get missed.",
  painPoints: [
    { title: "Documents Published Daily", stat: "50,000+", description: "New earnings transcripts, SEC filings, analyst reports, and news articles published every trading day across global markets.", color: "blue" },
    { title: "Research Time on Routine Tasks", stat: "60%", description: "Of an analyst's day spent on document retrieval, reading, and summarization rather than actual investment judgment.", color: "amber" },
    { title: "Signal Miss Rate", stat: "~35%", description: "Estimated proportion of relevant market signals that go unnoticed due to volume constraints with human-only research processes.", color: "red" },
  ],
  solutionTitle: "Semantic Financial Intelligence Across All Document Types",
  solutionDescription: "AGIX Technologies built an NLP pipeline tailored to financial language—understanding jargon, entity relationships, and sentiment signals that generic models miss. The system creates a unified semantic index across all document sources, allowing analysts to query by concept rather than keyword.",
  solutionComponents: [
    { title: "Financial NLP Model", description: "Domain-specific language model trained on 15 years of financial documents, understanding terms like 'margin compression', 'buy-side consensus', and 'channel checks' in context." },
    { title: "Semantic Search Engine", description: "Concept-based search that understands that 'pricing power concerns' and 'customer pushback on price increases' are the same signal, even if worded differently." },
    { title: "Sentiment Tracking", description: "Tracks management tone, analyst tone, and news tone across companies and sectors over time, detecting shifts before they appear in price action." },
    { title: "Entity & Event Extraction", description: "Automatically identifies company mentions, financial figures, competitive references, and material events across every document." },
    { title: "Smart Summaries", description: "Generates executive summaries of earnings calls and research reports with direct source citations and sentiment attribution per section." },
    { title: "Watchlist Alerting", description: "Real-time alerts when signals matching an analyst's criteria appear in newly indexed documents, with configurable relevance thresholds." },
  ],
  architectureTitle: "AlphaSense AI Architecture",
  architectureLayers: [
    { name: "Data Ingestion", components: ["Earnings Call Transcripts (50K+/yr)", "SEC EDGAR Filings", "Sell-Side Research Reports", "News & Media Feeds", "Expert Network Transcripts"], color: "sky" },
    { name: "NLP Processing Pipeline", components: ["Document Parsing & Chunking", "Financial Entity Recognition", "Coreference Resolution", "Sentiment Scoring Engine", "Topic Classification"], color: "blue" },
    { name: "Intelligence Layer", components: ["Semantic Vector Index", "Cross-Document Signal Correlation", "Temporal Sentiment Tracking", "Competitive Intelligence Graph"], color: "indigo" },
    { name: "User Interface", components: ["Natural Language Query", "Smart Summaries", "Document Viewer with Highlights", "Watchlist & Alerts", "Export & API"], color: "violet" },
  ],
  resultsTitle: "Measurable Research Efficiency Gains at Scale",
  resultsMetrics: [
    { value: "94%", label: "Signal Accuracy", description: "Relevant results in top 10 search results vs 67% with keyword search", color: "blue" },
    { value: "-60%", label: "Research Time", description: "Analysts complete comprehensive research in hours vs days", color: "emerald" },
    { value: "10M+", label: "Documents Live", description: "Continuously updated index across all major financial document types", color: "cyan" },
    { value: "4,000+", label: "Enterprise Clients", description: "Including 85% of S&P 500 companies and major investment firms", color: "violet" },
  ],
  resultsQuote: {
    text: "What used to take my team three days to pull together for an earnings preview, we now complete in two hours. The semantic search actually understands what we're looking for—not just the words we typed.",
    author: "Director of Equity Research",
    role: "Top-5 US Asset Manager",
  },
  howItWorksTitle: "How AlphaSense AI Processes Financial Documents",
  steps: [
    { title: "Document Ingestion & Parsing", description: "Every new filing, transcript, and article is ingested within minutes", detail: "Documents arrive via direct feeds from EDGAR, transcript providers, and news wires. Each document is parsed, cleaned of formatting artifacts, and segmented into semantic chunks (paragraphs, Q&A exchanges, financial tables) before entering the processing pipeline." },
    { title: "Financial Entity Recognition", description: "Identify companies, people, metrics, and events", detail: "A fine-tuned NER model identifies all company mentions (including subsidiaries and brand names), financial figures with their context, named executives, geographic markets, and material events. Each entity is linked to a canonical identifier for cross-document tracking." },
    { title: "Sentiment Analysis", description: "Score tone at sentence, paragraph, and document level", detail: "A domain-specific sentiment model trained on analyst report labels scores each sentence for direction (positive/negative/neutral) and confidence. Sentiment is computed separately for management language vs. analyst language, as these carry different signals." },
    { title: "Semantic Indexing", description: "Generate vector embeddings for semantic search", detail: "Each document chunk is converted to a dense vector embedding using a financial domain-adapted transformer. These embeddings power the semantic search layer, allowing queries to find conceptually similar passages even when no keywords overlap." },
    { title: "Signal Correlation", description: "Identify cross-document patterns and anomalies", detail: "The intelligence layer correlates signals across documents and time: if a company's management tone is declining across three consecutive earnings calls while analysts are still bullish, that divergence is surfaced as a watchlist signal." },
    { title: "Query & Alert Delivery", description: "Serve results to analysts via search and real-time alerts", detail: "Analyst queries are processed against the live semantic index. Watchlist alerts fire within minutes of new documents matching the configured criteria. All results include source attribution with direct links to the relevant passage in the original document." },
  ],
  whyItWorkedTitle: "Why AlphaSense AI Succeeded Where Generic Tools Failed",
  whyFactors: [
    { title: "Domain-Specific Training Data", description: "Generic NLP models don't understand financial language nuance. Training on 15 years of analyst-labeled financial documents produced dramatically better precision for investment queries." },
    { title: "Source Attribution at Every Step", description: "Analysts trust results they can verify. Showing the exact passage from the original document with confidence scores built credibility that drove adoption." },
    { title: "Speed as the Core Value Prop", description: "Reducing research cycle time from days to hours was a measurable competitive advantage analysts could demonstrate to portfolio managers immediately." },
    { title: "Cross-Document Intelligence", description: "Correlating signals across thousands of documents—something no human team can do manually—created a genuinely new capability rather than just automating existing workflows." },
    { title: "Gradual AI Assistance Model", description: "The system augments analysts rather than replacing them—surfacing relevant passages and summaries while leaving judgment to the humans who understand context better." },
  ],
  limitations: [
    { title: "Cannot Interpret Non-Textual Data", description: "Financial charts, technical analysis, satellite imagery, and other non-text signals aren't part of the system. It's purely a document intelligence platform." },
    { title: "Recency Bias in Training", description: "Models trained on historical financial language may miss signals in genuinely new market paradigms (e.g., cryptocurrency markets, new business models)." },
    { title: "Regulatory and Compliance Sensitivity", description: "In regulated environments like hedge funds, AI-generated research summaries must be reviewed before reliance in investment decisions." },
    { title: "Private Company Coverage Is Limited", description: "For companies that don't file public documents or issue press releases, coverage is thin. Private credit and VC use cases require supplementary data sources." },
  ],
  whenToUseGoodFit: [
    "Research teams covering 50+ companies across multiple sectors",
    "Investment processes requiring comprehensive document review before decisions",
    "Competitive intelligence functions tracking market signals in real time",
    "M&A diligence teams needing to review thousands of documents quickly",
  ],
  whenToUseNotGoodFit: [
    "Teams covering only 5–10 well-known companies with small document sets",
    "Investment strategies based primarily on quantitative price signals",
    "Organizations without analysts who can interpret and act on surfaced signals",
  ],
  connections: [
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Core retrieval-augmented generation for document intelligence", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Natural language query interface for research analysts", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Signal correlation and sentiment trend prediction", type: "service" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Financial services AI deployment and compliance patterns", type: "industry" },
    { name: "Enterprise Knowledge AI", slug: "enterprise-knowledge-ai", relevance: "Document search and synthesis at enterprise scale", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "AI-augmented investment decision frameworks", type: "intelligence" },
  ],
  keyTakeaways: [
    "Semantic search outperforms keyword search by 40% in financial document retrieval",
    "Domain-specific NLP training is essential for financial language precision",
    "Cross-document signal correlation creates capabilities humans physically cannot replicate",
    "Source attribution at every query drives analyst trust and adoption",
    "Research teams see 60% time savings within 90 days of deployment",
  ],
  faqs: [
    { question: "How does AlphaSense handle real-time document processing?", answer: "Documents are ingested within minutes of publication via direct data feeds from EDGAR, transcript services, and news wires. NLP processing and indexing typically completes within 5–15 minutes of document receipt, making signals available well before end-of-day research summaries." },
    { question: "Can the system replace financial analysts?", answer: "No, and it's not designed to. The system handles the retrieval, reading, and organization tasks that consume 60% of an analyst's time. The remaining 40%—interpreting signals, forming investment theses, and making judgment calls—still requires human expertise. The goal is to give analysts 2.5x more time for high-value work." },
    { question: "What is the accuracy of the sentiment analysis?", answer: "In back-testing against analyst-labeled financial sentiment, the model achieves 88% agreement with expert human raters on directional sentiment classification. For investment-grade applications, all AI-generated sentiment signals are presented with confidence scores so analysts can apply appropriate weight." },
    { question: "How does the system handle documents in multiple languages?", answer: "The system supports English, German, French, Spanish, Japanese, and Mandarin, with cross-lingual search allowing English queries to retrieve relevant non-English documents. Coverage of non-English document types depends on data licensing agreements with international publishers." },
    { question: "What's the implementation timeline for a new enterprise customer?", answer: "Standard onboarding for an enterprise customer takes 4–6 weeks: 2 weeks for IT integration and data access setup, 2 weeks for analyst onboarding and training, and 2 weeks of supported usage before independent operation. Custom integrations with internal research platforms may extend this timeline." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function AlphaSenseCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
