'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "enova",
  company: "Enova",
  industry: "Fintech",
  subIndustry: "Explainable Credit Decisioning",
  accentColor: "emerald",
  gradientClasses: "bg-gradient-to-br from-background via-emerald-500/5 to-blue-500/10",
  heroHeadline: "Enova: Explainable AI Credit Decisioning at Scale",
  heroSubheadline: "Processing millions of credit applications with 94.7% accuracy and 100% regulatory audit compliance—every decision fully explainable to borrowers and examiners.",
  heroStats: [
    { value: "94.7%", label: "Model Accuracy", color: "text-emerald-400" },
    { value: "100%", label: "Audit Compliance", color: "text-blue-400" },
    { value: "-67%", label: "Review Time", color: "text-green-400" },
  ],
  directAnswerQuestion: "How does Enova use AI for credit decisioning?",
  directAnswer: "Enova deployed an explainable AI credit decisioning system using gradient boosting algorithms with SHAP-based attribution that generates plain-language rationales for each approval and decline decision. The model incorporates 1,400+ behavioral and alternative data signals while the explanation framework satisfies ECOA, CFPB, and SR 11-7 regulatory requirements—producing adverse action codes that examiners can audit without exposing proprietary model logic.",
  clientDescription: "Enova International is a leading technology-enabled financial services company providing credit products to non-prime consumers and small businesses across the US, UK, Brazil, and Australia. With millions of loan applications processed annually, Enova faces both high-volume decisioning demands and stringent regulatory scrutiny from the CFPB, FTC, and banking regulators.",
  clientFounded: "2004",
  clientSize: "1,400+ employees, $1.8B revenue",
  clientLocation: "Chicago, Illinois, USA",
  problemTitle: "Black-Box Models Don't Pass Regulatory Scrutiny",
  problemDescription: "Enova's traditional credit models were accurate but completely opaque. Regulatory examinations required months of effort to explain model decisions, adverse action codes were non-existent, and the inability to demonstrate fair lending compliance created existential regulatory risk.",
  painPoints: [
    { title: "Audit Duration", stat: "4 months", description: "Each regulatory audit required months of manual analysis to reconstruct model logic for examiners.", color: "red" },
    { title: "Adverse Action Codes", stat: "0%", description: "Zero explainability on declined applications—a direct ECOA compliance violation.", color: "amber" },
    { title: "Annual Compliance Cost", stat: "$2.1M", description: "Regulatory overhead from opaque model documentation and examination support.", color: "orange" },
  ],
  solutionTitle: "SHAP-Powered Explainable Credit Decisioning",
  solutionDescription: "AGIX Technologies built an explainable AI credit decisioning system using gradient boosting with SHAP value attribution that generates machine-readable and human-readable rationales for every decision—meeting ECOA, CFPB, and SR 11-7 requirements automatically.",
  solutionComponents: [
    { title: "Gradient Boosting Core Model", description: "XGBoost model trained on 1,400+ credit, behavioral, and alternative data signals achieving 94.7% prediction accuracy on held-out test sets." },
    { title: "SHAP Attribution Engine", description: "SHAP (SHapley Additive exPlanations) calculates each feature's marginal contribution to every individual decision—generating transparent factor rankings." },
    { title: "ECOA Adverse Action Codes", description: "Automated generation of plain-language adverse action codes compliant with ECOA requirements, delivered to declined applicants within milliseconds of decision." },
    { title: "Fair Lending Bias Monitoring", description: "Continuous disparate impact monitoring across protected class proxies with automated flagging when model drift creates potential fair lending exposure." },
    { title: "Regulatory Audit Interface", description: "Examiner-facing portal allowing regulators to interrogate specific decisions, view feature contributions, and validate model documentation without accessing proprietary weights." },
    { title: "Model Governance Dashboard", description: "SR 11-7 compliant model governance tracking including champion-challenger testing, performance monitoring, and model validation documentation." },
  ],
  architectureTitle: "Enova Explainable Credit Architecture",
  architectureLayers: [
    { name: "Data Ingestion", components: ["Credit Bureau APIs", "Bank Transaction Data", "Employment Verification", "Alternative Data Sources", "Application Form Signals"], color: "sky" },
    { name: "Feature Engineering", components: ["1,400+ Signal Extraction", "Behavioral Pattern Mining", "Income Consistency Scoring", "Delinquency Trajectory", "Credit Mix Analysis"], color: "blue" },
    { name: "Core Model Layer", components: ["XGBoost Gradient Boosting", "SHAP Value Computation", "Confidence Interval Estimation", "Threshold Optimization"], color: "emerald" },
    { name: "Compliance Layer", components: ["Adverse Action Code Generator", "ECOA Reason Codes", "Bias Monitoring Engine", "SR 11-7 Documentation"], color: "green" },
    { name: "Decision & Audit", components: ["Real-Time Approval/Decline", "Examiner Audit Portal", "Model Performance Dashboards", "Regulatory Report Generation"], color: "teal" },
  ],
  resultsTitle: "Regulatory Compliance and Business Performance Transformed",
  resultsMetrics: [
    { value: "94.7%", label: "Model Accuracy", description: "On held-out test data vs. prior black-box model's undocumented estimates", color: "emerald" },
    { value: "+22%", label: "Approval Rate", description: "More qualified borrowers approved without any increase in realized default rates", color: "green" },
    { value: "-67%", label: "Decision Latency", description: "Automated decisions in milliseconds vs. days for manual review queues", color: "teal" },
    { value: "100%", label: "ECOA Compliance", description: "Every decline has a compliant adverse action code—from 0% before deployment", color: "blue" },
  ],
  resultsQuote: {
    text: "We went from four-month audit nightmares to examiners being satisfied in days. The SHAP explanations let regulators see exactly what the model was doing without us having to build custom documentation every time.",
    author: "Chief Risk Officer",
    role: "Enova International",
  },
  howItWorksTitle: "How Enova's Explainable Credit Decisions Work",
  steps: [
    { title: "Application Intake", description: "Collect 1,400+ signals from bureau and alternative data", detail: "When an application is submitted, the system pulls credit bureau data, bank transaction history, employment verification, and 1,200+ additional behavioral signals in under 500ms via parallel API calls." },
    { title: "Feature Engineering", description: "Transform raw data into model-ready signals", detail: "Raw data is transformed into behavioral features—income consistency over 12 months, payment trajectory slope, credit utilization velocity—that capture creditworthiness signals beyond what raw bureau scores reflect." },
    { title: "Model Scoring", description: "XGBoost generates probability of default", detail: "The gradient boosting model generates a probability of default score with a calibrated confidence interval. Scores below the threshold route to automated approval; scores above route to decline or manual review." },
    { title: "SHAP Attribution", description: "Calculate each feature's contribution to the decision", detail: "SHAP values are computed for every application, ranking each of the 1,400+ features by its marginal contribution to the final score. The top 5 positive and negative factors become the basis for the decision explanation." },
    { title: "Adverse Action Generation", description: "Produce ECOA-compliant decline reasons automatically", detail: "For declined applications, the SHAP attribution is translated into standardized adverse action reason codes using a mapping layer that satisfies ECOA notification requirements—delivered in the decline response payload." },
    { title: "Audit Trail Logging", description: "Store complete decision record for regulatory access", detail: "Every decision—approval, decline, and manual review—is logged with full feature values, SHAP attributions, model version, and timestamp. The audit portal allows examiners to query any historical decision and view its complete explanation." },
  ],
  whyItWorkedTitle: "Why Enova's Explainability Deployment Succeeded",
  whyFactors: [
    { title: "SHAP Chosen for Additive Properties", description: "SHAP's additive nature means factor contributions sum to the final score, making explanations mathematically precise rather than approximate approximations." },
    { title: "Compliance Built Into Architecture", description: "Adverse action code generation was built into the model pipeline rather than bolted on afterward, ensuring every decision produces compliant documentation automatically." },
    { title: "Examiner-Specific Interface Design", description: "The regulatory audit portal was designed with actual CFPB examination workflows in mind, reducing examiner friction and building goodwill during the first examination cycle." },
    { title: "Champion-Challenger Testing", description: "The explainable model was validated against the prior black-box model in parallel before cutover, proving both accuracy parity and compliance improvement simultaneously." },
    { title: "Alternative Data Validated for Fairness", description: "Every alternative data signal was tested for disparate impact before inclusion, ensuring expanded signal set improved accuracy without creating fair lending exposure." },
    { title: "Model Documentation Automated", description: "SR 11-7 model documentation is generated automatically from model metadata, eliminating the manual documentation burden that previously cost millions annually." },
  ],
  limitations: [
    { title: "Thin-File Applicants Still Challenging", description: "Borrowers with fewer than 12 months of credit history have limited signal, making the model rely more on alternative data where accuracy is lower." },
    { title: "Model Requires Regular Revalidation", description: "SR 11-7 requires annual revalidation. Economic regime changes can cause model drift that reduces accuracy below acceptable thresholds before the next revalidation cycle." },
    { title: "Alternative Data Jurisdiction Limits", description: "Some alternative data sources are unavailable or legally restricted in certain states, requiring state-specific model variants with reduced signal sets." },
    { title: "Explanation Lag at Scale", description: "SHAP computation adds ~50ms to decision latency at scale. For extremely high-volume bursts, this requires careful infrastructure capacity planning." },
  ],
  whenToUseGoodFit: [
    "Operate in a regulated lending environment requiring explainable decisions",
    "Face regulatory examination risk from opaque ML models",
    "Need to expand credit access to thin-file or non-prime borrowers",
    "Process more than 10,000 credit decisions per month",
    "Have existing credit bureau integrations and historical decision data",
  ],
  whenToUseNotGoodFit: [
    "Operate entirely outside regulated lending with no compliance requirements",
    "Have fewer than 12 months of historical credit decision data",
    "Need only a simple rule-based scorecard, not ML-powered decisioning",
    "Lack engineering resources to integrate API-based decisioning infrastructure",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Core credit risk modeling and probability of default prediction", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Bespoke explainable model architecture for regulatory compliance", type: "service" },
    { name: "Fintech AI Solutions", slug: "fintech-ai-solutions", relevance: "Credit risk, fraud, and lending AI in regulated financial services", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Automated credit approval systems with human-readable explanations", type: "intelligence" },
    { name: "Enterprise Knowledge AI", slug: "enterprise-knowledge-ai", relevance: "Regulatory knowledge base and compliance documentation systems", type: "intelligence" },
  ],
  keyTakeaways: [
    "SHAP-based explainability achieves 100% ECOA adverse action code compliance automatically",
    "Model accuracy improved while expanding credit access to 22% more qualified borrowers",
    "Regulatory audit cycles shortened from 4 months to days with examiner-facing portal",
    "$2.1M annual compliance cost reduced through automated SR 11-7 documentation",
    "Gradient boosting with 1,400+ signals outperforms bureau-only models without fair lending risk",
  ],
  faqs: [
    { question: "How does SHAP explainability satisfy ECOA requirements?", answer: "SHAP values are mapped to standardized adverse action reason codes that satisfy ECOA's requirement to provide specific reasons for credit denials. The system automatically selects the top factors with the highest negative SHAP contributions and translates them into plain-language reason codes that meet Regulation B standards." },
    { question: "Can the model be audited for fair lending compliance?", answer: "Yes. The system includes continuous disparate impact monitoring that tests model outputs across protected class proxies (race, gender, national origin) using HMDA and application data. Statistically significant disparities trigger automated alerts and documentation for fair lending review before they become examination findings." },
    { question: "What credit bureau data does the system require?", answer: "The system integrates with all three major bureaus (Experian, Equifax, TransUnion) via standard API connections. Bureau tradeline data, inquiry history, and public records provide the foundation, supplemented by alternative data sources including bank transaction feeds and employment verification APIs." },
    { question: "How does the model handle economic downturns?", answer: "The system includes economic regime indicators as features, allowing it to adjust predictions based on macro signals. However, severe regime changes (like COVID-19) still require manual threshold adjustments and accelerated revalidation cycles to maintain calibration accuracy." },
    { question: "What is the decision latency in production?", answer: "Automated approvals and declines are returned in under 800ms end-to-end, including bureau pulls, feature engineering, model scoring, and SHAP computation. Manual review queues for edge cases typically complete within 24 hours through the underwriter interface." },
  ],
  prevCase: { name: "Dave", url: "/case-studies/dave/" },
  nextCase: { name: "GeOvea", url: "/case-studies/geovea/" },
};

export default function EnovaCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
