'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "albertsons",
  company: "Albertsons",
  industry: "Grocery Retail",
  subIndustry: "Demand Forecasting AI",
  accentColor: "emerald",
  gradientClasses: "bg-gradient-to-br from-background via-emerald-500/5 to-green-500/10",
  heroHeadline: "Albertsons: AI Demand Forecasting That Cut $180M in Food Waste",
  heroSubheadline: "Predicting demand for perishables that expire in days—reducing annual food waste by 45% while keeping shelves stocked with the freshest products across 2,200+ stores.",
  heroStats: [
    { value: "-45%", label: "Food Waste", color: "text-emerald-400" },
    { value: "+23%", label: "In-Stock Rate", color: "text-green-400" },
    { value: "$180M", label: "Annual Savings", color: "text-teal-400" },
  ],
  directAnswerQuestion: "How does Albertsons use AI to reduce food waste?",
  directAnswer: "Albertsons deployed a predictive demand forecasting system that ingests 1,400+ signals—weather forecasts, local events, school schedules, store demographics, and historical purchase data—to predict daily demand for each SKU at each store. The system generates automated replenishment orders with optimal quantities, reducing over-ordering of perishables by 45% while maintaining or improving shelf availability.",
  clientDescription: "Albertsons Companies is one of the largest food and drug retailers in the United States, operating more than 2,200 stores across 34 states under 20 well-known banners including Safeway, Vons, Pavilions, and Randalls. With billions in revenue from perishable products and a commitment to sustainability, reducing food waste while maintaining freshness is both a financial and social imperative.",
  clientFounded: "1939",
  clientSize: "2,200+ stores, 300,000+ employees",
  clientLocation: "Boise, Idaho, USA",
  problemTitle: "Perishable Inventory Is a Billion-Dollar Guessing Game",
  problemDescription: "Fresh produce, dairy, bakery, and meat products expire in days—sometimes hours. Traditional forecasting models used simple historical averages and couldn't account for the dozens of variables that swing demand unpredictably. Store managers made educated guesses, and the margin for error was measured in millions of dollars of wasted product.",
  painPoints: [
    { title: "Annual Food Waste Cost", stat: "$180M", description: "Lost revenue from expired or unsold perishables across all store categories before AI intervention.", color: "red" },
    { title: "Forecast Accuracy Gap", stat: "62%", description: "Traditional rule-based models only predicted demand correctly 62% of the time for fresh categories.", color: "amber" },
    { title: "Manual Override Rate", stat: "47%", description: "Store managers overrode system suggestions nearly half the time due to low confidence in forecasts.", color: "orange" },
  ],
  solutionTitle: "Multi-Signal Perishable Demand Forecasting at Store-SKU Level",
  solutionDescription: "AGIX Technologies built a demand forecasting system that operates at the individual store × SKU level, ingesting over 1,400 real-time and predictive signals to generate daily replenishment recommendations with confidence intervals. The system learns from each store's unique patterns while sharing signals across similar stores.",
  solutionComponents: [
    { title: "Weather Integration Engine", description: "Real-time weather API feeds predict demand shifts: heat waves boost watermelon and ice cream; cold snaps increase soup and hot beverages." },
    { title: "Event & Calendar Intelligence", description: "Local event databases detect Super Bowls, school calendars, community events, and holidays to pre-position inventory weeks in advance." },
    { title: "Store Demographic Modeling", description: "Each store's unique customer demographic profile drives preference-based demand curves, distinguishing urban from suburban buying patterns." },
    { title: "Supply Chain Feedback Loop", description: "Real-time supplier availability feeds allow dynamic reforecasting when supply disruptions occur, preventing phantom demand signals." },
    { title: "Automated Replenishment Orders", description: "System generates purchase orders automatically with human-readable confidence scores and override mechanisms for store managers." },
    { title: "Waste Tracking & Model Retraining", description: "Every unit of waste is logged and fed back into the model, creating a continuous improvement loop that sharpens forecasts over time." },
  ],
  architectureTitle: "Albertsons Demand Forecasting Architecture",
  architectureLayers: [
    { name: "Data Ingestion Layer", components: ["POS Transaction Streams", "Weather API (NOAA)", "Event Databases", "Supplier Inventory Feeds", "Store Demographics DB"], color: "sky" },
    { name: "Feature Engineering", components: ["1,400+ Signal Extraction", "Time-Series Decomposition", "Event Proximity Scoring", "Demographic Weighting", "Seasonal Adjustment"], color: "blue" },
    { name: "Forecasting Models", components: ["Gradient Boosting (XGBoost)", "LSTM for Seasonality", "Bayesian Uncertainty Quantification", "Ensemble Stacking"], color: "emerald" },
    { name: "Decision & Execution", components: ["Store-SKU Order Generation", "Confidence Interval Display", "Manager Override UI", "Supplier EDI Integration"], color: "green" },
    { name: "Feedback & Learning", components: ["Waste Tracking Ingestion", "Model Retraining Pipeline", "A/B Testing Framework", "Performance Dashboards"], color: "teal" },
  ],
  resultsTitle: "Measurable Impact Across All Fresh Categories",
  resultsMetrics: [
    { value: "-45%", label: "Food Waste Reduction", description: "Across produce, dairy, bakery, and meat categories systemwide", color: "emerald" },
    { value: "+23%", label: "In-Stock Improvement", description: "Fewer stockouts on high-velocity fresh items during peak periods", color: "green" },
    { value: "89%", label: "Forecast Accuracy", description: "vs 62% with traditional rule-based methods—a 44% relative improvement", color: "teal" },
    { value: "$180M", label: "Annual Savings", description: "In reduced waste and improved margin recovery across the chain", color: "blue" },
  ],
  resultsQuote: {
    text: "We went from educated guessing to surgical precision. The system predicted the Super Bowl chip spike three weeks out, so we had inventory positioned before our suppliers even knew demand was coming.",
    author: "VP of Supply Chain Innovation",
    role: "Albertsons Companies",
  },
  howItWorksTitle: "How Albertsons AI Forecasting Works End-to-End",
  steps: [
    { title: "Signal Aggregation", description: "Collect 1,400+ demand signals daily", detail: "Every morning, the system pulls weather forecasts for the next 14 days, scrapes local event databases for each store's trade area, checks school calendars, and ingests the previous day's POS data. All signals are normalized and feature-engineered before entering the model." },
    { title: "Store-SKU Demand Curves", description: "Generate individual forecasts per store per item", detail: "For each of 2,200 stores and thousands of SKUs, the model generates a daily demand probability distribution with a median prediction and 80% confidence interval. High-uncertainty forecasts are flagged for human review." },
    { title: "Replenishment Order Generation", description: "Translate forecasts into purchase orders", detail: "The order generation engine takes the demand forecast plus current inventory levels, lead times from suppliers, and minimum order quantities to calculate the optimal replenishment quantity that minimizes both waste risk and stockout risk simultaneously." },
    { title: "Manager Review & Override", description: "Human-in-the-loop for context the system can't see", detail: "Store managers receive a daily order summary with confidence scores. They can override any line item and add free-text notes explaining why (e.g., 'local festival this weekend'). These overrides are fed back into the model as training signals." },
    { title: "Execution & Tracking", description: "Submit orders and monitor fulfillment", detail: "Approved orders are submitted via EDI to suppliers. The system tracks actual delivery quantities, records any shortfalls, and adjusts the following week's forecast to account for supplier reliability patterns." },
    { title: "Waste Recording & Retraining", description: "Close the loop with actual outcomes", detail: "At end of day, store associates scan and record all discarded product. This waste data is the most valuable signal in the system—it tells the model exactly where its predictions were too high, driving the continuous retraining that has improved accuracy from 62% to 89% over 18 months." },
  ],
  whyItWorkedTitle: "Six Factors That Made This Deployment Successful",
  whyFactors: [
    { title: "Store-Level Personalization", description: "Rather than a single national model, each store gets a model that understands its specific customer mix, traffic patterns, and local events." },
    { title: "Manager Trust Through Transparency", description: "Displaying confidence intervals and explainable factors convinced skeptical managers to trust the system rather than override it reflexively." },
    { title: "Closed Feedback Loops", description: "Waste tracking data fed directly into model retraining ensured the system improved from every mistake rather than repeating errors indefinitely." },
    { title: "Weather as a Primary Signal", description: "Incorporating 14-day weather forecasts gave the system a significant advantage over models that only looked at historical sales patterns." },
    { title: "Gradual Rollout Strategy", description: "The system launched in 50 pilot stores before chain-wide deployment, building both confidence and a rich dataset for model validation." },
    { title: "Clear Commercial KPIs", description: "Tying the system directly to waste percentage and in-stock rate gave the project undeniable business value from day one." },
  ],
  limitations: [
    { title: "Novel Disruptions Require Human Judgment", description: "Black swan events—a viral social media food trend, a product recall, a pandemic—can't be predicted by historical patterns and require manual overrides." },
    { title: "New Products Have No History", description: "New SKU introductions rely on analogous product signals and supplier forecasts rather than direct historical data, reducing accuracy for the first 90 days." },
    { title: "Last-Mile Weather Accuracy Limits", description: "Hyperlocal weather variation within a store's trade area can cause forecast errors when a thunderstorm hits one side of town but not the other." },
    { title: "Doesn't Eliminate Perishable Risk Entirely", description: "Even with 89% accuracy, 11% of forecasts are materially wrong. High-value categories like fresh seafood still carry meaningful waste risk." },
  ],
  whenToUseGoodFit: [
    "Sell perishable products with expiration windows under 30 days",
    "Operate multiple stores with differing demand patterns",
    "Have POS transaction data going back at least 2 years",
    "Face meaningful financial pressure from waste or stockouts",
    "Can integrate with supplier ordering systems via EDI or API",
  ],
  whenToUseNotGoodFit: [
    "Sell exclusively non-perishable products with long shelf lives",
    "Operate fewer than 10 locations with very similar customer profiles",
    "Lack historical sales data at the SKU level",
    "Have fully manual supply chains with no digital ordering capability",
  ],
  connections: [
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Core demand modeling and inventory optimization", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Automated order generation and supplier EDI integration", type: "service" },
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Structured product and supplier knowledge base", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "Grocery and CPG-specific AI deployment patterns", type: "industry" },
    { name: "Logistics AI Solutions", slug: "logistics-ai-solutions", relevance: "Supply chain optimization and last-mile delivery", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Automated replenishment decision systems", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Store operations and inventory management AI", type: "intelligence" },
  ],
  keyTakeaways: [
    "Reduced annual food waste by $180M across 2,200+ stores",
    "Forecast accuracy improved from 62% to 89% within 18 months",
    "1,400+ demand signals including weather, events, and demographics",
    "Closed-loop retraining from actual waste data drives continuous improvement",
    "Manager override UI maintains human oversight while building trust in AI",
  ],
  faqs: [
    { question: "How long did it take Albertsons to deploy this system?", answer: "The system launched in 50 pilot stores after a 6-month build phase. Full chain-wide deployment across 2,200+ stores took an additional 12 months, with continuous model improvement ongoing." },
    { question: "What data sources does the system require?", answer: "The minimum requirements are POS transaction history at the SKU level (2+ years recommended), current inventory levels, supplier lead time data, and store location for weather integration. Event databases and demographic data enhance accuracy but aren't required to launch." },
    { question: "Can smaller grocery chains implement a similar system?", answer: "Yes, but the approach must scale to available data. Chains with 10–50 stores can implement simpler gradient boosting models without needing the full ensemble architecture. The fundamental loop—signal ingestion, forecast, order, track waste, retrain—works at any scale." },
    { question: "How does the system handle seasonal items that only sell part of the year?", answer: "The model uses seasonal decomposition to understand which items have annual, monthly, or weekly seasonality patterns. For items with very limited history (e.g., a holiday product with only 3 years of data), it relies more heavily on analogous category signals and vendor sell-through guidance." },
    { question: "What happens when a supplier can't fulfill an order?", answer: "Supplier shortfall data is tracked and fed back into the model as a constraint. If a supplier consistently delivers only 80% of ordered quantity, the model learns to order 25% more to hit the target stock level, accounting for supply-side uncertainty." },
    { question: "How do you calculate the ROI on a system like this?", answer: "ROI is measured across three dimensions: waste reduction (units discarded × average unit cost), stockout avoidance (lost sales from empty shelves on high-velocity items), and labor savings from automated order generation replacing manual calculations. For Albertsons, waste reduction was the dominant driver at $180M annually." },
  ],
  prevCase: { name: "Hello Driven", url: "/case-studies/hello-driven/" },
  nextCase: { name: "Kroger", url: "/case-studies/kroger/" },
};

export default function AlbertsonsCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
