'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "luxury-escapes",
  company: "Luxury Escapes",
  industry: "Luxury Travel",
  subIndustry: "AI Concierge & Personalization",
  accentColor: "amber",
  gradientClasses: "bg-gradient-to-br from-background via-amber-500/5 to-yellow-500/10",
  heroHeadline: "Luxury Escapes: AI Concierge That Converts Browsers Into Luxury Bookers",
  heroSubheadline: "Building the digital concierge that luxury travelers actually trust—+189% booking conversion, 94% CSAT, and personalized deal curation that serves the right offer to the right traveler at the right moment.",
  heroStats: [
    { value: "+189%", label: "Booking Conversion", color: "text-amber-400" },
    { value: "94%", label: "Customer Satisfaction", color: "text-yellow-400" },
    { value: "+$420", label: "Avg Basket Value", color: "text-orange-400" },
  ],
  directAnswerQuestion: "How does Luxury Escapes use AI to drive travel booking conversions?",
  directAnswer: "Luxury Escapes uses a multi-layer AI system that combines behavioral targeting, personalized deal curation, and a conversational concierge to move luxury travelers from browsing to booking. The deal recommendation engine matches each user's travel history and preference signals to the most relevant limited-time offers, while the AI concierge answers complex questions about properties, destinations, and inclusions in real time—converting the research phase into a booking decision.",
  clientDescription: "Luxury Escapes is one of the world's fastest-growing luxury travel platforms, offering curated hotel packages at exclusive prices to over 8 million members. Unlike traditional OTAs, Luxury Escapes curates a small number of exceptional deals with value-adding inclusions rather than listing every available room. This curated model requires sophisticated personalization to match the right deal to each member.",
  clientFounded: "2013",
  clientSize: "8M+ members, operations in 30+ countries",
  clientLocation: "Melbourne, Australia",
  problemTitle: "Luxury Travel Customers Require Concierge-Level Personalization—At Scale",
  problemDescription: "Luxury travelers have high expectations and specific preferences. Generic OTA-style listings of hundreds of properties are overwhelming and fail to create the curated, trusted experience luxury buyers expect. But providing genuine concierge-level service to 8 million members is impossible with human teams alone—the economics simply don't work.",
  painPoints: [
    { title: "Homepage Abandonment Rate", stat: "76%", description: "Proportion of visitors who left Luxury Escapes without engaging with any deal—the curated model failed without personalization to show each visitor their most relevant deals.", color: "red" },
    { title: "Research-to-Book Conversion", stat: "1.2%", description: "Baseline conversion rate before AI personalization—luxury travel requires extensive research, and without AI assistance that research often completed off-platform.", color: "amber" },
    { title: "Deal Relevance Rate", stat: "14%", description: "Proportion of displayed deals that were relevant to the visitor's actual travel interests before personalization—86% of deals shown were noise.", color: "orange" },
  ],
  solutionTitle: "Personalized Deal Curation Plus AI Concierge for Luxury Travel",
  solutionDescription: "AGIX Technologies built a two-layer AI system: a recommendation engine that curates the 5–10 most relevant deals for each member's visit, and a conversational AI concierge that answers complex property and destination questions with the knowledge depth of an expert travel consultant.",
  solutionComponents: [
    { title: "Luxury Travel Preference Engine", description: "Builds rich preference profiles from browsing behavior, booking history, wishlist actions, and search patterns—identifying destination preferences, resort types, inclusion priorities, and budget signals for each member." },
    { title: "Deal-Member Matching Algorithm", description: "Matches each member's preference vector to the live deal catalog, surfacing the 5–10 most likely-to-convert deals from thousands available rather than displaying everything to everyone." },
    { title: "Urgency & Scarcity Intelligence", description: "Identifies and surfaces deals where urgency signals (expiring soon, limited rooms remaining) align with the member's established interest—creating authentic urgency without manufactured FOMO." },
    { title: "AI Travel Concierge", description: "Trained on rich property knowledge, destination intelligence, and past traveler reviews, the concierge answers specific questions: 'Is this resort good for honeymooners?', 'How far is this villa from the airport?', 'What's included in the food & beverage credit?'" },
    { title: "Comparison & Shortlist Intelligence", description: "When members compare multiple deals, the AI highlights the differentiators most relevant to their preference profile—pointing to the right choice for this specific traveler rather than listing generic features." },
    { title: "Email Personalization Engine", description: "Weekly member emails are personalized at the individual level—each member sees the most relevant deals for their preferences and travel calendar in each send, improving email-to-booking rates significantly." },
  ],
  architectureTitle: "Luxury Escapes AI Personalization Architecture",
  architectureLayers: [
    { name: "Member Data Layer", components: ["8M Member Profiles", "Booking & Wishlist History", "Browse & Search Signals", "Email Engagement Data"], color: "amber" },
    { name: "Preference Intelligence", components: ["Destination Affinity Modeling", "Resort Type Classification", "Budget & Timing Signals", "Travel Purpose Inference"], color: "orange" },
    { name: "Deal Curation Engine", components: ["Deal-Member Matching", "Urgency & Scarcity Detection", "Inventory Availability Integration", "Real-Time Personalization API"], color: "yellow" },
    { name: "Concierge Intelligence", components: ["Property Knowledge Base", "Destination Encyclopedia", "Review Synthesis Engine", "Comparison Assistance"], color: "teal" },
    { name: "Conversion & Learning", components: ["A/B Testing Framework", "Booking Attribution", "Preference Model Update", "Email Performance Optimization"], color: "slate" },
  ],
  resultsTitle: "Booking and Revenue Outcomes From Personalization",
  resultsMetrics: [
    { value: "+189%", label: "Booking Conversion", description: "Conversion rate improved from 1.2% to 3.5% with personalized deal curation and AI concierge support", color: "amber" },
    { value: "+$420", label: "Basket Value Increase", description: "Average transaction value increase from concierge-guided bookings vs unassisted browsing", color: "yellow" },
    { value: "94%", label: "Concierge Satisfaction", description: "Members who interacted with the AI concierge rated the experience 94% positively", color: "orange" },
    { value: "-76%", label: "Homepage Abandonment", description: "Reduction in immediate site abandonment as personalized homepage shows relevant deals instantly", color: "teal" },
  ],
  resultsQuote: {
    text: "Before AI personalization, we showed the same deals to a 28-year-old backpacker and a 65-year-old retiree looking for their dream anniversary trip. Now each member sees a completely different homepage, and both are more likely to book.",
    author: "Chief Product Officer",
    role: "Luxury Escapes",
  },
  howItWorksTitle: "How Luxury Escapes AI Converts Browsers Into Bookers",
  steps: [
    { title: "Member Recognition & Profile Loading", description: "Identify the visitor and load their preference profile", detail: "When a member visits the site or opens an email, their preference profile is loaded instantly: destination history, wishlisted properties, search patterns, budget signals, and travel timing preferences. First-time visitors are shown curated editorial content while their preference signals are collected during the session." },
    { title: "Personalized Deal Selection", description: "Filter and rank deals for this specific member", detail: "The deal-member matching algorithm scores every live deal in the catalog against the member's preference vector. The top 5–10 deals with the highest predicted relevance and conversion probability are selected for display—often very different from what a different member would see." },
    { title: "Urgency Signal Integration", description: "Apply authentic urgency to high-interest deals", detail: "For deals where the member has demonstrated interest (viewed, wishlisted, searched similar) and genuine inventory scarcity exists, urgency signals are displayed prominently. The system only shows urgency where it's real—manufactured urgency destroys the trust that luxury buyers require." },
    { title: "Concierge Engagement", description: "Activate the AI concierge for research-phase members", detail: "Members who view multiple deals, compare properties, or spend extended time on a deal page are prompted to engage the AI concierge. The concierge has access to deep property knowledge, past traveler reviews, destination intelligence, and inclusion details to answer the specific questions that block booking decisions." },
    { title: "Comparison & Decision Support", description: "Guide members comparing similar deals to a decision", detail: "When members add multiple deals to a comparison view, the AI concierge generates a personalized comparison summary highlighting the differentiators most relevant to this member's preference profile—pointing toward the better fit for their situation rather than listing identical feature columns." },
    { title: "Post-Booking Personalization", description: "Continue personalization after booking", detail: "Post-booking communications are personalized to the confirmed destination: relevant packing tips, local intelligence, add-on recommendations for the specific resort's amenities, and pre-departure excitement content. This post-booking engagement reduces cancellations and builds anticipation that generates positive reviews." },
  ],
  whyItWorkedTitle: "Why Luxury Travelers Responded to AI Personalization",
  whyFactors: [
    { title: "Curation Is the Core Value Proposition", description: "Luxury travelers don't want to search 500 hotels. They want someone they trust to say 'these 5 are right for you.' AI personalization delivers this at scale—matching the curated experience luxury buyers expect." },
    { title: "Concierge Knowledge Depth Built Trust", description: "The AI concierge's ability to answer specific, detailed questions ('Is the pool heated in November?', 'Are children allowed at the spa?') demonstrated expertise that turned research into confidence to book." },
    { title: "Authentic Urgency vs FOMO Manipulation", description: "Only displaying urgency signals when inventory genuinely is limited maintained the trust that luxury buyers require. Manufactured urgency would have been immediately detected and damaged the brand." },
    { title: "Email Personalization Compounded Results", description: "Personalized weekly emails showing each member's most relevant deals created a recurring purchase trigger that generic mass emails couldn't achieve—members waited for 'their' deal to appear." },
  ],
  limitations: [
    { title: "New Members Have Minimal Preference Data", description: "First-time visitors see editorial curation rather than personalized recommendations until behavioral signals accumulate. The first visit is necessarily less personalized." },
    { title: "Very High Budget Segments Require Human Concierge", description: "Ultra-high-end bookings (luxury villas, private islands, custom itineraries above $50,000) benefit from human concierge involvement—AI handles the research phase but closes hand off to specialists for the transaction." },
    { title: "Deal Catalog Dependency", description: "The recommendation system's value is bounded by the quality of deals in the catalog. Personalization can't compensate for a weak deal offering in a destination a member wants to visit." },
    { title: "Real-Time Inventory Accuracy", description: "Room availability signals depend on accurate real-time inventory feeds from hotel partners. Inventory discrepancies can show deals as available when they're not—a trust-damaging experience in luxury segments." },
  ],
  whenToUseGoodFit: [
    "Travel platforms with curated deal catalogs where personalization improves relevance significantly",
    "Luxury or premium commerce brands where customer trust and curation are competitive differentiators",
    "Membership-based commerce platforms with rich historical member data",
    "E-commerce platforms where research-phase support would improve conversion from browsing to purchase",
  ],
  whenToUseNotGoodFit: [
    "Commodity travel OTAs where price is the primary decision factor and personalization has limited impact",
    "Platforms with very thin member histories (fewer than 2 interactions per member)",
    "Single-product businesses where there's nothing to personalize",
  ],
  connections: [
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "AI travel concierge for research-phase member questions", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Deal-member matching and booking conversion prediction", type: "service" },
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Property and destination knowledge base for concierge accuracy", type: "service" },
    { name: "Hospitality AI Solutions", slug: "hospitality-ai-solutions", relevance: "Travel and luxury hospitality AI deployment patterns", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Expert-level travel concierge dialogue at scale", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Deal curation and booking decision support systems", type: "intelligence" },
  ],
  keyTakeaways: [
    "+189% conversion from showing 5 personalized deals vs 500 generic ones",
    "AI concierge knowledge depth (specific property details) is what converts luxury researchers",
    "Only authentic urgency signals work for luxury buyers—manufactured FOMO destroys trust",
    "Email personalization at individual level outperforms segmented lists by 4x in travel",
    "Post-booking personalization reduces cancellations and builds the experience that generates reviews",
  ],
  faqs: [
    { question: "How does the concierge handle questions it doesn't know the answer to?", answer: "The concierge is trained to explicitly acknowledge when information is uncertain or unavailable and offer to connect the member with a human specialist. For high-stakes property-specific questions (e.g., accessibility requirements, medical facilities), the system defaults to human expert verification rather than providing potentially wrong information." },
    { question: "How quickly does the personalization improve for a new member?", answer: "Meaningful personalization begins after 3–5 site interactions or email engagements. After a first booking, personalization accuracy increases dramatically as the system knows the member's actual purchase behavior rather than just browsing signals. Members with 3+ bookings in their history receive the highest-accuracy personalization." },
    { question: "Does the system work for group travel and corporate bookings?", answer: "The preference engine currently models individual traveler preferences. Group travel introduces multi-decision-maker complexity that the current system handles by defaulting to the primary account holder's preferences. Corporate travel personalization is an extension on the product roadmap." },
    { question: "How does AI personalization interact with Luxury Escapes' manual deal curation?", answer: "Deal curation (selecting which properties and packages to feature) remains a human editorial function—experienced travel curators select deals based on quality, value, and exclusivity. AI personalization operates downstream, determining which curated deals to surface to each member. The two layers work together: human curation ensures quality; AI personalization ensures relevance." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function LuxuryEscapesCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
