'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "hilton-hotels",
  company: "Hilton Hotels",
  industry: "Hospitality",
  subIndustry: "AI Guest Experience",
  accentColor: "amber",
  gradientClasses: "bg-gradient-to-br from-background via-amber-500/5 to-yellow-500/10",
  heroHeadline: "Hilton: AI Personalization That Converts Guest Preferences Into Revenue",
  heroSubheadline: "Moving beyond loyalty points to genuine personalization—predicting what each of Hilton's 150M Honors members wants before they ask, driving 31% upsell revenue growth and 4.7/5 satisfaction scores.",
  heroStats: [
    { value: "+31%", label: "Upsell Revenue", color: "text-amber-400" },
    { value: "4.7/5", label: "Guest Satisfaction", color: "text-yellow-400" },
    { value: "150M", label: "Members Personalized", color: "text-orange-400" },
  ],
  directAnswerQuestion: "How does Hilton use AI to personalize the guest experience?",
  directAnswer: "Hilton uses a guest intelligence platform that builds behavioral profiles from stay history, preference signals, and loyalty program interactions for 150 million Honors members. The AI predicts needs before arrival (preferred room type, likely amenity usage, dining preferences), serves personalized recommendations throughout the stay via the Hilton app, and identifies upsell opportunities matched to each guest's demonstrated preferences and willingness to pay—driving a 31% increase in ancillary revenue per stay.",
  clientDescription: "Hilton Hotels & Resorts is one of the world's largest hotel companies, operating 7,200+ properties across 123 countries under 22 distinct brands from luxury (Waldorf Astoria) to extended stay (Home2 Suites). With 150 million Hilton Honors members, Hilton has one of the richest guest data assets in hospitality—the challenge was turning that data into genuine personalization rather than generic loyalty program benefits.",
  clientFounded: "1919",
  clientSize: "7,200+ hotels, 150M Honors members, 1.4M rooms",
  clientLocation: "McLean, Virginia, USA",
  problemTitle: "Loyalty Programs Create Data—But Not Personalization",
  problemDescription: "Hilton had years of guest stay data but was using it to assign tier levels and points—not to actually personalize the experience. A Diamond member who always requests a high floor got the same room assignment process as a new member. The spa, restaurant, and fitness center teams had no visibility into which arriving guests were likely to use their services. Data sat in silos while guests experienced generic hospitality.",
  painPoints: [
    { title: "Data Silos Across Properties", stat: "22 brands", description: "Guest data existed separately across Hilton's 22 hotel brands, preventing cross-brand preference learning for the same guest.", color: "amber" },
    { title: "Ancillary Revenue Per Stay", stat: "Low", description: "Amenity and service upsells were offered generically at check-in rather than targeted to guests with demonstrated affinity—conversion rates were under 15%.", color: "orange" },
    { title: "Preference Memory Gap", stat: "67%", description: "Proportion of returning guests whose stated preferences were not proactively applied at their next stay—creating repeated 'I always request a quiet room' conversations.", color: "red" },
  ],
  solutionTitle: "Guest Intelligence Platform With Real-Time Personalization Across All Touchpoints",
  solutionDescription: "AGIX Technologies built a unified guest intelligence platform that consolidates stay history, service usage, app interactions, and feedback signals into a single guest profile per Honors member. Real-time inference serves personalized recommendations across every guest touchpoint: pre-arrival emails, check-in app, in-stay dining recommendations, and concierge interactions.",
  solutionComponents: [
    { title: "Unified Guest Profile Engine", description: "Consolidates 150M Honors member profiles from 22 brand systems into a single preference graph, learning from every stay, feedback signal, and app interaction." },
    { title: "Pre-Arrival Preference Application", description: "24 hours before check-in, the system sends automated room assignment recommendations to the property based on the guest's preference history—high floor, quiet hallway, king bed, specific amenities requested." },
    { title: "Personalized Amenity Recommendations", description: "In-app recommendations for spa, dining, fitness, and local experiences are tailored to each guest's demonstrated interests, not generic 'popular with guests'." },
    { title: "Revenue Opportunity Scoring", description: "Each guest receives a propensity score for amenity categories (spa likely, dining likely, room upgrade likely) that guides concierge and front desk conversations without scripting." },
    { title: "Dynamic Pricing Personalization", description: "Room upgrade offers and amenity package pricing are calibrated to each guest's historical willingness to pay, improving conversion rates while protecting rate integrity." },
    { title: "Service Recovery Intelligence", description: "The system flags guests with negative feedback patterns for proactive service recovery outreach before checkout, significantly reducing negative review rates." },
  ],
  architectureTitle: "Hilton Guest Intelligence Architecture",
  architectureLayers: [
    { name: "Data Integration Layer", components: ["Hilton Honors CRM", "22-Brand PMS Systems", "App Interaction Events", "Review & Feedback Signals"], color: "amber" },
    { name: "Guest Profile Engine", components: ["150M Member Profiles", "Stay History Graph", "Preference Vector Building", "Sentiment History Tracking"], color: "orange" },
    { name: "Personalization Intelligence", components: ["Preference Prediction Models", "Amenity Propensity Scoring", "WTP Estimation", "Service Recovery Flagging"], color: "yellow" },
    { name: "Delivery & Touchpoints", components: ["Pre-Arrival App Notifications", "Digital Check-In Personalization", "In-Stay Concierge Interface", "Staff Dashboard"], color: "green" },
    { name: "Measurement & Learning", components: ["Conversion Rate Tracking", "Revenue Attribution", "Guest Satisfaction Monitoring", "Model Retraining Pipeline"], color: "slate" },
  ],
  resultsTitle: "Revenue and Satisfaction Outcomes at Chain Scale",
  resultsMetrics: [
    { value: "+31%", label: "Upsell Revenue", description: "Increase in ancillary revenue per stay from targeted vs generic amenity recommendations", color: "amber" },
    { value: "4.7/5", label: "Guest Satisfaction", description: "Average satisfaction score vs 4.1/5 before personalization deployment", color: "yellow" },
    { value: "+34%", label: "Spa Conversion", description: "Increase in spa booking rate when recommendations were matched to guest's demonstrated wellness interest", color: "orange" },
    { value: "-28%", label: "Negative Reviews", description: "Reduction in negative online reviews from proactive service recovery identification", color: "green" },
  ],
  resultsQuote: {
    text: "We went from 'here's your key card' to 'welcome back, your high-floor king room with extra pillows is ready, and we've reserved your usual 7am fitness spot.' Guests don't describe this as technology. They describe it as feeling genuinely valued.",
    author: "Chief Experience Officer",
    role: "Hilton Hotels & Resorts",
  },
  howItWorksTitle: "How Hilton's AI Personalizes the Guest Journey",
  steps: [
    { title: "Reservation & Profile Matching", description: "Connect the booking to the guest's 360-degree profile", detail: "When a reservation is made, the system matches it to the guest's Honors profile and retrieves their complete preference history: room type preferences, pillow choices, floor level, noise sensitivity, dietary restrictions, amenity usage patterns, and any service recovery flags from past stays." },
    { title: "Pre-Arrival Preparation", description: "Send personalized preparation to the property", detail: "24 hours before arrival, the system generates a personalized briefing for the property: recommended room assignment based on preferences and availability, predicted amenity interest (spa today? dining tonight?), and any VIP or service recovery notes. Staff can review and action this briefing before check-in." },
    { title: "Digital Check-In Personalization", description: "Serve a personalized check-in experience via the app", detail: "The Hilton app check-in experience serves each guest personalized room selection (showing their preferred room types first), pre-fills dietary preferences for restaurant reservations, and presents targeted upgrade offers priced to their willingness-to-pay history." },
    { title: "In-Stay Recommendations", description: "Serve relevant suggestions throughout the stay", detail: "During the stay, the app proactively surfaces relevant recommendations: a spa slot matched to a guest who always uses the spa, a dinner reservation offer matched to a guest's cuisine preferences, a local experience matched to their travel purpose and activity history." },
    { title: "Service Recovery Monitoring", description: "Detect and address dissatisfaction proactively", detail: "The system monitors in-stay feedback signals: slow in-app responsiveness, unreturned housekeeping requests, low service ratings. When a negative pattern emerges, it flags the case for proactive manager outreach before checkout—turning a potential complaint into a service recovery success story." },
    { title: "Post-Stay Learning", description: "Update the guest profile from stay outcomes", detail: "After checkout, all interactions, amenity usage, spending patterns, and feedback are written back to the guest profile. Preferences that were confirmed, expanded, or contradicted during the stay update the model for more accurate predictions at the next property visit anywhere in the Hilton portfolio." },
  ],
  whyItWorkedTitle: "Why Hilton's AI Personalization Drove Real Revenue",
  whyFactors: [
    { title: "Preference Data at Chain Scale", description: "150 million Honors member profiles spanning years of stay history created a preference dataset rich enough to make genuinely accurate predictions rather than demographic generalizations." },
    { title: "Staff Interface That Enabled Action", description: "Presenting guest intelligence to staff in a simple briefing format they could action in 30 seconds—not a complex dashboard—was crucial to adoption at the property level." },
    { title: "Targeted Upsells Aren't Annoying", description: "When a guest who always books spa treatments receives a pre-arrival spa offer, it feels like service—not sales. When a guest with no spa history receives the same offer, it feels like spam. Targeting is the difference." },
    { title: "Cross-Brand Learning", description: "A guest who always stays at Hampton Inn can have their preferences transferred to a first-time Waldorf Astoria visit—cross-brand intelligence creates value that brand-siloed approaches miss entirely." },
    { title: "Service Recovery Before Checkout", description: "Detecting and addressing service failures during the stay rather than reading about them in post-checkout reviews was a paradigm shift that dramatically reduced negative review rates." },
  ],
  limitations: [
    { title: "First-Time Guests Have No Profile", description: "New Honors members and non-members have no preference history to draw from. The system uses demographic and behavioral signals during the first stay to bootstrap a profile, but the first stay is always less personalized." },
    { title: "Cross-Culture Personalization Complexity", description: "Preference patterns learned from US guests may not transfer accurately to guests from other cultural contexts. Regional profile variants are needed for global accuracy." },
    { title: "Property-Level Adoption Varies", description: "Chain-wide AI personalization requires property-level staff to action the intelligence. Properties with lower adoption rates see proportionally lower results than those who integrate it into check-in workflows." },
    { title: "Data Privacy Compliance Variation", description: "GDPR and regional privacy regulations create different consent and data handling requirements across markets. European properties have stricter data usage constraints than US properties." },
  ],
  whenToUseGoodFit: [
    "Hotel chains with 100+ properties and a loyalty program with multi-year member history",
    "Hospitality groups seeking to grow ancillary revenue beyond room rate",
    "Properties with low amenity conversion rates despite willing-to-pay guests",
    "Hotel companies with multiple brands where cross-brand preference transfer has value",
  ],
  whenToUseNotGoodFit: [
    "Independent boutique hotels where personalization is delivered through relationship memory",
    "Limited-service hotels where amenity upsell opportunities are minimal",
    "Properties without a loyalty program or guest data infrastructure",
    "Organizations where data privacy constraints limit guest profile building",
  ],
  connections: [
    { name: "Agentic AI Systems", slug: "agentic-ai-systems", relevance: "Multi-step guest journey orchestration and personalization", type: "service" },
    { name: "AI Predictive Analytics", slug: "ai-predictive-analytics", relevance: "Guest preference prediction and propensity scoring", type: "service" },
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "In-stay concierge and guest communication interface", type: "service" },
    { name: "Hospitality AI Solutions", slug: "hospitality-ai-solutions", relevance: "Hotel and resort AI personalization deployment patterns", type: "industry" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Guest intelligence and upsell opportunity decisioning", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Hotel operations and service delivery optimization", type: "intelligence" },
  ],
  keyTakeaways: [
    "31% upsell revenue growth proves targeted personalization converts better than generic offers",
    "Pre-arrival preparation briefs for staff are the operational bridge between AI insights and guest experience",
    "Cross-brand preference learning creates compound value unique to large hotel chains",
    "Service recovery detection during stay, not post-checkout review, is the satisfaction game-changer",
    "150M member profiles at chain scale create personalization accuracy that small datasets cannot match",
  ],
  faqs: [
    { question: "How does Hilton protect guest preference data?", answer: "Guest preference data is stored within Hilton's enterprise data infrastructure with role-based access controls. Property staff see anonymized preference recommendations, not raw personal data. Guests can view, correct, and delete their preference data via the Hilton Honors profile portal, consistent with GDPR and CCPA requirements." },
    { question: "How does the system work for guests who haven't built a preference history?", answer: "First-stay and new member guests receive a baseline personalization experience based on demographic and booking signals (room type booked, purpose of travel, length of stay). The app prompts preference capture during the stay—room comfort feedback, dining interest signals—to bootstrap a profile faster. By the second stay, most personalization features are fully active." },
    { question: "Does the personalization work the same across all 22 Hilton brands?", answer: "The personalization platform is brand-aware—it knows that a Waldorf Astoria guest's expectations differ from a Hampton Inn guest, even if it's the same person. Recommendations and communication style are calibrated to the brand context while leveraging cross-brand preference signals." },
    { question: "What is the incremental cost per stay to deliver AI personalization at this scale?", answer: "At chain scale, the compute cost per guest interaction is a fraction of a cent. The platform cost is amortized across 7,200 properties and 150 million members. The incremental revenue per personalized stay ($42 average) far exceeds the per-stay technology cost, producing industry-leading ROI on the technology investment." },
  ],
  prevCase: { name: "Quizlet", url: "/case-studies/quizlet/" },
  nextCase: undefined,
};

export default function HiltonHotelsCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
