'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "quizlet",
  company: "Quizlet",
  industry: "EdTech",
  subIndustry: "Socratic AI Tutoring",
  accentColor: "indigo",
  gradientClasses: "bg-gradient-to-br from-background via-indigo-500/5 to-purple-500/10",
  heroHeadline: "Quizlet Q-Chat: AI That Teaches Through Questions, Not Answers",
  heroSubheadline: "Socratic AI tutor serving 60M+ students with personalized learning that delivers +67% learning gains and 89% misconception resolution—changing how a generation learns.",
  heroStats: [
    { value: "+67%", label: "Learning Gains", color: "text-indigo-400" },
    { value: "60M+", label: "Students Served", color: "text-purple-400" },
    { value: "89%", label: "Misconception Resolution", color: "text-cyan-400" },
  ],
  directAnswerQuestion: "How does Quizlet's Q-Chat AI tutor improve student learning?",
  directAnswer: "Q-Chat is a Socratic AI tutor that teaches through targeted questions rather than direct information delivery. The system models individual knowledge states across concept hierarchies, identifies specific gaps through diagnostic question sequences, and crafts follow-up questions at calibrated difficulty levels that build toward genuine mastery. Students using Q-Chat demonstrate 68% better long-term retention on delayed recall assessments compared to traditional flashcard study, because they construct understanding rather than passively recognizing correct answers.",
  clientDescription: "Quizlet is one of the world's largest student learning platforms, serving over 300 million students and teachers in 130+ countries. Known for its flashcard and quiz tools, Quizlet sought to transform from a passive content review platform to an active learning partner by deploying AI that could genuinely improve educational outcomes—not just engagement metrics.",
  clientFounded: "2005",
  clientSize: "300M+ registered users, 60M+ monthly active students",
  clientLocation: "San Francisco, California, USA",
  problemTitle: "AI That Gives Answers Fails Students Who Need to Learn",
  problemDescription: "When ChatGPT launched, students started using it for homework—and stopped learning. Getting answers immediately short-circuits the learning process. Quizlet needed AI that guided students to discover answers themselves, not an answer machine that produced academic dishonesty at scale.",
  painPoints: [
    { title: "Learning Gains Lost", stat: "-40%", description: "Students using answer-giving AI showed 40% lower learning gains vs. active study methods on delayed recall assessments.", color: "red" },
    { title: "Session Engagement", stat: "4.2 min", description: "Average passive flashcard session length—too short for meaningful knowledge consolidation on complex topics.", color: "amber" },
    { title: "Misconception Rate", stat: "31%", description: "Percentage of students with persistent misconceptions that traditional flashcard review failed to detect and correct.", color: "orange" },
  ],
  solutionTitle: "Socratic AI Tutoring With Knowledge State Modeling",
  solutionDescription: "AGIX Technologies helped build Q-Chat, a Socratic AI tutor that teaches through targeted questions rather than information delivery. The system models each student's knowledge state across concept hierarchies, identifies gaps, and guides students to construct understanding through calibrated question sequences.",
  solutionComponents: [
    { title: "Socratic Question Generation", description: "Rather than answering student questions, Q-Chat responds with carefully calibrated follow-up questions that guide the student toward the answer using what they already know as scaffolding." },
    { title: "Knowledge State Modeling", description: "Each student's mastery is modeled across a concept graph with 300+ nodes per subject. The system tracks mastery level, misconception patterns, and knowledge stability per concept." },
    { title: "Misconception Detection", description: "When a student response reveals an underlying misconception—not just a wrong answer—the system identifies the specific false belief and designs a targeted correction sequence." },
    { title: "Adaptive Difficulty Calibration", description: "Questions are dynamically selected at the student's zone of proximal development—challenging enough to require effort, achievable enough to maintain confidence and momentum." },
    { title: "Curriculum Alignment", description: "Question sequences align to course curriculum and upcoming assessment topics, making session content directly relevant to the student's current academic context." },
    { title: "Teacher Insight Dashboard", description: "Teachers receive class-level misconception maps showing which concepts their students collectively struggle with—enabling targeted classroom intervention at the moments that matter." },
  ],
  architectureTitle: "Quizlet Q-Chat AI Tutoring Architecture",
  architectureLayers: [
    { name: "Student Interface", components: ["Chat UI with Socratic Prompting", "Study Set Integration", "Progress Visualization", "Goal Setting & Tracking", "Spaced Repetition Scheduler"], color: "indigo" },
    { name: "Knowledge Modeling", components: ["Concept Graph (300+ nodes)", "Knowledge State Tracker", "Mastery Probability Model", "Misconception Pattern Library", "Forgetting Curve Integration"], color: "purple" },
    { name: "Question Generation", components: ["Socratic Question Templates", "Difficulty Calibration Engine", "Scaffolding Logic", "Hint Sequencing", "Encouragement Generation"], color: "blue" },
    { name: "Response Analysis", components: ["Answer Correctness Classifier", "Misconception Detector", "Partial Knowledge Scorer", "Learning Velocity Calculator", "Frustration Signal Detection"], color: "cyan" },
    { name: "Teacher & Analytics", components: ["Class Misconception Heatmap", "Learning Gain Tracking", "Session Quality Score", "Curriculum Coverage Map", "Parent Progress Reports"], color: "violet" },
  ],
  resultsTitle: "Learning Outcomes Improved Across Every Measured Dimension",
  resultsMetrics: [
    { value: "+67%", label: "Learning Gains", description: "Measured by delayed recall assessments vs. traditional flashcard study", color: "indigo" },
    { value: "+183%", label: "Test Score Improvement", description: "Students using Q-Chat improved assessment scores from 12% to 34% above baseline", color: "purple" },
    { value: "11.8 min", label: "Avg Session Length", description: "Up from 4.2 minutes—interactive dialogue is more engaging than passive review", color: "blue" },
    { value: "78%", label: "Teacher Adoption", description: "In pilot schools, teachers recommended Q-Chat as a supplementary learning tool", color: "cyan" },
  ],
  resultsQuote: {
    text: "Q-Chat represents what AI in education should be. It's not about giving students answers faster—it's about helping them think better. The misconception detection alone is worth it. Teachers can now see exactly where students struggle and intervene at the right moment.",
    author: "VP of Learning Sciences",
    role: "Quizlet",
  },
  howItWorksTitle: "How Q-Chat Builds Genuine Understanding",
  steps: [
    { title: "Session Initialization", description: "Assess current knowledge state and set session goals", detail: "When a student starts a Q-Chat session, the system loads their current knowledge state model and identifies the 2-3 concept nodes with the highest expected learning value for this session—prioritizing concepts with weak mastery, upcoming assessment relevance, or recent forgetting curve signals." },
    { title: "Diagnostic Opening", description: "Probe current understanding with targeted questions", detail: "The session opens with a diagnostic question designed to reveal the student's current understanding of the target concept. Their response is analyzed not just for correctness but for the underlying mental model it reveals—correct answers, incorrect answers, and partial answers all provide signal." },
    { title: "Socratic Scaffolding", description: "Guide toward understanding through question sequences", detail: "Rather than providing the answer when a student is wrong, Q-Chat responds with a question that helps the student reason toward the correct understanding. 'You said X. What do you think would happen if we removed Y from the equation?' The scaffolding is built on what the student already knows." },
    { title: "Misconception Identification", description: "Detect and directly address false beliefs", detail: "When a student response pattern reveals a persistent misconception—not just a knowledge gap—the system identifies the specific false belief and switches to a targeted correction sequence designed to expose the contradiction between the misconception and observable facts." },
    { title: "Mastery Confirmation", description: "Verify understanding transfers across problem variations", detail: "Once a student answers correctly, Q-Chat tests transfer by presenting the same concept in a different context or with different surface features. Genuine understanding—as opposed to pattern matching—is confirmed when the student applies the concept correctly across variations." },
    { title: "Session Summary & Next Steps", description: "Consolidate learning and schedule future review", detail: "At session end, Q-Chat provides a summary of concepts covered, mastery progress, and any misconceptions identified and addressed. The spaced repetition scheduler is updated based on demonstrated mastery to schedule optimal review timing for each concept." },
  ],
  whyItWorkedTitle: "Why Q-Chat's Socratic Approach Succeeded",
  whyFactors: [
    { title: "Questions Beat Answers for Learning", description: "Decades of educational research confirms that generating answers requires deeper cognitive processing than recognizing correct answers—Q-Chat's question-based design is grounded in evidence, not trend." },
    { title: "Misconception Detection as Core Feature", description: "Identifying that a student believes the wrong thing (not just doesn't know the right thing) is fundamentally different from gap detection and requires a separate response strategy." },
    { title: "Calibration at the Zone of Proximal Development", description: "Questions that are too easy bore students; too hard triggers frustration and disengagement. Calibrating to each student's current ZPD was essential for maintaining engagement through challenge." },
    { title: "Curriculum Alignment vs. Generic Tutoring", description: "Aligning session content to the student's actual curriculum and upcoming assessments made Q-Chat immediately relevant to real academic stakes, driving adoption among students who wouldn't use generic AI tools." },
    { title: "Teacher Insight Creates Classroom Leverage", description: "The class misconception heatmap gave teachers actionable information they couldn't get from any other source—driving adoption among educators who became Q-Chat advocates." },
    { title: "Safety and Academic Integrity by Design", description: "Building Q-Chat to guide rather than give answers addressed the academic integrity concerns that prevent many institutions from allowing AI study tools—enabling school-sanctioned adoption." },
  ],
  limitations: [
    { title: "Works Best for Conceptual Learning", description: "Q-Chat's Socratic approach is most effective for conceptual subjects (science, social studies, literature). Purely procedural skills like arithmetic computation benefit less from dialogue-based tutoring." },
    { title: "Requires Student Willingness to Engage", description: "Students who want quick answers resist the dialogue format. Without institutional or parental encouragement, low-motivation students are less likely to engage with Socratic prompting." },
    { title: "Knowledge Graph Coverage Varies by Subject", description: "Subjects with well-mapped curricula (high school biology, US history) have comprehensive concept graphs. Highly specialized or advanced topics have thinner coverage." },
    { title: "Language Model Limitations on Factual Accuracy", description: "For highly technical subjects, the Socratic guiding question must be factually precise. Errors in the scaffolding questions themselves can inadvertently reinforce misconceptions." },
  ],
  whenToUseGoodFit: [
    "EdTech platforms serving students who need to build genuine conceptual understanding",
    "Subjects with well-defined concept hierarchies (science, history, literature, social studies)",
    "Schools concerned about AI academic dishonesty who want AI that promotes learning",
    "Platforms with curriculum data that can align AI tutoring to assessment preparation",
    "Organizations measuring learning outcomes, not just engagement or completion",
  ],
  whenToUseNotGoodFit: [
    "Pure drill-and-practice for procedural skills where practice volume matters more than dialogue",
    "Professional training where answer lookup efficiency is valued over conceptual depth",
    "Subjects with rapidly changing factual content that the knowledge graph cannot keep current",
    "Highly specialized graduate-level subjects with insufficient curriculum mapping",
  ],
  connections: [
    { name: "Conversational AI Chatbots", slug: "conversational-ai-chatbots", relevance: "Socratic dialogue engine and multi-turn tutoring conversation design", type: "service" },
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Q-Chat product architecture and knowledge state modeling system", type: "service" },
    { name: "EdTech AI Solutions", slug: "edtech-ai-solutions", relevance: "AI deployment patterns across K-12 and higher education platforms", type: "industry" },
    { name: "Conversational AI", slug: "conversational-ai", relevance: "Natural language dialogue and adaptive question generation", type: "intelligence" },
    { name: "Decision AI", slug: "decision-ai", relevance: "Adaptive question selection and difficulty calibration systems", type: "intelligence" },
  ],
  keyTakeaways: [
    "+67% learning gains on delayed recall assessments vs. passive flashcard study",
    "Misconception detection reveals false beliefs, not just knowledge gaps—enabling targeted correction",
    "Average session length increased from 4.2 to 11.8 minutes through engaging Socratic dialogue",
    "78% teacher adoption in pilot schools because class misconception maps provide actionable insight",
    "Socratic design addresses academic integrity concerns enabling school-sanctioned AI adoption",
  ],
  faqs: [
    { question: "How does Q-Chat know when a student has a misconception vs. just a knowledge gap?", answer: "The system maintains a library of known misconception patterns per concept—common false beliefs identified through educational research. When a student's response matches a misconception pattern (not just an incorrect answer), it triggers a targeted correction sequence rather than a standard hint." },
    { question: "How does Q-Chat handle a student who just wants the answer?", answer: "When a student repeatedly requests direct answers, Q-Chat acknowledges the frustration, explains briefly that guiding questions lead to better retention, and offers a slightly more direct hint. If the student continues to resist the dialogue format, the session flag this for parent/teacher visibility." },
    { question: "What subjects does Q-Chat currently support?", answer: "Q-Chat has comprehensive concept graph coverage for biology, chemistry, US history, world history, economics, literature, and geography at middle and high school levels. College-level coverage is expanding for introductory STEM and social science courses." },
    { question: "How does Q-Chat protect student privacy?", answer: "Knowledge state models and session transcripts are stored under COPPA-compliant privacy protections for users under 13. No conversation content is used for model training without explicit parental consent. School district deployments include FERPA-compliant data processing agreements." },
    { question: "Can Q-Chat be integrated with existing LMS platforms?", answer: "Yes. Q-Chat provides LTI (Learning Tools Interoperability) integration with Canvas, Schoology, and Google Classroom, allowing teachers to assign Q-Chat sessions as activities and view results within their existing LMS gradebook." },
  ],
  prevCase: { name: "Stitch Fix", url: "/case-studies/stitch-fix/" },
  nextCase: { name: "Hilton Hotels", url: "/case-studies/hilton-hotels/" },
};

export default function QuizletCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
