'use client'
import { CaseStudyV2, CaseStudyV2Data } from "@/components/case-study/CaseStudyV2";

const data: CaseStudyV2Data = {
  slug: "naratix",
  company: "Naratix",
  industry: "E-Commerce Technology",
  subIndustry: "AI Product Content Generation",
  accentColor: "violet",
  gradientClasses: "bg-gradient-to-br from-background via-violet-500/5 to-purple-500/10",
  heroHeadline: "Naratix: AI That Writes 1M Product Descriptions Per Month Across 28 Markets",
  heroSubheadline: "Replacing content agencies and spreadsheet workflows with automated, brand-consistent product copy—+129% conversion lift in Germany, 98% semantic accuracy, and 28 language markets served from a single product feed.",
  heroStats: [
    { value: "+129%", label: "Conversion Lift (DE)", color: "text-violet-400" },
    { value: "1M+", label: "Descriptions/Month", color: "text-purple-400" },
    { value: "28", label: "Markets Served", color: "text-indigo-400" },
  ],
  directAnswerQuestion: "How does Naratix generate product descriptions with AI at scale?",
  directAnswer: "Naratix uses a multi-stage AI pipeline that takes structured product data (attributes, specs, category, price tier) and generates SEO-optimized, brand-consistent product descriptions localized for each target market. The system combines a fine-tuned generation model trained on high-converting e-commerce copy with a cultural localization layer that adapts messaging—not just translating, but rewriting for local buyer psychology. Output is validated for semantic accuracy, brand compliance, and SEO requirements before publishing.",
  clientDescription: "Naratix is an AI content platform serving e-commerce retailers and marketplace sellers who need to maintain high-quality product descriptions at scale across multiple markets and languages. Their customers range from large marketplaces with millions of SKUs to branded retailers expanding into new markets who face the content bottleneck that prevents fast international expansion.",
  clientFounded: "2020",
  clientSize: "200+ enterprise e-commerce customers, 30M+ descriptions generated",
  clientLocation: "Amsterdam, Netherlands",
  problemTitle: "E-Commerce Content at Scale Is a Human-Speed Bottleneck",
  problemDescription: "A retailer expanding from Germany to 5 new European markets needs hundreds of thousands of product descriptions rewritten for each market—not just translated, but culturally adapted. A traditional content agency charges $0.10–0.50 per word and takes weeks. At 1 million products, this is economically impossible. Retailers either expand slowly, publish low-quality content, or don't localize at all.",
  painPoints: [
    { title: "Content Agency Cost Per Description", stat: "$2-10", description: "Typical cost per professionally written product description from a content agency—multiplied by millions of SKUs across 28 markets becomes economically prohibitive.", color: "violet" },
    { title: "Time to Market for New Market", stat: "6 months", description: "Average time to generate localized content for a new market entry using traditional translation and copywriting workflows.", color: "amber" },
    { title: "Generic Description Conversion", stat: "-43%", description: "Conversion rate deficit of generic translated descriptions vs market-specific copy adapted for local buyer behavior and cultural expectations.", color: "red" },
  ],
  solutionTitle: "AI Product Copy Generation With Cultural Localization, Not Just Translation",
  solutionDescription: "AGIX Technologies built a multi-stage content pipeline that generates brand-consistent, SEO-optimized product descriptions from structured data and then localizes them for each market through cultural adaptation—not translation. The distinction is critical: the German version of a product description emphasizes technical specifications; the French version leads with aesthetic appeal; the Japanese version prioritizes detailed care and usage instructions.",
  solutionComponents: [
    { title: "Structured Data Ingestion", description: "Ingests product data in any format (CSV, XML, API, PIM export) and normalizes it into a structured attribute set that drives the content generation." },
    { title: "Brand Voice Training", description: "Each customer's brand voice is captured through a training process using existing approved copy and brand guidelines—ensuring generated content matches the established brand tone and style." },
    { title: "SEO-Optimized Generation", description: "Generated descriptions incorporate target keywords, optimal length for each category, structured data markup, and natural keyword integration that improves search ranking without triggering spam detection." },
    { title: "Cultural Localization Layer", description: "A market-specific adaptation layer transforms base content for each culture: adjusting formality level, emphasizing locally relevant product attributes, and adapting calls-to-action for local buyer psychology." },
    { title: "Multi-Dimensional Quality Validation", description: "Every generated description is validated across four dimensions: semantic accuracy (does it correctly represent the product?), brand compliance, SEO quality, and localization accuracy before publishing." },
    { title: "CMS & Marketplace Integration", description: "Direct publishing integrations with Shopify, Magento, WooCommerce, Amazon Seller Central, and major European marketplaces eliminate the manual upload step from the workflow." },
  ],
  architectureTitle: "Naratix AI Content Pipeline Architecture",
  architectureLayers: [
    { name: "Data Ingestion", components: ["PIM & CSV Import", "Product Attribute Normalization", "Category Classification", "Price Tier Detection"], color: "violet" },
    { name: "Brand & Style Layer", components: ["Brand Voice Model", "Tone & Style Calibration", "Category-Specific Templates", "Competitor Differentiation Signals"], color: "purple" },
    { name: "Content Generation", components: ["Fine-Tuned Generation Model", "SEO Keyword Integration", "Length & Format Optimization", "Unique Copy Generation"], color: "indigo" },
    { name: "Cultural Localization", components: ["28-Market Cultural Adaptation", "Formality Level Adjustment", "Local Feature Emphasis", "CTA Localization"], color: "blue" },
    { name: "Validation & Publishing", components: ["Semantic Accuracy Check", "Brand Compliance Scoring", "SEO Quality Gate", "CMS/Marketplace Publishing"], color: "slate" },
  ],
  resultsTitle: "Content Performance and Operational Efficiency Results",
  resultsMetrics: [
    { value: "+129%", label: "Conversion Lift DE", description: "Increase in product page conversion rate for culturally adapted German descriptions vs translated content", color: "violet" },
    { value: "98%", label: "Semantic Accuracy", description: "Proportion of generated descriptions that correctly represent all product attributes and specifications", color: "purple" },
    { value: "1M+", label: "Descriptions/Month", description: "Monthly throughput for a single enterprise customer across all markets and categories", color: "indigo" },
    { value: "-94%", label: "Content Cost Reduction", description: "vs traditional content agency costs for the equivalent volume and quality of product descriptions", color: "blue" },
  ],
  resultsQuote: {
    text: "We entered the German market in 6 weeks instead of 6 months. The AI-generated descriptions outperformed our English-language translations by 129% in conversion rate because they weren't just translated—they were written for German shoppers. That's a completely different product.",
    author: "Head of International Expansion",
    role: "Pan-European E-Commerce Retailer",
  },
  howItWorksTitle: "How Naratix Generates 1 Million Descriptions Per Month",
  steps: [
    { title: "Product Data Ingestion & Normalization", description: "Import and structure the product catalog", detail: "Product data arrives from any source—PIM export, CSV feed, direct API—and is normalized into a standardized attribute schema. Category classification adds implicit attributes (a 'wireless headphone' inherits connectivity and battery attributes even if not explicitly provided in the product feed)." },
    { title: "Brand Voice Application", description: "Load the customer's calibrated brand voice", detail: "Each enterprise customer completes a brand voice calibration process using existing approved copy samples. The system extracts voice parameters: formality level, technical depth, benefit vs feature emphasis, characteristic phrases, and prohibited language. These parameters are applied to all generated content for that customer." },
    { title: "Base Content Generation", description: "Generate SEO-optimized product descriptions", detail: "The generation model produces a base description incorporating all product attributes, relevant keywords for the category, optimal content length for SEO in that product category, and brand voice compliance. Each description is generated uniquely—not templated—to avoid duplicate content penalties." },
    { title: "Cultural Localization", description: "Adapt the content for each target market", detail: "The cultural localization layer transforms the base content for each of 28 markets. For Germany: more technical detail and specification focus. For France: aesthetic appeal and lifestyle context. For Japan: extremely detailed usage instructions and care guidance. These aren't translation variations—they're culturally calibrated rewrites." },
    { title: "Multi-Dimensional Validation", description: "Validate accuracy, brand compliance, and SEO quality", detail: "Every generated description passes through four automated quality gates: semantic validation (product attributes accurately represented), brand compliance scoring (voice parameters met), SEO quality gate (keyword density, length, readability), and localization accuracy (no translation artifacts, culturally appropriate). Failures route to human review queue." },
    { title: "Automated Publishing", description: "Publish to all channels without manual upload", detail: "Validated content is published directly to the customer's CMS platforms, marketplace accounts, and regional storefronts via pre-built integrations. The complete pipeline from product data to live description typically completes in under 60 minutes for standard requests." },
  ],
  whyItWorkedTitle: "Why Cultural Adaptation Outperformed Translation",
  whyFactors: [
    { title: "Cultural Adaptation vs Translation Is a Different Product", description: "German shoppers prioritize technical specifications; French shoppers respond to lifestyle context; Japanese shoppers want exhaustive detail. Translation preserves words; cultural adaptation preserves persuasive effectiveness." },
    { title: "Brand Voice Consistency at Scale", description: "Generating 1 million descriptions that all sound like the same brand is impossible for human teams. AI with a trained brand voice model maintains consistency that human copywriters working at scale inevitably lose." },
    { title: "SEO Integration From Generation, Not Post-Processing", description: "SEO optimization built into the generation model produces more natural keyword integration than adding keywords to human-written copy after the fact—avoiding the stilted language that triggers algorithmic penalties." },
    { title: "Validation Gates Maintained Quality Confidence", description: "Customer adoption required confidence in quality. Multi-dimensional automated validation plus a human review option for any description gave customers the quality assurance needed to publish without per-description review." },
  ],
  limitations: [
    { title: "Creative Category Copy Needs Human Review", description: "Fashion editorials, lifestyle photography captions, and brand story content benefit from human creative direction that AI generation captures imperfectly for top-of-funnel brand content." },
    { title: "Highly Technical B2B Products Need SME Input", description: "Industrial equipment, specialized medical devices, and complex software products require subject matter expert review to ensure technical claims are accurate and appropriately caveated." },
    { title: "Brand Voice Calibration Takes Initial Effort", description: "The brand voice model requires an upfront calibration process using approved existing copy. Brands without an established content library need to develop reference materials first." },
    { title: "Cultural Accuracy Requires Market Validation", description: "Generated descriptions should be validated by native speakers in each new market during initial deployment—AI cultural models improve with feedback but aren't perfect out of the box." },
  ],
  whenToUseGoodFit: [
    "Retailers with 50,000+ SKUs needing high-quality product descriptions across multiple markets",
    "Marketplace sellers who lose ranking to competitors with better descriptions",
    "Brands entering new international markets who face the content localization bottleneck",
    "E-commerce platforms managing seller content quality at scale",
  ],
  whenToUseNotGoodFit: [
    "Boutique retailers with fewer than 500 SKUs where bespoke human copy is feasible",
    "Brands where creative product storytelling is the primary differentiator",
    "Highly regulated industries (medical devices, pharmaceuticals) where copy requires regulatory review regardless of generation method",
  ],
  connections: [
    { name: "Custom AI Product Development", slug: "custom-ai-product-development", relevance: "Fine-tuned content generation models with brand voice calibration", type: "service" },
    { name: "RAG Knowledge AI", slug: "rag-knowledge-ai", relevance: "Product knowledge retrieval for accurate content generation", type: "service" },
    { name: "AI Automation", slug: "ai-automation", relevance: "Automated content pipeline from data ingestion to publishing", type: "service" },
    { name: "Retail AI Solutions", slug: "retail-ai-solutions", relevance: "E-commerce content and conversion optimization AI", type: "industry" },
    { name: "Enterprise Knowledge AI", slug: "enterprise-knowledge-ai", relevance: "Product catalog knowledge management at scale", type: "intelligence" },
    { name: "Operational AI", slug: "operational-ai", relevance: "Content operations automation and quality management", type: "intelligence" },
  ],
  keyTakeaways: [
    "+129% conversion from cultural adaptation—not translation—proves messaging matters more than words",
    "1M descriptions/month proves AI content generation is a fundamentally different economic model",
    "Brand voice training from existing approved copy maintains consistency that human teams can't at scale",
    "SEO integration at generation is more effective than keyword insertion after writing",
    "Multi-dimensional validation gates are what enable confident publishing without per-description review",
  ],
  faqs: [
    { question: "How does Naratix ensure the AI doesn't make false product claims?", answer: "The semantic validation gate compares every generated description against the source product attributes. Claims about specifications (battery life, material, dimensions) are fact-checked against the product data. Any description where the generated claim doesn't match the source data is flagged and either auto-corrected or routed to human review before publishing." },
    { question: "Can the system handle products with very limited attribute data?", answer: "Yes, but output quality is proportional to input data richness. The system supplements sparse attribute data using category inference (a 'wool sweater' can inherit care instructions even without them in the feed), but descriptions for products with only 3-4 attributes will be shorter and less differentiated than those with 15+ attributes." },
    { question: "How long does the brand voice calibration take?", answer: "Initial brand voice calibration takes 2-5 business days: the customer provides 100-200 samples of approved product copy, and the team tunes the voice parameters and validates output against customer approval. After calibration, any new product can be described in that voice without additional configuration." },
    { question: "What languages are supported?", answer: "Full cultural localization is available for English, German, French, Spanish, Italian, Dutch, Polish, Czech, Japanese, Korean, and Mandarin Chinese. Machine translation (without cultural adaptation) is available for an additional 18 languages. New cultural localization modules are added quarterly based on customer demand." },
  ],
  prevCase: undefined,
  nextCase: undefined,
};

export default function NaratixCaseStudyPage() {
  return <CaseStudyV2 data={data} />;
}
